### ISSUE TITLE
Low Priority navigation and other issues

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1006]
I think the Low-priority and LP omnibus measures for practices and CCGs could be easier to navigate by adding more links. This is an issue because people may not realise they can access all the possible comparisons/breakdowns that we have available, or have to click through many views to get what they are after. Sometimes using the back button solves the issues but if links are shared it can be difficult to access some of the other views. 

### Issue 1
From a CCG's homepage you can click "View the 17 measures" to see a breakdown of the measures for the whole CCG. Or, if you click on the measure itself you see it broken down across the practices in the CCG. It's not obvious that these links will lead you to different pages. (Not sure if there's an easy solution for this except stating the second option in the text also).

### Issue 2 
It's difficult to navigate all the pages because a lot of them aren't linked to each other, for example haing clicked on either of the links above, it's difficult to get to [this](https://openprescribing.net/measure/lpzomnibus/) page where you can compare the omnibus measure across all CCGs. 

### Summary of page navigation as it stands

| page | navigates to | also navigates to | | problem |
| -- | -- | -- | -- | -- |
| CCG homepage | CCG-level breakdown into individual LP measures | practice-level omnibus | | not obvious that the two links take you to different pages ![image](https://user-images.githubusercontent.com/24392156/44522496-9babc700-a6ce-11e8-8a6b-47c1b0b55d62.png)
| CCG-level breakdown into individual LP measures | any breakdown for the individual measures ![image](https://user-images.githubusercontent.com/24392156/44521296-787f1880-a6ca-11e8-8def-8e5140774fcf.png) | standard measures | | no direct link back to omnibus, for practices or CCGs
| practice-level omnibus (for any CCG) | CCG-level breakdown into individual LP measures | | | no direct link back to omnibus for whole CCG, or practice-level breakdown into individual LP measures ![image](https://user-images.githubusercontent.com/24392156/44521500-2c80a380-a6cb-11e8-9de6-752f55458afa.png)
| practice-level breakdown into individual measures | CCG-level breakdown into individual LP measures | *presentation*-level breakdown | | no link to practice-level omnibus
| measure (all CCGs) page | practice-level omnibus (for any CCG) | | | no link to CCG-level breakdown into individual LP measures

**Comment by HelenCEBM** [comment]
### Issue 3 - similar to issue 1 but for practices
On the dashboard page you see the combined spend for your practice but it's not possible to open this measure page itself for just your practice. Clicking on the measure title goes to the omnibus measure for all practices in your CCG (I think this is particularly unhelpful and unexpected from a practice page as you then have to scroll through to find your practice). The other links (yellow highlights) go to the 18 individual measures for the practice
![image](https://user-images.githubusercontent.com/24392156/55787812-04558180-5aaf-11e9-8a73-19acd021bf1b.png)

Suggest that clicking the title (particularly when you're on a practice page) should take you to the individual measure page ie. https://openprescribing.net/measure/lpzomnibus/practice/B87002/

**Comment by HelenCEBM** [comment]
Similar to Issue 3, also suggest that clicking on the title of the measure highlighted on a practice dashboard page should take you to that individual measure (presentation breakdown) for that practice only, rather than to "all practices in CCG" single-measure page
![image](https://user-images.githubusercontent.com/24392156/58893814-bcd32680-86e8-11e9-8180-1a8a6ddbd7d2.png)

**Comment by HelenCEBM** [comment]
Individual practice individual measure pages (e.g. https://openprescribing.net/measure/statinintensity/practice/A81036/)
should have link to "Compare all practices in CCG on this measure" - at present this is linked via the title but it's not obvious.

The same goes, in fact, for the individual practice all-measures pages, e.g. https://openprescribing.net/practice/A81036/measures/
again you have to click on the titles to see the comparison across practices in CCG on a measure

**Comment by brianmackenna** [comment]
discussion Alex, Brian , Helen and Rich

Could breadcrumbs help?  See [NICE example](https://www.nice.org.uk/guidance/ta246)

![image](https://user-images.githubusercontent.com/40460354/59259906-8474a080-8c32-11e9-934c-1ec64b39ba10.png)

On CCG measures page you can't return to CCG homepage. Could the title link back to the CCG homepage or button like @evansd implemented for individual measures to return to full measures.

![image](https://user-images.githubusercontent.com/40460354/59260583-cbaf6100-8c33-11e9-8ee7-784a62d0f5da.png)

![image](https://user-images.githubusercontent.com/40460354/59260866-4f694d80-8c34-11e9-9845-2527868510fb.png)


Re 

> The same goes, in fact, for the individual practice all-measures pages, e.g. https://openprescribing.net/practice/A81036/measures/
again you have to click on the titles to see the comparison across practices in CCG on a measure

This is related to bar chart discussion

**Comment by HelenCEBM** [comment]
To do:
- [ ] On CCG/practice measures pages (e.g. https://openprescribing.net/ccg/99E/measures/) make title a hyperlink back to CCG/practice dashboard page (i.e. https://openprescribing.net/ccg/99E/)
- [ ] On CCG/practice dashboard pages make titles go to individual measure pages for that CCG/practice, i.e. from https://openprescribing.net/ccg/99E/ the two highlighted links below should go to the respective individual measure page for that CCG/practice
![image](https://user-images.githubusercontent.com/24392156/59276280-ed214480-8c55-11e9-8a18-e1f5f87b4210.png)
- [ ] Make sure that the all-18 LP measures pages have a link to the combined measure (so people know it exists if they came via non-standard route (e.g. from https://openprescribing.net/ccg/99E/measures/?tags=lowpriority to https://openprescribing.net/measure/lpzomnibus/ccg/99E/
- [ ] Make sure Low Priority omnibus pages (all practices in CCG) have a link back to the onmibus page for the whole CCG (e.g. from https://openprescribing.net/ccg/99E/lpzomnibus/ to https://openprescribing.net/measure/lpzomnibus/ccg/99E/
- [ ] Make individual practice individual measure pages (e.g. https://openprescribing.net/measure/statinintensity/practice/A81036/)
should have an explicit link to "Compare all practices in CCG on this measure" - at present this is linked via the title but not obvious.
- [ ] As previous, the individual practice all-measures pages, (e.g. https://openprescribing.net/practice/A81036/measures/) need to have option to "Compare all practices in CCG on this measure" for each measure.

**Comment by HelenCEBM** [comment]
This is great thanks @evansd !

Minor suggestions
- Button text:
http://staging.openprescribing.net/ccg/00K/statinintensity/
Not immediately obvious what button text refers to
![image](https://user-images.githubusercontent.com/24392156/61398501-0441fa80-a8c4-11e9-8266-293b630895ad.png)
Suggest: "View measure for all practices in CCG combined" or "View measure for CCG combined"

- Can't see links back to dashboards from measure pages, for either practices or CCGs, are you sure it worked?
- I can see the link to the omnibus measure from the low-priority pages but also thought perhaps we could make a separate tag "Low Priority Omnibus / combined" to make it even more easy to find?

**Comment by evansd** [comment]
Thanks @HelenCEBM 

 * I've gone with "View measure as combined total for this CCG" which is hopefully clear.
 * The CCG/practice title on the measure pages links back to the dashboard, which what the plan above suggested. But maybe we need something more explicit?
 * We could certainly make a tag which was just applied to the omnibus measure if you think that would be helpful. I'm not 100% convinced of that though. What would be the route via which people would end up on that tag?

Also, the measures page which wasn't loading on staging wasn't just down to staging being slow. It was a genuine bug which I've now fixed.
