### ISSUE TITLE
There should be a way to view a practice in national context

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#101]
The current histogram view for analysis only supports viewing a practice or CCG against another CCG.

Options for implementation:
- Support querying all practices by code for a given date, e.g. https://openprescribing.net/api/1.0/spending_by_practice/?code=0212&date=2015-04-01. This would return a few thousand datapoints for that month, which we could then combine on the client side.
  - Pros: could reuse most of the client-side code without changing; consistent with current API
  - Cons: might use too many client resources; the SQL query might not be peformant
- Combine the data into a histogram server-side
  - Pros: less data to transfer over the wire; opportunity to optimise in SQL
  - Cons: might still not be performant SQL

Other things to consider:
- Currently all the data is returned for all months for a histogram, then the current month is extracted client-side. It's likely we'd have to change the code so new requests are made when the slider is moved. This would give an unpleasant user experience.
- The time series chart _requires_ all months to be retrieved at once. If this were impossible in the current architecture, we'd have to support deciles in that chart sooner than we thought.
- If we want to support both, we simply have to find a performant way to get all data for all months, in histogram and with-deciles form.

Performant ways to do this:
- Map-reduce (in Google Cloud)
- Can't think of any other way of doing it

**Comment by sebbacon** [comment]
Some notes / thoughts.

In order to achieve aggregating all the data at once, I don't think we can avoid a query which at its core is of the order of:

```sql
SELECT sum(total_items) 
  AS items 
  FROM frontend_prescription
  WHERE presentation_code = '0208010W0AAAJAJ'

```

This takes 14 seconds in postgres at the moment:
```
 Aggregate  (cost=97265.38..97265.39 rows=1 width=4) (actual time=14512.596..14512.597 rows=1 loops=1)
   ->  Bitmap Heap Scan on frontend_prescription  (cost=737.37..97203.19 rows=24877 width=4) (actual time=88.192..14469.140 rows=35240 loops=1)
         Recheck Cond: ((presentation_code)::text = '0208010W0AAAJAJ'::text)
         Heap Blocks: exact=35240
         ->  Bitmap Index Scan on frontend_prescription_by_pct  (cost=0.00..731.15 rows=24877 width=0) (actual time=79.746..79.746 rows=35240 loops=1)
               Index Cond: ((presentation_code)::text = '0208010W0AAAJAJ'::text)
 Planning time: 0.350 ms
 Execution time: 14512.688 ms
```


The equivalent takes 2s on bigquery:

```sql
SELECT
  SUM(items) AS items
FROM
  [hscic.prescribing]
WHERE
  bnf_code = '0208010L0AAAIAI';
```

Note that there is a useful function for computing histograms in postgres:

```sql
SELECT width_bucket(total_items, 0, 100, 100), count(*)  
  FROM frontend_prescription
  WHERE presentation_code = '0208010W0AAAJAJ' group by 1 order by 1;
```

**Comment by sebbacon** [comment]
Looking at the last BigQuery example, but done in postgres: 

```sql
EXPLAIN ANALYSE SELECT
  COUNT(practice_id),
  bucket
FROM (
  SELECT
    round(sum(total_items)/2) AS bucket,
    practice_id
  FROM
    frontend_prescription
  WHERE
    presentation_code = '0501013B0AAAAAA'
  GROUP BY
    practice_id ) t
GROUP BY
  bucket
ORDER BY
  bucket;


 GroupAggregate  (cost=1806406.57..1806406.71 rows=8 width=15)
   Group Key: (round(((sum(frontend_prescription.total_items) / 2))::double precision))
   ->  Sort  (cost=1806406.57..1806406.59 rows=8 width=15)
         Sort Key: (round(((sum(frontend_prescription.total_items) / 2))::double precision))
         ->  HashAggregate  (cost=1806406.23..1806406.37 rows=8 width=11)
               Group Key: frontend_prescription.practice_id
               ->  Bitmap Heap Scan on frontend_prescription  (cost=15771.68..1803730.68 rows=535110 width=11)
                     Recheck Cond: ((presentation_code)::text = '0501013B0AAAAAA'::text)
                     ->  Bitmap Index Scan on frontend_prescription_by_pct  (cost=0.00..15637.90 rows=535110 width=0)
                           Index Cond: ((presentation_code)::text = '0501013B0AAAAAA'::text)
(10 rows)
```

The really expensive bit is grouping by practice id. We could probably significantly improve this by making the `frontend_prescription_by_pct` index a [*covering index*](https://wiki.postgresql.org/wiki/Index-only_scans#Covering_indexes), covering practice id.

**Comment by annapowellsmith** [comment]
I agree about `CLUSTER` - the only other kind of query we care about on that data is per-PCT or per-practice, and we do those via materialized views. 

Next steps as discussed: let's try clustering (given that that will almost certainly improve the current performance, which would be a win) and updating the estimate figures above.

**Comment by sebbacon** [comment]
# General benchmarking approach
We need to have some confidence our changes are making a difference, so we need some kind of benchmark plan.

The actual run time of a query is dramatically different depending on if the disk access has been cached or not.

The best way to deal with this is presumably to run 10 (or more) queries against random presentation codes. We can select some random `presentation_code` like this:

```sql
SELECT
  presentation_code
FROM (
SELECT DISTINCT 1 + trunc(random() * 5100000)::integer AS id
    FROM   generate_series(1, 10) g) r
JOIN
  frontend_prescription using (id);
```
We can then capture the output of the following 10 times:
```sql
EXPLAIN (analyze,
    buffers)
SELECT
  SUM(total_items)
FROM
  frontend_prescription
WHERE
  presentation_code = '%s'
```

I've got a management command to this which I've not quite finished.

# CLUSTER plan

`CLUSTER` performs an exclusive lock on the table. So when shall we try it? I have no idea how long it will take.

You need free space on disk at least equal to the sum of the table size and the index sizes; for the fastest method, the peak temporary space requirement is as much as double the table size, plus the index sizes. The table is currently 99GB and the indexes 208GB. So that's 400GB we need spare. Given we currently have 71GB, that's not going to happen without a bit more thought!

We also need to run `ANALYZE` after the cluster operation; and if it's successful, we need to run this after each monthly import.

## Covering indexes

In the example above (summing across `total_items`), the high cost is because once we have selected a particular presentation, there are still typically 500k rows of filtered data, each of which is associated with a page block which must be loaded to check `total_items`. 

`CLUSTERING` should reduce the number of pages that need to be loaded, but I guess it's always going to be a large number. 

Using a covering index on `total_items` might be worth trying, because it is a low cardinality index (571 distinct values) so should fit in `work_mem` (if I understand correctly).  `actual_cost` (which is the other main column of interest) has 37,497 values so this may or may not also work. I think it's worth trying.
