### ISSUE TITLE
PPU: Text on x axis sometimes overlaps

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1012]
![image](https://user-images.githubusercontent.com/15875191/29625781-998c4b9e-8824-11e7-9ff8-786a68417384.png)
https://openprescribing.net/practice/E81061/0105010B0AAAAAA/price_per_unit/?date=2017-05-01
(Firefox, Chrome, IE11 tested)

(issue extracted from #555)

**Comment by evansd** [comment]
I can reproduce this in IE11 but not Chrome or Firefox. Still working on a fix.

**Comment by sebbacon** [comment]
If you've not considered it, might be worth trying to upgrade Highcharts.

Though ISTR it's a PITA for some reason...
