### ISSUE TITLE
All-England measures feedback

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1017]
This is to collect suggestions in one place

* [x] Round savings off to a sensible significant digit (applies wherever measures appear
* [x] Remove the mean line. This means it no longer makes sense to allow ordering by potential for improvement; we could perhaps redefine this as a measure of skew or spread?
* [x] Add measures-tag-filter box at the top
* [x] Add summary statistics at the top (total possible savings, ...)
* [x] Add mouseover text to all deciles

**Comment by sebbacon** [comment]
* [ ] There's a stray `<` in the page title

**Comment by HelenCEBM** [comment]
Some suggestions!
- [ ] Can the banner titles be sorted either big-to-small or small-to-big?
![image](https://user-images.githubusercontent.com/24392156/45617018-f84d9800-ba68-11e8-88fa-397f5c8cd45e.png)

- [ ] Can the headers be links to the measure pages? 
- [ ] For the individual measures it would be good to round to sensible significant figures 
![image](https://user-images.githubusercontent.com/24392156/45616883-a1e05980-ba68-11e8-86d9-ae97e5f0a118.png)

- [ ] Create an FAQ section for this page and link to it
- [ ] People might like to know how the measures are sorted (this could be put in the FAQs).

**Comment by HelenCEBM** [comment]
- [ ] **It would be good to have an All-England summary dashboard, similar to the new CCG and practice dashboards**
Mock-up of potential layout here: https://docs.google.com/presentation/d/1ixQ5OvAZnp4iGlCDSPcNid9iFUwtfYB9ub65cYUCbus/edit
(note there are some suggestions in the comments section)
![image](https://user-images.githubusercontent.com/24392156/45877122-bf793000-bd94-11e8-912c-fdab8ca349d2.png)


- [ ] **@Bengoldacre suggested tables/charts of savings at CCG/practice levels compared to 10th/50th centiles**, mocked up here: https://docs.google.com/spreadsheets/d/1Yy85_dpXzevwRqliQmIJ_eTUuBk0C92qoiIkHFWBiz8/edit#gid=295524793
I've excluded statins as we are yet to make the adjustment for the new generics. I've included Lyrica but the savings are not all achievable during the period of the patent/licencing issue (prior to July 2017).  We might need to think more about how to account for these changes if we choose to display this kind of chart - but could just limit to latest 12 months for example. 
![image](https://user-images.githubusercontent.com/24392156/45876999-5396c780-bd94-11e8-948d-7297d1c33f0c.png)

**Comment by HelenCEBM** [comment]
Short term plan: ignore the new dashboard page for now and make some small improvements to the full measures list page and deploy. @brianmackenna will then do some user testing. 

Improvements to make: 
- [ ] Rename "cost savings" title and wording, to make it clear these are low-priority savings
- [ ] Make the right-hand paragraph match the left hand side: 
Add cost savings figure (total savings from standard measures compared to ?10th centile) and add a button to skip down to where the measures begin.
- [ ] Change title to ".. across the NHS in England"
- [ ] Possibly make it easier to get to the low-priority measures?

**Comment by brianmackenna** [comment]
On an android device I selected the "compare all CCGs on this measure" - the first three graphs load immediately but no other graphs load giving the impressions the page is broken (you can scroll down the blankness)

Is this possibly related to another issue on this page when using a browser (I can't find an open issue but it has definitely been going on for at least a few weeks)
When you select "compare all CCGs" on the browser (e.g. [Keppra](https://openprescribing.net/measure/keppra/) ) it displays the first 6, then the page freezes for 5-10 seconds where you cannot scroll down. Once time elapses the graphs are all displayed.
