### ISSUE TITLE
Analyse Page - Total for NHS England 

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1019]
On the analyse page it would be helpful for people in national organisations (and others I imagine) to be able to see the "Total Items" and "Total Cost" on queries they do. It links to the All England update as well.

It would be good display as the "NHS England Total" for the 
a) month selected 
b) the last 12 months

Potentially in a box above/below the CCG/Practice graph

**Comment by brianmackenna** [comment]
Discussed at Datalab day and added to Top 3 priority. Discussion points

- Could the user select the timeframe of interest for the total e.g. to see the total for England for the last x months click here
- Potentially use the same format as NCSO calculator page _Over the last 12 months we estimate that price concessions have cost NHS England an additional £144,560,000 (of which £127,240,000 is in the current financial year)_
- Could total be added to the chemical and BNF sections trends

**Comment by sebbacon** [comment]
(=I personally think if someone wants custom sums over periods they should download the data and sum it in a spreadsheet - perhaps we could subtly point to this in the UI somehow, so point (2) is better ("last 12 months" / "current financial year to date")

**Comment by brianmackenna** [comment]
Happy with 2 as it is the most common query. Option 1 might be more related to #1099 

More generally I think we should be try to discourage spreadsheet option
a) because its an extra step for user
b) we actively lose out on credit points as some people will forget to credit us through carelessness (or expensive consultancy firms will intentionally not credit us!)

Also I am getting a lot of requests at NHSE which will be solved by this. It'll make me very happy :)
