### ISSUE TITLE
Query regarding practice mergers 

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1024]
From a user:

> I just tried to check the data for my own local practice, which is Dukinfield Medical practice. You don't show this. It was formed by a merger of The Hollies surgery and Davaar Practice well over a year ago. You only show Davaar. Is this because you haven't caught up with the change of name but are including all the data, or are you only showing half the data - the combined practice is using both sites as before.

In our current practices table:

* Dukinfield Medical practice does not exist
* Davaar Medical Centre is `P89021` and is Active
* Hollies `P89027` is Closed

This is reflected in the `epracurr.csv` we used in August for the June import.

@brianmackenna says:

> Dukinfield P89021 and Hollies P89027 is listed on epracur but not Davaar

Which I have verified. But I note the current NHS Digiral epraccur was uploaded on 31 August, after our last import.

It looks like the data on our website is correct, but NHSD hadn't updated `epraccur` with the name of the mergee practice.  That, or there was an issue with our import, but I doubt it.

Suggest waiting til next month and seeing if that's fixed then. @inglesp feel free to take a look sooner if you feel like it!

To close this issue: check that  [this practice](https://openprescribing.net/practice/P89021/) is now called Dukinfield Medical Practice.

**Comment by HelenCEBM** [comment]
Practice now has correct name
