### ISSUE TITLE
June alerts repeatedly failing 

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1028]
When the email alerts reach the phase where they screenshot analyse charts, they are repeatedly failing, e.g.:

```
frontend.management.commands.send_monthly_alerts.BatchedEmailErrors: Encountered 2 mail exceptions (showing last traceback only): `CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=11H,12A,11T&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button" /mnt/database/tmp/tmpdxNqUG.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 139, CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=12A&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button" /mnt/database/tmp/tmpTz9HnH.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 1`
```

Here are all the failed analyse url fragments in the June run. Note that there are two near-dupes there, which suggest the user noticed they weren't getting the alerts and re-subscribed.

* org=practice&orgIds=11H,12A,11T&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true
* org=practice&orgIds=11H,12A,11T&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button
* org=practice&orgIds=12A&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button
* org=practice&orgIds=12A&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true
* org=practice&orgIds=G81074&numIds=0408010AEAA&denom=total_list_size&selectedTab=chart

There was also one failed measure:

* practice/L81089/measures/ (for chart `#soluablepara`)

On re-running, the measure was sent, and all but two of the analyse alerts. The remaining two are for:

* org=practice&orgIds=12A&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true
* org=practice&orgIds=11H,12A,11T&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true

Both links timed out (at our [58s limit](https://github.com/ebmdatalab/openprescribing/blob/ec1e249b1adbab7aeb2895c30204d4fc9eeb1930/openprescribing/api/views_spending.py#L337-L339)) when I tried to access them just now.  Selecting all practices from a CCG is a [known](https://github.com/ebmdatalab/openprescribing/issues/294#issuecomment-280681512) performance issue, and selecting all practices from *three* is... unlikely to have a user-friendly outcome. The first query is less complex, but still times out.

Possible solutions:

* Delete those bookmarks, email the users apologising, worry about this later (hopefully our database structure review will address these kinds of performance concerns)
* Attempt to fix the proximate issue (look at indexes and/or clustering on the relevant view, etc)
* Up the database timeout beyond 58 seconds and see if it works then
* Do nothing

**Comment by evansd** [comment]
Given that these pages don't load at all in the browser I think the right thing to do is definitely to delete the bookmarks. The underlying performance issue should, to repeat our new catchphrase, be fixed with the MatrixStore.

Given that these were created on 2017-08-11 and have, presumably, never worked I'm not convinced that contacting the user is a good idea. But in case we decide to, the user id is 830 and the alerts concern Opioid Analgesic prescribing in South Gloucestershire.

**Comment by evansd** [comment]
I've now deleted these bookmarks. Here there are in case we decide we want to do something with them later:
```json
[
{
  "model": "frontend.searchbookmark",
  "pk": 63,
  "fields": {
    "name": "Items for Opioid Analgesics vs patients on list by practices in NHS SOUTH GLOUCESTERSHIRE CCG",
    "user": 830,
    "url": "org=practice&orgIds=12A&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button",
    "created_at": "2017-08-11T10:25:35.420Z",
    "approved": true
  }
},
{
  "model": "frontend.searchbookmark",
  "pk": 62,
  "fields": {
    "name": "Items for Opioid Analgesics vs patients on list by practices in NHS BRISTOL CCG + practices in NHS SOUTH GLOUCESTERSHIRE CCG + practices in NHS NORTH SOMERSET CCG",
    "user": 830,
    "url": "org=practice&orgIds=11H,12A,11T&numIds=4.7.2&denom=total_list_size&selectedTab=summary&hideOutliers=true&source=button",
    "created_at": "2017-08-11T10:24:11.583Z",
    "approved": true
  }
}
]
```
