### ISSUE TITLE
Make sure measures contain links to guidance where relevant

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1034]
Add links to guidance for:
- [x] Fungal nail
- [x] KTT12 (long acting insulin)
- [x] Gluten free
- [x]  Nebivolol
- [x] KTT9 (abx volume)
- [x] KTT3 other lipid-modifying drugs
- [x] Keppra - link to BSA, MHRA
- [x] Trimethoprim/nitrofurantoin
- [x] KTT9 cephalosporins
- [x] Lyrica
- [x] Non-preferred NSAIDs /COX-2i
- [ ] Extended release quetiapine
- [x] Soluble/effervescent paracetamol and co-codamol
- [x] High cost ARBs ("NICE guidance for treating high blood pressure recommends that the low-cost versions should be used.")
- [x] high dose corticosteroids - any links for the COPD guidance?
- [ ] Tramadol (this is a cost one but can we link to anything? "Modified release and non-standard tramadol preparations vary widely in cost. Generic tramadol 50mg capsules are low-cost. Ideally modified-release and other high cost preparations should be reserved for patients who have compliance issues.")

**Comment by richiecroker** [comment]
quetiapine now retired.
probably nothing we can link to about tramadol.
others done

**Comment by HelenCEBM** [comment]
thanks @richiecroker !
