### ISSUE TITLE
Fix link to lp breakdown pages

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1041]
The link to the breakdown into individual LP measures from here https://openprescribing.net/ccg/99P/measures/#lpzomnibus doesn't work

... you get https://openprescribing.net/ccg/99P/?tags=lowpriority which is not longer valid so just shows the new dashboard. It should direct you to here instead https://openprescribing.net/ccg/99P/measures/?tags=lowpriority

**Comment by sebbacon** [comment]
Similarly the link to a CCG page from the "all CCGs for a measure" page should be linking to `/ccgs/<ccg>/measures/`, not `/ccgs/<ccg>/`
