### ISSUE TITLE
Make browser for dm+d data

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1057]
Code at https://github.com/ebmdatalab/openprescribing/tree/dmd-browser, and currently on staging at http://staging.openprescribing.net/dmd/.

TODO:

Simple things:

- [x] Only include valid records
- [x] Show ticks/crosses instead of True/False
- [x] Show parent objects at top of page
- [x] Order child objects by name/descr
- [x] Order search results by name/descr
- [x] Fix pluralisation of "Moietys"
- [x] Only show "invalid" field for invalid records
- [x] Paginate search results
- [x] Allow restricting search to one category
- [x] Add "about" page describing data
- [x] Import weekly
- [x] Show date of import at bottom of page
- [x] Test import steps
- [x] Test views

Less simple things:

- [x] Work out how to link `Presentation`s to the `[AV]MPP?` objects (#947)
- [x] ~Generate `dmd_product` (materialised?) view~
- [x] Move to `dmd` app and update existing models and FKs appropriately
- [ ] Do proper full-text search
- [x] Offer search by other fields

**Comment by brianmackenna** [comment]
Very slick and pleasing to the eye. Couple of suggestions on first use


- A button to generate a report on the analyse page for what you are actually looking at on the dm+d browser
- Compare multiple products side by side

**Comment by inglesp** [comment]
Thanks @HelenCEBM.

> If you search for something common you get a lot of results under several subheadings...

Yes, I plan to do some pagination.

> Perhaps we could allow users to select from a dropdown whether they only want one of the possible subheadings (or auto-select "all"), or offer filter by other options such as route or formulation?

Searching just one category (VTM/VMP/etc) would be easy.  (I've added it to the TODO list above.)  Getting a nice interface working to allow filtering by other things would be harder and I'd only want to spend time on this if we were sure it was going to be useful.

> We could explain better what some of the subheadings mean

Yes!  At the moment this only really makes sense to people who already understand the data model, so we'll need a page to document this.

**Comment by inglesp** [comment]
Thanks @brianmackenna.

> A button to generate a report on the analyse page for what you are actually looking at on the dm+d browser

This would be a good feature and easy to do... once we've nailed down once and for all how to link BNF codes to dm+d objects (see #947).

> Compare multiple products side by side

This might be a bit fiddly to implement.  One for the future?

**Comment by sebbacon** [comment]
Missing from the todo list but previously discussed - once we have linked BNF codes, we should default to only showing "available" items *that have BNF Codes*.  This will remove a whole mass of irrelevant products from the lists and make it all more navigable.

**Comment by sebbacon** [comment]
P.S. when we have linked BNF codes it would be relatively trivial to show a little spark chart of spending for that code.

**Comment by inglesp** [comment]
At the moment our dm+d browser only shows the fields that're present in the dm+d data dump we import, and for each dm+d object there are several fields that are not present (such as "Product Prescribing Information" in 1107).

We could have a "show all fields" toggle on each page, which might make comparisons easier.  I suppose we'd show a blank value for fields that are not present.  I'd like this toggle to be off by default.

If comparing objects is something that we're going to be doing a lot of, it might be worth implementing a side-by-side view, but that's for a future implementation.

**Comment by brianmackenna** [comment]
The toggle is a good suggestion and would serve the purpose for now. I think it is useful for people not looking at dm+d (which is me now but is rapidly changing) to ensure they can see the total info that could be there.

Definitely leave compare side by side for a bit. I think I mainly use that for the problem above, i.e. trying to work out the difference between products. If all products have the same standard categories it should be much better.

**Comment by brianmackenna** [comment]
Looking very very good.  One suggestion;
Add dmd search to product page. From a product (see [here](https://openprescribing.net/dmd/vmp/4030411000001107/) there is no obvious button to search dm+d. This is an issue if you arrive to it via a link

One comment;
Proposed weekly import: It would be a nice touch to do it weekly but is this necessary? I know we will automate as much as possible but my observation is that with other data streams you still have to wrestle a little bit with. System suppliers only have to update every two months for EPS spine requirements. It would be a nice touch to do it weekly. Would monthly suffice before prescribing data import?

**Comment by inglesp** [comment]
Closing this, as all TODOs ticked off except full text search which we can revisit if users ask for it.
