### ISSUE TITLE
MAILGUN_SENDER_DOMAIN looks wrong, but it somehow still works

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1070]
The sender domain config value for Mailgun is set to a single-member tuple rather than a string (note the trailing comma here):
https://github.com/ebmdatalab/openprescribing/blob/739b1677738186827457d4ba7cb69d8bc09c1114/openprescribing/openprescribing/settings/production.py#L56

According to the Anymail docs this is incorrect. But clearly we are able to send email. There's nothing in the Anymail code which converts this value, so maybe it's just that Mailgun's API silently converts it.

In any case, I'd like to change this but I want to make sure I'm not missing something first.

**Comment by sebbacon** [comment]
I'm not aware of any reason not to fix.
