### ISSUE TITLE
IE8: buttons on homepage don't work

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#108]
The big blue buttons ("Find a practice", "Start analysing" etc) don't do anything.

**Comment by annapowellsmith** [comment]
sigh, that's probably because of #110 - we maybe just need to remove the video

**Comment by sebbacon** [comment]
No, it's not -- I've tried that (conditional fix to follow) and the buttons still don't work.

**Comment by sebbacon** [comment]
It's because of the button. This works:

    <a href="#1">Thing</a>

And this doesn't:

    <a href="#1"><button>Thing</button></a>
