### ISSUE TITLE
Ansible build failures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1088]
During task `TASK [roles/setup : Install system packages]` (basically `apt-get install <stuff>`), we get  a [failure](https://travis-ci.org/ebmdatalab/openprescribing/jobs/435720423) `/dev/stdout: resource temporarily unavailable`

Known to be failing 2018/10/01 18:18; known to be working on 2018/09/27 14:18

**Comment by sebbacon** [comment]
[Heres](https://github.com/moby/moby/issues/13052#issuecomment-165469853) a similar issue hypthesising it's related to network I/O between docker containers.

I would also like to consider [this similar issue](https://www.mail-archive.com/issues@mesos.apache.org/msg44461.html) suggesting it's a pipes+buffer related issue.

**Comment by sebbacon** [comment]
This is looking healthier now. Leaving open to monitor for a week.

**Comment by evansd** [comment]
It's been 18 days and no more issues so closing now.
