### ISSUE TITLE
IE8: only the "All CCGs" tab is visible on analyse page

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#109]
![missingtabs](https://cloud.githubusercontent.com/assets/211271/16874741/f963ce6e-4a92-11e6-8819-a561ec9f7953.png)

**Comment by annapowellsmith** [comment]
That's deliberate^W graceful degradation - the time series and maps are too slow to render, they cause slow running script errors.

**Comment by sebbacon** [comment]
I've just seen that [this is deliberate](https://github.com/ebmdatalab/openprescribing/blob/2954a243684984124265bd4bfca563ece1d1282d/openprescribing/media/js/src/chart.js#L128-L138)
