### ISSUE TITLE
Chemical Trend Tool - Displaying same number for Items and Cost

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1107]
From doorbell
>  - the item value and the spend value seems to be the same figure when I search using the Trend tool. Could you tell me if this is an issue at my end or with the tool please?
[](https://openprescribing.net/chemical/)
> 
This does appear to be the case. 
For example on [Lactulose](https://openprescribing.net/chemical/0106040G0/) the items in July = 238 440 and the spend = £238 440.

The same issue is happening on the BNF sections trend tool. 
See [Proton Pump Inhibitors page](https://openprescribing.net/bnf/010305/)

**Comment by inglesp** [comment]
The API is returning something sensible, eg https://openprescribing.net/api/1.0/spending/?format=json&code=0101010C0.

So I suppose the problem is with the JS.

**Comment by inglesp** [comment]
I can't reproduce this locally.

**Comment by inglesp** [comment]
I can't spend any more time on this right now.

**Comment by inglesp** [comment]
I *can* reproduce this locally -- I hadn't rebuilt the JS.

**Comment by inglesp** [comment]
This was introduced in e1890111e0cf8315d7b4a43733ff0af40c9313cb (Upgrade to Highcharts 6.1.3 ).  Going by the timestamps on the filesystem on largeweb2, this has been broken since 2018-09-27.

I will spend a little bit of time investigating, but may need to wait for somebody who knows what they're doing with JS.

**Comment by inglesp** [comment]
When you change from viewing items to viewing spending, `barChart.updateChart` gets called as expected, which calls `barChart.getYValueOfData`, which returns its input, updated with the `y` property set correctly.  This all seems to work correctly.

But then either `chart.series[0].setData(newData, false)` doesn't update the chart's data, or `chart.redraw()` doesn't redraw the chart.

I don't have any more time today.  @evansd can you take a look tomorrow?

**Comment by evansd** [comment]
@inglesp I certainly can. It looks like you've done 80% of the hard work already. Thanks!
