### ISSUE TITLE
Sign up form layout on homepage is borked

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1122]
![staging openprescribing net_](https://user-images.githubusercontent.com/19630/47166799-e4f64c80-d2f4-11e8-98b6-84899a144ed9.png)

**Comment by inglesp** [comment]
Presumably related to 92cd639fbba30f9293e2931e9e5df2a901053164.

**Comment by evansd** [comment]
Yes, I've just realised that. The simplest thing would be to make both forms "vertical" i.e. label above control. Would you be happy with that?

**Comment by inglesp** [comment]
Yes.  Hands full now, but can do this tomorrow.
