### ISSUE TITLE
Consider using "Dependabot" to help us keep dependencies up to date

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1131]
[Dependabot](https://dependabot.com/) is free for public repos and looks quite useful. It automatically creates PR to update dependencies, with links to relevant changelogs. By default, it "drip feeds" you PRs initially to avoid swamping you with updates.

In my experience, regularly updating dependencies is far less painful than leaving it for ages and trying to do big bang upgrades. If nothing else, when problems do arise it's much more obvious which package is the culprit. But it's a hard discipline to maintain and this service would seem to make it a lot easier.

**Comment by sebbacon** [comment]
Great idea, nice service, I see no downside to trying it!

**Comment by evansd** [comment]
We are now doing this.
