### ISSUE TITLE
We've lost historic presentation mappings

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1153]
About 2 months ago, I accidentally deleted the Presentation table.

Today I noticed it no longer has any non-current entries in it, or replacement information (i.e. `is_current` column is always true, and `repaced_by_id` is always null).

I presume we have to run this to remedy

https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/generate_presentation_replacements.py

However, we need to remind ourselves if this means we need to fix any other data (e.g. will our measures be wrong because they are not mapping old to new codes in bigquery any more?)

**Comment by inglesp** [comment]
After fixing the presentation table, we'll need to recompute all derived data.

Plan:

- [ ] Run `generate_presntation_replacements` -- this will set `is_current` and `replaced_by` correctly, and will update the `bnf_map` table in BQ
- [ ] Run `create_views`
- [ ] Run `import_measures`
- [ ] Run `import_ppu_savings`

@sebbacon Anything I'm missing?

**Comment by sebbacon** [comment]
Looks good, thanks

**Comment by inglesp** [comment]
`import_ppu_savings` failed because `ImportLog.objects.latest_in_category('prescribing').current_at == ImportLog.objects.latest_in_category('ppu').current_at`

Will delete `ImportLog.objects.latest_in_category('ppu')` and try again.
