### ISSUE TITLE
It should always be possible to see selected practice(s) on spine chart

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#117]
We've had a report that when using the Highcharts "print" function, the histogram labelling does not always show the currently selected practice(s).

**Comment by annapowellsmith** [comment]
Can we have a few more details?

**Comment by annapowellsmith** [comment]
From discussion - the bar for the practice is always present and highlighted (assuming it is non-zero) but the axis tick/label may not be present, because Highcharts will automatically hide some labels to save space. This confused at least one user, who thought his practice was missing.
