### ISSUE TITLE
Still some measure URLs wrong

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1181]
In analytics data, we're seeing requests for `/ccg/13T/?tags=lowpriority`, which should be `/ccg/13T/measures/?tags=lowpriority` (e.g. on 10 November). Investigate, and inform @HelenCEBM, as this may be relevant to CCG analysis.

**Comment by evansd** [comment]
Here's the related issue where I _think_ fixed the internal links. But maybe there are external links, or other internal ones I missed. Can we see in the analytics data where they're being referred from?

**Comment by evansd** [comment]
I think we should definitely set up redirects, I'm happy to take a look at that.

In general I suppose there's a real difficulty in running RCTs with a website that isn't frozen in time, and I'm not sure what the best way of dealing with that is -- other than to try not to break anything!

**Comment by HelenCEBM** [comment]
Appears to have been fixed
