### ISSUE TITLE
Switch to using psycopg2-binary package

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1183]
This shouldn't involve any behavioural changes, it's just a change in the way Psycopg2 is being packaged. See: http://initd.org/psycopg/docs/install.html#binary-install-from-pypi

We want to fix this mainly because it stops the annoying warning message we get at the moment.

**Comment by evansd** [comment]
The proper explanation is here:
http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

I've been going back and force on what I think is the best option here. At the moment I feel we should just stick with the binary install option (which involves changing the package name to psycopg2-binary). This is what we've been using at the moment and it doesn't seem to have caused us any problems. If we did get a random segfault then the process manager would restart the web process and apart from a failed request things would carry on working. That doesn't seem like a big disaster to me. And compiling psycopg2 from source is just more faff.

Definitely open to other views on this though.

**Comment by inglesp** [comment]
Would we know if there was a segfault during a request?  We've almost certainly never seen one during nightly runs of the end-to-end pipeline tests.

My vote would be to use the binary installation and come back to this if we see problems.
