### ISSUE TITLE
There are active GP practices in things that are not CCGs

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1248]
According to the data in `epraccur.csv`, there are three active GP practices that belong to things that are not CCGs:

```
>>> for p in Practice.objects.filter(setting=4, status_code='A').exclude(ccg__org_type='CCG'):
...   print p.code, p.ccg.code, p.name
... 
Y04664 RXA THE WILLASTON SURGERY
Y03454 NMS CGL ASPIRE
A81630 112 FOUNDATIONS
```

There are also 39 closed GP practices that belong to things that are not CCGs:

```
>>> Practice.objects.filter(setting=4).exclude(ccg__org_type='CCG').count()
42
>>> Practice.objects.filter(setting=4).exclude(ccg__org_type='CCG').values('status_code').annotate(Count('status_code'))
<GeoQuerySet [{'status_code': u'C', 'status_code__count': 39}, {'status_code': u'A', 'status_code__count': 3}]>
```

The data comes from `epraccur.csv`, which is [published quarterly by NHSD](https://digital.nhs.uk/services/organisation-data-service/data-downloads/gp-and-gp-practice-related-data).

When this came up before (#323) it was decided that we wouldn't address it.  Eighteen months later, do we want to revisit this?

**Comment by HelenCEBM** [comment]
We've never had any requests for this as far as I'm aware. Something to consider in STP/regional dashboards possibly, since some of these non-CCG orgs might be part of STPs. But I suggest close again?
