### ISSUE TITLE
Sept 2018 alerts

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1270]
Taking into account #1087, and following merging #1264, am currently sending Sept 2018 alerts.

We expect two kinds of failures

1. Related to timeouts, mainly on complex analyse forms per #1028. These will result in batched/deferred errors, and will require the process to be restarted multiple times to see if we can get through them
2. Related to "disappearing" images per #1087. These will only log errors, and not cause the process to halt like timeouts from #1028 would. 

Therefore:

* Monitor the screen session that is sending out alerts; repeatedly restart the process, noting any errors of type (1) above in this issue
* Assess logging of errors of type (2); is it the same images each time which fail?

Discuss next steps here, including considering rolling up & closing linked issues here

**Comment by sebbacon** [comment]
Type (2) errors are being logged to `/webapps/openprescribing/logs/gunicorn.log` at `ERROR` level. They start at `2018-12-12 11:22:48`

**Comment by sebbacon** [comment]
* Make the email alerts send a message to slack when they've finished

**Comment by sebbacon** [comment]
Exciting new error - segfault in phantomjs:

```
1   0x1b67967 /usr/local/bin/phantomjs() [0x1b67967]
2   0x1baac35 /usr/local/bin/phantomjs() [0x1baac35]
3   0x1b9369c /usr/local/bin/phantomjs() [0x1b9369c]
4   0x18970ad /usr/local/bin/phantomjs() [0x18970ad]
5   0x1896ace /usr/local/bin/phantomjs() [0x1896ace]
6   0x1896ddf /usr/local/bin/phantomjs() [0x1896ddf]
7   0x18fe47b /usr/local/bin/phantomjs() [0x18fe47b]
8   0x7ff3583f1135 [0x7ff3583f1135]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault
```

**Comment by sebbacon** [comment]
So only 2 Org Bookmarks got sent this time. It looks like a reproducible error for these CCGs.

Now trying to send one of them, individually, to me: `./manage.py send_monthly_alerts --ccg=06V --recipient-email=seb.bacon@gmail.com`, and sure enough:

```
2018-12-13 11:17:39,914 ERROR [frontend.management.commands.send_monthly_alerts:175] send_monthly_alerts 4293 139955946575616 File at /mnt/database/tmp/tmpMlNCb2.png empty (generated from url /ccg/06V/measures/)
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 168, in callback
    org_bookmark, stats, tag=now_month)
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 656, in make_org_email
    get_chart_id(most_changing['declines'][0]['measure'].id)
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 495, in attach_image
    raise BadAlertIimageError(msg)
BadAlertIimageError: File at /mnt/database/tmp/tmpMlNCb2.png empty (generated from url /ccg/06V/measures/)
```

By contrast, doing the same for `99P` works.

**Comment by evansd** [comment]
Closing as doesn't look like there's anything actionable here.
