### ISSUE TITLE
Lutein and Antioxidants Measure

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1271]
On the site the following [measure](https://github.com/ebmdatalab/openprescribing/blob/9a577c06b74328b4dc92b5005e113be59f026cc8/openprescribing/frontend/management/commands/measure_definitions/lplutein.json) is not displaying on practice and CCG dashboards

However the title of the measure does display on our [all measures page](https://openprescribing.net/measure/) 

The measure is still relevant so would be god to get live again as people review low priority as a result of consultation

**Comment by HelenCEBM** [comment]
This seems to be fixed e.g. https://openprescribing.net/practice/E87024/measures/?tags=lowpriority
