### ISSUE TITLE
Inconsistent listing of closed practices

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/openprescribing#1279]
The lists of practices are not consistent in terms of stating which practices are closed/dormant. This example lists where they are closed: https://openprescribing.net/ccg/03N/measures/
...but this one doesn't: https://openprescribing.net/ccg/03N/ 

Additionally, it might be make things clearer in the below example to split the numbers into open and closed practices?
![image](https://user-images.githubusercontent.com/24895935/50087202-3177de80-01f7-11e9-8bba-7600a18f6c1d.png)

**Comment by HelenCEBM** [comment]
This has been fixed
