### ISSUE TITLE
Price Concessions Calculator

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1284]
Some suggestions

- On  the [ALL England page](https://openprescribing.net/all-england/concessions/) the normal cost of GTN is described as £95 for  12,114 pumps.
![image](https://user-images.githubusercontent.com/40460354/50208722-ddd9d200-0369-11e9-8526-bcc90f8cf59a.png)

Tariff prices are [here](https://openprescribing.net/tariff/?codes=0206010F0AACJCJ) but I wonder is it to do with the odd pack sizes?

- Buprenorphine there are significant amount of costs of Buprenorphine that go through "non-CCG routes" as Local Councils are generally responsible for funding it. Local councils and public health departments don't have access to the other NHS data sources commonly used on prescribing (PrescQIPP and ePACT2). My preference would be for us to make this information available in some way either on this dashboard or another method so this data is visible as the Buprenorphine has attracted a huge amount of interest. It is also proportionally a much bigger part of the relevant public health budget and will likely lead to cuts in other services.

Text on page

> Price concessions are a short term agreement by the NHS to pay for more expensive versions of a medicine because the cheaper version has temporarily gone out-of-stock.

Can this be changed please? Its a bit of a pedant point but there is actually stock obtainable when NCSO 
is applied - if there is temporary stock shortage no concession is paid as no product is dispensed.
I suggest
 _Price concessions are a short term agreement by the NHS to pay for more expensive versions of a generic medicine. This occurs because sometimes pharmacy contractors have to dispense an equivalent product that is only available above the set Drug Tariff price. Examples of why this may happen are changes in the value of sterling or manufacturers temporarily suspending production of a generic medicine meaning there is less supply_

- Financial reporting - CCGs will typically report the figures in one of two ways
 a) in the last 12 months we have spent an additional x on NCSO
 b) in the financial year to date we have spent/estimated to spend an additional x in the first x months (only available data and due to the nature of NCSO is it impossible to predict or average to get a 12 month estimate)
 It would be good if a total box could be placed on the page to reflect b) and a) if possible

- Latest month - due to the graphs updating daily we should probably indicate that the latest month is incomplete. Suggest doing it by colouring differently.

- Stray space:
![image](https://user-images.githubusercontent.com/19630/50214133-6874fe00-0377-11e9-9638-b358addd6e8d.png)

- [ ] GTN

- [ ] Buprenorphine

- [x] Text changes

- [x] Financial reporting

- [x] Latest month incomplete

- [x] Stray space

**Comment by evansd** [comment]
> Buprenorphine there are significant amount of costs of Buprenorphine that go through "non-CCG routes" as Local Councils are generally responsible for funding it. Local councils and public health departments don't have access to the other NHS data sources commonly used on prescribing (PrescQIPP and ePACT2). My preference would be for us to make this information available in some way either on this dashboard or another method so this data is visible as the Buprenorphine has attracted a huge amount of interest. It is also proportionally a much bigger part of the relevant public health budget and will likely lead to cuts in other services.

It turns out we already have dashboards for organisations that aren't standard GP practices, we just don't list them in the practice search. For example:
https://openprescribing.net/practice/Y06021/

And this also has its own concessions dashboard where you can see the Buprenorphine costs:
https://openprescribing.net/practice/Y06021/concessions/

What we don't have is anything that groups these together at e.g. local authority or national level. That's a wider piece of work, but something it definitely seems worth addressing. So I'm splitting that into a new issue.
