### ISSUE TITLE
Add JavaScript "send us feedback" overlay thing

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#130]
One of the generic ones

UPDATE: To clarify the background... We would like somewhere that users can send feedback in an instant, frictionless way. I believe are various JS plugins that make it easy for users to do this, without having to leave their workflow - typically these present as an unobtrusive popup on the page. We'd like one that simply sends us an email, rather than a full CRM system.

**Comment by annapowellsmith** [comment]
this could work? https://www.intercom.io/

**Comment by sebbacon** [comment]
That Intercom one seems like a different use case from ours -- it's more about handling high volumes of support, and/or generating marketing leads through live chat, I think.

I think that (at this stage) we simply want to encourage people to let us know if something is wrong or could be better. Is that right?

I wonder if it makes more sense to just add a top-level menu item "Get in touch" or a ribbon or something, that is just an HTML form-to-email, to a shared inbox (e.g. using Google Groups as a [Collaborative Inbox](https://support.google.com/a/answer/167430)?

(We should probably do the Collaborative Inbox for general support in any case)

**Comment by annapowellsmith** [comment]
Sorry, missed this comment!

Yes, agree that intercom is probably different use case.

But I quite like those little overlay "send us feedback" popups that appear at the bottom of the page in a visible but not-too-intrusive way.... like the intercom UX. Hopefully we could find a commodity javascript one that could go to our email address. 

I think collaborative inbox can be Lisa's decision, I want to start handing support over to her.

**Comment by annapowellsmith** [comment]
Oh and to answer your question, yes at the moment the user need is just "have minor issue or thought, have somewhere obvious I can send it in <2 seconds", not full-on customer support.

**Comment by annapowellsmith** [comment]
Stumbled across this one randomly https://userdeck.com/conversations

**Comment by sebbacon** [comment]
Although Userdeck is cheap and nice, I'm not convinced about locking ourselves into a kitchen-sink-user-ticketing-and-conversation-system when we still don't know how Lisa will be interacting with it.

[Here's](http://www.jqueryscript.net/demo/Minimal-Side-Feedback-Form-Using-jQuery-Bootstrap-feedback-js/) a really lightweight popover that we could just have send to an email address - what do you think?

http://www.jqueryscript.net/demo/Minimal-Side-Feedback-Form-Using-jQuery-Bootstrap-feedback-js/

**Comment by annapowellsmith** [comment]
ok! my only concerns would be 

i. is it quick to customise style
ii. does it work x-browser
iii. is spam filtering now good enough that we don't get bot spam

i guess if the form is added to the DOM after page load then iii is not an issue. 

it would be nice if the overlay could be made a little more obviously live - a bit of shadow on the page might do the trick, or some fancy CSS so it appears after a few seconds, does a little jump, or something like that... but tasteful :)

**Comment by sebbacon** [comment]
WIP

![in](https://cloud.githubusercontent.com/assets/211271/17481997/a8578ab8-5d77-11e6-9ed4-2581f102cb94.png)
![out](https://cloud.githubusercontent.com/assets/211271/17481998/a9a7679e-5d77-11e6-9a08-a2bbac147aa0.png)
