### ISSUE TITLE
Clarify process for adding dependencies for measures on BQ views / fix e2e tests

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1300]
A number of measures depend on calculations done off the books in various BQ views:

* `opioid_total_ome`
* `practice_data_all_low_priority`
* `pregabalin_total_mg`
* `vw__median_price_per_unit`

These views should be in the `measures` dataset.  However, `vw__median_price_per_unit` is in the `hscic` dataset.  This is the reason the end to end tests are currently failing.  (See e5546f633da0666064e9bb53bf8579fc0c490b69.)

Additionally, the SQL for these views should be stored in version control, so that we have (a) reproducibility (so that we know how a measure was calculated), and (b) testability (specifically, the end to end tests verify that all the measure values can be computed).

The SQL in BQ for `vw__median_price_per_unit` has changed recently, but the corresponding SQL in the git repo hasn't been updated.  This means that when the next monthly import is done, any changes in BQ will be lost.

This is mostly a communication and workflow problem -- I expect that Rich doesn't know that we keep the SQL in version control!

We should have a chat about this early in the new year.

**Comment by inglesp** [comment]
The version of the view in the `hscic` dataset includes `bnf_name` in the `SELECT`ed columns, while the version of the view in the `measures` dataset `ORDER`s results by `bnf_code, date`.

@richiecroker:

* Can you confirm that you made the changes to the SQL in the view in the `hscic` dataset, and that you're happy that this is the "correct" SQL?
* Are you happy with me deleting the view in the `hscic` dataset?

I will then:

* update the SQL in the `measures` dataset;
* update the checked-in SQL;
*  add a comment to the checked-in SQL for all the views to say that any changes made directly in BQ should also be made to the checked-in SQL.

**Comment by richiecroker** [comment]
not sure if I changed the SQL, or if it was @seb - but happy to do what you have to do!
