### ISSUE TITLE
Test the format of the new prescribing files

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1320]
As from 17th /18th  January 2019 the data we download will be from the new data source (I believe the same URLs, though)

They have highlighted three differences:

1. English prescribing data will now include items dispensed in England, Scotland, Wales and
the Isle of Man (only English prescribing dispensed in England, Scotland and the Isle of
Man is currently included)
2. The data included in the column called ‘Area_Team_Name’ has had the word ‘Team’
removed from the data (the column name continues to include ‘Name’)
3. Data from CCG’s that have closed are now included

The file is at `/mnt/database/tmp/20190110_1547116564417_Detailed_Prescribing_Information.zip`   There is also a `BNF code file at /mnt/database/tmp/20190108_1546960711417_BNF_Code_Information.zip` about which our correspondent said:

> I have attached the differences document and the BNF file as the source of that file has changed but the data and extract has not.

We need a plan about how to deal with this. I'm thinking diffing the fields we care about might be a good way of doing it - possibly in SQL in BigQuery?

**Comment by sebbacon** [comment]
Most of the differences are described in [a document they supplied]((https://github.com/ebmdatalab/openprescribing/files/2772531/Improvements-and-differenceswebsiteV5.1.docx))  (note this is v5, older versions are floating around on the internet).

Highlights:

* Includes English rx dispensed in Wales 
* Everything prescribed outside England and dispensed in England
* GP's location at *end of month* used consistently, rather than beginning of month or time of claim
* Prescribing still not linked to a practice 6 months after a prescriber left a practice is classed as "national unidentified" rather than whatever their last practice was
* Actual Cost discount applied is for the current month rather than the previous month

In addition, not mentioned in that document:

* Data from CCG’s that have closed are now included

**Comment by sebbacon** [comment]
The overall impact of these differences is very small in most cases, though we could potentially do some work to assess it more formally, I'm tempted just to press ahead and deal with any surprises post hoc.

**Comment by evansd** [comment]
Yes, I agree. I don't think it's worth spending more time doing upfront analysis at this stage.

**Comment by inglesp** [comment]
The only thing I could think of doing is recomputing the measures for October, and looking for differences.  This should be doable quite easily on staging, but I'm not sure it's worth it.

**Comment by sebbacon** [comment]
Keeping this open while we finish correspondence with BSA about differences.

GP movements explain a number of the differences identified, but not those where the total quantity dispensed across all of England has changed.

Reductions in total quantity could be explained by the introduction of "national unidentified" (I believe these are not recorded in the dataset supplied); increases could be explained by the inclusion of data from closed CCGs.  However, I'm checking this with BSA too. 

* [CSV of differing presentations](https://gist.github.com/41d690b283a172fc12b198e1784554cf)
* [SQL used to generate differences](https://gist.github.com/sebbacon/3aea7489776fb4a833ec67a5c838bd73)
* [detailed sample of some of the presentations](https://gist.github.com/ef802e53c83d5ba4b44f37afab5c6769)

Note the data provided was for October 2018; we were comparing the "new" and "old" data for that month.

**Comment by HelenCEBM** [comment]
Any update @sebbacon ?

**Comment by sebbacon** [comment]
Have just chased
