### ISSUE TITLE
"Latest prescribing" query slow

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1328]
Quick drive-by observation (which I should've noticed on review, sorry)

I noticed this query takes approx 5 seconds when run against `vw__presentation_summary_by_ccg`, as it does a seq scan:

https://github.com/ebmdatalab/openprescribing/blob/0ac4206a6dab8d215932b5ae9139e0ae94ccfae6/openprescribing/frontend/views/spending_utils.py#L233-L235

In fact, the conventional way to do this query elsewhere in the code is to rely on the ImportLog for the last date:

https://github.com/ebmdatalab/openprescribing/blob/0ac4206a6dab8d215932b5ae9139e0ae94ccfae6/openprescribing/frontend/views/views.py#L909-L910

As it's already called in `entity_home_page`, perhaps this could even be passed through to the NSCO-computing code...?

**Comment by evansd** [comment]
Fixed in cf78b4c064900d1a4816a919b638f55a6e5b7cec
