### ISSUE TITLE
Make design improvements to organisation dashboards

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#133]
Henry was very positive about the new dashboard design, said the new versions had already done most of what he was planning to suggest.

But here are of the possible further improvements we discussed. I've divided these into obvious wins, and things that need testing - but feedback welcome.

Obvious wins (imo)
- Make organisation metadata (address, map) smaller (and on CCG pages, no need to show list of GPs, just have number and then expandable list if we really want it)
- Make the important intro text bigger (h1, para) 
- Cut the unnecessary bits of that intro text (some of it can be collapsed)
- Make most of the text on the page bigger - too much small print
- Smooth graphs by default (NB this is non-trivial so probably needs a separate issue)
- Move the disclaimer to the bottom
- Use `<details>` tags to collapse/ expand details in the chart text
- Present clear actions that the user can take, and justify why they are worth taking (needs discussion with Croker, for non-cost-saving measures)
- Add links to explanatory URLs where available (e.g. for KTTs)

Need testing but worth doing so we can test (imo):
- Make the savings suggestions numbers vaguer - around £38k, not a precise number
- Experiment with presenting the savings suggestions per week / month / year, see what works best
- Make the median thicker
- ~~Use shading for deciles, not lines - [like this](http://www.astrostatistics.org/_/rsrc/1342861946353/projects/solar-statistics/3-data-analysis/TSquantiles.png)~~
- Have an overall visualisation in the intro for the number of measures worse than the median - a green-to-red indicator with an arrow, for example
- It's really confusing having some measures good when high, and some good when low. Why not just flip the second ones so they're all consistent? (NB this is more work obviously) - try testing this, try testing with good=100 and with good=0 and see which makes more sense

I also wonder if each measure should have a thumbs up or thumbs down, to simplify further, but we can test that. 

Henry says the way to test these is to (i) ask people comprehension questions about the page and see whether they can answer them, or (ii) check the time it takes the user to do something (e.g. identify the single thing they could change for biggest cost saving). In other words, don't just ask what they _think_ about the design.

And one note I can't read :)
- Don't present as "worse than" (todo: clarify!)

For the record, we also chatted about what happens when we have 80-100 measures, in the future. Henry suggested tabs for "where you're doing well", "where you're doing badly", and "everything else" - so the actionable measures are highlighted, and we effectively filter out the less interesting stuff.

**Comment by sebbacon** [comment]
Feedback:

* I'd consider going further than making the intro text about the organisation smaller, and actually hide all but the name by default 
* I actually found the example with shading for deciles harder to read than the current lines. Could be the choice of palette, though.
* Reducing the amount of text overall would be a big win, but also hard to do -- might be worth iterating that between all of us a bit?
* Re. the final point -- I even wonder if that's worth doing sooner, on the grounds that actionable data is the stuff we really care about, and less noise is good.

**Comment by annapowellsmith** [comment]
Thanks! 

I'll poke around with the metadata and intro text and see how it looks. 

I agree with you on shading (and it would also involve Highcharts work) so let's park that for now. 

Yes let's iterate on reducing text - tho I don't think it's necessarily that hard, will take a look. 

Good point re final point - will take a look.

**Comment by annapowellsmith** [comment]
Done a lot of this on a branch and pushed to staging for testing https://github.com/ebmdatalab/openprescribing/tree/improve-organisation-dashboards-%23133

**Comment by lmfrench** [comment]
Stuff that hasn't been done:
- Make organisation metadata (address, map) smaller (and on CCG pages, no need to show list of GPs, just have number and then expandable list if we really want it)
- Smooth graphs by default (NB this is non-trivial so probably needs a separate issue)
- Use details tags to collapse/ expand details in the chart text
- Present clear actions that the user can take, and justify why they are worth taking (needs discussion with Croker, for non-cost-saving measures) - part of #135 
- Add links to explanatory URLs where available (e.g. for KTTs)  - part of #135 
- [suggested] Make the savings suggestions numbers vaguer - around £38k, not a precise number    
- [suggested] Experiment with presenting the savings suggestions per week / month / year, see what works best
- [suggested] Make the median line thicker
- [suggested]Have an overall visualisation in the intro for the number of measures worse than the median - a green-to-red indicator with an arrow, for example (think Rich is working on this)

Stuff I don't think we need to do:
_But should consider dashboard design on #152 - but without making bigger changes I'm not sure how much suggestions below would help_
- Make  the important intro text bigger (h1, para) 
- Move the disclaimer to the bottom  
- Make most of the text on the page bigger


Completed
- Cut the unnecessary bits of that intro text (some of it can be collapsed)
- It's really confusing having some measures good when high, and some good when low. Why not just flip the second ones so they're all consistent? (NB this is more work obviously) - try testing this, try testing with good=100 and with good=0 and see which makes more sense
