### ISSUE TITLE
Ghost-generics tweaks

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1348]
* [x] Handle the cases where CCGs/practices are actually making savings
* [x] Consider removing quantity ("This seems to suggest e.g. that there are 220k atorvastatin 20mg tablets rx as GBG - which is not true")
* [ ] Make it possible to click through to practice savings per PPU page

**Comment by sebbacon** [comment]
I'm going to leave the final point for now. It's a nice to have; let's await feedback before bothering investing any more time

**Comment by HelenCEBM** [comment]
- [ ] add "generic prescribing" tag (suggested by user)
- [ ] Add link to blog in the "Why it matters" section in addition to the Description section
![image](https://user-images.githubusercontent.com/24392156/51743549-e7ef9e80-2094-11e9-8aca-3e092d331bf2.png)

**Comment by HelenCEBM** [comment]
Sorry two more things...
- [ ] (missed this from user email earlier) We have not included the measures breakdown link (https://openprescribing.net/ccg/99P/ghost_generics/) from the measures pages (https://openprescribing.net/ccg/99P/measures)
![image](https://user-images.githubusercontent.com/24392156/51755602-fcdd2980-20b6-11e9-8137-2919860c223b.png)


- [ ] And can we link back to measures from the [breakdown](https://openprescribing.net/ccg/99P/ghost_generics/) pages? Other breakdown pages have this at bottom of page: 
![image](https://user-images.githubusercontent.com/24392156/51755424-8e986700-20b6-11e9-835d-440411142d4a.png)
(from https://openprescribing.net/measure/lyrica/ccg/99P/)

**Comment by sebbacon** [comment]
The measures breakdown page isn't really a breakdown page. It works completely differently from the breakdown pages and making it appear there is pretty tricky without some other big changes.  Will take a look to think if there's some way of doing this that doesn't take a week...!

**Comment by HelenCEBM** [comment]
Another one... on practice "breakdown" pages the link to  "view change over time" is broken

It directs to `https://openprescribing.net/practice/E87026/ghost_generic_measure/`
but should go to
`https://openprescribing.net/measure/ghost_generic_measure/practice/E87026/`

e.g. https://openprescribing.net/practice/E87026/ghost_generics/
![image](https://user-images.githubusercontent.com/24392156/52219042-c744f700-2893-11e9-9ece-d90489954a68.png)

**Comment by HelenCEBM** [comment]
Left on this issue we have:
- link to PPU breakdown (tricky - wait for user feedback)
- link to GBG breakdown (I don't really follow why this isn't a relatively simple link to add with ccg code added in?)
- link back to all measures for CCG from the "breakdown" page (again shouldn't this be a straightforward-ish link to add?)
