### ISSUE TITLE
Rewrite the measure definitions

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#135]
These need to be rewritten so they don't lose the sense of what Croker has given us, but so that they are snappier and more clearly describe the problem and the solution. So instead of:

"Various angiotensin receptor blockers (ARBs) are available. A number of them are now available generically, and are of low cost. NICE guidance for treating high blood pressure recommends that the low-cost versions should be used."

We want something like:

"<link>NICE guidance for treating high blood pressure</link> recommends using the low-cost, generic versions of angiotensin receptor blockers (ARBs). Prescribe fewer high-cost ARBs to save money."

**Comment by annapowellsmith** [comment]
It would be nice also if each one explained the clinical purpose of the drugs in question - currently that isn't the case for e.g. Keppa, ACEs.

**Comment by HelenCEBM** [comment]
Measure wording has been improved ad-hoc.
