### ISSUE TITLE
Add alerts for NCSO concession changes

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1366]
Users should be able to sign up for alerts to tell them when their organisation is affected by NCSO concession changes.

**Comment by HelenCEBM** [comment]
From team chats so far:
- These will be triggered several times a month, any time that the NCSO list is updated
- Users opting to sign up for alerts for a practice/CCG should then have the following options (phrasing could be improved)
> please select whether you would like to receive alerts for:
> (1) NCSO costs (approx weekly)  - standard measures alerts will be included in each email, updated monthly; OR
> (2) Just standard measures (monthly)
   
- [ ] Question: how to deal with users already signed up for normal alerts who'd like to "upgrade"? Can we supply a link in the routine monthly alerts to let them know this is now an option? Will they have to manually unsubscribe from their "old" alerts?

- In the email, after the NCSO alerts there should be a line under which to show the normal alerts. 
- [ ] We should make it as clear as possible when the normal alerts are updated, e.g. by highlighting prominently which month the regular alerts apply to, or with some kind of "New Month!" message if possible.

**Comment by inglesp** [comment]
(@brianmackenna, @richiecroker)

**Comment by HelenCEBM** [comment]
I'd say remove or edit the first line, (`New price concession data has been published for January 2019.`) because it will come up several times and might look similar each time. 

E.g. if there is a new concession approved mid-month, but this CCG only prescribes a small amount of it, we will presumably trigger an alert but there might be no change to the top 10 list. Do we have a way of handling that? 

If we keep the line we could change it to 
> New or updated price concession data has been published for January 2019

**Comment by richiecroker** [comment]
I would go with:
New or updated price concession data has been published for January 2019

**Comment by richiecroker** [comment]
but apart from that, looks good!

**Comment by HelenCEBM** [comment]
After this:
> We estimate that in January 2019 price concessions for out-of-stock medicines will cost NHS Birmingham and Solihull CCG an additional £285,780. 

Can we say something like:
> - an increase of £XXX since the last price concession list was released.

**Comment by inglesp** [comment]
> New or updated price concession data has been published for January 2019

Good idea.

**Comment by inglesp** [comment]
> Can we say something like:
>>    -- an increase of £XXX since the last price concession list was released.

Not easily -- this would involve keeping track of what it was last time around, and would significantly increase the complexity of the work.

I'd like to get something simpler deployed first, but we could come back and revisit this.

**Comment by richiecroker** [comment]
how about something like:
We estimate that in January 2019 total price concessions for out-of-stock medicines will cost NHS Birmingham and Solihull CCG an additional £285,780.

**Comment by inglesp** [comment]
> We estimate that in January 2019 total price concessions for out-of-stock medicines will cost NHS Birmingham and Solihull CCG an additional £285,780.

@richiecroker Is that just the addition of the word "total" to my original proposal?

**Comment by richiecroker** [comment]
it is

**Comment by brianmackenna** [comment]
Will the emails go automatically or have to be manually teed up?

If automatic we should emphasise autmation and speed we get it to people.
If not above is cool - NCSO commonly gets announced on a Friday evening about 430 in my experience.

**Comment by HelenCEBM** [comment]
I can still imagine people getting confused about why we're emailing if nothing has changed (for them).

So can we add a sentence to convey something like 
> this may have increased since the last NCSO alert we sent this month.

Or *if not the first alert* for the month
> this now includes new items added since the initial release of the NCSO list for this month (which may or may not have increased the projected cost for your CCG).

**Comment by inglesp** [comment]
When we discussed this at the DL day a couple of weeks ago, it was decided, without much discussion, that the standard measures alerts would be included in the NCSO alert emails.

I'd rather not do this, as it makes the implementation fiddlier.  (Additionally, I think sending the same information to people five times a month is going to be a bit much.)

Is this OK?

**Comment by inglesp** [comment]
> I can still imagine people getting confused about why we're emailing if nothing has changed (for them).

Sounds sensible but again is a bit fiddly.  This might have to wait, but I'll see what I can do.

**Comment by inglesp** [comment]
> Will the emails go automatically or have to be manually teed up?

They can easily go out automatically.

**Comment by Bengoldacre** [comment]
If including standard alerts content is hard then let's just ship NSCO alerts now with only NCSO, but also please some text explaining that you can also subscribe to alerts on all our standard measures.

**Comment by inglesp** [comment]
OK, could I have feed back on this please?

![image](https://user-images.githubusercontent.com/28734/52404177-4880d180-2ac0-11e9-915a-0ec99da71495.png)

Note that it's not going to be possible, at this stage, to change the content of the email based on whether this is the first such email of the month or an update to a previous email.

**Comment by brianmackenna** [comment]
Looks great- coments/q

- Are we doing an All England one? 
- Can the graph be inserted into the email?

> There may be further updates later this month.

Suggest delete and use
_We check for updates on concessions every day and we will email you the next time concessions are announced _

**Comment by HelenCEBM** [comment]
Great! Only comment is I think we need to make it more clear what the figures in the table represent, ie. `quantity (AS PRESCRIBED 2 MO AGO)` and `this month's PREDICTED extra cost`

We dealt with this when making the dashboard so maybe can copy from there - possibly by adding a sentence above (however changing table headings is good otherwise context is lost if people copy-paste)

**Comment by inglesp** [comment]
> Only comment is I think we need to make it more clear what the figures in the table represent, ie. `quantity (AS PRESCRIBED 2 MO AGO)` and `this month's PREDICTED extra cost`

@HelenCEBM, do you think these should be in the table headings, or in some explanatory text?

**Comment by HelenCEBM** [comment]
let's say in the headers:
`quantity (Nov 2018)` 
`predicted extra cost in Jan 2019`
unless putting months in headers is too complicated?

**Comment by inglesp** [comment]
Good idea.

@HelenCEBM this is now on staging -- do you have time to sign up for some alerts for practices/CCGs/All England and check that it all looks sensible.  Then let me know and I'll trigger the sending of emails so you could check those too.

**Comment by brianmackenna** [comment]
**Signing-up**
It would be helpful to add another box on the main dashboard so someone can sign up for all three alerts at once.

![image](https://user-images.githubusercontent.com/40460354/53026991-f9418600-345b-11e9-99f4-fa91247acd53.png)

**Confirmation**
It looks like two-step confirmation but I don't think it is. Interestingly for gmail the confirmation went into "important emails" but the actual emails went in "everything else"

![image](https://user-images.githubusercontent.com/40460354/53027075-1ece8f80-345c-11e9-9b87-5e9a52413a2b.png)


**Received Email**

![image](https://user-images.githubusercontent.com/40460354/53026721-5be65200-345b-11e9-8d9f-047f1a0cf77b.png)

- Blue arrow: will cost *the* NHS in England
- Red arrow: this month's *projected* extra cost
- Yellow Highlight: So by only displaying the top 10 - if the added NCSO for that day to not figure in top 10 the person may not be receiving much extra information. Could we add the newly added concessions instead of top 10? Not a big deal if too much time

**Comment by inglesp** [comment]
Thanks for your feedback.  Unfortunately most of it is too fiddly to implement right now, unless you think it's really important -- sorry!

> It would be helpful to add another box on the main dashboard so someone can sign up for all three alerts at once.

Yes, agree (and this is what I first tried to implement) but it's surprisingly fiddly.

> It looks like two-step confirmation but I don't think it is

This affects all alerts, and we know it's not ideal, but fixing is a sizeable chunk of work.  See #1048 for further discussion.

> Blue arrow: will cost _the_ NHS in England

Done.

> Red arrow: this month's _projected_ extra cost

Done.

> Yellow Highlight: So by only displaying the top 10 - if the added NCSO for that day to not figure in top 10 the person may not be receiving much extra information. Could we add the newly added concessions instead of top 10? Not a big deal if too much time

Sorry, doing this is going to require quite a bit of extra machinery.  You could add a new issue if you think it's important.

**Comment by HelenCEBM** [comment]
Yes i agree sign-up should be clearer - we should make it more obvious that this is a new and different alert (e.g. a "New!" sticker as per measure categories etc) if we can't give all 3 options together.  It's easy to not read the text properly or ignore it because it looks like the alerts you have already signed up for.

### Lack of branding: 
The email doesn't mention OP at all (except in "from"). In normal alerts we only mention OP as follows:
> This is an experimental new service from OpenPrescribing and we are keen for feedback: just reply to this email.

Some possible options: 
- insert the experimental statement as above
- subject line 
  > Your update about NCSO Concessions for Circuit Lane Surgery *from OpenPrescribing*

  > *OpenPrescribing*: Your update about NCSO Concessions for Circuit Lane Surgery
- Body
  > Hello *from OpenPrescribing* !
  > New or updated price concession data has been published for January 2019.
  > We estimate that in January 2019 total price concessions for out-of-stock medicines will cost Circuit Lane Surgery an additional £3,580.
  > *At OpenPrescribing* we check for updates on concessions every day and we will email you the next time concessions are announced.
--

**Comment by HelenCEBM** [comment]
I think @evansd has now implemented one-step sign-up for regular alerts, can we make them all consistent?

**Comment by inglesp** [comment]
> Yes i agree sign-up should be clearer - we should make it more obvious that this is a new and different alert

![image](https://user-images.githubusercontent.com/28734/53085962-f9915e00-34fb-11e9-9169-e8a01318d80e.png)

> Lack of branding

Good ideas -- I can make all those changes.

> I think @evansd has now implemented one-step sign-up for regular alerts, can we make them all consistent?

Sign-up is all going through the same code, so the behaviour should be the same.  For all alerts, you have to click on a link in a confirmation email to be able to manage your alerts, otherwise anybody could manage the alerts of anybody else, just by entering an email address.  But you'll receive the emails even if you don't click on the link in the confirmation email.  (This is the recent change that @evansd made.)  Does this make sense?

**Comment by inglesp** [comment]
>> Lack of branding

> Good ideas -- I can make all those changes.

I've made some of those changes in https://github.com/ebmdatalab/openprescribing/pull/1447/commits/8b729a057d879f4643bf0ab15adc9133e0d85f08.

I could also change the subject, but it would have to be changed for all emails.  I don't have a strong opinion.

**Comment by HelenCEBM** [comment]
Great! We can leave subject line for now, maybe change all alert subject lines together later. 

I just realised this possibly doesn't describe well what you get:
> Get alerted by email (roughly weekly) when new price concession data is available.

Could say:
> Get email updates (roughly weekly) *for this organisation* when new price concession data is available.

or
> Get an email update showing the latest cost impact on this organisation every time new price concession data is available (roughly weekly)

**Comment by inglesp** [comment]
When you say "_for this organisation_" do you mean that literally, or do you mean "for this practice"/"for this CCG"/"for the NHS in England"?

**Comment by HelenCEBM** [comment]
> When you say "_for this organisation_" do you mean that literally, or do you mean "for this practice"/"for this CCG"/"for the NHS in England"?

The latter ideal if possible but the former if easier
