### ISSUE TITLE
Problem with playback function on analyse page

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1368]
It seems somewhat hit-and-miss but on most playback attempts, for at least part of the time course, bars are sliding around in an odd and jerky fashion
![image](https://user-images.githubusercontent.com/24392156/51737848-8e33a800-2085-11e9-8150-07e2c4f6f4e9.png)
https://openprescribing.net/analyse/#org=CCG&orgIds=10Q&numIds=0208020V0&denom=total_list_size&selectedTab=summary

Same happens for practice-level search e.g. https://openprescribing.net/analyse/#org=practice&orgIds=K84013&numIds=0208020V0&denom=nothing&selectedTab=summary

**Comment by evansd** [comment]
We've now temporarily disabled the play button. It's possible this issue is related to #1119 and we should revisit this when we have time to look at that issue.
