### ISSUE TITLE
Partition querying is very slow

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1370]
Our prescribing table is partitioned by date such that everything inside a partition has the same value for the `processing_date` column.

A common performance issue I've seen recently is that when a partition has been selected by date, there continues to be an (often expensive) sequence scan on that table to recheck the `processing_date` column with a filter. It takes up most of the time in this query, for example:

![image](https://user-images.githubusercontent.com/211271/51748115-576c8a80-20a3-11e9-8337-400c01852b2c.png)

We know that this is redundant as every value in that column is the same.

I have posed [a question](https://dba.stackexchange.com/questions/228088/where-each-partition-has-only-one-value-in-the-constraint-column-can-i-avoid-fi) on dba stackexchange about this.

**Comment by evansd** [comment]
I'm not at my computer now so can't easily check this myself, but are the partitions constrained by an exact match on the date (i.e. first of the month) or by a range which includes every day in the month?

If the latter, and if we do a query for a specific date then Postgres will still need to check whether there are any dates in the partition which don't match.

**Comment by sebbacon** [comment]
Not so sure. I changed the constraint from 

  CHECK (processing_date >= '2018-06-01'::date AND processing_date < '2018-07-01'::date)

To 

  CHECK (processing_date = '2018-06-01'::date)

And the query plan still involves a seq scan:

```sql
# explain select * from frontend_prescription rx where rx.processing_date = '2018-06-01';
┌───────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                            QUERY PLAN                                             │
├───────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Append  (cost=0.00..233408.70 rows=9780937 width=62)                                              │
│   ->  Seq Scan on frontend_prescription rx  (cost=0.00..0.00 rows=1 width=128)                    │
│         Filter: (processing_date = '2018-06-01'::date)                                            │
│   ->  Seq Scan on frontend_prescription_201806 rx_1  (cost=0.00..233408.70 rows=9780936 width=62) │
│         Filter: (processing_date = '2018-06-01'::date)                                            │
└───────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by evansd** [comment]
On further inspection of the [documentation](https://www.postgresql.org/docs/9.6/ddl-partitioning.html#DDL-PARTITIONING-CONSTRAINT-EXCLUSION) relating to this i think the answer is that "constraint exclusion" only serves to eliminate partitions from the query and, once that's been done, they play no further role in optimising the query.
