### ISSUE TITLE
Consider NP8 measure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1372]
Using [this SQL](https://gist.github.com/sebbacon/2fc545f80c6760ace624de567533b3d2), there is an interesting spike in October every month:

![image](https://user-images.githubusercontent.com/211271/51752866-5f7ef700-20b0-11e9-9317-595034cb98b1.png)

(note we use [this SQL](https://gist.github.com/sebbacon/14d7a5ef1de861fe9bd68a40e6a50de5) to create DT mapping view, as latest mapping not yet imported to canonical sources)

**Comment by sebbacon** [comment]
The October spikes are flu vaccines:

![image](https://user-images.githubusercontent.com/211271/51753430-a7524e00-20b1-11e9-8a91-238c2e1ab12e.png)

**Comment by sebbacon** [comment]
Flu vaccines have not appeared in 2018 because they have started to be prescribed as brands rather than generically.  Flu vaccines are weird in various ways.  For example, the cost isn't the CCG's cost - PHE are billed for it.  Also they change every year, and are black triangle drugs, and this year you are supposed to prescribed trivalent for over 65s (only one brand, Fluad) and quadrivalent for everyone else.

So for now - skip flu vaccines in the analysis.
.

**Comment by sebbacon** [comment]
We can attempt to work out possible savings at 10th and 50th percentiles ([sql](https://gist.github.com/sebbacon/12a89197264f9b9d61732fbe54928e71):

![image](https://user-images.githubusercontent.com/211271/51765793-b1d01000-20d0-11e9-8897-d6269dfbaf2a.png)

The variability is so great in these presentations the 10th might be the best, but also may be unrealistic.

**Comment by sebbacon** [comment]
When done as a measure (10th percentile saving), there is some interesting variation over time for some CCGs:
![image](https://user-images.githubusercontent.com/211271/51766269-088a1980-20d2-11e9-936a-ded83e13bd7e.png)
![image](https://user-images.githubusercontent.com/211271/51766349-3b341200-20d2-11e9-915b-acef3e0de970.png)

**Comment by sebbacon** [comment]
[Here's](https://gist.github.com/ff80f836c1d48dc5e5fe1966c3d66afc) a list of NP8 products that one CCG ([sql](https://gist.github.com/sebbacon/ae3e11776dfc5595691f4898181cad8d))

**Comment by sebbacon** [comment]
Thoughts/queries:

* This is not something CCGs normally have any control over, though they could consider switching to branded prescribing - in which case is this a special subset of PPU?
* This may be interesting as a policy piece. My question has always been, why is *anything* NP8?

**Comment by sebbacon** [comment]
[Here](https://gist.github.com/c0f7fa5e96bbcfb0bfa0b21b02e62d19) is some basic analysis by dispensing contractor. In a single month there are a few making over £1000k/month extra on NP8s, but we'd need to look at this over time to see if it's consistent.

**Comment by sebbacon** [comment]
Some final summary statistics:

* A total of £156, 950 could have been saved in November 2018 if there were no NP8 and tariff prices were set at the current median
* Or £2.6m if they were set at the best decile

The 10 most expensive NP8 presentations nationwide in November were:

bnf_name | bnf_code | median
-- | -- | --
Co-Proxamol_Tab 32.5mg/325mg | 0407010Q0AAAAAA | 81353.7161587303
Melatonin_Cap 2mg | 0401010ADAAAEAE | 46096.6833333333
Sucralfate_Tab 1g | 0103030S0AAAAAA | 29372.7180952381
Midazolam_Liq Spec 50mg/5ml | 0408020V0AAALAL | 26163.21
Mag Glycerophos_Cap 97.2mg | 0905013G0AAA4A4 | 26138.2985714286
Metolazone_Tab 2.5mg | 0202010V0AAANAN | 25054.8366666667
Mag Glycerophos_Cap 48.6mg | 0905013G0AABMBM | 16296.0175
Cyanocobalamin_Tab 1mg M/R | 0901020D0AAAHAH | 14928.0450052184
Biotin_Tab 5mg | 090602800AAAGAG | 14896.0978571429
Vit E_Cap 400u | 0906050P0AAAFAF | 13633.25875

Whereas these were obtained cheaper than the median:


bnf_name | bnf_code | median
-- | -- | --
Sertraline HCl_Oral Susp 50mg/5ml | 0403030Q0AAAQAQ | -6522.3504
Tramadol HCl_Tab 200mg M/R | 040702040AAAEAE | -8254.01434523812
Clonidine HCl_Oral Soln 50mcg/5ml | 0407042F0AAATAT | -9065.0927
Ranitidine HCl_Oral Soln 5mg/5ml | 0103010T0AABQBQ | -10630.88
Omeprazole_Oral Susp 5mg/5ml | 0103050P0AABNBN | -11677.7290476191
Tramadol HCl_Tab 100mg M/R | 040702040AAACAC | -13692.5879545455
Omeprazole_Oral Susp 10mg/5ml | 0103050P0AABLBL | -19166.6596
Omeprazole_Oral Susp 20mg/5ml | 0103050P0AABMBM | -22587.443
Paraldehyde 50%/Olive Oil_Rectal Soln | 0408020Q0AAAJAJ | -23883.5776666667
Melatonin_Oral Soln 5mg/5ml | 0401010ADAABABA | -24255.22255

**Comment by brianmackenna** [comment]
> 
> * This is not something CCGs normally have any control over, though they could consider switching to branded prescribing - in which case is this a special subset of PPU?>

It is similar to OOPE - As payers CCGs do have the ability to ask pharmacies to justify why they are charging like this and can refer any responses deem not to be sufficient to NHS England (as ultimate contract holders). 
> * This may be interesting as a policy piece. My question has always been, why is _anything_ NP8?
>
I agree, very interesting and would be relevant if any tariff reforms come about.
