### ISSUE TITLE
Items in data where quantity is zero

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1373]
Every few months there's a few items with a quantity of zero - usually with a non-zero NIC.

[Data here](https://gist.github.com/c26187c73522e170946db9101ed1ea79)

Created with this SQL:

```sql
SELECT
  month,
  bnf_name,
  bnf_code,
  SUM(net_cost) AS net_cost
FROM
  `hscic.normalised_prescribing_standard`
WHERE
  quantity = 0
GROUP BY
  month,
  bnf_name,
  bnf_code
ORDER BY
  month
```

**Comment by sebbacon** [comment]
Action: may want to ask BSA about this. Possibly add to FAQ or even a new "data quality notes" document

**Comment by HelenCEBM** [comment]
@brianmackenna is this on your ask-BSA list?

**Comment by brianmackenna** [comment]
I didn't know it was a thing. They should be at an event I am at tomorrow, I will ask. For reference March results are 
Ingenol Mebutate_Gel 150mcg/g
1308010Z0AAAAAA
£173.32999999999998

Zlatal_Inj 10mg/0.4ml Pfs
0801030P0BEADFH
£13.77

Picato_Gel 500mcg/g
1308010Z0BBABAB
£5557.5

Ingenol Mebutate_Gel 500mcg/g
1308010Z0AAABAB
£8807.5
	
Picato_Gel 150mcg/g
1308010Z0BBAAAA
£303.33000000000004

**Comment by sebbacon** [comment]
These look like cases where `quantity` is fractional, and it has been rounded down to zero.

For example, Ingenol Mebutate_Gel 150mcg/g is a single-supplier generic (brand Picato). 

In the [PCA data](https://www.nhsbsa.nhs.uk/prescription-data/dispensing-data/prescription-cost-analysis-pca-data), its brand is listed as having Standard Quantity Unit of 6, meaning grammes (n.b. the SQU column is no longer available since Dec 2018).  The [VMPP](https://openprescribing.net/dmd/vmpp/21632111000001101/) similarly indicates that the unit of measure is grammes, but the pack size is 1.41 grammes.

The [AMPP](https://openprescribing.net/dmd/ampp/21632311000001104/) tells us that it comes in 3 x 0.47g tubes.

The [Drug Tariff price](https://openprescribing.net/tariff/?codes=1308010Z0AAAAAA) has always been £65 for 1.41g (specified in the tariff as 3 x  0.47).

We can see using bigquery that all the rows for Ingenol Mebutate where quantity is zero are priced at less than £65, specifically at one or two thirds. Therefore these are prescriptions for one tube.

Therefore it looks like the unit of measurement in the BSA data is, in fact, packs-of-three-tubes (not grammes), and they do not support fractional quantities.  

## How should we handle this in our analyses?

The only options are to (a) drop the data, or (b) try to fix the data.

Given these are low numbers, and we've only hit this so far in one specific measure (ghost branded generics), I think we should just exclude things with a quantity of zero in that measure, specifically.

Otherwise, I'm not sure what else to do, other than report this to BSA as an oddity: the fix is either to change the quantity unit to "tube", or allow fractional quantities.

**Comment by brianmackenna** [comment]
Response from BSA

> The Quantity field on the detailed prescribing information available from the ISP does not hold decimal places.  This will affect data for items where a quantity is less than 1 will appear as 0.

**Comment by sebbacon** [comment]
Well, we'd worked that out already!

The important questions are:

* Why does it not hold decimal places? Is it a technical constraint that they can't fix?
* If it can't fix, is there any way to flag or work out which items this may apply to? It has the possibility to confound a number of our analyses, not just for 0/1 but all relatively low values of quantity
* Are they going to document this somewhere?

**Comment by richiecroker** [comment]
This has raised its head again in the ghost branded generics.  A CCG contacted us to say that ingenol showed up as saving £65, when PPU is calculated as zero.
https://openprescribing.net/practice/L83082/ghost_generics/?date=2019-08-01

Should we remove zero quantity rx from GBG calcs as well @sebbacon @brianmackenna ?

**Comment by richiecroker** [comment]
Just checked this again, still ongoing in one item only (Zuclopenthixol decanoate 500mg/1ml inj ampoules) where both quantity and cost = 0.  Not sure there's anything more we can do (I don't know how you can prescribe in less that 1 ampoule), and excluded from GBG and PPU, so will close action.
