### ISSUE TITLE
Make measures consistently high=bad

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#138]
Feedback from Henry and Lisa that it's really confusing having a mix of high=good and high=bad, and I agree. 

Henry suggested rewriting the definitions so that high=bad consistently. 

Breaking this out from #133 as a separate issue. 

I think we can leave the `low_is_good` JSON setting implemented previously in place, but use it to change the calculation of the measure, rather than the sort order.

**Comment by sebbacon** [comment]
To do:

* In measures calcuation code, flip non/demon where appropriate
* The wording might need changing and/or improving (e.g. proportion of X as of Y might need swapping in the measure definition)
* Recompute the affected measures

**Comment by sebbacon** [comment]
Does this work? It puts bad values at the top, but then a reversed Y axis is counter-intuitive in a different way...

![reversed](https://cloud.githubusercontent.com/assets/211271/17476052/ff438cfe-5d55-11e6-9fb9-007ab9add634.png)

**Comment by sebbacon** [comment]
Here's an example rolled up by practice

![mixed](https://cloud.githubusercontent.com/assets/211271/17476499/3b85f006-5d58-11e6-8aa6-d3f0a515a36f.png)

**Comment by annapowellsmith** [comment]
Brilliant! - as discussed let's test and make sure no-one is confused by it, but this is a great solution.
