### ISSUE TITLE
Consider NSCO measure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1386]
The simplest [definition](https://gist.github.com/sebbacon/175e4b35b6ad4acd8930faafe97b1ed9) is excess spend as a proportion of all spend.  However, the charts are so spiky, the deciles end up being hard to see:

![image](https://user-images.githubusercontent.com/211271/51846480-8ee06e80-2311-11e9-935e-b030877108be.png)

There is certainly some variation in this, from 1% to 1.7% of total prescribing spend, though the distribution is fairly normal.

**Comment by Bengoldacre** [comment]
i think given little control over this, and hard to read, and we are having NCSO alerts, park and don't do.
