### ISSUE TITLE
Consider tweaking layout to make width consistent

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1387]
The site currently has a "max-width" setting for paragraphs of text which prevent them from extending the full width of the column. I guess this was done as an aid to readability as very long lines of text can be hard to scan. But it has the effect of making the layout look untidy and a bit broken and has been low-level irritating me for ages. And I don't think removing it has much effect on readability.

Below are a bunch of side-by-side comparisons.

It's a very easy change to make, but it would be good to get people's views first.

| Before | After |
| --- | --- |
| ![openprescribing net_analyse_](https://user-images.githubusercontent.com/19630/51849687-25b02980-2318-11e9-9d1d-ac4c6131d25b.png) | ![openprescribing net_analyse_ 1](https://user-images.githubusercontent.com/19630/51849714-319beb80-2318-11e9-9053-a102d1152761.png) |
| ![openprescribing net_ccg_99p_measures__tags lowpriorityconsultation](https://user-images.githubusercontent.com/19630/51849797-68720180-2318-11e9-9e5a-9c9449b3021b.png) | ![openprescribing net_ccg_99p_measures__tags lowpriorityconsultation 1](https://user-images.githubusercontent.com/19630/51849827-758ef080-2318-11e9-9321-a2eaedd77217.png) |
| ![openprescribing net_bnf_01_](https://user-images.githubusercontent.com/19630/51849926-98b9a000-2318-11e9-8d0b-3ff5988ba49d.png) | ![openprescribing net_bnf_01_ 1](https://user-images.githubusercontent.com/19630/51849931-9c4d2700-2318-11e9-9d35-48125c9d0f3d.png) |
| ![openprescribing net_faq_](https://user-images.githubusercontent.com/19630/51849941-9fe0ae00-2318-11e9-8cc6-c47e7fe18fc2.png) | ![openprescribing net_faq_ 1](https://user-images.githubusercontent.com/19630/51849947-a1aa7180-2318-11e9-93a5-10c86326cce7.png) |

**Comment by alexwalkercebm** [comment]
I like it.

**Comment by brianmackenna** [comment]
Looks good. Are there any issues it might cause with site displaying on a mobile device?

**Comment by evansd** [comment]
Good question. But no, it won't make any difference either way on mobiles as on smaller screens the max width thing never kicks in anyway.

**Comment by sebbacon** [comment]
:+1:
