### ISSUE TITLE
Menu reorganisation

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1396]
Add:

* Research (should be top level)
* How-to guides

Reorganise the rest - suggestion:

* Analyse
   * Custom
   * Trends for BNF sections
   * Trends for chemicals
   * Etc
* Area and practice dashboards
  * Practices
  * CCGs
  * Etc

Probably also add a site map (maybe at the bottom of every page?)

Note there's an old issue about trends drop-down measures to review as part of this

**Comment by HelenCEBM** [comment]
see also #825 for improvements to the list items currently under the `trends` menu

**Comment by HelenCEBM** [comment]
Started mocking up some ideas but I think helpful if each menu item can have its own page to explain what all the options are, to help people navigate, e.g.
![image](https://user-images.githubusercontent.com/24392156/52072856-eb47c600-257d-11e9-9c64-ab706c41ddae.png)

...
![image](https://user-images.githubusercontent.com/24392156/52072903-0adeee80-257e-11e9-8519-871c709ba2bf.png)

However this would require having the top menu items each as clickable links to the above pages, perhaps using hover to expand the menu (so people who know where they're going can still easily access the things they're looking for). 

Thoughts?

**Comment by HelenCEBM** [comment]
Alternatively, if we want to have the above explanatory/navigation pages but not change how the menus work, we could add a "help" (or similar) item to each dropdown to help people see what everything is without having to click on them all. There will be quite a lot of options and e.g. if I'm a member of the public who has never heard of CCGs, I don't know whether or not I want to look at a CCG dashboard until it's explained what a CCG is.

**Comment by sebbacon** [comment]
Thanks!

We should err on the side of brevity with navigation, and I'm not yet convinced that the explanatory text is adds much, for the following reasons:

* Our target audience is not the public; if we wanted to focus on them I'd probably design a completely new pathway through the site. As it is, someone without the focused interest to find out what a CCG is is still going to be mystified when they get to a CCG dashboard...!
  * As a general point, any larger scale rethinking is better left to when we get budget to get UX expertise on the case
* For everyone else, the descriptions are redundant and I think we can get some further improvement by continuing to think hard about the titles (how about "time trends" rather than just "trends"?  E.g. "Drug Tariff and Concessions time trends"?

If we *do* decide we need more space, rather than inserting a clicky interstitial between content pages, we could do something with hovers -- for example, the "mega menu" and "half menu" options [here](https://uxwing.com/webslide/bootstrap-mega-menu/).

**Comment by sebbacon** [comment]
Yes to easy-as-possible, but I guess I place most weight on the "not too cumbersome" side of the equation. I tend to think people simply don't read words on websites, unless they are already invested.

I do think the *dashboards* explanations are redundant for *healthcare professionals*, cos they'll know what a CCG is.  But yeh, maybe if the suggested text was finished you might change my mind! :wink: 

(P.S. there will be both "Regional" and "STP" dashboards when we launch that)

If we know CCGs are confused about what's available, can we list what the things are that they're unaware of - then focus on those? 

Regarding patients, it's not that I don't want to help them, it's just I'm not convinced we can give enough information to significantly help them in a navigation element. How about a button in the nav bar "For patients" which takes them to a new FAQ just for them? Or "How-to"/"Guides" having sub menus "For clinicians", "For patients".

Just brainstorming the analyse section. How about "Prescribing data" as main heading? e.g.

* Prescribing data
  * Search 
  * Time trends
     * BNF chapters
     * etc

**Comment by HelenCEBM** [comment]
I agree people don't read words in general, but if someone is looking for something among all these menus but doesn't know how the thing they want might be described, then it's good to have the option of looking through a page that briefly explains what the menu options are. E.g. you have to perform an analysis before you realise that it doesn't show you the whole national trend in one go, then you have to start looking around again having wasted time not getting what you wanted. And a list of all the things would be a nice way to showcase all the things you can do on the site. 

One option is to put all the menu explainers into one page as a big long list and call it sitemap or similar.

**Comment by brianmackenna** [comment]
User feedback is on our google drive [here](https://docs.google.com/document/d/1h2rtZi3Snx5DquL0ooG5F0tIlyIbkwAF88tfPBixcpc/edit)
