### ISSUE TITLE
Write up short generic trends blog

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1406]
Topics:

* Describe "prescribe as generic" recommendation
* Describe clinical reasons to switch from generic
* Describe other incentives to switch from generic
  * PPU - branded generics being cheaper
  * Rebates
* Describe how DT could be more responsive to price. Venlafaxine example - when things are released as branded generics, they can't go in Category A, so it's up to DH to pick a reference brand - how do they do this?

Show with some trends.

I've made [a notebook](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/generic_trends/generic-trends-2.ipynb) for the last point. I want to discuss this with @richiecroker and @brianmackenna to pick out some representative examples for the narrative.  I think Venlafaxine, Pregabalin, Quetiapine, Estradiol & Estriol, Pneumonococcal. Not sure how to interpret Lantanaprost, Salbutamol, 

Some further thoughts below.
## Illustration of "how it's meant to work"

Aripiprazole is a good example of a cat A product with lots of available AMPs.

It became Cat A in April 2015, and its price dropped rapidly, settling around May 2017, and it was nearly always prescribed generically, so cost savings accrued automatically.

![image](https://user-images.githubusercontent.com/211271/52046510-c849f180-253e-11e9-98fb-e73734ff5996.png)

## Main trends

There are two main categories of things that move away from generic prescribing: 

(1) things where there are many new entrants to the market and the DT price is much higher than their price points (for example, many opioids, Enoxaparin, inhalers (?) etc). In many cases (opioids in MR form with 12/24h alternatives, skin creams) these are recommended to be prescribed as brands. What has changed in the market or the advice? In the past skin creams etc these tended to be prescribed generically, but never seem to be any more. In general chapter 13 is recommended to be prescribed generically because the products contain multiple ingredients and are not truly generically equivalent.

In general these graphs showing the proportion of generic prescribing going down would correlate with cost going down, and are examples of the market working; however, the system is designed so that the dispensing contractors are meant to be the ones pushing cost down, not the prescribers.

Charts showing quite pronounced drops appear to be products with more and more competitors entering the market.  

The most interesting example is *Venlafaxine*, a most of the prescribing of which is as [a Category C tablet product whose DT price dropped to the same price as Vensir in April 2017](https://openprescribing.net/tariff/?codes=0403040W0AAAEAE), using the brand Venlalic XL as a reference price. Vensir was introduced in April 2014 and has stayed that price ever since. This chart shows lots of people switching away from generic prescribing from mid-2014, and then starting to switch back to generic in mid-2017:

![image](https://user-images.githubusercontent.com/211271/51993988-c8e37900-24a7-11e9-8613-d4966d71b0ff.png)

(2) Things which may have rebates (though the only examples I found was Spiolto Respimat and Melatonin). I think these tend to be indicated by charts showing consistent linear decreases rather than sudden ones.

In general, things moving *towards* generic prescribing appear to be things going out of patent (?). What I don't understand is why these weren't always prescribed generically.

### Examples of moving away from generics
Looking at those charts, I note that a large number of high-volume chemicals with a pronounced move to branded generics are all *opioids*. These are of course profitable and addictive, but are also recommended to be prescribed by brand ([source](https://www.sps.nhs.uk/wp-content/uploads/2017/12/UKMi_QA_Brand-name_prescribing_Update_Nov2017.pdf)), on the grounds that (a) they are available as 12 and 24 hour versions, and (b) the pharmacokinetic profiles of MR products differ.

*Melatonin* has been in the DT at the same price since June 2012. There is only one product, Circadin (two suppliers, Flynn Pharma, and Waymade).  Therefore, the gradual change from generic to branded prescribing suggests rebates of some kind.

*Liquid paraffin* saw a huge drop in early 2016. This would appear to be a near-complete stop of people being prescribed it generically, but all the branded people staying on their brands:

```
127.0.0.1 prescribing@prescribing=# select processing_date as month, name,  substr(presentation_code, 0, 12) as product, sum(total_items) from frontend_prescription_201811 inner join frontend_product on bnf_code = substr(presentation_code, 0, 12) where presentation_code like '1302011M0%' group by month, product, name;
┌────────────┬────────────┬─────────────┬───────┐
│   month    │    name    │   product   │  sum  │
├────────────┼────────────┼─────────────┼───────┤
│ 2018-11-01 │ Doublebase │ 1302011M0BK │ 10359 │
│ 2018-11-01 │ Emulsiderm │ 1302011M0BB │  1263 │
│ 2018-11-01 │ Dermalo    │ 1302011M0BI │  1683 │
│ 2018-11-01 │ Liq Paraf  │ 1302011M0AA │   243 │
└────────────┴────────────┴─────────────┴───────┘
(4 rows)

Time: 20.896 ms
127.0.0.1 prescribing@prescribing=# select processing_date as month, name,  substr(presentation_code, 0, 12) as product, sum(total_items) from frontend_prescription_201601 inner join frontend_product on bnf_code = substr(presentation_code, 0, 12) where presentation_code like '1302011M0%' group by month, product, name;
┌────────────┬──────────────────────────┬─────────────┬───────┐
│   month    │           name           │   product   │  sum  │
├────────────┼──────────────────────────┼─────────────┼───────┤
│ 2016-01-01 │ Emulsiderm               │ 1302011M0BB │  2167 │
│ 2016-01-01 │ Doublebase               │ 1302011M0BK │ 15725 │
│ 2016-01-01 │ Liq Paraf                │ 1302011M0AA │ 12920 │
│ 2016-01-01 │ Zerolatum (Liq Paraffin) │ 1302011M0BL │     1 │
│ 2016-01-01 │ Alpha Keri               │ 1302011M0BF │     2 │
│ 2016-01-01 │ Dermalo                  │ 1302011M0BI │  2833 │
└────────────┴──────────────────────────┴─────────────┴───────┘

```

*Tiotropium Brom/Olodaterol* is the generic name for Spiolto Respimat, and there is only one AMP for the chemical  - I presume this is an example where there are rebates. However, the list price for Spiolto Respimat is the same as the Drug Tariff price, so the only explanation for that switch is non-firewalled rebates... I think....? 

We see a well-known pattern with *Budesonide* where the number of the most common brand (Symbicort) has remained the same but other brands (Easyhaler, DuoResp) have taken the share of "generic".

*Ibuprofen* is largely accounted for by PPU-style savings - in particular the Fenbid brand for gel.  This is Category C, and the reference brand is Ibugel Forte for the 100g pack. There are [several branded generics](https://openprescribing.net/ccg/99P/1003020P0AAAIAI/price_per_unit/?date=2018-11-01) and (possibly) only one true generic available (not sure I'm interpreting that data correctly)

*Enoxaparin* also has a number of branded generics, some of which are cheaper

### Examples of moving towards generics
*Pneumococcal* was all Pneumovax in 2016, and is now nearly all generic

A number of them are brands which were already very low numbers going even lower. For example, *Pheytoin Sod* shows the (already low) Epanutin decreasing, Primidone is the disappearance of Mysoline (interestingly, Primidone is recommended to be prescribed as a brand), *Latanoprost/Timolol* is the slow erosion of people on the brand Xalacom

*Clobetasone Butyrate* is interesting as it's a higher-volume version - the proportion has gone up because a particular brand (Trimovate) has seen a collapse in prescribing. Why would this be? Is it a patent expiry?
*Estradiol* is mostly the disappearance of Climaval (with a reasonable increase in Progynova) - I presume this is a patent expiry?
*Desogestrel* is Cerazette losing out after it went generic

# General questions
* Why is there a trend of inhalers becoming less generic? I believe this is because they're recommended to be prescribed by brand so patients stay with familiar devices; but when did this recommendation start, how was it disseminated, and why does Salbutamol buck the trend?
* Why is there a trend of opioids becoming less generic?  Presumably the recommendations regarding variation in MR profile and also 12/24 hour versions. Is there clinical need for these variations or may they have been introduced by a canny market? Again, but when did this recommendation start, how was it disseminated? And this "MR" phenomenon is interesting as I understand it doesn't really have any benefits to the patient but does vary how it works?
* Why would Nystatin become less generic (and now more generic again)?

**Comment by HelenCEBM** [comment]
I did some analysis in the long term trends data if helpful
