### ISSUE TITLE
New Tool to Support Changes to QoF

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1417]
NHS England and the BMA have announced changes to the [GP contract](https://www.bma.org.uk/collective-voice/committees/general-practitioners-committee/gpc-england/gp-contract-agreement-england) and QoF reform specifically mentions "Prescribing Safety modules".

> Prescribing safety: This module will cover the safe prescribing of NSAIDs, lithium and
valproate in women of child bearing age and will dovetail with the expansion of clinical
pharmacists in general 

We already have a [medicines safety dashboard](https://openprescribing.net/all-england/?tags=safety) for every practice, CCG and England so it would be good to think about how we can support in advance of more detailed advice about changes.

1. NSAIDs: We have a measure on the user of preferred NSAIDs. It is likely than any further development will need patient level data.
2. Lithium: The current [QoF measure](https://www.nice.org.uk/standards-and-indicators/qofindicators/the-percentage-of-patients-on-lithium-therapy-with-a-record-of-lithium-levels-in-the-therapeutic-range-within-the-previous-4-months) for Lithium is around blood monitoring. Possibility we could do somethig with [OpenPath](http://openpathology.net/) but likely there is minimal we can do in near future.
3. Valproate in women of child bearing age: This is related to MHRA (and others) [safety alerts](https://www.gov.uk/guidance/valproate-use-by-women-and-girls). The BSA release a quarterly file [here](https://www.nhsbsa.nhs.uk/prescription-data/prescribing-data/sodium-valproate) which breaks down prescribing by CCG, sex and age. Potentially we could build a user friendly tool in a similar manner to our other dashboards . Subsequently we could have discussions with BSA and our users about improvement, more timely/granular data

**Comment by sebbacon** [comment]
I would rather we at least have a go at getting the Valproate data *first* - because implementing a quarterly measure will be extra faff, won't work well with alerts, etc.

Also given we've been told before that custom monthly extracts should be possible, this would be the easiest thing to test that idea against, given they presumably have the query already made and ready? 

This will be a useful test case for the kind of ways we would work in the future with IPD (@evansd @inglesp)

**Comment by HelenCEBM** [comment]
@brianmackenna sounds like there's not a great deal we can do with this except having a tag for QOF (issue #1527). Perhaps make valproate into its own issue if we plan to do something with that?

**Comment by brianmackenna** [comment]
Agree - lets keep on backburner. Potentially stuff we can do with [OpenPatholgy.net](https://openpathology.net/) at some point for meds and blood tests.
