### ISSUE TITLE
Low Priority - Herbal Measure

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1422]
As part of the [NHS England Low Priority Prescribing](https://www.england.nhs.uk/wp-content/uploads/2017/11/items-which-should-not-be-routinely-precscribed-in-pc-ccg-guidance.pdf) herbal medicines were advised to be no longer prescribed for the rationale

> Due to the lack of scientific evidence required to register these
products with the MHRA, the joint clinical working group felt that
they were suitable for inclusion in this guidance. 

It is very difficult to measure herbal in a rolling fashion as all sorts of weirdness and different classifications. However NHS England did cite herbal products with a "[Traditional Herbal Registration](https://www.gov.uk/government/publications/herbal-medicines-granted-a-traditional-herbal-registration-thr/herbal-medicines-granted-a-traditional-herbal-registration)" from the MHRA.

We should produce a new measure using
a) the static list from MHRA possibly with some additions from where we find them.
or
b) dm+d does have a "license type" for herbal products from the list above

> Licensing Authority | 0004 | Traditional Herbal Medicine

An example can be seen on our dm+d browser for Atrogel [here](https://openprescribing.net/dmd/amp/11800211000001107/)

**Comment by richiecroker** [comment]
@sebbacon has created a DM+D to BNF code map, which is now at richard.herbal_list on BQ.  The THR list is not updated often, and therefore I suggest we deploy the herbal measure which I created today.

We can follow this up by creating a dynamic list courtesy of @sebbacon's SQL:
`select bnf_code, name from dmd_product inner join dmd_amp on dmd_amp.vpid = dmd_product.vpid where lic_authcd  = 4 and bnf_code is not null` and finding a way to get this into BigQuery.

This is also a useful test for creating other measures using DM+D classifications (e.g. dry powder inhalers?)
