### ISSUE TITLE
Users never see "You're already signed up for alerts..."

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1446]
`_force_login_and_redirect()` calls `perform_login(request, user, app_settings.EmailVerificationMethod.MANDATORY, signup=True)`.

This means the confirmation email is sent, but that the new user is not logged in.

So `_force_login_and_redirect()` doesn't force a login.

And this means that users never see "You're already signed up for alerts. You can change your subscriptions here."

**Comment by inglesp** [comment]
I think the fix is to change `app_settings.EmailVerificationMethod.MANDATORY` to `app_settings.EmailVerificationMethod.OPTIONAL`, but would like a second opinion.

**Comment by inglesp** [comment]
Unfortunately this change breaks a bunch of tests.

**Comment by evansd** [comment]
I think it will also result in being able to log in as any user, just by entering their email address in the alerts signup. At least, this was the problem I hit before when working on this.

**Comment by inglesp** [comment]
Yeah, have come to similar conclusion.

What about changing function name to `_send_confirmation_and_redirect`?

**Comment by HelenCEBM** [comment]
Any update @inglesp  @evansd ?

**Comment by evansd** [comment]
Fixed by #2271
