### ISSUE TITLE
Presentation breakdown on some measures not working correctly

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#1453]
When you click on the "Break the overall score down into individual presentations" link on some measures, it appears that not all presentations are shown.

1.  in the opioids OME measure (e.g. https://openprescribing.net/ccg/99P/opioidome/) when you click on the [link](https://openprescribing.net/measure/opioidome/ccg/99P/) the list is not correct.  For example, there are no branded preparations showing.

2.  It would also be useful if, for the OME measure, the list is not sorted by items or quantity, but instead have OME, as this is more relevance for the measure.  The items at the top of the list tend to be low dose, and therefore not as relevant as some of the presentations lower down.

**Comment by sebbacon** [comment]
I'm not going to look at this hard right now but FYI you'll see the way the list of BNF codes for the breakdown is generated is:

https://github.com/ebmdatalab/openprescribing/blob/4b286987a8a307c6949e80b0613c2b3f86f5c1cc/openprescribing/frontend/management/commands/measure_definitions/opioidome.json#L38

So there must be something wrong with that as a logic (per https://github.com/ebmdatalab/openprescribing/wiki/Measure-definitions)

**Comment by richiecroker** [comment]
`ebmdatalab.richard.opioid_measure` only contains generic BNF codes. whereas the view which creates the measure uses both brand and generic via `  CONCAT(SUBSTR(presc.bnf_code,0,9),'AA%',(SUBSTR(presc.bnf_code,-2,2)))=CONCAT(SUBSTR(opioid.bnf_code,0,11),'%',(SUBSTR(opioid.bnf_code,-2,2)))`

**Comment by inglesp** [comment]
1. Should be fixed.  @richiecroker please confirm!
2. Isn't possible, but will be once we're driving measures off the matrix store.
