### ISSUE TITLE
Understand STPs, ICPs, ICSs, PCNs

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1462]
This issue is really just documentation of some of the new TLAs floating around.

An STP (Strategic Transformation Partnership) is a partnership between NHS orgs (including CCGs) and councils.  Geographically, these are always an aggregation of CCGs. 

The current NHS long-term plan provides for replacing STPs with ICSs (Integrated Care Systems) by 2021. They are basically the same thing, but appear to be bigger than STPs, and thus also always an aggregation of CCGs, geographically speaking.

An ICP is a locality grouping with an ICS.

Here is an example of an ICS (Cumbria and North East), showing ICPs and CCGs:

![image](https://user-images.githubusercontent.com/211271/52699947-d6e8cd80-2f6e-11e9-9b18-4e7f7be78345.png)

This ICS is an aggregation of 3 STPs (not shown).

Further explanation (which is quite fuzzy) [here](https://www.england.nhs.uk/integratedcare/stps/faqs/).

**Comment by brianmackenna** [comment]
In addition the new [GP contract ](https://www.bma.org.uk/collective-voice/committees/general-practitioners-committee/gpc-england/gp-contract-agreement-england) has mandated that GPs must be part of a Primary Care Network (PCN).

A PCN is  a group of practices within "a coherent geographical area", typically covering a population of 30-50,000 patients. Practices will be expected  (but I don't think legally obliged!) to be part of a PCN by July 2019 with staff being recruited specifically to these PCNs after that.

In reality PCNs were in existence and becoming more prevalent before this announcement. I imagined PCNs as one of the main uses for "custom groupings" however this announcement helps as it means there will probably be a single list of PCNs and their members by the end of 2019 (might be a bit optimistic) so it might not be quite as random or custom as we first thought.
