### ISSUE TITLE
Check over the gitignore file

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1470]
It's already caused [one issue](https://github.com/ebmdatalab/openprescribing/pull/1433#issuecomment-463402156) and possibly there are other ones lurking ready to bite us. We should make sure we're only ignoring things we know we want to ignore, and that the matching rules are as specific as possible.

**Comment by HelenCEBM** [comment]
Any update @evansd ?

**Comment by richiecroker** [comment]
@evansd

**Comment by evansd** [comment]
Fine to close, we'll get to it when we get to it.
