### ISSUE TITLE
Consider ways to enforce sane measures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#149]
It is possible to make measures which will break our current price-saving calculations, because we currently assume that a numerator is always a subset of the denominator.

When we assume this, it makes it easier to understand measures as they all work as percentages, so it may be that this is a restriction we want to embed everywhere; or it may be that sometimes we don't.

If the former, we should have some way of asserting a measure meets these constraints before creating it; if the latter, we need to ensure the cost-saving-calculations won't break for non-proportion ratios.

As part of considering this, also think about if/how we might build a formal system for creating metrics. Ultimately this could form the foundation of something we could expose to end users for designing their own metrics.

The resolution of this task should be a proposal or detailed issue, covering:
- A classification and discussion of different kinds of measures and their pros and cons (ratios, proportions, etc)
- A formalisation of the design-a-measure process (e.g. how to decide if it's cost-saving or not, how to choose good numerators and denominators, etc)
- Possibly a more technical domain-specific analysis (data model, definitions, etc)
- Suggestions of next step (e.g. something that formalises the process as a DSL or a model with validations and/or workflow; or a lighter-touch validation of the existing workflow)

See discussion in #145 for background (and details of the cost-saving metrics)

**Comment by HelenCEBM** [comment]
@richiecroker @brianmackenna this relates to discussion of new measures and quality control procedures. Does it need to be an issue still?

**Comment by sebbacon** [comment]
I think this issue has been superseded by more recent QA discussions and will naturally come up again as and when it becomes a priority, so I'm happy to close
