### ISSUE TITLE
Broken link in NCSO alert email

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1503]
In my Islington CCG alert the link to the "[view our dashboard for NHS Islington CCG](http://email.openprescribing.net/c/eJx1kMFugzAMhp-muUSgEKDAISekbrt0h552Qk5w23TBqUjQtLdfYJO6SyVLtmPn92ePqjRV0xXMwHQHe6Eh-GU2qMgEnxlPBkOwnkIGDucYmFVSFJ2QUhaNbKoil0UpRd62VdvuKuFgvuAXapmjnkaI4EDnhJFdVdmN3blrsdZVPZadaar9fsS6AAECa1Ezp3ZSJmM4gXWDHVN-2OLkJ0_x6r75hsFXhkzIbO0_PEFNlZLNSs8WKJ_AfCIRJES6ho0oqodKSlaV4Z9KevqbOSz3tAk-TkQwoXoGxMKib2ii-kiH5L9fOWi_RH7sT--8f4zgZz_z4-uJvwVn6RI98b5_-QHQX4TN)" is broken. My browser gives  http://%22%22/

**Comment by HelenCEBM** [comment]
Was this fixed @brianmackenna ?

**Comment by brianmackenna** [comment]
It appears not however as no users have contacted us it probably isn't causing too much of an issue.

**Comment by evansd** [comment]
I've actually fixed this as part of #1731 which hasn't been merged yet but will be soon.
