### ISSUE TITLE
Bug in CCG calculations for measures querying practice_statistics

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1520]
There is a bug in our measure calculation code that affects measures where the value of a numerator or denominator for a practice can be null.

This affects the CCG ratios of measures that query the practice_statistics table, which is around half of our measures.

~specifically~

* ~ktt9_antibiotics~
* ~ktt9_cephalosporins_star~
* ~tamoxifen~

[Edit: I had originally thought that only three measures were affected..]

The problem is that if the denominator for a practice is null, the **numerator** for the corresponding measure value get set to zero (as well as the denominator, which is expected).  This doesn't affect the ratio for the practice measure, since if the denominator is zero we set the ratio to NULL.

However, it does affect the ratio for the CCG measure, because this is computed as the sum of all practice numerators over the sum of all practice denominators.  The sum of all practice denominators is never zero in practice so an incorrect sum of all practice numerators will give an incorrect ratio.

The denominator for a practice can be null when the denominator is selected from the practice_statistics table, because we don't have practice statistics for closed or dormant practices.

For example:

```
SELECT practice, month, SUM(items) AS numerator
FROM hscic.normalised_prescribing_standard
WHERE practice = 'Y02514' AND month = TIMESTAMP('2018-06-01') AND bnf_code LIKE '0501%'
GROUP BY practice, month
```

practice | month | numerator
-- | -- | --
Y02514 | 2018-06-01 00:00:00 UTC | 594

But:

```
SELECT practice_id, month, numerator, denominator, calc_value
FROM measures.practice_data_ktt9_antibiotics
WHERE practice_id = 'Y02514' AND month = DATE('2018-06-01')
```

practice_id | month | numerator | denominator | calc_value
-- | -- | -- | -- | --
Y02514 | 2018-06-01 | 0 | 0.0 | null

**Comment by inglesp** [comment]
I think the fix is to make the following change to `practice_ratios.sql`:

```
-      FROM num
-      RIGHT JOIN denom
-      ON num.practice = denom.practice AND num.month = denom.month
-      RIGHT JOIN practices_with_months
-      ON practices_with_months.practice_id = denom.practice
-        AND practices_with_months.month = denom.month
+      FROM practices_with_months
+      LEFT JOIN num
+        ON practices_with_months.practice_id = num.practice
+          AND practices_with_months.month = num.month
+      LEFT JOIN denom
+        ON practices_with_months.practice_id = denom.practice
+          AND practices_with_months.month = denom.month
```

The problem is that SQL `JOIN`s are left-associative, so in `num RIGHT JOIN denom RIGHT JOIN  practices_with_months`, `num RIGHT JOIN denom` is evaluated first, which loses any rows in `num` that do not have corresponding rows in `denom`.

**Comment by inglesp** [comment]
Having made this change locally, I've run a [hacked version of `import_measures`](https://gist.github.com/inglesp/fdb7ef7086b0bcb66e9272aa0bf02b12) to create new versions of the measure tables (with `_1520` appended to the measure name, eg `ktt9_antibiotics_1520`) in BQ.

I've then run:

```
SELECT COUNT(*)
FROM measures.ccg_data_{measure_id} t0
FULL OUTER JOIN measures.ccg_data_{measure_id}_1520 t1
  ON t0.month = t1.month AND t0.pct_id = t1.pct_id
WHERE t0.calc_value != t1.calc_value
```

against each measure to see where the new calculations differ with the old.  I was hoping only to see differences for only the three measures above, but there are difference for 43 (out of 70) measures.

| measure_id | n |
| - | - |
| bdzadq | 1042 |
| bdzper1000 | 1491 |
| ciclosporin | 1 |
| coproxamol | 3469 |
| fungal | 586 |
| ghost_generic_measure | 3451 |
| glutenfree | 1872 |
| ktt9_antibiotics | 652 |
| ktt9_cephalosporins_star | 395 |
| ktt9_uti_antibiotics | 174 |
| lpaliskiren | 33 |
| lpamiodarone | 161 |
| lpbathshoweremollients | 1466 |
| lpcoprox | 32 |
| lpdosulepin | 297 |
| lpdoxazosin | 359 |
| lpdronedarone | 9 |
| lpfentanylir | 111 |
| lpglucosamine | 145 |
| lpherbal | 21 |
| lphomeopathy | 7 |
| lplidocaine | 67 |
| lpliothyronine | 51 |
| lplutein | 291 |
| lpminocycline | 108 |
| lpneedles | 1722 |
| lpomega3 | 118 |
| lpoxycodone | 278 |
| lpperindopril | 265 |
| lprubefacients | 1209 |
| lpsilkgarments | 207 |
| lptadalafil | 140 |
| lptramadolpara | 86 |
| lptravelvacs | 234 |
| lptrimipramine | 84 |
| lpzomnibus | 1619 |
| opioidome | 1099 |
| opioidper1000 | 599 |
| other_lipid_modifying_drugs | 1404 |
| pregabalin | 331 |
| pregabalinmg | 331 |
| tamoxifen | 250 |
| test_strip | 1828 |

Oh dear.  Next step: look at measures where there is a difference and work out why.  Most likely candidate: my fix is faulty.

**Comment by inglesp** [comment]
We need to characterise how much of a problem this is.

First question: how many CCGs are affected?

* For each measure, how many CCGs have incorrect ratios?  How many in each month?
* For each measure, how many CCGs are ranked incorrectly?  How many in each month?

**Comment by inglesp** [comment]
There are a handful of pairs of measures/CCGs where the ratios and percentiles are noticeably different between the old (buggy) and new (fixed) methods of calculating ratios.  There are graphs demonstrating this below.

For each measure/CCG/month, we can calculate the absolute difference between the percentiles calculated with the old method and the new method.  We can then sum these differences over all months, to find out which measures/CCGs are most affected:

measure_id | ccg_id | diff
-- | -- | --
ktt9_antibiotics | 00R | 10.329897
ktt9_antibiotics | 02H | 5.077320
ktt9_antibiotics | 99N | 4.345361
ktt9_cephalosporins_star | 00R | 4.309278
ktt9_antibiotics | 01T | 4.103093
ktt9_antibiotics | 04Y | 2.701031
ktt9_antibiotics | 02E | 2.628866
ktt9_cephalosporins_star | 01T | 2.262887
ktt9_antibiotics | 01D | 1.850515
ktt9_cephalosporins_star | 02H | 1.505155

We can see how the ratios and percentiles change for the most affected measures/CCGs by plotting the old and new values on the same axes.

Here are the top four:

![image](https://user-images.githubusercontent.com/28734/54194048-4214b980-44b3-11e9-95ca-b0f93eba8f1a.png)

And here is the tenth:

![image](https://user-images.githubusercontent.com/28734/54194060-493bc780-44b3-11e9-9eeb-2859fe390773.png)

In terms of eyeballing it, there is very little difference here.

We can also see which measures are most affected by summing over months/CCGs:

measure_id | diff
-- | --
ktt9_antibiotics | 85.072165
ktt9_cephalosporins_star | 40.103093
lpneedles | 12.453608
fungal | 11.690722
tamoxifen | 11.690722
lpminocycline | 9.721649
bdzper1000 | 9.515464
test_strip | 9.432990
lpbathshoweremollients | 9.175258
opioidome | 8.958763

Or we can see which CCGs are most affected by summing over months/measures:

ccg_id | diff
-- | --
02E | 19.510309
00R | 17.319588
02H | 7.417526
01T | 7.268041
99N | 7.103093
10K | 6.675258
06T | 5.123711
04Y | 4.505155
10J | 4.170103
11N | 3.958763

**Comment by inglesp** [comment]
For discussion:

* What, if anything, should we do to notify users about this error?
* Are there any published papers that will need to be revisited?
* Is there any further analysis I can do that would be helpful here?

**Comment by inglesp** [comment]
[Here's a notebook with my analysis so far](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/issue-1520/issue-1520.ipynb).

**Comment by brianmackenna** [comment]
@inglesp really complicated but very clear. One question

> The denominator for a practice can be null when the denominator is selected from the practice_statistics table, because we don't have practice statistics for closed or dormant practices.

Is another type of error occurring with a practice when the CCG/BSA have classified the practice as a "normal practice" (i.e. =4) but its actually not and consequently has no list size?

> What, if anything, should we do to notify users about this error?

We should blog this once we have final analysis to make sure people are aware and the associated detailed analysis. Myself and @rich will be very familiar with getting emails about data along the lines of "the previous thing was incorrect, use this version", with none or minimal explanation.  I suspect the actual material impact on anyone is minimal and hopefully it'll be a subtle push to other NHS organisations to be more transparent about their data and errors. Additionally we should write to the CCGs in your table who were greatest affected to proactively point the towards the blog.

> Is there any further analysis I can do that would be helpful here?

Re: my question above, if the answer is yes. It might be helpful to get a list of top x practices who triggered the error to see if there is something consistent them.

**Comment by HelenCEBM** [comment]
Thanks @inglesp !

Question: there are new `1520` versions of all the practice tables but are they changed at all or is it just the CCG tables?

I don't *think* this will affect papers because we don't usually use the CCG measures tables, we use the raw prescribing data and/or the practice measures tables and perform calculations/aggregate as needed.

**Comment by HelenCEBM** [comment]
Also, I agree about writing a blog

**Comment by alexwalkercebm** [comment]
I can't think of any papers that this would affect either, as usual practice would be to get practice level data and aggregate it separately if CCG level was needed.
