### ISSUE TITLE
Poor peformance on `measure_for_all_ccgs`

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1528]
When visiting https://openprescribing.net/measure/ppi/, the API endpoint `/api/1.0/measure_by_ccg/?measure=ppi&format=json` is called.

Without caching, this takes in excess of one minute to return.

Informal profiling shows that most of the time is spent in [`_roll_up_measure_values`](https://github.com/ebmdatalab/openprescribing/blob/7c8f4a1fc37709a4345b0e07b16902427a47ceeb/openprescribing/api/views_measures.py#L262), which in this case loops over approx 12,000 values at a time of 5ms per loop iteration.

Things to think about:

* It's odd that 200ish sets of measurevalues being fetched take a minute to roll up; but 40ish standard measures at `measures_for_one_ccg` take much less than 12s to load
* Note that the same problem is exhibited for large CCGs (with many practices). Example: https://openprescribing.net/api/1.0/measure_by_practice/?org=15E&measure=ppi&format=json

**Comment by sebbacon** [comment]
Here's a quick profiling session done in a hurry ([link](https://rpm.newrelic.com/accounts/1550585/applications/45170403/profiles/3999890
)). Appears to show related field lookup taking most of the time, followed by some rather surprising gis-related stuff:

![image](https://user-images.githubusercontent.com/211271/53646257-a4a7c300-3c32-11e9-8cbe-db4668af0168.png)

**Comment by inglesp** [comment]
As Seb suspected there's an n+1 problem here.

I debugged it by making the following change to `LOGGING` in the local settings:

```
--- a/openprescribing/openprescribing/settings/local.py
+++ b/openprescribing/openprescribing/settings/local.py
@@ -110,7 +110,11 @@ LOGGING = {
             'filename':
             "%s/logs/mail-signals.log" % REPO_ROOT,
             'maxBytes': 1024 * 1024 * 100,  # 100 mb
-            }
+        },
+        'console': {
+            'level': 'DEBUG',
+            'class': 'logging.StreamHandler',
+        },
     },
     'loggers': {
         'django': {
@@ -128,6 +132,10 @@ LOGGING = {
             'handlers': ['signals'],
             'propagate': False,
         },
+        'django.db.backends': {
+            'level': 'DEBUG',
+            'handlers': ['console'],
+        },
     }
 }
```
