### ISSUE TITLE
Investigate NCSO concession problems

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1536]
The fetcher has been failing intermittently over the weekend, with `IntegrityError`s like:

```
Key (date, vmpp_id)=(2019-02-01, 1279011000001106) already exists.
```

**Comment by inglesp** [comment]
* The February 2019 data appears twice, on the [main page](http://psnc.org.uk/dispensing-supply/supply-chain/generic-shortages/) and on the [archive page](http://psnc.org.uk/dispensing-supply/supply-chain/generic-shortages/ncso-archive/).
* Two drugs (Lofepramine 70mg, Dosulepin 25mg) appear with slightly different names in each list -- in one list with a normal space character, and in the other list with a `\xa0` character.
* For each of these drugs ,`fetch_and_import_ncso_concessions` creates two `NCSOConcession` objects.
* These two `NCSOConcession`s would reconcile against the same `DMDVmpp`, which triggers the `IntegrityError`.
* After `fetch_and_import_ncso_concessions` creates a `NCSOConcession` it tries to reconcile it, but this is not wrapped in a transaction so if the reconciliation fails, the `NCSOConcession` stays in the database.  (I think this is what we want.)  This means that the next time the data is imported, the problem drug is ignored since the corresponding `NCSOConcession` already exists.

I don't think it's worth spending any time trying to fix this unless we see the problem again.  Instead, let's wait for the February data to disappear from the main page, and then we can remove the two unreconciled `NCSOConcession`s.

**Comment by evansd** [comment]
Just hit this again now and Seb and I were wondering why the `regularise_ncso_name` method isn't called at import time, as it would presumably prevent the duplicates ever making it into the database.
