### ISSUE TITLE
Systematically check for measures which need new BNF codes including

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1538]
E.g. the new formula measure, and opioids, depend on a list of BNF codes or calculations we've made in BigQuery but we should have a systematic way to know when any new codes should be included. 

Example SQL which could be the starting point for a check for the infant formula measure: 
```
SELECT COUNT(DISTINCT presentation) AS new_codes
FROM hscic.bnf b
LEFT JOIN measures.cmpa_products c ON 
WHERE 
presentation LIKE '%Althera%'
OR presentation LIKE '%Neocate%'
OR presentation LIKE '%Aptamil%'
OR presentation LIKE '%Similac%'
OR presentation LIKE '%Nutramigen%'
OR presentation LIKE '%Alfamino%'
OR presentation LIKE '%Pepti-Junior%'
OR presentation LIKE '%Pregestimil%'
```

**Comment by richiecroker** [comment]
Closing as we're moving towards dm+d where possible.
