### ISSUE TITLE
Get STP data from ODS

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1539]
It's linked to from https://digital.nhs.uk/services/organisation-data-service/data-downloads/other-nhs-organisations.

It helpfully contains STP to Regional Team mappings, which would allow a page like "show measure for all STPs in this Regional Team".

**Comment by brianmackenna** [comment]
I have had a discussion with ODS and they have informed me they have an "issue" with the API/xml that it doesn't flag dormant practices currently.

They are working on a fix. I have asked if it is documented on GitHub so we can be kept updated.

**Comment by inglesp** [comment]
Getting data out of the spreadsheet linked to from https://digital.nhs.uk/services/organisation-data-service/data-downloads/other-nhs-organisations will be possible, but as the spreadsheet format is unspecified, and STP changes are only likely to happen once a year, I'm not going to write a parser for the spreadsheet now.

Instead, I'm going to update STP membership by hand.  I'll identify which CCGs need membership updating by writing a hacky script to compare the spreadsheet with what we imported last year.  (https://data.gov.uk/dataset/ec1b6948-3c42-4abe-bfc0-8728f0911c0e/clinical-commissioning-group-to-stps-april-2018-lookup-in-england-version-2)
