### ISSUE TITLE
Integrate UX feedback into alert emails

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#155]
We made some reckons from our user research about the alert emails that we tested. We identified common problems and came up with some solutions.
- It takes too much work for the user to figure out what they have to do. We should just tell them clearly. (Kamal: "You prescribed XXXX Keppra items out of XXXX total for leviteracetam. If you could reduce this to XX%, you could save £XXXX over the next six months."
- The GPs in particular weren't actually sure what the measures were, because the descriptions we tested were a bit cryptic. We just need to be a bit clearer. 
- For CCGs, say how many practices are affected if possible - see #154
- For CCGs, highlight top practices affected

![img_20160815_135913](https://cloud.githubusercontent.com/assets/78156/17712722/234ac4a6-63ef-11e6-90f4-f925fab1d943.jpg)

**Comment by annapowellsmith** [comment]
This needs to be broken out into different tickets.

**Comment by HelenCEBM** [comment]
Closing in favour of #1295 (alerts feedback) and #864 (practice-level alerts for CCGs)
