### ISSUE TITLE
Links in All England measures are broken

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#1552]
The links in the main page for all-England returns an error - in the hyperlink there is an "undefined" definition:

https://openprescribing.net/ccg/undefined/keppra/

**Comment by inglesp** [comment]
Can you tell us which link is broken?

**Comment by richiecroker** [comment]
From here: https://openprescribing.net/all-england/#perfsummary

None seems to work:

![image](https://user-images.githubusercontent.com/18683239/54018410-7a995800-4180-11e9-82e8-fc10ba5fc41d.png)
