### ISSUE TITLE
All England Alerts

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1553]
Linked to #1017  and #1458 

Could we have a "regular alert" on prescribing measures, cost saving opportunities etc. and other things, particularly (Low Priority Prescribing) for All England page?

I think this would be very helpful for people at national NHS organisations but may also be useful for interested members of the public, pharma, journalists etc.

**Comment by brianmackenna** [comment]
These will be different from CCG/practice alerts as they are measuring change against peers. It should reasonably mirror the All England page. Features could include

- curated list of measures  national priority measures
- greatest spread/variation in CCGs
- top 5/10 spend
- where spend at a chemical level or chapter level has changed by x% compared to previous period
- total NHS spend YTD and versus this time last year

**Comment by evansd** [comment]
https://docs.google.com/document/d/1qHu02waSkGQBK-BYxLjYMTsGaI5YD8epU-Htkyc5niA/edit

**Comment by HelenCEBM** [comment]
Can we close this?

**Comment by evansd** [comment]
Yep! We'll make a new issue for feedback/improvements
