### ISSUE TITLE
Link to FAQ on items on analyse page results table

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1560]
In some analyses, e.g. small numbers and products only dispensed in single pack sizes at a known costs, users may be confused about why `items * price_per_pack != cost`. (We don't point out that `items != packs`)

Suggest most subtle solution may be to add a question mark to `items` in the results tables which links to the FAQ page (https://openprescribing.net/faq/#prescitem)

Or, point out that `items != packs` below the table and provide link there. We already have a note pointing at the general FAQ though. Do we need to be more specific?

![image](https://user-images.githubusercontent.com/24392156/54191294-87ce8380-44ad-11e9-88e1-740fd9da3d0e.png)

**Comment by evansd** [comment]
I wonder if part of the problem is that "items" sounds misleadingly understandable. Could we change it to something less obvious ("Prescribing Items" maybe, or even "RX Items") as well as having a question mark which links to the FAQ?
