### ISSUE TITLE
Hospital community prescribing data

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1584]
**New hospital data dispensed in the community**
https://www.nhsbsa.nhs.uk/prescription-data/prescribing-data/hospital-prescribing-dispensed-community

- [ ] Download and compile;
- [ ] Write a notebook describing it, trends and variation, high cost drugs;
- [ ] Write a blog, offer custom extracts, invite ideas;
- [ ] Apply for funding.

**Comment by brianmackenna** [comment]
Suggestion off the back off nonCCG data

> it would be helpful to know whether the team has access to hospital FP10 data, beyond drugs used in addictions. The reason for asking that we’re seeking similar price increases in risperidone, quetiapine and some commonly (and less commonly) prescribed medicines used in MH conditions. Most MHTs make use FP10s in their community teams, as they’re rarely located near to the to their Trust’s hospital pharmacy departments. It would be v helpful to be able to compare our FP10 spend with that of other MHTs (total 50 approx in England) via the OpenPrescribing resource
