### ISSUE TITLE
Many postgres errors continuing to happen

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1588]
[example](https://sentry.io/organizations/ebm-datalab/issues/901105946/?project=1254683&statsPeriod=14d)

These are affecting visits throughout the site and are [particularly noticeable](https://sentry.io/organizations/ebm-datalab/issues/901061670/?project=1254683) hitting the `/api/1.0/measure/` endpoint, in this example a bot which immediately previous to this visited the URL  `/practice/Y01025/price_per_unit/`.

Possibly related, we also had a high load incident around 2.10am this morning

![image](https://user-images.githubusercontent.com/211271/54683220-0019f200-4b09-11e9-9eee-51d728620997.png)

**Comment by sebbacon** [comment]
So the connections piled up at 11:32:29, and ended at 11:52:
```
2019-03-20 11:32:29 UTC [16777-1] prescribing@prescribing FATAL:  sorry, too many clients already
```

It was preceded by a series SQL queries that took in the region of 856s, on staging (NCSO calculations); could this be the culprit?  These started at 11:28:55. And staging *is* being crawled.

**Comment by sebbacon** [comment]
I also note that we previously decided to deal with this by adding a `robots.txt` disallowing API indexing, but since then we've added NCSO calculations that don't take place over the API.

I think the simplest solution is to add some HTTP basic auth to staging.

**Comment by evansd** [comment]
Yes, definitely in favour of basic http auth on staging

**Comment by sebbacon** [comment]
Closing in the hope this fixed it for now. There was quite a lot of bot activity indexing staging in the log files.
