### ISSUE TITLE
Cost Saving calculation at top of dashboard

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1598]
To be covered along with #986 

The cost saving calculation summary at the top of dashboards is not giving a sensible figure. For example on the [Luton STP dashboard](https://openprescribing.net/stp/E54000024/measures/?tags=cost)

> Over the past 6 months, if this STP had prescribed at the median ratio or better on all cost-saving measures below, then it would have spent **£1,643 less**. (We use the national median as a suggested target because by definition, 50% of practices were already prescribing at this level or better, so we think it ought to be achievable.

**Comment by HelenCEBM** [comment]
The figure now looks bigger and seems to reflect the sum of all of the parts.
