### ISSUE TITLE
FAQ: add clear link to measures code

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1601]
Currently it's not clear how to find the code behind the measures without navigating through the whole OP code. This is probably the most interesting part of the code to most users so could be easier to find.

Perhaps add link under here: https://openprescribing.net/faq/#measurechose ?

**Comment by brianmackenna** [comment]
Suggested text

> Our original list of measures were developed in discussion between Drs Jeff Aronson, Kamal Mahtani, Ben Goldacre at the University of Oxford, and Richard Croker from Northern, Eastern & Western Devon CCG.
> 
> Since then measures have been iteratively developed based on recommendations from national organisations or suggestions from users. The underlying code for our measures can be found on our [GitHub page](https://github.com/ebmdatalab/openprescribing/tree/master/openprescribing/frontend/management/commands/measure_definitions).

**Comment by HelenCEBM** [comment]
User request today looking for the list of ICS included in high-dose measure. 

Limitation of the above idea could be that the measure names in github are somewhat cryptic and it's annoying to have to navigate through FAQ Would be easier and more transparent if we can put a link to the measure on GitHub from each measure itself. It could be a small icon which tells you what it is on hover, to be less intrusive? Or a link such as "behind the scenes", "see the code/back-end", "see measure construction" or similar.

**Comment by richiecroker** [comment]
Closing as measure code link is included in measure details on site now.
