### ISSUE TITLE
Show all CCGs in Region/STP on single chart

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1603]
A user suggested

> To have all the data from the 10 CCGs for GM on one graph / dashboard so I can see how they compare with each other and have the comparator as GM Local Area and the national average

**Comment by inglesp** [comment]
This'd be great, but it's something that'll be much easier to implement once we've got the matrixstore.

**Comment by HelenCEBM** [comment]
See also #1882
