### ISSUE TITLE
Create PCN dashboards

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1614]
(see #1462 for some background)

@brianmackenna is trying to get codes for these groups. 

In the absence of national PCN map and codes perhaps we can prototype using a subset of PCNs...

**Comment by brianmackenna** [comment]
Following discussion at DataLab day. We should create a holding page for PCNs in order to a) reduce amount of queries we deal with b) direct users to NHS England to emphasise importance of ODS codes.

Suggested text

> Primary Care Networks (PCNs) are groups of general practices and other organisations working together to improve the health of their community. On this page we would love to display prescribing patterns for PCNs but unfortunately PCN groupings are not currently available.
> 
> PCNs are expected to be agreed  and confirmed by  31.5.19 with contracts signed by 30.6.19. Following this the NHS Digital Organisational Data Service (ODS) must provide ODS codes for every PCN in order for us to display dashboards here. For context, it took 18 months to develop ODS codes for the 44 STPs. If you would like PCN dashboards sooner than this please contact england.pcn@nhs.net and emphasise the importance of generating ODS codes.
> 
> Alternatively at OpenPrescribing we could build a feature that allows you to build your own custom groupings of organisations. In order to build this we need a small amount of funding. If you think this would be a useful feature and have access to some funding please get in touch at feedback@openprescribing.net

**Comment by brianmackenna** [comment]
Update from NHS England.

NHS England are expecting to release an electronic submissions form for PCNs which will be completeed via [CQRS ](https://digital.nhs.uk/services/calculating-quality-reporting-service). This means there should be an electronic list available in some form by the deadlines above. Official ODS codes will take longer as they have to build some more in future use cases.

**Comment by brianmackenna** [comment]
Discussion: Implement Devon as demonstration that we have built the infrastructure while we await NHS England list. @richiecroker  to upload of Devon members.

**Comment by richiecroker** [comment]
[Devon CCG PCN Practice Codes.zip](https://github.com/ebmdatalab/openprescribing/files/3569727/Devon.CCG.PCN.Practice.Codes.zip)

**Comment by brianmackenna** [comment]
Live at  https://openprescribing.net/pcn/
