### ISSUE TITLE
Remove unnecessary fields from database

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#162]
I aded the `price_per_unit` field in the prescribing table, but we don't need and never use it. It can just be deleted. 

Also we could potentially remove `net_cost`, `bnf_name`, and `sha`, since we never use any of these (the downside is that if we did want to query by any of them, we'd have to add them back in). 

Longer-term we could look at losing `pct` too, potentially, since we can derive this data from elsewhere at the matview stage. 

Also, @sebbacon spotted that we can save space by using more efficient data types for the numeric fields. 

Discuss whether any of this is worth doing before we get Postgres help.

**Comment by sebbacon** [comment]
From [previous notes](https://docs.google.com/document/d/1u1TQ4rw3QF5tgtYAAQdzPL5f5_7v2NRbybfVRy9emfM/edit#)

> A quick analysis suggests we could replace total_items with a tinyint, and the double precision fields with floats, and reduce the size of the table by at least than 30%. We can also drop the price_per_unit field.

**Comment by annapowellsmith** [comment]
Unfortunately, it's probably impractical to do this [as spotted by @sebbacon ](https://github.com/ebmdatalab/openprescribing/issues/202#issuecomment-248937928). Closing.
