### ISSUE TITLE
Page freezes after loading first few charts if you try to scroll

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1643]
When you select "compare all CCGs" on the browser (e.g. [Keppra](https://openprescribing.net/measure/keppra/) ) it displays the first 6, then the page freezes for 5-10 seconds where you cannot scroll down. Once time elapses the graphs are all displayed.

This is a design feature due to performance of trying to load all 200 at once. @sebbacon  suggestion _Probably the correct fix is to load each chart individually as it scrolls into view, each with its own spinner_

**Comment by HelenCEBM** [comment]
Seems to be fixed now @sebbacon ?
