### ISSUE TITLE
Android - no charts displayed on compare all measures

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1644]
Probably related to #1643  On my android mobile device I selected the "compare all CCGs on this measure" - the first three graphs load immediately but no other graphs load giving the impressions the page is broken (you can scroll down the blankness). On further plays the charts do load after about 20-30 seconds.

The non-appearance of any charts is new, I previously used to get the same amount of page freeze as in #1643 and is still on my browser.

**Comment by richiecroker** [comment]
seems to work now on my android phone
