### ISSUE TITLE
Colour changes on OP screen - Black and Purple

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1645]
We received this screenshot below from a user. After receiving his browser version info (IE and Chrome) We advised him to 
a) hard refresh
b) check configuration settings (i.e. is it an accessibility setting)
c) contact his IT

The user advised it was working fine on all his other devices and his IT thought it was a local issue but they were not sure which. (I have sent a follow up)

Nothing immediate to be done but I think it happened before and @helen asked about it on slack since this report so guess there was another report to her personally.

![image](https://user-images.githubusercontent.com/40460354/56229879-da81f900-6072-11e9-926e-599388b5e964.png)

**Comment by sebbacon** [comment]
It's pretty clearly the stylesheet not loading - possibly just the bootstrap one. If it's in Chrome and IE then it sounds like a network configuration issue, possibly.

The bootstrap stylesheet is loaded from https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css, but I can't think how that would be related.

We could ask the user if they can load that page when they click on it.

Any thoughts @evansd?

**Comment by brianmackenna** [comment]
User feedback
>Just checked it on the same laptop but at home and it works like normal (no purple thing)?! Must be something to do with set-up at work.

**Comment by sebbacon** [comment]
Great - can we ask them to visit that link from work? viz https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css  

and report back what they see. it should be a bunch of code.

**Comment by brianmackenna** [comment]
Update
> The link is blocked by our firewall !!! MY head of dept has asked our IT dept to resolve the issue. She (rightly) thinks your site is too important to be restricted in anyway.  I will let you know if that sorts it out as I guess that is a solution of sorts even if it not something that can be resolved ‘your side’

**Comment by sebbacon** [comment]
I think we can count this as fixed!

I would be intrigued to know what the IT dept justification is for blocking files from that link (it's widely used across the internet and will break quite a few sites) but I doubt we'll get much of an answer.

**Comment by evansd** [comment]
I actually think we should self-host all our dependencies anyway. Relying on third-party hosted stuff just creates potential for mysterious problems (like this one) and prevents doing development offline. Given that we're using Cloudflare there's no performance advantage. (The other possible advantage -- that first time visitors might already have some of those dependencies in their browser cache -- is pretty negligible I think.)

**Comment by sebbacon** [comment]
I agree, TBH it's just sheer laziness on my part because we don't have nice tooling around self-hosting such resources yet

**Comment by evansd** [comment]
@brianmackenna I've pushed out a change which should hopefully fix the issue he was having and prevent weird things like this happening in future. Do you mind getting back to him and letting him know?

**Comment by brianmackenna** [comment]
Response from user

> Good work! Looks fine now. Thanks to the team
