### ISSUE TITLE
Ghost branded generics number disagreement

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/openprescribing#1646]
The figures for GBG excess costs for the measure and on the CCG front page should match, and don't:
![image](https://user-images.githubusercontent.com/24895935/56293929-f09ac280-6121-11e9-96ee-c979af12b69f.png)

![image](https://user-images.githubusercontent.com/24895935/56294142-58510d80-6122-11e9-9ca8-6be4b4e71cac.png)

Seb suggested "might be related to non-standard practices", but it seems to be discrepant at practice level too, e.g. https://openprescribing.net/practice/D83030/ and https://openprescribing.net/measure/ghost_generic_measure/practice/D83030/

**Comment by inglesp** [comment]
They're computed differently.  One comes from a measure, which is calculated from data in BQ, and the other is calculated from various tables in Postgres.

Working out how/why they're different is going to be a bit fiddly, and I might not get to that today.

**Comment by inglesp** [comment]
Both calculations ignore presentations where the possible savings are small, but they have different definitions of small.

The measure definition ignores presentations where the possible savings are less than 2, while the GBG page ignores presentations where the possible savings are less than 5.

It'd be easier to change the calculation for the GBG page.  This would mean changing `api.views_spending.MIN_GHOST_GENERIC_DELTA` to 2.

@sebbacon Any reason not to do this?

**Comment by alexwalkercebm** [comment]
Less than 2 is the definition I've used in the paper too, so everything being 2 seems fine to me.

**Comment by sebbacon** [comment]
:+1:

**Comment by HelenCEBM** [comment]
Any update on this @inglesp ?

**Comment by inglesp** [comment]
Slipped off my radar, sorry.  This is fixed in #1733.
