### ISSUE TITLE
Products coming off patent 

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1649]

**Comment by sebbacon** [comment]
Is this an idea for a measure?

**Comment by brianmackenna** [comment]
From a user for suggested development
>Is there anyway of knowing which products are coming off patent or when cheaper alternatives become available?Is there anyway of knowing which products are coming off patent or when cheaper alternatives become available?

NHS SPS does produce a [horizon scan document](https://www.sps.nhs.uk/articles/prescribing-outlook-2018/) that provides some of this information. I have knocked up a prototype before for SPS to include links to OP in their document.

As regards on the OP site if we did get a feed of data it may help CCGs to plan but there are other considerations e.g. does stock arrive in the UK, drug tariff negotiations Cat M that makes it impossible to reasonably predict.

**Comment by sebbacon** [comment]
I see SPS claim to publish this as a spreadsheet, though all the links are broken, so hard to say.

This reminded me of "price shock calculator" idea which we've discussed previously and I feel has some legs

Couldn't find an issue for it, so have made one here #1650

Maybe close this issue as incorporated into that, or do you think this is quite different?
