### ISSUE TITLE
make a csv for all practices/CCGs for all measures

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1666]
To reduce load on bespoke data requests, produce a monthly csv file with measures that we can direct people too.

fields requested for people.

Measure | pct_id | Practice_id | Month | Numerator | Denominator | calc_value | Percentile
-- | -- | -- | -- | -- | -- | -- | --

**Comment by inglesp** [comment]
Created with:

```
COPY (SELECT measure_id, pct_id AS ccg_id, practice_id, month, numerator, denominator, calc_value AS ratio, percentile FROM frontend_measurevalue WHERE practice_id IS NOT NULL ORDER BY measure_id, pct_id, practice_id, month) TO '/tmp/measures201902.csv' WITH (FORMAT CSV, HEADER);
```
