### ISSUE TITLE
Bug on positive messages for cost savings for cost-related measures

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1687]
Following on from #1684.

 There seems to be a bug on practice pages in calculating "positive" messages.  For example in [Islington Cental](https://openprescribing.net/practice/F83010/measures/?tags=lowpriority) the prescribe no co proxamol ([link to measure](https://openprescribing.net/measure/lpcoprox/practice/F83010/)) so it should have a postive message like _By prescribing better than the median, this prctice has saved the NHS £xxxx over the past 6 months_

It seems to work ok on CCG pages see liothyronine [here](https://openprescribing.net/ccg/08H/measures/?tags=lowpriority)  and regions [here](https://openprescribing.net/regional-team/Y56/measures/?tags=lowpriority)

**Comment by inglesp** [comment]
This affects measures where the median practice (or CCG, in the case of lphomeopathy) has zero prescribing.

We can change

> If it had prescribed in line with the median, this practice would have spent £0 less over the past 6 months

to

> By prescribing better than the median, this practice has saved the NHS £0 over the past 6 months

which is slightly more positive!

**Comment by brianmackenna** [comment]
I don't think it make sense to majority of our users. Should we not have something like

> By prescribing better than the median, this practice has saved the NHS £0 over the past 6 months. Your prescribing is in line with most practices and you have all reduced your prescribing to £0 so therefore we don't assign a positive sum  

I'm not fully happy with that wording so please feel free to tweak. 

If this is fiddly and requires messing with frontend code can I suggest we do the pull request as is and make a new issue? We can then review with #986 when we get to it, when we get user feedback or when we decide it hits top three

**Comment by inglesp** [comment]
How about:

> Over the last six months this practice spent £0, which is in line with the median practice.  No further improvement is possible!

**Comment by brianmackenna** [comment]
Perfect!
