### ISSUE TITLE
Herbal Measure returning homeopathy prodoucts

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1688]
The herbal measure has started to return homeopathic products (see [example](https://openprescribing.net/measure/lpherbal/ccg/04J/)) Checking the [measure definition](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/lpherbal.json) makes it most likely that homeopathic products are included in the table `ebmdatalab.richard.herbal_list`  as they are probably tagged in dmd by BSA as herbal.

Querying the table (SQL below) however only returns  _Strains 9% homeopathic cream_

Any ideas @richiecroker ? I'm sure I am doing something wrong on investigation.

```
SELECT *
FROM `ebmdatalab.richard.herbal_list`
WHERE name like "%homeo%"
```

**Comment by richiecroker** [comment]
These products all seem to have a code of "Homeopathic presentations - proprietary" - possibly incorrectly?
![image](https://user-images.githubusercontent.com/18683239/57850160-2a202580-77d5-11e9-9b20-64b8119bc4ae.png)

**Comment by inglesp** [comment]
Here is a list of all the dm+d objects with that BNF code: https://openprescribing.net/dmd/bnf/190203000BBAAA0/relationships/.

This is derived from the latest mapping from the BSA (from September).  We could contact them about mistakes in the mapping, but as [their mapping page](https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping) says "The next version is currently delayed", I'm not hopeful!

**Comment by inglesp** [comment]
@richiecroker How is `richard.herbal_list` curated?  Is it the current licence authority in dm+d?

**Comment by inglesp** [comment]
And what should the BNF code be for these?

**Comment by richiecroker** [comment]
@inglesp yes anything with THR license in dm+d.  

Sort answer I think is that mapping is wrong.  They are all mapped to same BNF presentation code, which is a shame.  I think the only thing we can do is exclude `190203000BBAAA0` from that measure.

**Comment by richiecroker** [comment]
They don't seem to have understood difference between "herbal" and "homeopathic"

**Comment by richiecroker** [comment]
I need to update list anyway, as it should be grouped and it isn't, leading to multiple lines for same product.  I will do that now.

**Comment by HelenCEBM** [comment]
Any update on this @richiecroker ?

**Comment by brianmackenna** [comment]
@richiecroker @inglesp  [does this PR fix](https://github.com/ebmdatalab/openprescribing/pull/2208) this issue?

**Comment by richiecroker** [comment]
@brianmackenna yes it does
