### ISSUE TITLE
Querying ranges of dates via the API

### ISSUE THREAD

**Issue by glfharris** [ebmdatalab/openprescribing#170]
Just wondered if there were any plans to allow querying between a range of dates for the views that already allow selection by date. 

I'm writing a python wrapper for the api part of which I want to be able to query for a range, but as it stands either it seems a little inefficient retrieving the whole timeline, or requires repeated calls per month. Might also make testing/writing tutorials a little more robust as you could ensure each person would get the same result even after more data is added.

I've got an [example here](https://github.com/glfharris/openprescribing/commit/8713a64a57ca5b9e86a96c689a1e2c4443d9b178) that I haven't been able to test yet, though I'm not a fan of how the dates are input as it's a little ambiguous whether it's a list or a range.

**Comment by sebbacon** [comment]
Hi there, thanks for this. 

We're not planning to add support for more dates, as internally we now use BigQuery for analysis on this dataset, and the API now only really drives the website. You might want to look at that instead. 

Happy to give you access to our BigQuery dataset if that's of interest - just let us know a Google account name. We just ask that you cite us if you produce anything using it.

**Comment by glfharris** [comment]
That would be much appreciated, though full disclosure I'm only a medical student, so can't guarantee any publications etc. If that's still ok I think glfharris should work.

Cheers!

**Comment by annapowellsmith** [comment]
@glfharris just given you access - you should have an email. "prescribing" is the dataset of interest. 

It's fine to poke around and run queries, but please don't start scripting anything, because it'll get expensive fast :) if you want to do that then please let us know and you can fork the dataset - Google will give you a monthly quota to run queries for free.

**Comment by annapowellsmith** [comment]
I'm going to close this now, but shout if you object!
