### ISSUE TITLE
Make data in BQ public

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1719]
We can make the following data public:

* Practices/CCGs/STPs/Regions
* Normalised prescribing data
* List sizes
* BNF codes

@brianmackenna  Is this enough?

We could also make the following public:

* Measures
* dm+d

Measures would require some thought, and dm+d would require some documentation, although we need to do that anyway.

I would prefer to create a new dataset (eg `ebmdatalab.public`) and copy data into it, rather than giving access to existing datasets.  This would allow us to:

* change the format of the tables we use as intermediate stages in the import without worrying about external users
* make the data more consistent (see https://github.com/ebmdatalab/openprescribing/issues/764#issuecomment-365753196 for some old notes about consistency)
* manage access on a per-dataset basis

@sebbacon does this make sense?

**Comment by sebbacon** [comment]
Yes this makes sense, though I think the new dataset could use views rather than copying data, which requires new tooling that might be overkill at this early prototyping staging.

We should take the opportunity to review our IAM setup and move internal users to GSuite accounts.

**Comment by brianmackenna** [comment]
Happy with that as a starter, maybe leave measures and dm+d until we are comfortable with people using it and they can assist with documentation as an independent view.

**Comment by sebbacon** [comment]
Things to think about:

* Would it be faster to materialise our "views" and if so by how much?
* How would we publish this? I think there's some way of making datasets freely published for all if you put them in the public domain.

**Comment by brianmackenna** [comment]
Brief discussion with meds analysis team on current process and what they would like

- They use R and SQL mainly
- They need access to do quick bespoke analysis
- Currently process is
have to download from ePACT (which takes ages) and then upload to R
bespoke request discrete datsets which are provided in a 2week turnaround in a "letterbox" analysis style"
- They generally only use CCG level as nobody has ever asked for it
- they would like Prescribing data, some statistics data such as patient list size, and they are quite interested in using dm+d

**Comment by inglesp** [comment]
Conventions:

* Use singular table names
* Use `id` for primary key
  * except for `presentation`, where we use `bnf_code`?
* Use `_id` suffix for foreign keys
  * except for `presentation_id`, where we use `bnf_code`?
* Use "ccg" instead of "pct" everywhere
* Use `DATE` type for all dates (not `TIMESTAMP` as we do currently)
* Use `INTEGER` type for all costs, in pence
  * check that costs are actually in pence!

**Comment by inglesp** [comment]
Feedback on #2017 (now merged) from @HelenCEBM:

Great, happy to work with Caroline on writing guidance.

Some thoughts:
- It would be useful to describe what period each dataset covers (e.g. ccgs and practices are current - so you can't see which CCG your practice belonged to last year for example, bnf is current, prescribing and list sizes cover 2010-present, or last 5 years?) - will they be automatically updated each month?
- People may often want to recreate our measures so that could be a good thing to include in guidance (e.g. how to copy and adapt from our measure definitions) - or they might want to adapt from an Analyse query. 
- we might need to make a note of which tables are not currently available that some measures rely on e.g. ADQs and opioid OME, if we release without them. These might be useful to release, though (in due course), as these will be the complex measures that can't currently be recreated in the Analyse page. 
- People may wish to select "all generics" or similar for a query. 
- Is prescribing table normalised? We should describe if so. 
- Are there any ways that the results might differ from what's on the site? (E.g setting=4)
