### ISSUE TITLE
Common javascript could do with refactoring

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#173]
This is an attempt to explain what I was inexpertly waffling about the other day!
- All our pages require jquery and bootstrap (for the main menu, at a minimum)
- The forms javascript requires jquery but not bootstrap
- The measures javascript requires neither

Ideally, we would include jquery and bootstrap on every page, stuff only for forms on forms pages, and stuff only for measures on measures pages. The current approach requires us to load (and remember to load) jquery and bootstrap on every page using a [synchronous require](https://webpack.github.io/docs/motivation.html#commonjs-synchronous-require).

It would be nice (read: less client side code to download, less likelihood of bugs like #171) to be able to specify "jquery and bootstrap on all pages, form.js on the analyse page (wtih a dependency on jquery and boostrap)".

Not sure of the best solution yet, or if we should worry about it at all at this stage; just throwing this out there for discussion. I guess the pattern is something like [this](https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points) or [code splitting](https://webpack.github.io/docs/code-splitting.html) ([example](https://github.com/webpack/webpack/tree/master/examples/code-splitting))

**Comment by HelenCEBM** [comment]
Is this still an issue?

**Comment by sebbacon** [comment]
This was fixed about a year ago :)
