### ISSUE TITLE
Rename dmd2 to dmd

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1734]
Plan:

- [x] Run `./manage.py migrate_some_dmd_data` to copy `TariffPrice` and `NCSOConcession` data from the `dmd` models to the new models in `frontend`.
- [x] Deploy #1718 
- [x] Rename all `dmd_XXX` tables to `dmd_XXX_old`
  * For each table, run `ALTER TABLE dmd_XXX RENAME TO dmd_XXX_old;`
- [ ] Copy all `dmd2_XXX` tables to `dmd_XXX`
  * For each table, run `CREATE TABLE dmd_XXX AS TABLE dmd2_XXX`
- [ ] Create and deploy new PR that does:
  * `rm -r dmd`
  * Remove `dmd` from `INSTALLED_APPS`
  * `mv dmd2 dmd`
  * `rg -l dmd2 | xargs sed -i s/dmd2/dmd/`
  * `find . -name *dmd2* | sed 'p;s/dmd2/dmd/' | xargs -n2 mv`
- [ ] Update the migrations table with:
  * `DELETE FROM django_migrations WHERE app = 'dmd'`
  * `UPDATE django_migrations SET app = 'dmd' WHERE app = 'dmd2'`

Is there anything I'm missing?

**Comment by sebbacon** [comment]
I can't think of anything else

**Comment by evansd** [comment]
That looks right to me. Although I think that between the "deploy" and "DELETE" steps it would be good to get the rest of the team to do some click-around testing

**Comment by inglesp** [comment]
>  Copy all `dmd2_XXX` tables to `dmd_XXX`

I'd planned to do this with `CREATE TABLE dmd_XXX AS TABLE dmd2_XXX` but this doesn't copy the structure.

We can do `CREATE TABLE dmd_XXX (LIKE dmd2_XXX INCLUDING ALL);` but this won't get the constraints right (eg `dmd_amp.vpid` will have a foreign key constraint on `dmd2_vmp.vpid`.

I think we'll have to split this into a couple of steps:

* remove old `dmd` app (PR 1)
* delete old `dmd` migrations from `django_migrations`
* create new `dmd` app with `models.py` and migrations from `dmd2` (PR 2)
* copy contents of `dmd2_XXX` tables new `dmd_XXX` tables
* rename `dmd2` to `dmd` everywhere (PR 3)

**Comment by inglesp** [comment]
Done!
