### ISSUE TITLE
Support PCNs

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1747]
Agreed to:

* Use the same approach Peter used for Regions and STPs (q.v. old PRs)
* Take the opportunity for light refactoring with a view to our planned big refactor about groupings

**Comment by inglesp** [comment]
The relevant PRs:

* #1238 (Add RegionalTeam and STP models)
* #1243 (Add tasks to import STPs and regional teams)
* #1244 (Update import_measures for STPs and regional teams)
* #1251 (Support CCG groupings in API)
* #1257 (Preparation for CCG grouping frontend changes)
* #1345 (Fix e2e tests)
* #1415 (Add Regional Team and STP pages)

**Comment by evansd** [comment]
Closed by #1810 #1813 #1825 and #1828
