### ISSUE TITLE
Matrix store import slower than expected

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1767]
It is currently taking up to 19 hours

```
# select status, year, month, ended_at - started_at as time_elapsed from pipeline_tasklog where task_name like 'build_matrixstore';
┌────────────┬──────┬───────┬─────────────────┐
│   status   │ year │ month │  time_elapsed   │
├────────────┼──────┼───────┼─────────────────┤
│ failed     │ 2019 │     3 │ 00:00:00.248543 │
│ successful │ 2019 │     3 │ 17:22:06.908056 │
│ successful │ 2019 │     4 │ 19:05:59.498378 │
└────────────┴──────┴───────┴─────────────────┘
(3 rows)
```
On the one hand, building the views takes 11.5 hours, and that can potentially go away relatively soon, mitigating the problem somewhat.

Also, per #1763, once we have dropped views and are generating measures from the matrix store, it won't matter so much if the matrix store takes so long, as it won't impact site functionality while building.

However, it's probably going to take a while for us to be able to retire the views and measures, so it is probably worth doing a little investigation.

These DO charts do suggest what you'd think, which is that it is CPU-bound:

![image](https://user-images.githubusercontent.com/211271/59905516-58110f00-93fe-11e9-97dc-92904638aadd.png)

@evansd has suggested looking at compression options.

We could also look at running the build in Google Compute.

**Comment by richiecroker** [comment]
@evansd is this still current?

**Comment by evansd** [comment]
In practice this turns out not to have caused us any real problems so we've never bothered investigating further.
