### ISSUE TITLE
PPU Page - New "Generic" Product

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1770]
On the [All England PPU page](https://openprescribing.net/all-england/price-per-unit/) new presentations have appeared which don't make complete sense.

- [Generic](https://openprescribing.net/all-england/190700000AABABA/price-per-unit/?date=2019-03-01) this appears to be nutritional thickeners. This needs a better name than generic
- [Generic Aveeno](https://openprescribing.net/all-england/130201000AAA8A8/price-per-unit/?date=2019-04-01) This appears to be all Aveeno but BNF code associated with Gppe product. There is probably a different PPU due to different reimbursement amounts for different quantities.  I think the name is fine as is.

I imagine these have arisen due to the new matching.

**Comment by sebbacon** [comment]
I wonder if this is related to the left-stemming-on-name logic I remember discussing. 

If so, just to note I found a [formal dm+d naming specification document yesterday](https://www.nhsbsa.nhs.uk/sites/default/files/2018-09/dm%2Bd%20description%20guidance%20v1.0.docx).
