### ISSUE TITLE
Consider uploading lower-res CCG boundaries

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1797]
The current 2019/20 boundaries JSON file is around 7Mb compared with less than 2Mb for previous years.

I suspect I downloaded and imported the "generalised" rather than "super generalised" boundaries ([source](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=BDY_CCG%2CAPR_2019).

To reimport, I must do the QGIS dance again.

**Comment by sebbacon** [comment]
I'm puzzled.  I imported the "ultra generalised" boundaries, but these were clearly not what we used before:

![image](https://user-images.githubusercontent.com/211271/60429542-2f092f00-9bf3-11e9-9146-9da02fea3264.png)

And the file size of the downloaded JSON was about half of previous years' JSON.  So previously, it appears we used less generalised boundaries than the "ultra" release.

I've just worked it out. Last year they provided "Generalised", "Super Generalised" and "Ultra Generalised"; this year they only provided "Generalised" and "Ultra Generalised" boundaries :angry: :

![image](https://user-images.githubusercontent.com/211271/60431027-a68c8d80-9bf6-11e9-95f0-4bacf3cb6673.png)

2018 boundaries:
![image](https://user-images.githubusercontent.com/211271/60431055-b86e3080-9bf6-11e9-945d-107f87914d94.png)

**Comment by sebbacon** [comment]
So the next question is, do we want to use Generalised or Ultra Generalised from now on?

The former uses 7Mb uncompressed on disk, where the latter uses 950Kb (as opposed Super Generalised which used about 1.7Mb).

The data is very compressible so under normal circumstances the download time won't be enormous; however, the JSON deserialisation may be quite expensive particularly in slower mobile devices.  Without lots of testing we can't really know, but it's generally a good idea to go for smaller filesizes unless otherwise indicated.  So it boils down to if we think Ultra looks good enough.

## London ultra-generalised:
![image](https://user-images.githubusercontent.com/211271/60432595-8e1e7200-9bfa-11e9-9b0c-9b5e21b9e471.png)

## London generalised:
![image](https://user-images.githubusercontent.com/211271/60432633-a4c4c900-9bfa-11e9-9b10-2f016653632d.png)

**Comment by HelenCEBM** [comment]
The simpler one looks fine to me - I can't think of a reason we (or our users) would need really detailed boundaries

**Comment by alexwalkercebm** [comment]
It does make the Thames look a bit funny, but probably not a big issue for the site. Maybe the more detailed would be better for papers?

What's the downside to using the more detailed version? Performance?

**Comment by evansd** [comment]
I would definitely prefer to use the most generalised boundaries we can get away with. I agree with Helen that our users don't need geographic precision and so I'd much rather optimise for performance, both server and client side.

FWIW, in the past I've used [mapshaper](https://github.com/mbloch/mapshaper) to produce my own generalised boundaries from high res input data. So we're not stuck with the generalisation levels that ONS decide to give us.

**Comment by sebbacon** [comment]
Thanks all!

FYI I use QGIS for all such magic @evansd. And for the record that's how I updated the cartogram base map for our `datalab-pandas` package, i.e. using the `cartogram3` plugin.
