### ISSUE TITLE
Link to or embed our new research page

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#1798]
https://ebmdatalab.net/openprescribing-research/

**Comment by sebbacon** [comment]
I'd probably put this in the "More" menu.

Ideally we'd embed it somehow, but the duplication is a bit of a PITA

There is the `gdoc_view` in OP that allows us to pull in a Google Doc, although the formatting often comes out a bit wonk.

Note we will be implementing our website as more of a content-type-focussed thing in the next few months (i.e. database tables representing things like Papers, Jupyter Notebooks, etc) so probably not worth spending more than a few minutes thinking about this now...

**Comment by HelenCEBM** [comment]
happy to do the gdoc if helpful

**Comment by evansd** [comment]
Done the quick and dirty way in #1808 to meet a deadline

**Comment by evansd** [comment]
@HelenCEBM or someone else with access to the ebmdatalab.net version of that page, there are two changes we could make to the original version which would make our copy of it display better:

 * [ ] Replace the sub headings which are just bolded text with H4 elements i.e.,
   replace `<p><strong>...</strong></p>` with `<h4>...</h4>`
   (H2 would be the semantically correct thing here but that doesn't work with the ebmdatalab.net styles)
 * [ ] Consistently use line breaks before the DOI link. The original page is narrow enough that they always break on to a new line anyway, but not so for the embedded copy.

I can fix the box colours and padding to look a bit nicer.

**Comment by HelenCEBM** [comment]
Done @evansd

**Comment by HelenCEBM** [comment]
@evansd is there anything else to do on this or can we close it?

**Comment by evansd** [comment]
I'll close it. I was holding off closing while I was thinking about ways of automatically keeping it updated. We've got [a plan](https://github.com/ebmdatalab/sysadmin/issues/72) now but it will be a little while before that gets implemented.
