### ISSUE TITLE
Make an all-England equivalent of the "single measure for one entity" page

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1823]
Specifically, we want to be able to include the GBG measure in an iframe for a "live figure" in a paper, like this:

![image](https://user-images.githubusercontent.com/211271/60878928-99941d80-a238-11e9-8697-bae2112d1757.png)

**Comment by evansd** [comment]
Done in #1824 

For actually embedding the chart it an iframe we're going to use the technique here:
https://github.com/evansd/screenshotter
