### ISSUE TITLE
PCN implementation feedback

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1833]
There's no single PR to record feedback in, so this issue is standing in.

For the purposes of testing, @evansd has created [dummy PCNs which have exactly the same membership as CCGs](http://staging.openprescribing.net/pcn/).

Please test measures, dashboards and analyse form for PCNs on staging, and add feedback here.

**Comment by sebbacon** [comment]
* On the map view of the analyse form, there should be a warning (underneath?) that the boundaries are indicative only

**Comment by HelenCEBM** [comment]
Looks great!

Can the maps on dashboards be more zoomed in, by about 2 levels? These are generally going to be pretty small areas when we get the real ones so it'll be hard to see them on such a zoomed out map.
![image](https://user-images.githubusercontent.com/24392156/61034670-970f0080-a3bd-11e9-875c-654b16fd0648.png)
(IMO this is also an issue for practices and CCGs #1021 )

Breaking down measures / analyses into constituent practices not currently possible but presumably users will want to do this?
- Might need to exclude any that are only made up of a single practice.

**Comment by HelenCEBM** [comment]
There'll be a lot (several hundred?) PCNs so maybe the index page should be a search box as per practices, rather than a list, for ease of use http://staging.openprescribing.net/pcn/

**Comment by evansd** [comment]
Thanks all. Think I've addressed everything in the latest PR (#1825) and have re-deployed to staging,

**Comment by brianmackenna** [comment]
Dashboards are now live https://openprescribing.net/pcn/

**Comment by brianmackenna** [comment]
will make a separate issue #2281
