### ISSUE TITLE
£ sign showing on Analyse 'Show over Time' graph

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#191]
If you hit the 'spending' button on the 'Show Summary'  results tab in the Analyse section, and then select the 'over time' graph, the items will be listed as £'s even though it is showing items not spend.

![image](https://cloud.githubusercontent.com/assets/15875191/18432574/a2965c7a-78da-11e6-93f8-d689bed89226.png)

The text on the tooltip does say it is showing items, it is only the '£' that is incorrect. Can't send a link for it as it works fine if you link to it!

**Comment by annapowellsmith** [comment]
This is a bug, well spotted!

**Comment by sebbacon** [comment]
Unable to reproduce:

![image](https://cloud.githubusercontent.com/assets/211271/25129374/ac122f5c-2435-11e7-8c3a-936b81c5b78e.png)

**Comment by lmfrench** [comment]
It happens if you switch it to spending in maps or spine before going to over time

**Comment by lmfrench** [comment]
Seb - have checked this, and the £ signs have been removed, but the tooltip also says 'Items for X per £1,000 spend on X:

![image](https://cloud.githubusercontent.com/assets/15875191/26053595/510b8572-3961-11e7-9211-e7bf5dcd9d26.png)

**Comment by HelenCEBM** [comment]
this seems to be fixed
