### ISSUE TITLE
Make raw number searches available through OpenPrescribing

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#192]
User story from Lisa's testing:
- **As a** commissioner
- **I want** to see (and download) the raw numbers for prescribing of drug X
- **So that** I know whether it's a large enough area to be worth working on. 

Richard Croker has also asked for this

**Comment by lmfrench** [comment]
I think this is a mix of #58 and a separate issue to allow users to search without selecting a denominator

**Comment by richiecroker** [comment]
My view exactly what @lmfrench described above.   Just a quick look at raw numbers, at practice or ccg level.  No denominators, just pure numbers.  Doesn't have to even been graphical, could we use the table that we create for the breakdown?
