### ISSUE TITLE
dm+d advanced search feedback

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1957]
Currently on staging at http://staging.openprescribing.net/dmd/advanced-search/vmp/.

Still to do:

* Search by BNF prefix
* Search for BNF generic equivalents
* Search on a handful of complex fields, including ingredients, DT info, and several things at AMPP level (fiddly, but I have a plan)
* Search for objects of one type based on properties of objects of another type, eg all VMPs with one controlled drug schedule, that have an AMP licensed by a particular authority (still not sure of the best interface for this)

Please add comments below for missing features, bugs, or other feedback.

**Comment by brianmackenna** [comment]
This is magnificent. Its already helpful for me in that I don't have to go to separate BQ tables for different info. Applying my two tests 

_Does it work on mobile?_
Answer is yes. However the search button is partly obscured by the footer by default  (certainly on an android device)

![image](https://user-images.githubusercontent.com/40460354/62684531-c2830c00-b9b8-11e9-98f0-3d660b96304b.png)

_Does it require training?_
Unfortunately yes with regards group function. It is not intuitive and it is unclear exactly what it is from playing around with. My guess is that it splits the rules so for example you could have "cfc or sugar free AND "drug form and drug route" 

If so could they be separated by pure white space in between? The branch structure for groups doesn't look clear to me as is.

_Re:user interface for different types_
Would below work? Perhaps add tick boxes to make it more intuitive?
![image](https://user-images.githubusercontent.com/40460354/62684318-556f7680-b9b8-11e9-89b6-19a70e4100f0.png)

Advance and Normal SEarch page
_Documentation_
This goes for a [monograph](https://openprescribing.net/dmd/amp/24576611000001105/) (is this the right word?). For the field names, when you hover could a slightly longer explanation appear? I'm happy to do write all the definitions over coming months. It should just be copy+paste+simplify from source material - I don't think it is essential for launch but maybe after we get to know who the users are.

For all pages - we should link to further dm+d documentation. Again not essential for launch, I have started on a series of blogs. We can decide what documentation is needed based on user queires - all other stuff to be referred to NHSD/BSA source material.

_Character Length_
Search currently needs 6 characters minimum - could this be shortened? I was searching for an AMP called _MXL_ yesterday.

**Comment by sebbacon** [comment]
Just chipping in briefly - great work! 

Longer term I would like to think about if/how we could allow users to search a combination of fields from different entities (VMP/AMP/AMPP/VMPP). This will be difficult, maybe impossible, but if we can get it right it would be well worth it.

**Comment by brianmackenna** [comment]
Small point. Where the field is a date/timepoint could we use before/after instead of less/greater?

**Comment by sebbacon** [comment]
A possibly interesting use-case to discuss along with Brian (to check it's a sensible one):

* I would like to be able to browse all products not recommended to be prescribed as a VMP here: http://staging.openprescribing.net/dmd/advanced-search/vmp/?search=%5B%22pres_stat%22%2C%22equal%22%2C4%5D
* Having to add another filter before I can see items > 100 is a bit annoying as a user - can we page the results?
* I would like to filter out appliances, which are not interesting to me. How would I do this? 
  * Is this a common enough use case we should include it as a canned filter?
  * Can it be done via dm+d already, and if so, how?  
  * It would be good to be able to additionally filter by BNF chapter / section etc (which would also support my appliances use case)
* I would also like to filter by Drug Tariff category; I can't find the field (possibly because it's one of the tricky fields to implement?)  Again, this is probably a common enough use case it should be surfaced more clearly than other options (e.g. canned filter)

Sorry it's a bit of a stream-of-consciousness but wanted to add feedback while I knew you were working on it

**Comment by sebbacon** [comment]
One thing that I've found confusing was the interaction between the tickboxes and the search form.  I can't reproduce now but I managed to get something with `(not available)` when the tickbox was not selected.

**Comment by HelenCEBM** [comment]
Can we make sure the search criteria you've entered aren't lost when you switch between AMP, VMP etc?

**Comment by HelenCEBM** [comment]
- `Dose form` is in the drop-down list twice
  - First instance gives "continuous" vs "discrete"
  - the second has the expected "tablet"/"capsule" etc options.
  - the continuous/discrete option seems like the easiest way of distinguishing between tablets etc versus liquid formulations - should we make this more obvious?

- Do we need "top tips" or quick-start guide or similar for the common filters people are likely to want e.g. liquids vs tablet forms?

**Comment by inglesp** [comment]
I've made fixes to the following:

* the search button is partly obscured by the footer by default
* Search currently needs 6 characters minimum - could this be shortened?
  * yes, it's now 3 characters but we may have to revisit if this places too much load on the server
* Where the field is a date/timepoint could we use before/after instead of less/greater?
* Having to add another filter before I can see items > 100 is a bit annoying as a user - can we page the results?
  * I'm not sure on the best way to do pagination, so I've bumped the limit to 10,000 which is lazy but it works
* It would be good to be able to additionally filter by BNF chapter / section etc
* I would like to filter out appliances
  * Done, through filtering/excluding BNF prefixes
* Can most fields with equal and contains as options (text fields) default to the latter instead of the former?
  * I've just removed "equal" from the options
* Can we fix the grammar with greater *than* [selection] instead of greater [selection] etc?
* Dose form is in the drop-down list twice

And things I haven't addressed:

* Brian's concerns about usability of the group button
  * I can't easily change the spacing on the controls
* The user interface for searching by different types
  * this is a limitation of the framework I've used to build the interface
* A canned filter to filter out appliances
  * appliances can be filtered out via BNF code, but a canned filter would be easy to add
* Can we make sure the search criteria you've entered aren't lost when you switch between AMP, VMP etc?
  * Sorry, this is a bit too fiddly for now
* Can pressing enter perform the search?
  * You'd have thought this would be easy.

**Comment by inglesp** [comment]
Closing as this is now deployed.  Separate issues for further enhancements please!
