### ISSUE TITLE
PPU blog seems out of proportion

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#1970]
Issue #460 mentions that there is a minimum blob size.

![image](https://user-images.githubusercontent.com/18683239/62773949-6e9d2380-ba9b-11e9-941b-858ff86beee6.png)
![image](https://user-images.githubusercontent.com/18683239/62773975-7b217c00-ba9b-11e9-806d-8082ded47ae2.png)

The above example shows whether there are two presentations prescribed.  Proportions are similar (188 vs 154), but blog sizes are vastly different.  

This led to members of the MO team assuming (by eyeballing the charts) that there wasn't much prescribed, which is inaccurate.

What is the current metholdology for blog size?

**Comment by inglesp** [comment]
Could you include a URL for this image please?

**Comment by richiecroker** [comment]
https://openprescribing.net/practice/L83016/0402010ABAAAXAX/price_per_unit/?date=2019-05-01#local-panel

**Comment by inglesp** [comment]
Definitely a bug.  I have a fix, will do a PR later.
