### ISSUE TITLE
Support Welsh practices

### ISSUE THREAD

**Issue by stupidpupil** [ebmdatalab/openprescribing#2]
I have done some work on supporting Welsh data from Primary Care Services from the NHS Wales Shared Services Partnership (NWSSP) in my [`wales` branch](https://github.com/ebmdatalab/openprescribing/compare/master...stupidpupil:wales) and a version of the OpenPrescribing site populated with this data can be found at [`http://prescribing.stupidpupil.co.uk/`](http://prescribing.stupidpupil.co.uk/).

I'm afraid that I haven't used Python much, let alone Django, and this might be obvious even in the little code that I've written. You can also see that I've ended up mixing fixes to Python 3 compatibility with that branch, which I know is rather unclean. 

Outstanding issues with the Welsh data are described below. I'd appreciate any criticisms or warnings of things to watch out for. Thank you for producing this tool.
# Immediate issues
## Registered populations

I don't believe that there are any sources of regular information on Welsh practice's list sizes/registered populations broken down by gender and 10-year age-bands, as required to calculate STAR-PUs and ASTRO-PUs. (The only information I've turned up can be found on the [Welsh Government website](http://gov.wales/statistics-and-research/general-medical-practitioners/?lang=en), and it's this that I've tortured to provide data for the site linked above.) I have begun to pursue this.
## Practice setting/Type of Practice

The HSCIC's `epraccur.csv` file has the setting of all Welsh practices as 'Other'. For now, I've simply marked any practice listed in WG's QOF Practice Lookup file as a 'GP Practice'.
## Smoke tests, and other validation

I haven't had the chance to investigate the smoke tests and construct Welsh equivalents, nor to validate the outputs of the tool against anything else.
# Next steps
## Compatibility with HSCIC data

The only areas that I believe there's a risk of conflict are:
- Deleting prescribing data when importing either NWSSP or HSCIC data. I've tried to prevent this for HSCIC data in da4513a6484afbf5e649a94730d4ccfc74e44694 and avoided it in the NWSSP import command.
- The 'chemicals' that HSCIC groups under 4-character codes I believe that NWSSP provides full 9-character codes for. (My guess is that it's probably entirely unnecessary to use both sets of Chemicals data, and that a preference for or against these 4-character codes could be fixed or made available as an option for the `import...prescribing` commands.)
- Determining practice settings, for the reasons described above. Currently determining the setting of Welsh practices would have to take place _after_ doing so for English practices. (Although there's plenty of management commands that are order-sensitive, this is still little irritating.)

However, I have not checked there aren't other problems yet by actually trying to run a site with both sets of data.
## Replacing Localities with GP Clusters?

I'm not sure that 'Localities' are a very useful way to group practices, and I've only done so because the NWSSP prescribing data extracts imply that it's the preferred one. Welsh GP Clusters might be more useful in Wales and more useful in the context of comparisons with English CCGs.

On the other hand, Clusters don't have a defined catchment area and so any geographical representation of them is probably going to depend on the distribution of practices' population. It's possible that the Public Health Wales Observatory might be able to provide something useful.

**Comment by stupidpupil** [comment]
[@MalwenGoch](https://twitter.com/MalwenGoch) has turned up what I think might be a coding issue between the two countries.

BNF/Chem | England | Wales
--------------- | ----------- | -----------
041002, Nicotine Dependence | [~100k items](https://openprescribing.net/bnf/041002) | [~90 items](http://prescribing.stupidpupil.co.uk/bnf/041002)
0410020B0 | [~50k items](http://openprescribing.net/chemical/0410020B0) | [~75 items](http://prescribing.stupidpupil.co.uk/chemical/0410020B0)
0410000P0 | ['Unknown', ~100k items](http://openprescribing.net/chemical/0410000P0) | ['Nicotine', ~4k items](http://prescribing.stupidpupil.co.uk/chemical/0410000P0)

**Comment by HywelMJ** [comment]
Numbers of registered patients by GP practice, 2004-14: http://gov.wales/docs/statistics/adhocrequests/2015/151214-number-registered-patients-gp-practice-2004-2014-en.xlsx

**Comment by stupidpupil** [comment]
Unfortunately we need registered populations broken down by age and gender, not just the total list size.

**Comment by HywelMJ** [comment]
Figures for 2014 here: https://t.co/FSbJD0pDyz Any good?

**Comment by stupidpupil** [comment]
Better! It is those figures that I have used so far and that I have linked to in the issue above. (Similar data can be found for 2013 also, by looking at the related [ad-hoc statistical requests](http://gov.wales/statistics-and-research/general-medical-practitioners/ad-hoc-statistical-requests). 

Unfortunately, even these one-off releases are not detailed enough to calculate STAR-PUs (etc.) correctly (as described [in the HSCIC's Prescribing Measures document](http://www.hscic.gov.uk/media/10952/Prescribing-Measures/pdf/CHttpHandler.pdf)). I've tortured the data to produce STAR-PUs by making (silly) assumptions like the number of male 15-44 year olds is split evenly across the three 10-year age-bands.

I'm afraid that this data is simply currently publicly unavailable. I believe that it *will* be possible to get this data made a regular public release, and I have made some contact with people in Welsh Government and the NHS Wales Shared Services Partnership about this. (At this point in the year, I'm reluctant to badger them about this issue - I don't want them to experience OpenPrescribing as just another demand on their time.)

**Comment by stupidpupil** [comment]
I've met with someone from Primary Care Services here - they were quite enthusiastic about OpenPrescribing and I'll be working with them to make the information available. However it looks like it's going to be a few months before we can get a reliable feed of the practice demographics available - I'm hoping that this can happen by June.

**Comment by brianmackenna** [comment]
Closing as a very old issue.

We have written about supporting other countries on our blog but it isn't a priority at the moment due to [OpenSAFELY](https://www.opensafely.org/).

https://www.bennett.ox.ac.uk/blog/2020/02/openprescribing.yourcountry/
