### ISSUE TITLE
Pipeline runner cannot delete numbers.json

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2011]
The `/tmp/numbers-checker/*/numbers.json` files are created by `check_numbers`, which runs after each deploy.  The pipeline runner then tries to delete them (as the numbers will have changed making a comparison pointless) but it fails to do so, because they are owned by `ebmbot`, while the runner is run by `hello`.

**Comment by evansd** [comment]
Did we not fix this by fiddling with group memberships?

**Comment by inglesp** [comment]
Yes.  Closing.
