### ISSUE TITLE
Running of of disk space: urgent steps

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#202]
Our 630G root partition is at 89% capacity. This does not leave enough space to calculate materialized views. We need to:

* Reclaim as much space as possible in the short term (tracked in this issue)
* Work out a longer term plan (tracked in #203)

Overall, most of the disk is occupied by postgres. The next largest users of space are `/home` (23GB) and `/webapps` (12GB)

Plan:

* [x] Delete `/webapps/openprescribing/openprescribing/data` -- now redundant, and taking up 8.2GB
* [x] Delete older folders at `/home/hello/openprescribing-data/data/prescribing/` - about 5.3GB of space - once an import has finished these are redundant
* [x] Compress /var/lib/postgresql/9.4/main/logs (set up logrotate to deal with these) - about 2GB
* [ ] Analyse indexes in postgres and drop ones we don't use -- unknown but prob at least 20GB, maybe 50GB+
* [ ] Drop columns we don't need from the prescribing table and reindex with more parsimonious data types (see #162). This will probably save 150GB+. However, changing column types is likely to be impossible as that process requires a copy of the entire table to be written by postgres.

Expected space gain: 135GB - 200GB.

**Comment by annapowellsmith** [comment]
See also #162.

I'd be tempted to look at the `frontend_prescription_general` index, it's 47GB and seems lightly used.

**Comment by annapowellsmith** [comment]
The prescribing table itself is only 100GB. But I'd hope we could lose at least 50GB from trimming duplicate indexes: 

> prescribing=> SELECT nspname || '.' || relname AS "relation",
> prescribing->     pg_size_pretty(pg_relation_size(C.oid)) AS "size"
> prescribing->   FROM pg_class C
> prescribing->   LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
> prescribing->   WHERE nspname NOT IN ('pg_catalog', 'information_schema')
> prescribing->   ORDER BY pg_relation_size(C.oid) DESC
> prescribing->   LIMIT 20;
>                      relation                      |  size
> ---------------------------------------------------+---------
>  public.frontend_prescription                      | 104 GB
>  public.frontend_prescription_general              | 47 GB
>  public.frontend_prescription_by_practice          | 41 GB
>  public.frontend_prescription_by_prac_date_code    | 35 GB
>  public.frontend_prescription_by_pct_and_code      | 30 GB
>  public.frontend_prescription_by_pct               | 30 GB
>  public.frontend_prescription_idx_date_and_code    | 28 GB
>  public.frontend_prescription_by_practice_and_code | 26 GB
>  public.vw__chemical_summary_by_practice           | 22 GB
>  public.frontend_prescription_6ea07fe3             | 19 GB
>  public.frontend_prescription_pkey                 | 15 GB
>  public.vw__idx_chem_by_practice                   | 15 GB
>  public.vw__idx_practice_by_chem                   | 14 GB
>  public.vw__idx_chem_by_practice_unique            | 12 GB
>  public.idx_chem_by_practice_bydate                | 10 GB
>  public.vw__presentation_summary_by_ccg            | 6409 MB
>  public.vw__idx_pres_by_ccg_unique                 | 5218 MB
>  public.vw__idx_pres_by_ccg_joint_code             | 5060 MB
>  public.vw__idx_pres_by_ccg_pres_code              | 3618 MB
>  public.frontend_measurevalue                      | 1876 MB

**Comment by annapowellsmith** [comment]
Might be wrong but we could probably get rid of `public.frontend_prescription_by_prac_date_code` - think it's only used in measures, and as discussed a temporary index works better for these anyway. 

And we might be able to get rid of either `public.frontend_prescription_by_pct` or `frontend_prescription_by_pct`.

**Comment by sebbacon** [comment]
The thing is, all these indexes *have* been used, so it's a bit of a shot in the dark what will happen if we remove them...

For example, `public.frontend_prescription_by_prac_date_code` is in fact the fourth-most used index according to the query below, which sorts them in order of the tuples read (table rows fetched by simple index scans using the index).

We could:

* Try removing the least-accessed and see what happens
* Do more analysis to try to work out what indexes are used when
* Set up another server on a short term basis to try it out
* Something else...?

```sql
prescribing=# SELECT
    t.tablename,
    indexname,
ize,pg_size_pretty(pg_relation_size(quote_ident(indexrelname)::text)) AS index_si
    idx_scan AS number_of_scans,
    idx_tup_read AS tuples_read
FROM pg_tables t
LEFT OUTER JOIN pg_class c ON t.tablename=c.relname
LEFT OUTER JOIN
e FROM pg_index xidx_scan, idx_tup_read, idx_tup_fetch, indexrelname, indisunique
           JOIN pg_class c ON c.oid = x.indrelid
           JOIN pg_class ipg ON ipg.oid = x.indexrelid
           JOIN pg_stat_all_indexes psai ON x.indexrelid = psai.indexrelid )
    AS foo
    ON t.tablename = foo.ctablename
WHERE t.schemaname='public' AND t.tablename LIKE 'frontend_%'
ORDER BY 5,1 DESC;
prescribing=# SELECT
    t.tablename,
    indexname,
ize,pg_size_pretty(pg_relation_size(quote_ident(indexrelname)::text)) AS index_si
    idx_scan AS number_of_scans,
    idx_tup_read AS tuples_read
FROM pg_tables t
LEFT OUTER JOIN pg_class c ON t.tablename=c.relname
LEFT OUTER JOIN
e FROM pg_index xidx_scan, idx_tup_read, idx_tup_fetch, indexrelname, indisunique
           JOIN pg_class c ON c.oid = x.indrelid
           JOIN pg_class ipg ON ipg.oid = x.indexrelid
           JOIN pg_stat_all_indexes psai ON x.indexrelid = psai.indexrelid )
    AS foo
    ON t.tablename = foo.ctablename
WHERE t.schemaname='public' AND t.tablename LIKE 'frontend_prescript%'
ORDER BY 5,1 DESC;
       tablename       |                 indexname                  | index_size | number_of_scans |  tuples_read  
-----------------------+--------------------------------------------+------------+-----------------+---------------
 frontend_prescription | frontend_prescription_by_pct               | 30 GB      |         2064253 |      28162541
 frontend_prescription | frontend_prescription_by_pct_and_code      | 30 GB      |            4797 |      83045485
 frontend_prescription | frontend_prescription_pkey                 | 15 GB      |           70779 |      89379997
 frontend_prescription | frontend_prescription_general              | 47 GB      |          150792 |     112540508
 frontend_prescription | frontend_prescription_by_practice          | 41 GB      |        37194117 |     606034371
 frontend_prescription | frontend_prescription_by_prac_date_code    | 35 GB      |       158603263 |    2910977447
 frontend_prescription | frontend_prescription_6ea07fe3             | 19 GB      |          320246 |    4696000909
 frontend_prescription | frontend_prescription_by_practice_and_code | 26 GB      |        44730674 |    9673248521
 frontend_prescription | frontend_prescription_idx_date_and_code    | 28 GB      |          613128 | 1952331104367
```

**Comment by sebbacon** [comment]
Re. dropping columns, [the manual](https://www.postgresql.org/docs/current/static/sql-altertable.html) states:

> The DROP COLUMN form does not physically remove the column, but simply makes it invisible to SQL operations. Subsequent insert and update operations in the table will store a null value for the column. Thus, dropping a column is quick but it will not immediately reduce the on-disk size of your table, as the space occupied by the dropped column is not reclaimed. The space will be reclaimed over time as existing rows are updated. (These statements do not apply when dropping the system oid column; that is done with an immediate rewrite.)
>
> To force immediate reclamation of space occupied by a dropped column, you can execute one of the forms of ALTER TABLE that performs a rewrite of the whole table. This results in reconstructing each row with the dropped column replaced by a null value.

IIUC this means we need to do a `VACUUM FULL` or `CLUSTER`, and these require disk space equal to the size of the table being vacuumed, as the process copies the table in order to free the space.

**Comment by sebbacon** [comment]
(...this implies we need at least 100GB free to release the space freed by dropping the columns that we need to drop in order to free up space.... :confounded: Currently we have 82GB free). Leaving the next steps until tomorrow.

**Comment by annapowellsmith** [comment]
I think `frontend_prescription_general` may be a recent addition - do you remember adding it? If it is, it could probably be deleted safely.  

`frontend_prescription_by_pct_and_code` is used much less than the other one, so I'd start by getting rid of that. 

`frontend_prescription_by_prac_date_code` may be used in API queries like `/api/1.0/spending_by_practice/?code=0212000AAAAAAAA&date=2015-04-01`, unsure. It's not used anywhere in the UI, but we could just drop that method and point people at BigQuery. 

For all deletions the process should be: 

- save the definition
- delete index
- clear cache
- run smoke tests / try all query types on site
- recreate if necessary. 

This should all be done in late afternoon / early evening to avoid disrupting live site during working hours, as index should re-create overnight. I can do, if you need to do childcare then.

**Comment by sebbacon** [comment]
For the record, the prescribing table takes up 104Gb and its indexes 271GB. The next largest table is measurevalue which is 1.9GB with 4.8GB indexes.

**Comment by annapowellsmith** [comment]
Cool, sounds like the indexes are the bigger issue, and if it's not trivial to delete a column we can just park that.

**Comment by annapowellsmith** [comment]
Site status for reference: queries that are currently showing empty graphs due to half-run import:

- [anything involving list sizes](https://openprescribing.net/analyse/#org=CCG&numIds=0205051I0&denom=total_list_size&selectedTab=summary)
- [per-practice presentation or chemical queries](https://openprescribing.net/analyse/#org=practice&orgIds=10Q&numIds=0212000AAAAACAC&denomIds=2.12&selectedTab=summary)

**Comment by annapowellsmith** [comment]
OK, I've deleted `frontend_prescription_by_pct_and_code` and run analyse and cleared cache, and none of the obviously related queries are  obviously on fire. 

This takes free disk space to 82% (112G).

Haven't run the smoke tests as the whole site is half way through an update so they'll all fail anyway. Can continue tomorrow when we know the answer re `frontend_prescription_general`.

**Comment by sebbacon** [comment]
Sorry, got people round for dinner this evening so can't look at it tonight, but yes `frontend_prescription_general`  was one I added -- the theory is that it's the only index we'd need as it's a covering index. But the practice might not work out like that. So prob best to drop it for now.

**Comment by annapowellsmith** [comment]
Ah right, yes, a new 47GB index will do that! I've deleted it and run `ANALYZE`, now 159GB available, if you'd like to restart the matview updates tomorrow I think all will be well.

**Comment by annapowellsmith** [comment]
I just kicked off `manage.py refresh_matviews` manually in the same screen session as before - it might as well run overnight. Can then go back to `runner.py` tomorrow.

**Comment by sebbacon** [comment]
Update: matviews still updating

**Comment by annapowellsmith** [comment]
The data import finished successfully. I had to recreate one index as per #209 but we still have 128GB available. Closing.
