### ISSUE TITLE
Improve alert/newsletter signup confirmation page

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#2028]
After checking the box to receive both the newsletter and alerts, the following text is a bit confusing:

![image](https://user-images.githubusercontent.com/24392156/63850069-33e82600-c98b-11e9-9397-29531c37deda.png)

It should instead (1) confirm that you're signed up for alerts (e.g. "check your inbox/junkmail for the confirmation email") and (2) emphasise that you still need to click continue to sign up for the newsletter even if you don't want to supply the information in the optional boxes.

Having clicked continue you then get a nice pair of confirmation messages at the top of the page.

**Comment by brianmackenna** [comment]
DL discussion: Suggest building a pop-up to offer them the alerts service on their second visit.

**Comment by inglesp** [comment]
Have suggested tweaks to the signup process at #2180.  Making a decision on that is a prerequisite for addressing this.

**Comment by evansd** [comment]
Fixed by #2271
