### ISSUE TITLE
Running out of disk space: longer term plan

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#203]
Our 630G root partition is at 89% capacity. This does not leave enough space to calculate materialized views. We need to:
- Reclaim as much space as possible in the short term (tracked in #202)
- Work out a longer term plan (tracked in this issue)

**Comment by sebbacon** [comment]
#202 outlines a plan that should win us at least 20% of disk space back. However, we're putting off the inevitable to some degree -- it's a pretty small disk for a lot of data.

Possible options:

* Use spinning disks rather than SSDs -- we can get much cheaper hardware this way and TBs of storage. Will the site be fast enough? Probably, as it's very low traffic, but needs more investigation
* Hybrid: 
  * use SSDs for postgres indexes, spinning disks for everything else; or
  * use SSD for all of postgres, separate cheap commodity box for website
* High-end:
  * Just use much larger SSDs throughout

**Comment by annapowellsmith** [comment]
It's good to think about this, but I would hope we could reclaim back an awful lot of space by getting rid of duplicate indexes. By the time it becomes a live issue the whole technology space for this problem may have moved on anyway.

There's also another possible option: only hold 5 years of data, and remove earlier data. Not obvious that it's useful for active prescribers (Richard seems unbothered about it). Useful for analysis potentially, but we should be pointing people at BigQuery for analysis anyway.

**Comment by annapowellsmith** [comment]
[This might be relevant](https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean). 

For example as a quick fix, if we want to rebuild the database over a weekend with columns tidied up, but without having to delete the existing database (or export it, which I think also throws disk space errors) we could stick the existing database on one of these while we attempt to rebuild it.

**Comment by sebbacon** [comment]
Just to note that each new measure uses around 90MB of space plus about the same for indexes.  So if we have 50 measures that'll be around 9GB. Not strictly relevant as this isn't too bad a figure, just wanted to write it down somewhere.

**Comment by sebbacon** [comment]
Thinking about this again.

It seems to me that we could get away with halving our CPU capacity. If so, we could save us $320 / month, and then easily afford adding a terabyte block storage for $200 / month.

* [] Check my sense that we are overprovisioned for CPU
* [] Create snapshot of current system
* [] Start that as a droplet in `FRA` with 32 CPUs
* [] Add 1TB block storage
* [] Format block storage (research which filesystem is best for postgres files with our load (I think we want to optimise for writes)
* [] Move postgres data to new device
* [] Test
* [] Switch over domains
* [] Deprovision old server

**Comment by HelenCEBM** [comment]
Is this still an issue?
