### ISSUE TITLE
Cross-linking from section trends to dm+d doesn't work

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#2032]
![image](https://user-images.githubusercontent.com/211271/63865895-432a9c00-c9aa-11e9-8576-179c9d2642f6.png)

This is for both sections and chemicals, at least in some cases.

Example: https://openprescribing.net/bnf/010606/

Additionally, it seems that truncated BNF codes don't work at all in the dm+d search.

One of the reasons for doing this was to provide entry points for spiders to the dm+d; could we also change the query string to be a path segment so they will get crawled?

**Comment by inglesp** [comment]
Could you add a link to the issue please?

**Comment by sebbacon** [comment]
done
