### ISSUE TITLE
Fix broken newsletter signup process when going from CCG/practice page (sorry!)

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#2039]
When signing up for the newsletter via the box on CCG/practice pages (just selecting "newsletter" not "alerts"), it comes up with (a) "There was a problem signing you up for the newsletter" and (b) Error 500, i.e. not redirected back to page. 

When I repeated this with a different email address (in incognito mode) I got problem (a) but not (b). 

Perhaps we need to fix the python that feeds into this - as per #2027 there is now an additional field (though hidden) present in the newsletter signup process
![image](https://user-images.githubusercontent.com/24392156/63955683-09769580-ca7d-11e9-8169-b2492aea7503.png)

**Comment by HelenCEBM** [comment]
Can we record the people who are trying and failing to sign up this way to make sure we don't miss them?

**Comment by inglesp** [comment]
Here's an error in Sentry: https://sentry.io/organizations/ebm-datalab/issues/1195725996.

The error is `RelatedObjectDoesNotExist: User has no profile` in `last_bookmark = request.user.profile.most_recent_bookmark()`.

From Sentry, the user id is 2160, which is linked Helen's phc.ox.ac.uk address.  There is no profile object for this user.  This would explain the 500 error.

In the Sentry breadcrumbs, we have a 400 from mailchimp:

`{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"helen@gmail.com was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"f08e6ad8-f247-466c-985e-2f975b393b09"}`.  This would explain the "There was a problem signing you up for the newsletter." message.

(I've obfuscated the email address here.)

And then later: `Unable to subscribe helen@gmail.com to newsletter`.

**Comment by inglesp** [comment]
There are only two users without a profile, "admin" (tech@ebmdatalab.net) and Helen:

```
>>> User.objects.filter(profile__isnull=True)
<QuerySet [<User: admin>, <User: helen>]>
```

No idea how this could have happened, but may be unrelated to mailchump problems.

**Comment by inglesp** [comment]
There's no documentation for "Forgotten Email Not Subscribed", but [this SO question](https://stackoverflow.com/questions/52198510/mailchimp-resubscribe-a-deleted-member-causes-the-api-to-return-a-400-bad-reques) has a response from mailchimp support, which suggests that the error's something to do with trying to resubscribe a deleted user.

**Comment by inglesp** [comment]
I have just tried this myself with my datalab address (which doesn't have an associated user in our system) and it appeared to work -- I got the "You have successfully signed up for the newsletter." message.

**Comment by inglesp** [comment]
@HelenCEBM can you see whether my datalab address is showing up as expected in mailchimp?

**Comment by inglesp** [comment]
I've also signed up (again with my datalab address) to the newsletter and alerts, and again this appeared to work.

**Comment by inglesp** [comment]
@HelenCEBM do you have any guesses about why your address may have been deleted by/from mailchimp?

**Comment by HelenCEBM** [comment]
I had previously signed up and then removed myself in order to test the sign-up process again.

**Comment by HelenCEBM** [comment]
Your signup has showed up in mailchimp (without the group selected) but only once

**Comment by evansd** [comment]
I think this was already fixed, but in any case it's rendered irrelevant by #2271
