### ISSUE TITLE
Add "raw prescribing" view to codebase

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2054]
The BQ view added in #1994 should be added to the codebase and created automatically in `create_bq_views` so the end-to-end tests can work.

This view is itself based on the `raw_prescribing` table which is an external table backed by a bunch of CSV files in Google Cloud Storage. We'll need to think about how best to replicate this in the end-to-end tests. I think we might need to add a new command which creates that table.

**Comment by inglesp** [comment]
Note: I have had to change change `PARSE_DATE` to `PARSE_DATETIME` to allow the `seven_day_prescribing` measure to be imported.

**Comment by evansd** [comment]
Closed by #2166
