### ISSUE TITLE
add CCG/practice into analyse page link, for links from measure pages

### ISSUE THREAD

**Issue by alexwalkerepi** [ebmdatalab/openprescribing#2067]
It would be helpful to add in the CCG/practice to the analyse page link, when navigating from e.g. this page: https://openprescribing.net/ccg/10V/lpdronedarone/

i.e. change from this link:
https://openprescribing.net/analyse/#org=CCG&numIds=0203020X0&denom=total_list_size&selectedTab=summary

to this:
https://openprescribing.net/analyse/#org=CCG&orgIds=10V&numIds=0203020X0&denom=total_list_size&selectedTab=summary

**Comment by HelenCEBM** [comment]
Often people want to see all practices in CCG so we should think about which view we should link to.
