### ISSUE TITLE
Upgrade to Python 3.7

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2103]
We've just upgraded to Python 3.5, which is the version available in stretch.

We should upgrade to Python 3.7.  This means we can run `black` in the development environment, and opens up shiny new features.

**Comment by inglesp** [comment]
When we do this, we should reopen https://github.com/ebmdatalab/openprescribing/pull/2245, and check whether any other [unmerged dependency PRs](https://github.com/ebmdatalab/openprescribing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+is%3Aunmerged+label%3Adependencies+comments%3A%3E1+updated%3A%3E%3D2019-11-27) should be reopened.

**Comment by evansd** [comment]
As per #2925 and #2926 we've now upgraded to Python 3.8.

Closing this and pulling dependency review stuff in a new ticket.
