### ISSUE TITLE
Build and push docker image for Python 3.5

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2104]
This might be as simple as following these instructions from our README:

    # Base docker image, for production
    docker build -t ebmdatalab/openprescribing-py3-base .
    # Built from base image, with extras for testing
    docker build -t ebmdatalab/openprescribing-py3-test -f Dockerfile-test .
    docker login  # details in `pass`; only have to do this once on your machin
    # push the images to hub.docker.io
    docker push ebmdatalab/openprescribing-py3-base
    docker push ebmdatalab/openprescribing-py3-test

Doing so should speed up Travis test runs.

**Comment by CarolineMorton** [comment]
i can try this if suits you all

**Comment by inglesp** [comment]
Suits me!

**Comment by evansd** [comment]
Obviated by #2925
