### ISSUE TITLE
Add "alerts" tag to identify measures for alert email

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#2127]
Currently measures have to be in the "core" tag in order for alerts to be sent.  This may create issues with additional measures, such as zuclopenthixol, which we may choose not to add to the core group. 

Following discussion with @sebbacon I have set up an "alert" tag, which we can add to all measures that are suitable (i.e. most of them).  We'll need to change the code to reflect this when triggering the alert.

One thought though - would it be better for us to have a "no_alert" tag instead, so that we exclude measures which aren't suitable, rather than include ones that are?  @sebbacon @evansd @inglesp ?

**Comment by inglesp** [comment]
We don't want to use a separate tag for this, unless we want "not for alert" to appear in the list of tags for a measure or in the dropdown for "Show measures categorised as..." (which I think would be meaningless for a user).

Instead, we should make a new `no_alert` attribute on the measure definition, and filter out those measures where this is `True` when sending alerts.

Does this sound sensible?

**Comment by sebbacon** [comment]
Good point. I concur.

**Comment by richiecroker** [comment]
Eminently

**Comment by inglesp** [comment]
I'd got the impression (although I'm not sure from where) that we now want to include all current measures in the alerts.  Is that correct?  @richiecroker

**Comment by richiecroker** [comment]
I think that'd be helpful.  We don't currently include individual LVM in there, and I think we should.  @brianmackenna do you agree?

**Comment by richiecroker** [comment]
So yes, let's include all LVM, but *exclude* the `lzomnibus`

**Comment by inglesp** [comment]
OK, thanks!

**Comment by evansd** [comment]
There are also two measures tagged as "papers" which aren't currently in "core":
https://openprescribing.net/measure/tamoxifen/
https://openprescribing.net/measure/nimodipine/

**Comment by inglesp** [comment]
Thanks for checking @evansd.

**Comment by inglesp** [comment]
Although is this an oversight?  Is there any reason why they shouldn't be included in alerts?

**Comment by richiecroker** [comment]
yes, they're not strictly measure measures...

**Comment by sebbacon** [comment]
Just to mention I recall it was a positive decision to exclude individual LP measures from alerts. Not saying it was a good decision. Just that there was a discussion.  I guess it was because many of them, being low numbers, would result in lots of false positives for change over time.

**Comment by richiecroker** [comment]
Fair enough, but I now think it'd be useful for individual alerts to start to go out, as we're some time down the line on the programme.

**Comment by inglesp** [comment]
Fixed by #2128.
