### ISSUE TITLE
Hide "presentations contributing to variation" table where not appropriate

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#2135]
On some occasions, such as the proposed "seven-day prescribing" measure, the presentations contributing to variation table is not correct:
![image](https://user-images.githubusercontent.com/18683239/66515831-b78f4980-ead7-11e9-91f6-a7fa3a34b11d.png)
In this example the quantity and items relate to the *total* number of prescriptions, not those for seven days only.

For these occasions, the most simple thing to do is to have a flag in the measure definition (e.g. `presentation_table = FALSE` so that the table is not shown.  

How feasible is this?

**Comment by brianmackenna** [comment]
This has arisen again with the [semaglutide measure](https://openprescribing.net/measure/semagglutidequantity/all-england/). Discussed with @inglesp  and the temporary fix suggested by @richiecroker  is feasible. All we need is a form or words to go in place (i'll do a couple of versions in next comment).

I propose we turn off presentation table for seven day measure BUT for the moment we leave on for semaglutide even though it is slightly misleading. The reason being that semaglutide is new, brand names and strengths will be unfamiliar. I believe benefit of leaving the information accessible to the cursory reader  so they can search on their systems.

Perm fix will be via matrix store at some point when less competing priorities.
