### ISSUE TITLE
There should be better handling of chemicals changing classification

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#214]
Currently, when a chemical changes its classification in the BNF, it leads to surprising and sometimes inaccurate results.

This is because our unique id for a chemical includes its classification in the unique identifier for the presentation. For example, Linaclotide was classified as a Laxative (chapter 1.6) in November 2013, and an antispasmodic (chapter 1.2) afterwards. As a consequence, searching under the old name results in graphs with a sharp cutoff, like this:

[![image](https://cloud.githubusercontent.com/assets/211271/19233591/4e13222c-8ede-11e6-840d-792453426987.png)](https://openprescribing.net/analyse/#org=CCG&orgIds=99P&numIds=0102000AH&denom=total_list_size&selectedTab=chart).

When such a paragraph or section is used a denominator, the problem will be less obvious, as the effect will be obscured by other things that have not moved classification.

The _proper_ fix is tricky; as @annapowellsmith has pointed out, it would involve interpreting the raw data, which isn't something we currently do, and we're wary of; specifically, we'd have to infer a chemical had changed section by using its presentation name as a key (which might not be reliable). It's possible the changes are explicitly described in some other data source (more research needed) in which case we could potentially do this more reliably. If we felt this was possible to do reliably, we could then map prescriptions to the _current_ classifications rather than the ones correct at the time.

We should at least look into ways of warning people when this might happen. My estimate (using variations of the query at the end of this issue) is that 336 chemicals have changed paragraph, 79 have changed section, and 33 have changed chapter (a CSV of the latter attached).

So, as a minimum, we could add a warning on the analysis page when someone does a search for something in a list that we generate of things-that-have-been-reclassified, plus a link to an FAQ.  

The only way to fix the denominator-pollution problem would be to produce a normalised classification as described above. This is likely to be a few days' work so we need to establish the user need for this.

---

BigQuery SQL for estimating changes in classification:

``` sql
SELECT * FROM (SELECT
  COUNT(DISTINCT SUBSTR(bnf_code, 0, 6)) AS paragraph_count,
  bnf_name
FROM
  [ebmdatalab:hscic.prescribing]
GROUP BY
  bnf_name
) where paragraph_count > 1
```

**Comment by Bengoldacre** [comment]
This is rather frustrating data management on the part of the data providers... chemicals don't have unique identifiers, and the point at which you need a unique identifier is the time when the thing moves...

**Comment by Bengoldacre** [comment]
let's put a warning in when ppl use one of the 336 chemicals with high priority and think about manual matchin on the rest if no mapping exists (L will check..)

**Comment by sebbacon** [comment]
Somewhere within the NHS, someone must have some kind of mapping between actual drugs and BNF codes at the time! @lmfrench, do you think you could do some enquiries?

**Comment by lmfrench** [comment]
will do

**Comment by sebbacon** [comment]
Summary of the problem:

For any given line in the prescribing data, the question is if we can look up that code in our BNF table (downloaded from https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=126)

There are two reasons we might not be able to look up a code.

1. The code for a presentation has changed. We think this is usually (always?) because it has been moved to a different section, chapter, etc.
2. It is a drug which is no longer in the BNF tables for the dates we have available

The correct solution is for us to be able to look up a drug by BNF code *for a particular month*.

Our needs would be met by any of:

* A series of files which list the BNF pseudo-classification as was current at each month going back as far as possible
* A list of changes to the BNF codes for each month
* A list of BNF -> SNOMED mappings for each month

**Comment by sebbacon** [comment]
Another example is Relvar Ellipta which has (for example) seen its `Relvar Ellipta_Inha 184mcg/22mcg (30 D)` presentation switch thus:

|year | from | to |
|-------|-------|-----|
|2015|0301011Y0BBAAAA|0302000N0BEAABM|
|2017|0302000N0BEAABM|0302000V0BBAAAA|
