### ISSUE TITLE
Make it clear when a practice is no longer prescribing

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#215]
There are > 400 practices which are marked "D" in epraccur, which means "Dormant". See #197 for some statistics about this issue.

Surgeries which are Dormant should be clearly marked as such, with a message like "this practice is no longer prescribing and is no longer part of this CCG".

**Comment by sebbacon** [comment]
There are also some other interesting edge cases, e.g. North Tawton Medical Practice (L83633) is closed.  North Tawton Medical Practice (Y04979) is open in the same place.  They look identical on the site.

![image](https://cloud.githubusercontent.com/assets/211271/19236102/6c3e9704-8eed-11e6-8ad9-a57b45e143db.png)

I think this would be adequately dealt with by indicating in the CCG's list-of-practices where a practice is dormant (or possibly adding a "these are current practices, click here for former practices" button).

**Comment by sebbacon** [comment]
Another side effect of this pointed out by @richiecroker is that we sometimes see remnants of historical CCGs in measures:

![image](https://cloud.githubusercontent.com/assets/211271/22146649/4d7a06fe-defd-11e6-9f6e-44924af5bc6a.png)

In this case, the CCG no longer exists and a couple of practices associated with it closed, so their CCG membership is still associated with that CCG:

SELECT
  practice,
  pct AS ccg_at_the_time,
  MAX(ccg_id) AS current_ccg,
  MAX(close_date) AS close_date
FROM
  ebmdatalab.hscic.prescribing AS prescribing
JOIN
  `ebmdatalab.hscic.practices` practices
ON
  practices.code = prescribing.practice
WHERE
  pct = '00F'
GROUP BY
  practice,
  pct

**Comment by richiecroker** [comment]
The issue for me is not that these practices "close", although their prescribing code becomes dormant.  Usually the site remains open, with the same GPs and patients, but prescribing under a new code (or more often a code of the existing practice that they have merged with.  However it looks like historic data doesn't include the "other" practice, in effect therefore not comparing like with like,

**Comment by lmfrench** [comment]
Discussion at DataLab day:
- We don't want to do any corrections to the data, but we could add a graph with practice list over time so people can see they have likely merged.
- Contact the BSA to ask how they do mergers in ePACT using Combe Coastal Practice & L83017 

Also change Current Practice Type to Closed

On hold until we get a reply from the BSA.

**Comment by sebbacon** [comment]
We finally got a response to our FOI for merger data!

https://www.whatdotheyknow.com/request/practice_mergers_and_closures_no?nocache=incoming-1165255#incoming-1165255

**Comment by sebbacon** [comment]
Wrapped up into #891
