### ISSUE TITLE
Update with July data

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#216]
http://content.digital.nhs.uk/searchcatalogue?productid=21933&q=title%3a%22presentation+level+data%22&sort=Relevance&size=10&page=1#top

Note also: "Following a review of our processes, NHS Digital has recently decided to bring forward the publishing date for Practice Level Prescribing data. This data is currently published on the 1st Friday of the month. The August 2016 data will be published on Friday 4 November 2016, however these dates are constantly under review and may move earlier."

**Comment by barryrowlingson** [comment]
Bump! August data is out now too!
