### ISSUE TITLE
Changes to alert signup process

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2180]
Allowing people to sign up for alerts and the newsletter at the same time is confusing for users and complicates the code.

Instead, we should separate the two, but allow users to sign up for the newsletter when they sign up for an alert.

The workflow would now be:

* Enter your email address and click Subscribe (this signs you up for an alert)
* If you have signed up for the newsletter before, you’re returned to the page you came from
* If you have not signed up for the newsletter before, you then see the newsletter signup form and you can subscribe (returning you to the page you came from) or click a “Back” button to return to the page you came from (or this could be done via a popup)

You can already sign up for the newsletter from any page via the "Stay in touch" link under "More" in the navbar, but we could make this more prominent.

Thoughts?

**Comment by HelenCEBM** [comment]
Sounds good to me. This would fix the problem with the groupings on the Mailout for OpenPath vs OpenPresc which seemed tricky to sort out for the current joint signup method. I.e. everyone signing up on OP needs to be added to the OP group in mailchimp, which is easy to set up on a standard form but is currently not happening when people sign up by the above API method.

**Comment by evansd** [comment]
Fixed by #2271
