### ISSUE TITLE
Make download file from API save as csv rather than File

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#221]
Downloaded from the api yesterday, using Chrome. File saved in my documents as 'File' rather than .csv

It is still in csv format when opened, it but means you have to do an extra step of having to select a program to open it with 

Example:
https://openprescribing.net/api/1.0/spending_by_ccg/?code=0602010Z0&format=csv

Edit: This also happens when downloading from the trends page e.g. https://openprescribing.net/chemical/0107010S0/

**Comment by HelenCEBM** [comment]
Duplicated in #933. Closing.
