### ISSUE TITLE
all-england can be broken during deploy

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2228]
If PPU savings are imported before measures are recomputed, the all-england page breaks because it tries to find `MeasureGlobal` objects with a month corresponding to the latest `ImportLog` with `category='ppu'`.

**Comment by evansd** [comment]
I had a look to see if this was something that could be easily and quickly fixed, but it doesn't look like it is. What we want is to take the minimum of the latest PPU date and the latest measure date. But there's no category in the ImportLog that represents the measures having finished importing. We could try to get that date from the MeasureValue table, but that would only tell us that _some_ measure had finished importing, not that _all_ measures had. And that would mean we would get an inaccurate total savings figure which would then be cached.

I think the most straightforward fix would be to create a new ImportLog event `measures` after all the measures have finished re-importing.
