### ISSUE TITLE
Support multi-paragraph measure descriptions

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2238]
Measure descriptions appear in two contexts. As the main page body text on pages like [this](https://openprescribing.net/measure/seven_day_prescribing/)
where it is wrapped like so:
```html
<p>
  <strong>Why it matters</strong>: [MEASURE DESCRIPTION]
</p>
```

And as part of the measure panel on pages like [this](https://openprescribing.net/measure/seven_day_prescribing/all-england/) where it is wrapped like so:
```html
<div class="descriptive">
  <strong>Why it matters:</strong> [MEASURE DESCRIPTION]
</div>
```

It would be nice to be able to break the text up into multiple paragraphs in a way which produces valid HTML and looks right in both contexts. (See discussion [here](https://github.com/ebmdatalab/openprescribing/pull/2007#issuecomment-558099423).)

If we're going to do this then "Why it matters" should probably become a heading rather than a bold introductory sentence.

**Comment by richiecroker** [comment]
this works now.
