### ISSUE TITLE
Change openprescribing.net/caution so it doesn't redirect to RocketChat

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#224]
Typing in openprescribing.net/caution directs you to the rocket chat rather than to openprescribing. Not sure if this is happening on other links, I tried openprescribing.net/analyse and openprescribing.net/ccg and they both went to the right page

www.openprescribing.net/caution goes to the right place, and so does https://openprescribing.net  - seems to be http:// that is the problem

Tried it on chrome and firefox

**Comment by annapowellsmith** [comment]
Thanks, well spotted Lisa! This is probably related to our CloudFlare move earlier today - will have a look at it now.

**Comment by annapowellsmith** [comment]
Fixed.
