### ISSUE TITLE
Consider how to deal with caching when logged in

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#225]
Currently we aggressively cache everything.

The new alerts features introduce some subtle logged-in features: once you've subscribed to an alert, you are logged in (without this being indicated in the UI), which means we can prefill the subscribe box with their current email address. We also log them in when they follow an unsubscribe link.  This is not a very important feature but it's nice UI sugar.

We also add a menu option for site admins so they can preview what an email would look like from the organisation dashboard. 

Both of these features will not play nicely with aggressive caching.

I think there are two broad options:

1. Stop caching HTML pages
2. Don't prefill email addresses for logged in users; and get admins logging in via a different (uncached) domain

(There's also 3. pay for a Cloudflare enterprise plan but I think that'll not be suitable for our budget...)

I think I would prefer (1) because we are a low-traffic website, and it's nice to have uncomplicated ways of providing user-based customisations; it's uncomplicated.

The argument for (2) is that aggressively caching HTML does mean we're better protecting ourselves against performance issues when we're being scraped (or indeed DDoS attacks). There again, all our CPU-heavy operations are via the JSON API and that could easily continue to be cached aggressively.

It would be nice to get some stats to test my hypothesis that aggressive HTML caching is a bit YAGNI but again, you don't get that kind of data without an enterprise plan, so it's going to have to be based on gut feeling and Anna's historic experience.

So, what are your thoughts @annapowellsmith?

**Comment by annapowellsmith** [comment]
If I've understood correctly, we could still continue to cache everything except `/analyse` and the organisation dashboards (using CloudFlare's page rules). 

I think (1) should be fine because as you say, we will still cache the API, which is where most of the work happens.

**Comment by sebbacon** [comment]
Right, we could just skip `/analyze`. I'll do that, then. Thanks!
