### ISSUE TITLE
Add links, for all measures, to data / code / text explaining how measure was built

### ISSUE THREAD

**Issue by Bengoldacre** [ebmdatalab/openprescribing#2258]
We have this done for all that can be driven from analyse page; but those relying on e.g. quantity cannot be done this way. For those we could swiftly zip thru and manually make a link to the code driving the measure, not necessary for it to be perfect text, just discoverable and intelligible to an expert crowd.

**Comment by evansd** [comment]
@inglesp Given that we now have `SOURCE_COMMIT_ID` in settings and that the measure ID maps straightforwardly to a filename, I suppose we could generate a link to the measure definition on github fairly easily.

**Comment by evansd** [comment]
After discussion with @inglesp, we think we should have a page for each measure showing the SQL which drives it, together with some generic explanatory text (the same for all measures). This can piggy back off the work Peter's already done in getting our measures to run off the public BQ dataset. There will still be some "black box" elements (e.g. private tables which Rich manually curates) but it's a solid step in the right direction.

Tech notes:
 * Use the template in `bq_public_tables/_measure_template.sql`
 * Maybe inject comments into the template making it visually clear which are the key parts of the query which define the numerator and denominator
 * I think there are some SQL syntax highlighting libraries written in JS which we could use for added prettiness.

**Comment by inglesp** [comment]
We could just show the SQL for the two subqueries that calculate the numerators and denominators -- that'd be significantly less overwhelming that showing the full query.
