### ISSUE TITLE
Standardise BNF code searches on Analyse page 

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#226]
Standardise BNF code searches on the Analyse page so that e.g. searching 10010 will find 10.1.1, and 10.1.1 will also suggest products beginning 100101

![image](https://cloud.githubusercontent.com/assets/15875191/20001529/891f2a10-a274-11e6-8478-75f0345d72c3.png)

As a prescribing analyst I want the BNF searches in the analyse page to be more flexible when searching for codes so that I can find the BNF chapter I am looking for

Priority: Medium
Ease: Medium

**Comment by HelenCEBM** [comment]
closing in favour of #1099
