### ISSUE TITLE
Give option on Analyse to only show data for GP Practices/CCGs selected

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#228]
Add an option to the Analyse tool to only show the data for the GP Practices & CCGs selected. This would help a number of use cases:

**CCG Comparisons:**
CCGs quite often want to compare themselves to similar CCGs, rather than to all of them, and this would allow them to pick out the CCGs they are interested in.

Use Case
As a prescribing analyst, I only want to see te CCGs I select on the graphs so I can compare our performance to similar CCGs

**Locality/GP Partnership Groups:**
Instead of adding locality or GP Partnerships to the CCG/GP Dashboards, the analyse tool would allow users to only look at data for practices they are interested in. This will have even more benefit once we add the e-mail alerts to the Analyse page, as users will then only need to run searches once and can subscribe to emails.

Use Case:
As a GP Partnership that crosses CCGs, I want to be able to look at a dashboard of our practices so I can compare our practices against each other

As a prescribing analyst, I would like to look at dashboards for locality groups so our medicines optimisation pharmacists can focus on the practices they manage

Priority: Low
Ease: Medium

**Comment by HelenCEBM** [comment]
another request from a user on this: 
> Hi I run 36 practices
> would be great to get a view of these practices

**Comment by HelenCEBM** [comment]
request from another user 
> I did select from the options but it still showed me all the ccgs in the country not just the ones I had chosen - could you advise?
