### ISSUE TITLE
Allow users to search on Analyse using drug and dose

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#229]
Add the ability for users to search by drug and dose/pillsize on analyse

Use Case:
As a consultant, I want to be able to identify patients currently on doses higher than recommended so we can provide GP practices with education and support

Priority: Low
Ease: Uncertain - requires discussion on how to identify dose from BNF code

**Comment by HelenCEBM** [comment]
added to #1099
