### ISSUE TITLE
Add national average line to Analyse Spine Chart

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#230]
Add a national median line to the analyse spine chart. 

We could also consider adding a CCG average line when someone searches analyse by practice

Use Case:
As a prescribing analyst I would like to see a line for the CCG and national average on the analyse page graphs so that I can understand our performance

Priority: Low
Ease: Medium

**Comment by HelenCEBM** [comment]
Closing as similar to #101 and therefore covered by #1099
