### ISSUE TITLE
Possible cost saving inconsistency

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2302]
User feedback from email:

> However, I think I may have spotted an error, or at least an inconsistency, here:
> https://openprescribing.net/measure/lyrica/ccg/11X/
>  
> The description does not match the graph.
>  
> The description reads, under “Performance”:
> If it had prescribed in line with the median, this CCG would have spent £1,122 less over the past 6 months. If it had prescribed in line with the best 10%, it would have spent £7,484 less.
>  
> However, in the accompanying graph, there was no month in the last 6 months where Somerset CCG was at or greater than the median (click and drag a box, on the graph, to zoom in to have a look). In fact there was no month since July 2017, where this was the case.
>  
> Therefore, I would expect the description to say (like it does with other CCGs that spend less than the median, but more than the best 10%):
> By prescribing better than the median, this CCG has saved the NHS £X over the past 6 months. If it had prescribed in line with the best 10%, it would have spent £7,484 less.

**Comment by evansd** [comment]
I suspect this is to do with the fact that the measure is defined in terms of items, but we're trying to calculate savings from it in terms of quantity and cost. As a quick test I generated two new staging measures which use the same BNF codes but have quantity and cost in place of items:
http://staging.openprescribing.net/measure/lyrica_quantity/ccg/11X/
http://staging.openprescribing.net/measure/lyrica_cost/ccg/11X/

As you can see, this CCG scores quite differently on these measures, although still better than the median. For comparison, here is the original measure on staging:
http://staging.openprescribing.net/measure/lyrica/ccg/11X/

This needs more thought that I can give it right now, but I wanted to record this somewhere.

**Comment by evansd** [comment]
I've finally got to the bottom of this, and it is an error on our part. I think it will affect cost savings calculations for any measure which is:
 * a percentage measure;
 * cost based;
 * and is not of the form `quantity / quantity`.

Which at the moment means that only `lyrica` is affected.

The issue is that the cost saving calculation assumes the values at each decile are always a ratio of quantities, which is mostly true but not true for `lyrica` where it's a ratio of items.

To give a worked example from the case that brought this to our attention: In May 2019 the median CCG had about 0.8% of Pregabalin items prescribed as Lyrica, and 11X had about 0.5%. And in terms of quantity the median practice had about 0.1% Lyrica and 11X had 0.09%. So it both cases 11X is better than the median. However the cost saving calculation proceeds by comparing 11X's 0.9% for quantity against the median CCGs 0.8% for items, resulting in a positive cost saving.

I don't think there's an easy fix for this because when a measure is defined in terms of items we never calculate the deciles for quantities. (I only know the quantity deciles above because I created an additional `lyrica_quantity` measure.) And even if we did calculate deciles based on quantity then, while our cost savings would no longer be incorrect, they might still be surprising. A CCG could be below the median in terms of items but above the median in terms of quantity and so it would look odd to say "if it performed as well as the median it would have saved X".

**Comment by evansd** [comment]
### Summary for people who don't want to read all of the above

Our cost savings for the "Pregabalin prescribed as Lyrica" are wrong because that measure is defined as a ratio of items, rather than a ratio of quantities like we usually do.

Our options are:
 1. switch off cost savings calculations for this measure; or
 2. change the measure to use quantity instead of items (compare on staging: [items](http://staging.openprescribing.net/measure/lyrica/ccg/11X/) vs [quantity](http://staging.openprescribing.net/measure/lyrica_quantity/ccg/11X/)); or
 3. do both of the above: keep the items-based measure without cost savings and add a new quantity-based one with cost savings.

**Comment by inglesp** [comment]
Yikes.

Is it easy to work out how many CCGs/etc are affected?

**Comment by HelenCEBM** [comment]
Option 4: add a note to say the cost savings are approximate for this measure? (if we think they're close)

**Comment by richiecroker** [comment]
quantity is tricky as liquids can quickly skew data

**Comment by richiecroker** [comment]
also, how does calculation take into account different prices for different strengths?

**Comment by evansd** [comment]
> quantity is tricky as liquids can quickly skew data

Yeah, items feels like the right unit to be using here, as a measure of prescriber behaviour. We want to say: how often, when given the option to prescribe something equivalent to Lyrica, did you choose to prescribe Lyrica? And I guess we're less interested in how much of anything they're prescribing.

> how does calculation take into account different prices for different strengths?

I don't think it does. The cost saving calculation is basically this: assume you prescribe 10 units of brand at a total cost of £10 and 90 units of generic at a total cost of £9. Your branded prescribing rate is then 10% (10 units out of 100). Your price per unit is £1 for branded and £0.10 for generic. Your total spend is £19.

Say the median practice has a 5% prescribing rate. If you had matched that then, with your 100 units total, you would have prescribed 5 units of brand and 95 of generic. Using your current price per unit that would have cost £14.50 (5 x £1 + 95 x £0.10). So we say there's a potential cost saving of £4.50 (£19 - £14.50).

So we're assuming (a) your total quantity stays the same and (b) your average price-per-unit of both branded and generic stay the same and then asking what happens if we shift your ratio of branded to generic prescribing.

Hope that makes sense! It took me a while to get my head round it.

**Comment by richiecroker** [comment]
I have created a PR (https://github.com/ebmdatalab/openprescribing/pull/2369) which amends the measure to quantity, and looks at capsules only.  Let's see how that effects 11X
