### ISSUE TITLE
Re-write the error codes on the Analyse page to be more understandable to users

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#232]
Error codes on the analyse page are not always clear to users, and don't explain how they might be able to fix the issues e.g:
![image](https://cloud.githubusercontent.com/assets/15875191/20003559/0d6cd79a-a27f-11e6-961f-8c5394b6bf8d.png)

Use Case:
As the Head of Medicines Optimisation, I want the error codes on the analyse page to be clear on how I can solve the problem so that this doesn't prevent me using this area of the site *

*This particular user tried to use analyse, got an error code, didn't understand it, so didn't use it again

Two things to deal with:
Easy: I can review the error codes we already have (Seb needs to send them across to me)

Hard: We don't have a comprehensive list of all the things that may cause an error to show up on that page. I will make a note of any that come up with demonstrating to users, and will create new github issues as they arise 

(this issue can be marked as completed once our current error codes are re-written)

Priority (for rewriting error codes): Low
Ease: Easy

**Comment by Bengoldacre** [comment]
great, plan: seb to generate list error codes, lisa to review and write clearer ones for now, then we rethink

**Comment by sebbacon** [comment]
@lmfrench not very user-friendly, but the codes are basically in here - let me know if they are not standing out enough for you! https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/api/views_spending.py

**Comment by lmfrench** [comment]
yes thanks will go through them later in the week!

**Comment by lmfrench** [comment]
I think the only error code from that list which might appear to users on the analyse page is this one:
'Error: Codes must all be the same length'

Possible change:
'Error: BNF codes must all be the same length if included in the same search box e.g. if you want to look at Cerelle and Cerazette prescribing, you cannot search for Cerazette_Tab 75mcg (0703021Q0BBAAAA) and Cerelle (0703021Q0BD) under 'on'. You could search for Cerazette (0703021Q0BB) and Cerelle (0703021Q0BD)

Is it clear that by search box I mean under 'on' they must be the same, and under 'versus' they must be too, but that you could have different lengths in each? I couldn't think of a better way to phrase it

**Comment by lmfrench** [comment]
Will add this to the FAQs, and then need link added to error code
