### ISSUE TITLE
Alert on missing presentations

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2322]
Sometimes we have prescribing recorded against BNF codes for which we have no corresponding entry in our `Presentations` table (`1106000AKBBABAB`, a form of eye drop, is an example at time of writing.)

The root of this issue is (we're pretty confident) that there's been a change in BNF codes but we don't have a copy of the latest BNF code mapping file (see #380). We've requested an up-to-date copy.

It would be good to check automatically for future instances of this problem. Probably this would be best done as an import pipeline step. It needn't block import of the data but it would be good to know about the issue as soon as possible.

The alert should include information on what to do next i.e. who to email at NHSBSA, which file to request, and what to do with it once we have it.

**Comment by richiecroker** [comment]
@evansd can we close this - we seem to handle it ok now
