### ISSUE TITLE
Change percentiles on dashboard graphs to a range if measure is at 100%

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#234]
Change the percentiles to a range if the measure is at 100% to make the percentiles more easily understandable for users.

Example of where this is currently confusing:
https://openprescribing.net/practice/K84009/
![image](https://cloud.githubusercontent.com/assets/15875191/20004059/e950580c-a281-11e6-8ec7-cf0b0f0a766d.png)

With the change, this should instead read '60-100th percentile nationally in Nov 2010'

Ranges should only be included if at 100%, the rest should all remain unchanged.

Use Case:
As a prescribing analyst, it should be clearer what the percentiles show when a measure is at 100%, so that it can be understood by all members of the medicines optimisation team

Priority: Low
Ease: Medium

**Comment by HelenCEBM** [comment]
Minor issue affecting very few practices and (I think) only this measure. Closing
