### ISSUE TITLE
Allow users to search by GP Practice Code in the GP Practice Dashboard Search

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#236]
The GP Practice search currently states you can search by practice name or code, but searching by code does not work
https://openprescribing.net/practice/

This search does allow you to search by postcode - so a quick fix to this will be to change the search text to say 'Search by name or postcode' instead of 'Search by name or code'

Use Case:
As community manager, I want to be able to search by GP Practice code when looking at practice dashboards so that I don't have to google the practice name if all the information I have is the code

**Comment by sebbacon** [comment]
The easy way to do this is to add the practice code in brackets after the practice name.

It does make the list a bit harder to scan.

I don't think this is worth the effort of doing a more elegant solution, so I propose either just changing the text to "postcode" in the input box, or doing something like the screenshot below (we could change the wording with the brackets, but to make the search work with both types of code, we need to show them both).

Another alternative would be to get rid of postcode. I expect a postcode search to work based on proximity. I'm not sure how many users will know the postcode (or postcode area) of a practice but not the practice name?

![download](https://cloud.githubusercontent.com/assets/211271/20216278/9539cba0-a811-11e6-86cc-48bdfcfe47cd.png)

**Comment by annapowellsmith** [comment]
I think I'm missing something... how does adding the practice code in the results help with searching by practice code?

**Comment by sebbacon** [comment]
It's the [way list-filter.js works](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/media/js/list-filter.js#L10)  (which is used in a couple of other places) , so [this change](https://github.com/ebmdatalab/openprescribing/commit/af169d869883aa3ced08e8b28fd5f5348d6d54fd) is the easiest way to fix it.

The implementation makes sense, in that you want to see the text you're matching. But making the output more scannable feels like a bigger issue and when prioritising we discussed this being a pretty minor thing to fix (the easiest thing being to specify that you can search by *postcode*, not *code* (as currently stated in the placeholder text)

**Comment by annapowellsmith** [comment]
Oh cool - forgot that. Yeah, that looks like the easiest fix then. 

Postcode is just included so people can easily verify that they've got the right surgery (e.g. if I type in "Green Lane" then there are quite a few surgeries with similar names). 

The whole design needs rethinking, obviously, but this seems like a sensible quick fix!

**Comment by lmfrench** [comment]
Yeah I think changing it to say postcode is best option, I don't like how the practice code text looks & I don't think many people will want to search that way. 

CCG  code searching might be more common (when I was at Leicester CSU I knew the CCG codes, but I still think I would have just typed in Leicestershire)
