### ISSUE TITLE
"Contact Us" link breaks on pages with very long URLs

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2376]
For example, the [Analyse link](https://openprescribing.net/analyse/#numIds=0301011AB%2C0301011E0AAADAD%2C0301011E0BD%2C0301011U0AAACAC%2C0301011U0AAAHAH%2C0301011U0BBACAC%2C0301011U0BBADAD%2C0301011U0BBAFAH%2C0301011U0BD%2C0301011U0BE%2C0301011U0BF%2C0301011U0BG%2C0301011V0AAAAAA%2C0301011V0BBADAA%2C0301020I0AAAAAA%2C0301020I0AAANAN%2C0301020I0BBAAAA%2C0301020I0BBADAD%2C0301020I0BBAGAG%2C0301020I0BBAJAN%2C0301020I0BI%2C0301020P0%2C0301040M0BB%2C0301040M0BC%2C0301040R0AAAAAA%2C0301040R0BBAAAA%2C0302000C0AAAAAA%2C0302000C0AAABAB%2C0302000C0AAACAC%2C0302000C0AAARAR%2C0302000C0AAASAS%2C0302000C0AAATAT%2C0302000C0AAAUAU%2C0302000C0AABEBE%2C0302000C0AABFBF%2C0302000C0AABGBG%2C0302000C0AABHBH%2C0302000C0AABVBV%2C0302000C0AABWBW%2C0302000C0AABXBX%2C0302000C0AABZBZ%2C0302000C0BB%2C0302000C0BCAHAB%2C0302000C0BCAIAA%2C0302000C0BCAQAR%2C0302000C0BD%2C0302000C0BE%2C0302000C0BF%2C0302000C0BG%2C0302000C0BJ%2C0302000C0BP%2C0302000C0BQ%2C0302000C0BS%2C0302000C0BT%2C0302000K0AAAAAA%2C0302000K0AAADAD%2C0302000K0AAAZAZ%2C0302000K0AABABA%2C0302000K0AABBBB%2C0302000K0BBADAD%2C0302000K0BBAEAA%2C0302000K0BBAMAZ%2C0302000K0BBANBA%2C0302000K0BDADBB%2C0302000N0AABABA%2C0302000N0AABCBC%2C0302000N0AABEBE%2C0302000N0AABFBF%2C0302000N0AABGBG%2C0302000N0AABHBH%2C0302000N0AABJBJ%2C0302000N0AABKBK%2C0302000N0AABLBL%2C0302000N0AABPBP%2C0302000N0AABQBQ%2C0302000N0BBAXBA%2C0302000N0BBAYBB%2C0302000N0BBAZBC%2C0302000N0BBBBBH%2C0302000N0BCADBE%2C0302000N0BCAEBF%2C0302000N0BCAFBG%2C0302000N0BD%2C0302000N0BF%2C0302000N0BGABBF%2C0302000N0BGACBG%2C0302000N0BI%2C0302000N0BJ%2C0302000N0BL%2C0302000U0%2C0303010J0%2C0303010Q0AAABAB%2C0303010Q0AAANAN%2C0303010Q0BBAFAB%2C0303010Q0BBAJAL%2C0303010Q0BBALAN&measure=environmental_inhalers&denomIds=0301011AB%2C0301011E0%2C0301011U0AAAAAA%2C0301011U0AAABAB%2C0301011U0AAACAC%2C0301011U0AAAEAE%2C0301011U0AAAHAH%2C0301011U0BB%2C0301011U0BD%2C0301011U0BE%2C0301011U0BF%2C0301011U0BG%2C0301011V0AAAAAA%2C0301011V0AAALAL%2C0301011V0AABBBB%2C0301011V0BBADAA%2C0301011V0BBAMAL%2C0301011V0BBARBB%2C0301011X0%2C0301011Z0%2C0301020I0AAAAAA%2C0301020I0AAANAN%2C0301020I0BBAAAA%2C0301020I0BBADAD%2C0301020I0BBAGAG%2C0301020I0BBAJAN%2C0301020I0BI%2C0301020P0%2C0301020Q0%2C0301020R0%2C0301020S0%2C0301020T0%2C0301040M0BB%2C0301040M0BC%2C0301040R0AAAAAA%2C0301040R0BBAAAA%2C0301040V0%2C0301040W0%2C0301040X0%2C0301040Y0%2C0302000C0AAAAAA%2C0302000C0AAABAB%2C0302000C0AAACAC%2C0302000C0AAAFAF%2C0302000C0AAAGAG%2C0302000C0AAAIAI%2C0302000C0AAAJAJ%2C0302000C0AAAKAK%2C0302000C0AAALAL%2C0302000C0AAAQAQ%2C0302000C0AAARAR%2C0302000C0AAASAS%2C0302000C0AAATAT%2C0302000C0AAAUAU%2C0302000C0AABEBE%2C0302000C0AABFBF%2C0302000C0AABGBG%2C0302000C0AABHBH%2C0302000C0AABIBI%2C0302000C0AABJBJ%2C0302000C0AABKBK%2C0302000C0AABSBS%2C0302000C0AABUBU%2C0302000C0AABVBV%2C0302000C0AABWBW%2C0302000C0AABXBX%2C0302000C0AABYBY%2C0302000C0AABZBZ%2C0302000C0AACACA%2C0302000C0BB%2C0302000C0BC%2C0302000C0BD%2C0302000C0BE%2C0302000C0BF%2C0302000C0BG%2C0302000C0BH%2C0302000C0BI%2C0302000C0BJ%2C0302000C0BL%2C0302000C0BN%2C0302000C0BP%2C0302000C0BQ%2C0302000C0BR%2C0302000C0BS%2C0302000C0BT%2C0302000K0AAAAAA%2C0302000K0AAADAD%2C0302000K0AAAGAG%2C0302000K0AAAHAH%2C0302000K0AAAKAK%2C0302000K0AAALAL%2C0302000K0AAAMAM%2C0302000K0AAAUAU%2C0302000K0AAAVAV%2C0302000K0AAAWAW%2C0302000K0AAAZAZ%2C0302000K0AABABA%2C0302000K0AABBBB%2C0302000K0BBADAD%2C0302000K0BBAEAA%2C0302000K0BBAHAG%2C0302000K0BBAIAH%2C0302000K0BBAKAK%2C0302000K0BBAMAZ%2C0302000K0BBANBA%2C0302000K0BD%2C0302000K0BF%2C0302000K0BG%2C0302000K0BH%2C0302000K0BI%2C0302000N0AAAAAA%2C0302000N0AAACAC%2C0302000N0AAADAD%2C0302000N0AAAEAE%2C0302000N0AAAFAF%2C0302000N0AAAPAP%2C0302000N0AAARAR%2C0302000N0AAASAS%2C0302000N0AAATAT%2C0302000N0AAAUAU%2C0302000N0AAAXAX%2C0302000N0AAAYAY%2C0302000N0AAAZAZ%2C0302000N0AABABA%2C0302000N0AABCBC%2C0302000N0AABEBE%2C0302000N0AABFBF%2C0302000N0AABGBG%2C0302000N0AABHBH%2C0302000N0AABJBJ%2C0302000N0AABKBK%2C0302000N0AABLBL%2C0302000N0AABPBP%2C0302000N0AABQBQ%2C0302000N0BBAAAA%2C0302000N0BBACAC%2C0302000N0BBAEAE%2C0302000N0BBAFAF%2C0302000N0BBARAR%2C0302000N0BBASAS%2C0302000N0BBATAT%2C0302000N0BBAUAU%2C0302000N0BBAXBA%2C0302000N0BBAYBB%2C0302000N0BBAZBC%2C0302000N0BBBBBH%2C0302000N0BC%2C0302000N0BD%2C0302000N0BF%2C0302000N0BG%2C0302000N0BH%2C0302000N0BI%2C0302000N0BJ%2C0302000N0BK%2C0302000N0BL%2C0302000N0BM%2C0302000R0%2C0302000U0%2C0302000V0%2C0303010J0%2C0303010Q0AAABAB%2C0303010Q0AAADAD%2C0303010Q0AAANAN%2C0303010Q0BB%2C0307000R0) for the [Environmental Inhalers](https://openprescribing.net/measure/environmental_inhalers/all-england/) measure.

The error message is:
```
Bad Request

Request Line is too large (4966 > 4094)
```

We just need to set a max length limit on the `from_url` parameter. Possibly with something obvious in the URL to indicate (to us) that it's been truncate so we don't get confused.

**Comment by richiecroker** [comment]
closed, as contact us has been deprecated
