### ISSUE TITLE
All England measure savings incorrect following monthly import

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#2391]
After importing Nov 2019, the measure savings at All England level are shown as zero.

**Comment by sebbacon** [comment]
This is a caching issue:

```python
>>> print(json.dumps([(k, cache.get(k)) for k in keys], indent=2))
[
  [
    "27f9a721b61f3ffc9644fee32f8a291ab1ada5b4:frontend.views.views:all_england_measure_savings:CCG:2019-11-01",
    {
      "70": null,
      "20": null,
      "50": null,
      "30": null,
      "10": null,
      "60": null,
      "90": null,
      "80": null,
      "40": null
    }
  ],
...
```

**Comment by sebbacon** [comment]
Presumably this is because the cache was hit for the first time following a deploy (so with new git commit hash) but *during* a pipeline ingest, when we know some values come out as zero?

The pipeline finished at 1705 yesterday (19 Jan) and the last deploy was at 1036 on 19th, so this is at least possible as that deploy was [fixing something in the pipeline](https://github.com/ebmdatalab/openprescribing/compare/096d27f6a1fa6e7638dd955bd335e00bcecfbb3c...27f9a721b61f3ffc9644fee32f8a291ab1ada5b4).

**Comment by evansd** [comment]
Thanks Seb. I think this is essentially the same issue as in the related #2228 you found, and the same fix would work:
> I think the most straightforward fix would be to create a new ImportLog event `measures` after all the measures have finished re-importing.
That doesn't strike me as an enormous amount of work, although there may well be complications due to the fact that measures can be imported both within and outside of the pipeline. It's just a question of priorities though.

**Comment by sebbacon** [comment]
It does sound reasonably straightforward, and as this has actually bitten us, I think worth doing now - what do you think?

**Comment by evansd** [comment]
I think it's worth tackling with a time box. Happy to take a look today.
