### ISSUE TITLE
Start creating an alpha for the "Labs" outlier detection pages

### ISSUE THREAD

**Issue by Bengoldacre** [ebmdatalab/openprescribing#2398]

**Comment by inglesp** [comment]
Straw man from discussion with Seb:

* Alex writes notebook that produces a CSV with data
  * TODO: agree on CSV columns
* After each monthly import, Alex runs the notebook and commits the CSV to the openprescribing repo
  * TODO: agree on where to commit the CSV
* Once deployed, we run a management command to load the new data into a database table
* There will be a page at `/practice/P12345/outliers/` that shows the rows for a practice in the most recent month, with a Google Form for feedback

@alexwalkercebm what do you think?

**Comment by alexwalkercebm** [comment]
1. How easy will it be to change the CSV columns?
2. Can the CSV include images? (They could be formatted in HTML or however is best.)
3. There are two types of outliers we want to include, which might have different structure requirements:
a. Fixed time outliers - entities that are different to others within the last X months.
b. Change outliers - entities that are especially fast or slow to change.
I guess it might be better to have separate pages for each of these? E.g. `/practice/P12345/static-outliers/` and `/practice/P12345/change-outliers/`

**Comment by inglesp** [comment]
Sounds like we've got very different ideas -- let's talk at 11.

**Comment by inglesp** [comment]
As discussed, uploading CSVs alone won't really do the job.  We want to display graphs, and we want Alex to be able to change how the graphs are rendered without having to get a developer involved.

Instead, we talked about Alex generating HTML pages for each practice, interpolating charts/tables into a template that he controls.

I'm going to work out a good way to render as HTML a dataframe that includes a chart (cell 4 from [this notebook](https://github.com/ebmdatalab/opioids-change-detection-notebook/blob/073ba0f/notebooks/ccg-opioids-change-detection-analysis.ipynb)).

**Comment by inglesp** [comment]
Here’s a notebook with an example of generating an HTML document that contains DataFrames: https://github.com/ebmdatalab/html-template-demo/blob/master/notebooks/demo.ipynb

**Comment by alexwalkercebm** [comment]
The current outliers repo now contains a sample of prototype HTML pages, for practices, CCGs and PCNs:
https://github.com/ebmdatalab/outliers/tree/2bfc3620a579088aeaa2429ec7ce3c6d3e7d8f0c/data
@Jongmassey has made the HTML fit with the OpenPrescribing style.
cc @sebbacon for our chat tomorrow on reviving this.
