### ISSUE TITLE
PPU substitutions code doesn't work as intended

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2411]
I'm documenting this just to confirm my understanding. The issue, assuming I've understood it correctly, will be fixed as part of the MatrixStore-powered reimplementation in #2394 

Can others check over and see if the below makes sense?

---------------------

We have a [formulation swaps](https://github.com/ebmdatalab/price-per-dose/issues/11) spreadsheet which we use to mark different formulations of a given presentation (e.g. tablets and capsules) as equivalent for the purposes of the PPU calculation. But there are two issues with the way this is currently implemented.

### 1. We don't handle branded prescribing correctly

The formulation swaps are implemented by creating a `prescribing_with_merged_codes` table which performs a substitution on BNF codes using a `CASE` statement. For instance, if the spreadsheet says that generic A can be substituted for generic B then whenever we see the BNF code B we replace it with A. Later we apply various BNF code matching rules to also include all prescribing of branded A. But we never include branded B.

Interestingly the code which renders the bubble charts, which are driven directly from the prescribing data and not from the PPU table, _does_ seems to handle substitution of branded prescribing correctly. But not the code which calculates the target PPU or the available savings.

As a concrete example, if you look at savings for Co-codamol 30mg/500mg tablets at [this CCG](https://openprescribing.net/ccg/15E/price_per_unit/?date=2019-11-01) it shows a total quantity of 2,318,288. If you look at what the [bubble chart API](https://openprescribing.net/api/1.0/bubble/?format=json&date=2019-11-01&bnf_code=0407010F0AAAHAH&highlight=15E&focus=1) returns and add up the quantities you get a figure which is greater by 34,952. The difference is exactly equal to the quantity of branded capsules (e.g. "Kapake_Cap 30mg/500mg"). So the PPU figure is including generic tablets, branded tablets, generic capsules but not branded capsules.

This omission can sometimes have quite large effects on the target PPU. For instance, on [this chart](https://openprescribing.net/all-england/0301020Q0AAABAB/price-per-unit/?date=2019-11-01) it's fairly obvious from the big green blob of "Braltus_Pdr For Inh Cap 10mcg+Zonda Inh" priced at 86p that the best decile price should be around 86p. But looking at the Target PPU column in the table we can see that it's been calculated at £1.03.

### 2. We don't handle multiple formulation swaps correctly
 
Sometimes we want to say that not only is A equivalent to B, but C is also. For instance, on the last two lines of the current spreadsheet we have:

Formulation | Code | Alternative Formulation | Alternative Code
-- | -- | -- | --
Tiotropium_Pdr For Inh Cap 18mcg | 0301020Q0AAABAB | Tiotropium_Pdr For Inh Cap 10mcg + Dev | 0301020Q0AAADAD
Tiotropium_Pdr For Inh Cap 18mcg + Dev | 0301020Q0AAAAAA | Tiotropium_Pdr For Inh Cap 10mcg + Dev | 0301020Q0AAADAD

But the PPU code can't handle the same presentation occurring multiple times in the spreadsheet i.e. it can't handle saying as we do above "A is equivalent to B and C is also equivalent to B". If it encounters the same presentation a second time it just ignores it:
https://github.com/ebmdatalab/openprescribing/blob/e7104cf8305793172cd82989dd0b70471f247613/openprescribing/frontend/management/commands/import_ppu_savings.py#L53-L58

**Comment by inglesp** [comment]
This all makes sense, well done.
