### ISSUE TITLE
Direction of "good" still confusing

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#242]
The change in #138 didn't clarify matters and we now get feedback about people being confused in a different way.

Mock up a few options and test them with people:

* Inverting nominator and denominators and rewording so everything has good at the same end
* Adding colour coding to the deciles
* Adding an arrow on the y-axis along the lines of `<--- better -------- worse --->`

**Comment by HelenCEBM** [comment]
All measures now have "low is good". Other improvements could still be added in some way to make this clearer but in general we think people should read and understand the text to interpret the data properly; allowing fast judgements may do more harm than good.
