### ISSUE TITLE
Cannot sign up for All England alert if already signed up for another alert

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2440]
In `_get_or_create_bookmark()`, `bookmark_args` is set to `{}` the user signs up for an All England alert.

This means that the next line, `bookmark_cls.objects.get_or_create(user=user, **bookmark_args)` is effectively `bookmark_cls.objects.get_or_create(user=user)`, which will either return the single existing bookmark for the user, or raise `MultipleObjectsReturned` if the user has more than one bookmark.

Fix incoming.

**Comment by brianmackenna** [comment]
Not sure if related - but I am signed up and didn't get the NHS in England alert. (I also didn't get the Islington CCG alert, should I make a separate issue?)

![image](https://user-images.githubusercontent.com/40460354/73926415-7f521900-48c7-11ea-9449-bd75738e4afb.png)

**Comment by inglesp** [comment]
Won't be related, as you've already signed up.  And alerts are still being sent, which would explain why you haven't received all yours yet.

**Comment by brianmackenna** [comment]
Not sure if relevant but I never received the All England alert - all others are there.
