### ISSUE TITLE
Pre-2017 prescribing data includes BNF codes for appliances with trailing spaces

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2447]
In prescribing data published before 2017, the prescribing data includes BNF codes with trailing spaces.  This only affect appliances (ie presentations with short codes) like 21350000100 (Aknicare Crm), and affects all appliances except 21300000100 (Oxyal Sod Hyaluronate Eye Dps 10ml).

This does not cause problems for anything driven off the MatrixStore, since this this [strips the whitespace](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/matrixstore/build/import_prescribing.py#L109-L111).

It would cause problems with a measure that was defined in terms of exact BNF codes (eg `numerator_where: "bnf_code = '21350000100'"`) but no measures are affected.  (I checked by looking at the `numerator/denominator_bnf_codes` -- only two measures (`silver` and `lpsilkgarments`) have `numerator/denominator_bnf_codes` that include spaces, and these are both defined in terms of whole BNF chapters.

Given that the prescribing table is going away, I think we should ignore it here.

However, BigQuery also has the bad data (going back to 2010).  We should fix this.  The easiest way to do that would be to add the truncation in the SQL for the `normalised_prescribing_standard` view.

I'll let the team know that this might affect any analyses they've done.

Are there any other considerations we should be aware of?

**Comment by richiecroker** [comment]
Pre-2017 BNF name also includes trailing spaces.  It would be helpful if these were also stripped in `normalised_prescribing_standard`

**Comment by inglesp** [comment]
@richiecroker Welcome to my time machine: https://github.com/ebmdatalab/openprescribing/pull/2465

**Comment by richiecroker** [comment]
@inglesp ;) didn't see it because it was closed!  Thanks!
