### ISSUE TITLE
Links from DMD browser to PPU pages are broken in some instances

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2508]
For example:
https://openprescribing.net/dmd/ampp/4881611000001105/
links to the PPU page using the branded BNF code:
https://openprescribing.net/all-england/1502010J0BNAACE/price-per-unit/
where in fact we want the generic:
https://openprescribing.net/all-england/1502010J0AACECE/price-per-unit/

It may be that we just change the way the DMD browser generates links, or we may decide we should make the PPU pages accept branded codes and work out the appropriate generic itself.

**Comment by evansd** [comment]
Another option is to make the PPU view accept the branded code but automatically redirect to the generic

**Comment by inglesp** [comment]
> we may decide we should make the PPU pages accept branded codes and work out the appropriate generic itself

As there's a mechanical translation from branded to generic BNF code, that should be "quite easy", shouldn't it?  Alternatively we could do the translation on the dm+d page -- but it'd probably be more useful to do it on the PPU page.

**Comment by sebbacon** [comment]
I believe the previous PPU implementation treated brands and generics as equivalent, i.e. it accepted branded codes. 

It did not redirect. Arguably I think that's still the correct implementation, as this is a page for comparing things that are equivalent so there's no natural "master" code.

**Comment by evansd** [comment]
I've tried a fix locally and I'm know more of the opinion that redirecting is the right thing to do. For instance, here's a screenshot of the PPU page for a particular brand of co-codamol tablet:

![localhost_8000_all-england_0407010F0BEAAAD_price-per-unit__date=2019-11-01](https://user-images.githubusercontent.com/19630/76310959-cddc4400-62c7-11ea-8a75-35f60b6288ca.png)

The phrase "all brands and formulations of Tylex 30mg/500mg capsules" is a little odd. And the presence of the savings table then seems to read as if these were savings that could be made by switching away from that specific brand, which is not the case.

Of course, it would be possible (and easy enough) to make the page refer to the generic throughout. But then it would be byte-for-byte identical with the generic page, so I think redirecting would be more appropriate.
