### ISSUE TITLE
Decide what to do with BQ data when reimporting prescribing data

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2513]
Because of the One Drug Database changes, the BSA are republishing the last five years of prescribing data, ie data from 2015_01 to 2019_12.  When we import this, we will have to decide what to do with the prescribing data in BigQuery.

Prescribing data in BigQuery is used both as in intermediate step in importing data into the databases (Postgres, MatrixStore) that drive OpenPrescribing.net, and for analyses (including for published papers).

There is a concern that if we change the data that's already in BigQuery, analyses in published papers will not be reproducible.

The most straightforward option from an implementation perspective is to:

* back up the existing prescribing table (by copying it somewhere with a new name, like `hscic.prescribing_pre_odd`)
* create a version of the normalised prescribing table with pre-ODD data
* replace the last five years of data in the existing prescribing table with updated ODD data
* continue to append new data to the existing prescribing table

This would mean that:

* there will be a discontinuity between 2014_12 and 2015_01, where prescribing will jump for some BNF codes
  * this won’t affect the site since we only show five years of data
  * I've investigated applying the ODD changes to data from before 2015_01, and it's not possible
* certain historic analyses (including potentially some in papers) will have different results if those analyses depend on BNF codes that have changed
  * but how different will depend on the BNF codes in question
* any historic analysis could be reproduced by changing `hscic.prescribing` to `hscic.prescribing_pre_odd` in the SQL

Another option would be to:

* create a new prescribing table (eg `hscic.prescribing_post_odd`, or `hscic.prescribing2`)
* create a new normalised prescribing table (we could call it `hscic.normalised_prescribing`, since we currently have `hscic.normalised_prescribing_legacy` and `hscic.normalised_prescribing_standard` for, um, legacy reasons)
* write the updated ODD data to the new prescribing table
* append new data to the new prescribing table

This would mean that:

* anybody doing an analysis covering months from 2015_01 to 2019_12 would have to decide which table to use
* anybody doing an analysis from before and after 2015_01 would have to use two tables (and still decide which table to use for the five years where we have both)
* we'll have to fiddle with our import code (but not too much)

We could mitigate some of this if we:

* copy data from before 2015_01 into the new table
  * this would give the discontinuities mentioned above
* append new data to the existing prescribing table
  * this would give discontinuities between 2019_12 and 2020_01
  * this would add extra implementation fiddliness

It is worth bearing in mind that the data in the `hscic.normalised_prescribing_XXX` tables can change as the BSA's version of the BNF hierarchy changes.  For instance, drugs may move from one BNF chapter to another.  This will have an impact on the reproducibility of certain historical analyses.  (This had not occurred to me until just now, but it may be known by the rest of the team.)

Given that the data in our BQ database is not generally accessible, I am perhaps more relaxed about introducing an extra hurdle to reproducing our published results than others might be.

I'd like input from @alexwalkercebm @HelenCEBM @sebbacon @evansd please.

**Comment by sebbacon** [comment]
How about:

* rename existing data to `*_pre_one_drug_database`
* create new data as `*_post_one_drug_database`
* create `normalised_prescribing` view which combines both (perhaps with a boolean `pre_one_drug_database` field as a hint to users) 

I think we should then go back and change everything in our github org to use `normalised_prescribing`. Most historic analyses are (I think) date-bounded so the crossing-the-boundary issue shouldn't be a problem. Github search is good enough this shouldn't be too onerous.

**Comment by HelenCEBM** [comment]
- I prefer the idea of having a single dataset that includes ALL data so we don't have to use two... ideally this would have the new ODD data for 2015 onwards so that any new queries match the data on the site. (However, saying that, maybe querying two isn't actually that bad...)
- Such a combined and ODD-updated dataset should be separate from the "old" data that we have used for old papers etc. Ideally I would keep the name `normalised_prescribing_standard` for this so that archived queries work, and use new table name for live queries. 
- I like seb's idea of spelling out ODD as it is a confusing acronym!

**Comment by inglesp** [comment]
The plan:

* Rename `hscic.prescribing` to `hscic.prescribing_v1`
* Import republished ODD data to `hscic.prescribing_v2`
* Rename `normalised_prescribing_standard` to `normalised_prescribing`, and get it to pull in pre-2015 data from `hscic.prescribing_v1`
* Drop `normalised_prescribing_legacy`
* Do a GitHub search for any repos that query `normalised_prescribing_XXX` and add a note to the README to say that these queries will have to be updated
  * Any repos that use `bq.cached_read` will be unaffected
  * Any repos that don't use `bq.cached_read` will probably not be reproducible

**Comment by alexwalkercebm** [comment]
@HelenCEBM and I think that we should keep `normalised_prescribing_standard`, but change it to point to `hscic.prescribing_v1`. That way old repos should just work as previously, and should use exactly the same data as when originally run. Then there shouldn't be any need for GitHub searches etc.

`normalised_prescribing` sounds great as you describe: using ODD data from 2015, but `hscic.prescribing_v1` before then.

We could double check that `normalised_prescribing_legacy` isn't used anywhere, if not, bin it.

**Comment by inglesp** [comment]
@alexwalkercebm I'm happy with that plan -- but this line isn't quite true:

> old repos should just work as previously, and should use exactly the same data as when originally run

because of:

> It is worth bearing in mind that the data in the hscic.normalised_prescribing_XXX tables can change as the BSA's version of the BNF hierarchy changes. For instance, drugs may move from one BNF chapter to another. This will have an impact on the reproducibility of certain historical analyses. (This had not occurred to me until just now, but it may be known by the rest of the team.)

**Comment by alexwalkercebm** [comment]
Am I right in thinking this is because of the normalisation, i.e. joining with `ebmdatalab.hscic.bnf_map`, and that this has always been an issue, but might be a slightly bigger issue now, because a big chunk of codes are being re-mapped?

If so I guess we either accept that, or devise some sort of legacy `bnf_map`?

**Comment by inglesp** [comment]
> Am I right in thinking this is because of the normalisation, i.e. joining with `ebmdatalab.hscic.bnf_map`, and that this has always been an issue, but might be a slightly bigger issue now, because a big chunk of codes are being re-mapped?

Yes.  Additionally, it also maps prescribing against a practice's current CCG membership.

> If so I guess we either accept that, or devise some sort of legacy `bnf_map`?

I'm not sure what a "legacy `bnf_map`" would look like.  We *could* add a `date` column to the `bnf_map` table, but that would make the SQL in the papers significantly fiddlier (and add a bit of maintenance burden to OP too).

There's a bigger question here about what we really mean by reproducibility, and what requirements that imposes on OP development -- could we add it to the agenda for the next DL day?

**Comment by alexwalkercebm** [comment]
An imperfect solution is to just create a frozen copy of any mapping as it exists now, and join to that in `normalised_prescribing_standard`, but that doesn't deal with past changes that have happened (which we weren't doing anything about previously anyway).

Definitely worth discussing at DL day, as it'll continue to be an issue with the new database.
