### ISSUE TITLE
Make time window clear and/or consistent

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#256]
In analysis:

 * Drug v. Drug numerator / denominator goes back to April 2013
 * Drug v. Patient List Size goes back to 2010

..and Measures go back to 2010.

78ed0cf183c39b16efc57d40f37c6e3aff153a67 restricts all analysis data to a rolling 5-year window.

Our Measures code uses only the *current* membership of a given practice to compare CCG performace. The analysis code uses the membership of a practice at the time of the prescription. 

Decide on if/how to resolve this and include an explanation in our documentation somewhere.

**Comment by sebbacon** [comment]
Places which code could touch:
* Views calculation in bigquery
* Smoketest amount-of-months calculation
* Measures calculations
* API where it touches on list sizes

**Comment by HelenCEBM** [comment]
Think this is no longer an issue
