### ISSUE TITLE
Discrepancy between QoF ACE Inhibitor Lists and our dm+d browser

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2560]
I was compiling a reference code list of Renin Angiotensin drugs (RAAS e.g. ACE inhibtors, ramipril etc) for research. I used the following SQL in BQ to generate a list

```
WITH bnf_codes AS (
  SELECT bnf_code FROM hscic.presentation WHERE bnf_code LIKE '020505%'
)

SELECT "vmp" AS type, id, bnf_code, nm
FROM dmd.vmp
WHERE bnf_code IN (SELECT * FROM bnf_codes)

UNION ALL

SELECT "amp" AS type, id, bnf_code, descr
FROM dmd.amp
WHERE bnf_code IN (SELECT * FROM bnf_codes)

ORDER BY type, bnf_code, id
```

This returns 1964 results at AMP/VMP level.

For validation I pulled out the [QoF business rules for 2020 v44](https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-collections/quality-and-outcomes-framework-qof/quality-and-outcome-framework-qof-business-rules/quality-and-outcomes-framework-qof-business-rules-v44-2019-2020-october-2020-release) to validate. One of the QoF points is for getting certain people on these RAAS medicines.  In the QoF rules it returns a different number of results, 2354 - a discrepancy of 390 products.

See this file here
[qofACE.xlsx](https://github.com/ebmdatalab/openprescribing/files/4379722/qofACE.xlsx)
 for differences which appears that excess results are AMPs in the dm+d which are marked as `unavailable`. 

In interests of time - have quick discussion with @inglesp about this to see I have done it right

**Comment by inglesp** [comment]
Have reformatted the SQL in the issue, hope that's OK.

I'm a bit confused by the spreadsheet -- the last line contains


Concept ID QOF | Code description | id OP | nm
-- | -- | -- | --
9810811000001102 | Lisinopril 20mg tablets (Almus Pharmaceutical   Ltd) (product)

which I interpret to mean that 9810811000001102 isn't in OP -- but [it is](https://openprescribing.net/dmd/amp/9810811000001102/), and it's in the results of the query.

Shall we chat?

**Comment by brianmackenna** [comment]
Apolgies - forgot how much you dislike BQ autoformatting!

In tab 2 of the excel sheet marked `diff` I think I have done is referenced QoF codes and returned `False` where it does not appear it OP list.

but it gives 420 results while the pure number diff is 390

**Comment by inglesp** [comment]
I've found 1933 records in both, 31 only in dm+d, and 421 only in QoF.

**Comment by inglesp** [comment]
I've found 1933 records in both, 31 only in dm+d, and 421 only in QoF.

<details>
<summary>SQL</summary>

```
WITH qof_records AS (
  SELECT Cluster_ID AS cluster_id, Concept_ID AS snomed_code, Code_description AS qof_name
  FROM qof.expanded_clusters_v44
  WHERE Cluster_description IN ('Angiotensin-converting enzyme (ACE) inhibitor prescription codes', 'Angiotensin II receptor blockers (ARB) prescription codes')
),

dmd_records AS (
  SELECT "vmp" AS type, id AS snomed_code, bnf_code, nm AS dmd_name
  FROM dmd.vmp
  WHERE bnf_code LIKE '020505%'

  UNION ALL

  SELECT "amp" AS type, id AS snomed_code, bnf_code, descr AS dmd_name
  FROM dmd.amp
  WHERE bnf_code LIKE '020505%'
)

SELECT "qof_only", COUNT(*)
FROM qof_records LEFT JOIN dmd_records USING(snomed_code)
WHERE dmd_name IS NULL

UNION ALL

SELECT "dmd_only", COUNT(*)
FROM qof_records RIGHT JOIN dmd_records USING(snomed_code)
WHERE qof_name IS NULL

UNION ALL

SELECT "both", COUNT(*)
FROM qof_records INNER JOIN dmd_records USING(snomed_code)
```
</details>

**Comment by inglesp** [comment]
Of the 421 that are only in QoF, only 4 have BNF codes, and these are all in [2.6.2 (Calcium-Channel Blockers)](https://openprescribing.net/bnf/020602/) (not 2.5.5 where all the others are).


Row | snomed_code | cluster_id | qof_name | bnf_code |  
-- | -- | -- | -- | -- |
1 | 11160111000001107 | AII_COD | Valsartan 160mg / Amlodipine 10mg tablets (product) | 0206020Z0AAACAC |  
2 | 11160211000001101 | AII_COD | Valsartan 160mg / Amlodipine 5mg tablets (product) | 0206020Z0AAABAB |  
3 | 11160311000001109 | AII_COD | Valsartan 80mg / Amlodipine 5mg tablets (product) | 0206020Z0AAAAAA |  
4 | 11160711000001108 | AII_COD | Exforge 10mg/160mg tablets (Novartis Pharmaceuticals UK Ltd) (product) | 0206020Z0BBACAC |  


<details>
<summary>SQL</summary>

```
WITH qof_records AS (
  SELECT Cluster_ID AS cluster_id, Concept_ID AS snomed_code, Code_description AS qof_name
  FROM qof.expanded_clusters_v44
  WHERE Cluster_description IN ('Angiotensin-converting enzyme (ACE) inhibitor prescription codes', 'Angiotensin II receptor blockers (ARB) prescription codes')
),

dmd_records AS (
  SELECT "vmp" AS type, id AS snomed_code, bnf_code, nm AS dmd_name
  FROM dmd.vmp
  WHERE bnf_code LIKE '020505%'

  UNION ALL

  SELECT "amp" AS type, id AS snomed_code, bnf_code, descr AS dmd_name
  FROM dmd.amp
  WHERE bnf_code LIKE '020505%'
),

qof_only_records AS (
  SELECT qof_records.*
  FROM qof_records LEFT JOIN dmd_records USING(snomed_code)
  WHERE dmd_name IS NULL
),

dmd_products AS (
  SELECT "vmp" AS type, id AS snomed_code, nm, bnf_code, NOT (non_avail IS NULL OR non_avail != 1) AS unavailable FROM dmd.vmp
  UNION ALL
  SELECT "AMP" AS type, id AS snomed_code, descr, bnf_code, NOT (avail_restrict IS NULL OR avail_restrict != 9) AS unavailable FROM dmd.amp
)

SELECT snomed_code, cluster_id, qof_name, bnf_code
FROM qof_only_records
LEFT JOIN dmd_products 
  USING(snomed_code)
WHERE bnf_code IS NOT NULL
```
</details>

**Comment by inglesp** [comment]
I can't see anything obvious that connects the 31 that are only in dm+d.


Row | snomed_code | type | bnf_code | dmd_name | unavailable |  
-- | -- | -- | -- | -- | -- |
1 | 425960005 | vmp | 0205053A0AAAAAA | Aliskiren 150mg tablets | false |  
2 | 425669009 | vmp | 0205053A0AAABAB | Aliskiren 300mg tablets | false |  
3 | 37422511000001107 | amp | 0205052A0AAAAAA | Irbesartan 150mg / Hydrochlorothiazide 12.5mg tablets (DE Pharmaceuticals) | false |  
4 | 37422711000001102 | amp | 0205052A0AAABAB | Irbesartan 300mg / Hydrochlorothiazide 12.5mg tablets (DE Pharmaceuticals) | false |  
5 | 37422911000001100 | amp | 0205052A0AAACAC | Irbesartan 300mg / Hydrochlorothiazide 25mg tablets (DE Pharmaceuticals) | false |  
6 | 37609411000001108 | amp | 0205052B0AAAAAA | Olmesartan medoxomil 10mg tablets (DE Pharmaceuticals) | false |  
7 | 37609611000001106 | amp | 0205052B0AAABAB | Olmesartan medoxomil 20mg tablets (DE Pharmaceuticals) | false |  
8 | 37610111000001106 | amp | 0205052B0AAACAC | Olmesartan medoxomil 40mg tablets (DE Pharmaceuticals) | false |  
9 | 37845711000001103 | amp | 0205052C0AAACAC | Candesartan 8mg tablets (Bristol Laboratories Ltd) | false |  
10 | 37554811000001108 | amp | 0205052C0AAACAC | Candesartan 8mg tablets (Lupin Healthcare (UK) Ltd) | false |  
11 | 37555411000001107 | amp | 0205052C0AAADAD | Candesartan 16mg tablets (Lupin Healthcare (UK) Ltd) | false |  
12 | 37559311000001103 | amp | 0205052C0AAAHAH | Candesartan 32mg tablets (Lupin Healthcare (UK) Ltd) | false |  
13 | 37265611000001105 | amp | 0205052I0AAAAAA | Irbesartan 75mg tablets (Zentiva) | false |  
14 | 37266311000001105 | amp | 0205052I0AAABAB | Irbesartan 150mg tablets (Zentiva) | false |  
15 | 37266511000001104 | amp | 0205052I0AAACAC | Irbesartan 300mg tablets (Zentiva) | false |  
16 | 37822211000001103 | amp | 0205052Q0AAAAAA | Telmisartan 40mg tablets (DE Pharmaceuticals) | false |  
17 | 37822411000001104 | amp | 0205052Q0AAABAB | Telmisartan 80mg tablets (DE Pharmaceuticals) | false |  
18 | 37821911000001101 | amp | 0205052Q0AAACAC | Telmisartan 20mg tablets (DE Pharmaceuticals) | false |  
19 | 37819711000001105 | amp | 0205052R0AAAAAA | Telmisartan 40mg / Hydrochlorothiazide 12.5mg tablets (DE Pharmaceuticals) | false |  
20 | 37820211000001104 | amp | 0205052R0AAABAB | Telmisartan 80mg / Hydrochlorothiazide 12.5mg tablets (DE Pharmaceuticals) | false |  
21 | 37820811000001103 | amp | 0205052R0AAACAC | Telmisartan 80mg / Hydrochlorothiazide 25mg tablets (DE Pharmaceuticals) | false |  
22 | 37906011000001109 | amp | 0205052Y0AAABAB | Olmesartan medoxomil 20mg / Hydrochlorothiazide 25mg tablets (Thornton & Ross Ltd) | false |  
23 | 37906511000001101 | amp | 0205052Y0AAACAC | Olmesartan medoxomil 40mg / Hydrochlorothiazide 12.5mg tablets (Thornton & Ross Ltd) | false |  
24 | 11960911000001108 | amp | 0205053A0BBAAAA | Rasilez 150mg tablets (Noden Pharma DAC) | false |  
25 | 11961711000001103 | amp | 0205053A0BBABAB | Rasilez 300mg tablets (Noden Pharma DAC) | false |  
26 | 37259911000001107 | amp | 0205051K0AAAAAA | Lisinopril 20mg / Hydrochlorothiazide 12.5mg tablets (Mawdsley-Brooks & Company Ltd) | true |  
27 | 37502111000001104 | amp | 0205052Q0AAABAB | Telmisartan 80mg tablets (Mawdsley-Brooks & Company Ltd) | true |  
28 | 37142711000001104 | amp | 0205052R0AAABAB | Telmisartan 80mg / Hydrochlorothiazide 12.5mg tablets (Mawdsley-Brooks & Company Ltd) | true |  
29 | 37271211000001102 | amp | 0205052V0AAAAAA | Valsartan 40mg capsules (Mawdsley-Brooks & Company Ltd) | true |  
30 | 37271411000001103 | amp | 0205052V0AAABAB | Valsartan 80mg capsules (Mawdsley-Brooks & Company Ltd) | true |  
31 | 37905011000001100 | amp | 0205052Y0AAAAAA | Olmesartan medoxomil 20mg / Hydrochlorothiazide 12.5mg tablets (Thornton & Ross Ltd) | true |  

<details>
<summary>SQL</summary>

```
WITH qof_records AS (
  SELECT Cluster_ID AS cluster_id, Concept_ID AS snomed_code, Code_description AS qof_name
  FROM qof.expanded_clusters_v44
  WHERE Cluster_description IN ('Angiotensin-converting enzyme (ACE) inhibitor prescription codes', 'Angiotensin II receptor blockers (ARB) prescription codes')
),

dmd_records AS (
  SELECT "vmp" AS type, id AS snomed_code, bnf_code, nm AS dmd_name
  FROM dmd.vmp
  WHERE bnf_code LIKE '020505%'

  UNION ALL

  SELECT "amp" AS type, id AS snomed_code, bnf_code, descr AS dmd_name
  FROM dmd.amp
  WHERE bnf_code LIKE '020505%'
),

dmd_only_records AS (
  SELECT dmd_records.*
  FROM qof_records RIGHT JOIN dmd_records USING(snomed_code)
  WHERE qof_name IS NULL
),

dmd_products AS (
  SELECT id AS snomed_code, NOT (non_avail IS NULL OR non_avail != 1) AS unavailable FROM dmd.vmp
  UNION ALL
  SELECT id AS snomed_code, NOT (avail_restrict IS NULL OR avail_restrict != 9) AS unavailable FROM dmd.amp
)

SELECT *
FROM dmd_only_records
LEFT JOIN dmd_products
  USING(snomed_code)
```
</details>

**Comment by inglesp** [comment]
Attached is a CSV with all VMPs in 2.5.2 and all their AMPs.  It's got a `.csv.txt` extension because GitHub is weird.  Remove the `.txt` and you'll be able to open it in Excel etc.

[para-2.5.2.csv.txt](https://github.com/ebmdatalab/openprescribing/files/4380186/para-2.5.2.csv.txt)

**Comment by brianmackenna** [comment]
Some discrepancies can be explained by
*31 only in dm+d*
Aliskerin: this is only licensed for _Essential hypertension either alone or in combination with other antihypertensives_ . The Qof rules is concerned with heart failure so likely excluded.

*421 only in QoF*
4 with BNF codes: these are combination products with calcium channel blockers and are in a seperate section in BNF. [Prescribing is circa 22,000 scripts](https://openprescribing.net/analyse/#org=CCG&numIds=0206020Z0AAACAC,0206020Z0AAABAB,0206020Z0AAAAAA,0206020Z0BBACAC&denom=nothing&selectedTab=summary) annually so a fair chunk and need to be included.

Others for investigation at later date. It could be new AMPs since QoF list was generated - Some look like [Ghost Branded Generics](https://ebmdatalab.net/ghost-branded-generics-why-does-the-cost-of-generic-atorvastatin-vary%EF%BB%BF/) and I wouldn't expect many Rxs on it.

**Comment by alexwalkercebm** [comment]
The chemical code `0206020Z0` picks up 6 presentations, two of which aren't in the table above, which is odd, but it doesn't look like their inclusion is an issue.

![image](https://user-images.githubusercontent.com/24895935/77547684-6c120180-6ea5-11ea-88d7-f29afb60cabe.png)
