### ISSUE TITLE
Ghost Branded Generics: follow-up questions

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2565]
Follow up questions from the merge of the new Ghost Branded Generics code (#2563). These can be looked at in the post-Covid era, but I wanted to capture them here so we don't lose track entirely.

Questions:
1. How are negative savings possible? Can you sometimes get a generic at less than the tariff price by specifying a manufacturer? That seems weird if so, but we should try to confirm.
2. Assuming they are possible, should we exclude them when calculating total available savings, as we do for PPU?
3. To what extent is the [fractional quantities](https://github.com/ebmdatalab/openprescribing/issues/1764) issue still an issue with the One Drug Database data?
4. If it is still an issue, can we be any more systematic in identifying and excluding affected presentations (rather than just a fixed list of exclusions where we've happened to notice a problem).
5. Can we be any more systematic in identifying presentations where quantity means packs, rather than ml, grams etc? (This issue also affects PPU and NCSO). Can we identify presentations where there's inconsistency i.e. quantity is sometimes recorded in packs and sometimes not?

**Comment by brianmackenna** [comment]
quickly
1. It is possible - this is how "branded generics" incentivise CCGs. They are brands less than tariff price but in case of GBG the "brand" looks like a generic to human eye.
2. Seems unfair to exclude them from a measure of GBGs. You win some you lose some!

**Comment by evansd** [comment]
@brianmackenna Brilliant, make sense. Thanks!
