### ISSUE TITLE
Slow sort query

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#259]
This query sometimes takes more than 8 seconds:

```sql
SELECT
  pr.pct_id AS row_id,
  pc.name AS row_name,
  pr.processing_date AS date,
  SUM(pr.cost) AS actual_cost,
  SUM(pr.items) AS items,
  SUM(pr.quantity) AS quantity
FROM
  vw__chemical_summary_by_ccg pr
JOIN
  frontend_pct pc
ON
  pr.pct_id=pc.code
  AND pc.org_type='CCG'
WHERE
  (pr.chemical_id LIKE '23%' )
GROUP BY
  pr.pct_id,
  pc.code,
  date
ORDER BY
  date,
  pr.pct_id
```

Here's the output of `EXPLAIN ANALYZE`:

![image](https://cloud.githubusercontent.com/assets/211271/20967177/f0fdc61c-bc75-11e6-8b85-e9264c7b5c86.png)

**Comment by sebbacon** [comment]
The quicksort of 1.2m rows seems to be the thing taking the time. It uses 220Mb memory. I'm surprised the sort takes that long.

Seeing if an index on those columns helps:

```sql
create index idx_vw__chem_on_pct_date on vw__chemical_summary_by_ccg using  btree (processing_date, pct_id);```

**Comment by sebbacon** [comment]
Apparently not. Next step: delete that index, and [swat up properly on sort](https://madusudanan.com/blog/all-you-need-to-know-about-sorting-in-postgres/)

**Comment by HelenCEBM** [comment]
Any update @sebbacon ?
