### ISSUE TITLE
Error loading measures for a practice

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#263]
from @lmfrench:

> I'm trying to load https://openprescribing.net/practice/Y02873/ but it is stuck on fetching data, have picked another practice (https://openprescribing.net/practice/F81016/) and that one is loading - have tried both chrome & IE

**Comment by sebbacon** [comment]
The problem is that measures are occasionally returning invalid JSON containing the token `Inifinity` for `calc_value`.

In this case, practice `Y02873` has such a value in 2010-10-01 for the `celecoxib` measure.

**Comment by sebbacon** [comment]
In fact, it seems that the API is *not* returning Infinity:

```sh
$ curl 'https://openprescribing.net/api/1.0/measure_by_practice/?format=json&org=Y02873' -s --compressed | jq '.measures[]|select(.id == "celecoxib")|.data[]|select(.date == "2010-10-01")'
{
  "percentile": 0,
  "cost_savings": null,
  "practice_name": "COMPASS HEALTH",
  "calc_value": 0,
  "date": "2010-10-01",
  "denominator": 3,
  "numerator": 0,
  "practice_id": "Y02873"
}
```

**Comment by sebbacon** [comment]
I was checking the wrong measure -- I should have been looking at `ktt9_antibiotics`:

```sh
$ curl 'https://openprescribing.net/api/1.0/measure_by_practice/?format=json&org=Y02873' -s --compressed | jq '.measures[]|select(.id == "ktt9_antibiotics")|.data[]|select(.date == "2010-10-01")'
{
  "percentile": 99.664637933176,
  "cost_savings": null,
  "practice_name": "COMPASS HEALTH",
  "calc_value": 1.7976931348623157e+308,
  "date": "2010-10-01",
  "denominator": 0,
  "numerator": 17,
  "practice_id": "Y02873"
}
```

**Comment by sebbacon** [comment]
This happens where we have a non-zero numerator and zero denominator.

To fix the proximate bug:

* [ ] review code that produces practice_data_ktt9_antibiotics BigQuery interim table. When we have a non-zero numerator and zero denominator, it should return None, not Infinity (see #175 for discussion)
* [ ] delete data prior to 2011-09-01 (this isn't strictly about this issue, but we've agreed to 5 year rolling windows for all data, and there's bad data from before that date)

However, there's an underlying issue to investigate too, because having a zero denominator here implies that there was prescribing in chapter 0501 in Oct 2010, but a zero value for oral antibiotics STARPU.

**Comment by lmfrench** [comment]
Probably not relevant to the error, but the reason I was checking was we had the following query in doorbell:

'Please could you exclude Compass Health (Y02873) from Bristol CCG. This is an APMS practice with a tiny list size and it skews all of our practice level graphs.'

Might be the tiny list size that is the problem for the STARPU in 2010? (it opened in 2009, is a GP practice for the homeless)

APMS practices = Alternative Provider Medical Services (APMS) contracts - means it isn't run by the NHS (normally this means a private company runs it, but not always)

**Comment by sebbacon** [comment]
I have a fix for this but won't be able to deploy til Mon.

Not worked out where the missing list size data is.  I have confirmed there is prescribing in the months where we have a list size of zero.

```sql
SELECT
  p.month,
  total_list_size,
  COUNT(items) AS count
FROM
  ebmdatalab.hscic.prescribing AS p
JOIN
  ebmdatalab.hscic.practice_statistics s
ON
  p.practice = s.practice and p.month = s.month
WHERE
  p.practice = 'Y02873' 
GROUP BY
  p.month,
  total_list_size
ORDER BY
  p.month
```
![image](https://cloud.githubusercontent.com/assets/211271/21053120/e3b6afae-be1f-11e6-8b35-f72e150e76f6.png)

**Comment by lmfrench** [comment]
Might be that there were less than 100 people registered at the practice on those dates, so the data isn't really missing we just can't have it:
https://data.gov.uk/dataset/numbers_of_patients_registered_at_a_gp_practice
'GP Practices with 100 or fewer registered patients have been suppressed due to possible identification of individuals when data is linked to other data sets.'

**Comment by richiecroker** [comment]
Yep, this is likely for a practice that doesn't have a "real" list size.  When we apply for a "spurious code" for these, the list size is usually made up, and between 1-100.  Ours (Clock Tower) is for homeless patients.

**Comment by richiecroker** [comment]
From [NHSBSA](http://www.nhsbsa.nhs.uk/PrescriptionServices/3972.aspx):
Please note that a relevant prescribing budget (per annum) and patient list size (per quarter) must be assigned to a new GP practice or cost centre within a CCG. These can be nominal figures and, in the respect of a new service/clinic (where patients may be registered elsewhere), we advise that the patient list size does not exceed 100 patients per quarter.

**Comment by sebbacon** [comment]
OK, so does that mean we should always provide a calculated value of zero where the list size is 100 or less?

**Comment by richiecroker** [comment]
I would say so, as any practice with <100 patients probably isn't a normal GP practice!

**Comment by lmfrench** [comment]
The other question is whether we should be including those practices on the CCG averages - the reason the user asked about that practice is because they wanted it excluded

**Comment by richiecroker** [comment]
I would say not - as their prescribing tends to be more skewed than a normal practice

**Comment by richiecroker** [comment]
Historically I have always excluded Clock Tower from any comparisons.
