### ISSUE TITLE
Problems with new measures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#267]
Problems noticed so far:

* Some have broken HTML. Example: [dipyridamole](http://staging.openprescribing.net/measure/dipyridamole/), where the fix would be to add in a missing close-tag (angle bracket / greater-than-sign) in lines [12](https://github.com/ebmdatalab/openprescribing/blob/9a4d27f1daff8e78aca81f3926da5a79669c868f/openprescribing/frontend/management/commands/measure_definitions/dipyridamole#L12) and [14](https://github.com/ebmdatalab/openprescribing/blob/9a4d27f1daff8e78aca81f3926da5a79669c868f/openprescribing/frontend/management/commands/measure_definitions/dipyridamole#L14)
* Others have broken SQL. Example: [pregabalin](http://staging.openprescribing.net/measure/pregabalin/) has an extra leading zero in the numerator condition which means every numerator is coming out as zero.

@richiecroker, I've pulled your changes across to [this branch](https://github.com/ebmdatalab/openprescribing/tree/20-new-measures) in the main repository, so you'll want to go there to make subsequent edits (rather than the `patch-1` branch created automatically for you when you were originally editing).

**Comment by HelenCEBM** [comment]
on the quietiapine measure, "The _extended_ release preparations should ideally be reserved for patients who cannot tolerate the IR version or for whom compliance may be an issue.".... but we are measuring the _immediate_ release ones and only getting average around 2% of total quietiapine prescribing... seems low? why aren't we measuring the extended one instead, being the one that should be avoided?

**Comment by richiecroker** [comment]
@sebbacon I can't find the files in that branch.  Can you help please?

**Comment by sebbacon** [comment]
https://github.com/ebmdatalab/openprescribing/tree/20-new-measures/openprescribing/frontend/management/commands/measure_definitions

**Comment by richiecroker** [comment]
OK, so far:

Repaired HTML code in dipyridamole
Repaired BNF code in pregabalin
Repaired summing error in IM quetiapine
