### ISSUE TITLE
Old CCGs not marked as closed in eccg.csv

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2704]
In April 2020 there was a large reordering of CCGs, but several CCGs which have merged into others are not marked as closed in eccg.csv.

This has a number of effects:

* They obscure what's going on on the analyse choropleth
* They are listed on the CCG page
* The CCG page does not indicate that the CCG is closed, only that it has no practices

**Comment by inglesp** [comment]
This has probably also broken the orphan practice detection code.

**Comment by inglesp** [comment]
We can identify CCGs with open practices with:

```
select distinct ccg_id from frontend_practice where setting = 4 and close_date is null;
```

I propose to update all CCGs without a close date that are not in this set, and mark them as having closed on April 1st 2020.

**Comment by inglesp** [comment]
We'll chase up NHSD, and revisit on the next monthly import.

**Comment by evansd** [comment]
The sounds like a sensible way forward.

**Comment by inglesp** [comment]
I ran:

```
update frontend_pct
set close_date = '2020-03-31'
where org_type = 'CCG'
  and  close_date is null
  and code not in (
    select distinct ccg_id
    from frontend_practice
    where setting = 4
      and close_date is null
  );
```
