### ISSUE TITLE
Set up database access for team

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#278]
Initially so @richiecroker can query measures data directly.

**Comment by sebbacon** [comment]
I've shared the credentials with @richiecroker using LastPass.

To query the database you'll want a SQL database explorer for Windows. I use [this one](https://www.postgresql.org/ftp/pgadmin3/pgadmin4/v1.1/windows/).

Then, to connect, use the details in the LastPass note.

To get the global monthly totals for a measure, do something like:

```sql
select 
 * 
from 
  frontend_measureglobal 
where 
  measure_id = 'ace';
```

To get the individual data for a CCG, do this:

```sql
select 
  * 
from
   frontend_measurevalue
 where
  measure_id = 'ace'
   and pct_id = '99P'
   and practice_id IS NULL;
```

To get the individual data for a practice:

```sql
select 
  * 
from
   frontend_measurevalue
 where
  measure_id = 'ace'
  and practice_id = 'B84021';
```

Be careful not to do any expensive queries like ```select * from frontend_measurevalue```!

**Comment by HelenCEBM** [comment]
Please could you clarify how the pricing works for this tool, and where to find the LastPass note?
Thanks!

**Comment by sebbacon** [comment]
"how the pricing works for this tool" - it's our database, we can run whatever queries we want against it. If you want to query the prescribing table, though, you should restrict to a single month of data.
