### ISSUE TITLE
Feedback form: error 500

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2813]
Sending feedback via the form prompts a server 500 error. It isn't critical as thre is an email contact but very annoying for users I imagine.

![image](https://user-images.githubusercontent.com/40460354/92083912-9655dc80-edbe-11ea-933d-27fbbae2d8c8.png)

**Comment by inglesp** [comment]
This is caused by our Mailgun account being suspended.  (This is the same problem that caused sending the NCSO alerts to fail last night.)

**Comment by evansd** [comment]
Account is now unsuspended.
