### ISSUE TITLE
Use more timely datasets

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#282]
* [This prescribing data](https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=124) is released monthly 
* [This patient list data](http://content.digital.nhs.uk/article/2021/Website-Search?productid=22190&q=Numbers+of+Patients+Registered+at+a+GP+Practice&sort=Relevance&size=10&page=1&area=both#top) is released much more promptly than the other source we use

Used together, we should be able to get data 6 weeks after the end of every month, up to 3 weeks sooner that currently possible (and more like 6 or 7 weeks sooner on a new quarter, due to the delay in list size data on the current source)

**Comment by sebbacon** [comment]
* [ ] Map out the three data formats (table in our database, BQ table, new dataset)
* [ ] Think about quickest way to convert and store the new dataset
* [ ] Integrate this into current data importing regime
* [ ] Write a new importer for list sizes that converts to the version we use

**Comment by sebbacon** [comment]
## Mapping the data formats

* Raw, old CSV: `SHA, PCT, PRACTICE, BNF CODE, BNF NAME, ITEMS, NIC, ACT COST ,QUANTITY, PERIOD`
* Converted CSV: `SHA, PCT, PRACTICE, chemical, BNF CODE, BNF NAME,ITEMS,ACT COST ,QUANTITY, PERIOD`
* New CSV: `Regional Office Name,Regional Office Code,Area Team Name,Area Team Code,PCO Name,PCO Code,Practice Name,Practice Code,BNF Code,BNF Description,Items,Quantity,ADQ Usage,NIC,Actual Cost`
* local postgres table: 
```sql
CREATE TABLE public.frontend_prescription
(
  id integer NOT NULL DEFAULT nextval('frontend_prescription_id_seq'::regclass),
  presentation_code character varying(15) NOT NULL,
  presentation_name character varying(1000) NOT NULL,
  total_items integer NOT NULL,
  actual_cost double precision NOT NULL,
  quantity double precision NOT NULL,
  processing_date date NOT NULL,
  chemical_id character varying(9) NOT NULL,
  pct_id character varying(3) NOT NULL,
  practice_id character varying(6) NOT NULL,
  sha_id character varying(3) NOT NULL
)```

**Comment by sebbacon** [comment]
The current route is:
* Download and unzip the data
* Push it to GCS
* Transform it locally
* Load transformed version to posgres
* Transform GCS with Cloud SQL to append to cloud table

The route from the new CSV is:

* Download and unzip the data
* Push it to GCS
* Query it to transform it to the format we want (can we do all the transformation in SQL?)
* Download that and store to postgres
* Drop the chemical column and append that to the main BigQuery table

**Comment by sebbacon** [comment]
So, to test the process, I've manually:
* uploaded November's "new" data [here](https://console.cloud.google.com/storage/browser/ebmdatalab/hscic/prescribing/2017_02/?project=ebmdatalab)
* created a BigQuery table that queries that as an external data source [here](https://bigquery.cloud.google.com/table/ebmdatalab:tmp_eu.foo)
* Run this query against the "new" data:
```sql
SELECT
  BNF_Description AS presentation_name,
  SUM(Items) AS total_items,
  SUM(Quantity) AS quantity,
  SUM(NIC) AS net_cost
FROM
  [ebmdatalab:tmp_eu.foo]
WHERE
  Practice_Code = 'J82116'
GROUP BY
  presentation_name
ORDER BY
  presentation_name
```
* And run this query against the old data:
```sql
SELECT
  bnf_name,
  items,
  quantity,
  net_cost
FROM
  [ebmdatalab:hscic.prescribing]
WHERE
  practice = 'J82116'
  AND month = TIMESTAMP('2016-11-01')
ORDER BY
  bnf_name
```

I've found that the items and net_cost almost always  match up, but only 42% of the quantities match up.  The quantities are almost always smaller - frequently a fraction such as 1.2, 1/3, 1/7.

This suggests something related to the quantities mismatch we've seen previously.

**Comment by HelenCEBM** [comment]
I think the new dataset has each possible `quantity` separated out, ie. if a single presentation was doled out as 10 tabs in one case and 20 tabs in another, these will appear as two separate lines. So we need to multiply `items` by `quantity` in the new data, in order to match up with the `quantity` in the old data.

**Comment by sebbacon** [comment]
Note from @lmfrench: 

> Once the BSA finally release the list sizes for October we should check that none of the weird GP practices are missing from the NHS Digital list size. [BSA documentation](http://www.nhsbsa.nhs.uk/PrescriptionServices/5036.aspx
) says:
>> “Some of the "Practices" listed in the information are not traditional practices. They are other services which the PCO has set up as a practice ie specialist units or out of hours services These non-traditional practices do not have a patient list size or may not have a dedicated GP working for them.  In these situations the PCO may supply arbitrary numbers such as 1, 2, 50 etc.” 
> But the [NHS Digital documentation](http://content.digital.nhs.uk/catalogue/PUB22008/Data%20quality%20statement.pdf ) doesn’t mention this

**Comment by lmfrench** [comment]
Have checked practice codes in NHS Digital & BSA Dataset for October 16. The BSA have 4 practices not  in NHS Digital's dataset. NHS Digital have 33 practices not in the BSA data.

Have looked at how much prescribing has taken place in these practices.

Items for practices not in BSA Dataset (November 2016):
```sql
SELECT
  practice,
  SUM(items) AS items
    
FROM
  ebmdatalab.hscic.prescribing AS presc
   WHERE
  month = TIMESTAMP('2016-11-01')
  AND practice IN ('A81003','A82017','A82052','A83638','A86009','A89611','B82095','B85644','D82098','E82624','E82658','F82004','F82643','F84700','G81064','G81685','G82061','G82715','G83007','J81624','J82091','K82069','K84073','K84076','L83108','L83608', 'L85045','M86629','P84676','P89027','Y00079','Y02164','Y05021')

GROUP BY
practice

ORDER BY 
items
```
19/33 still prescribing
Min items (still prescribing): 1
Max items: 8435 items

Not in NHS Digital's dataset:
```sql
SELECT
  practice,
  SUM(items) AS items
    
FROM
  ebmdatalab.hscic.prescribing AS presc
   WHERE

  month = TIMESTAMP('2016-11-01')
  AND practice IN ('M85704','Y04894','Y01166','Y02128')

GROUP BY
practice

ORDER BY 
items
```
3/4 practices still prescribing
Min items (still prescribing): 31
Max items: 1496

I suspect NHS Digital keeps practices which have closed in their list size information longer than the BSA does e.g. even the practice prescribing 8435 items has merged with another practice https://openprescribing.net/practice/K82069/ - NHS Choices says 'Verney Close Surgery became part of The Swan Practice in July 2016. As a result some, of the information, which is updated by NHS England, is not yet showing. Please see our page for The Swan Practice - North End.' http://www.nhs.uk/Services/GP/Overview/DefaultView.aspx?id=125517

I am not sure why NHS Digital is missing M85704 (currently prescribing 1496 items). It doesn't appear to have shut
