### ISSUE TITLE
NumericValueOutOfRange on importing measure data

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#2847]
When importing the July 2020 prescribing data, we hit:

```
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 142, in handle
    self.build_measures(measure_defs, start_date, end_date, verbose, options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 119, in build_measures
    calcuation.calculate(options["bigquery_only"])
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 613, in calculate
    self.calculate_practices(bigquery_only=bigquery_only)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 631, in calculate_practices
    self.write_practice_ratios_to_database()
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 738, in write_practice_ratios_to_database
    cursor.copy_expert(copy_str % ", ".join(MEASURE_FIELDNAMES), f)
psycopg2.errors.NumericValueOutOfRange: integer out of range
CONTEXT:  COPY frontend_measurevalue, line 412988: "nimodipine,Y60,E54000016,05L,U45156,M88646,2016-04-01,0.0,2.075,0.0,0.0,"
```

`import_measures` downloads data from BQ and writes to a temporary CSV file, which it then tries to import into PG via `copy_expert`.

Have hacked `import_measures` to write the CSV to a non-temporary file (attached).

I can then reproduce the problem with:

```
from django.db import connection
from frontend.management.commands.import_measures import MEASURE_FIELDNAMES

with open("/tmp/nimodipine.csv") as f:
    copy_str = "COPY frontend_measurevalue(%s) FROM STDIN "
    copy_str += "WITH (FORMAT CSV)"
    with connection.cursor() as cursor:
        cursor.copy_expert(copy_str % ", ".join(MEASURE_FIELDNAMES), f)
```

However I cannot reproduce this locally.  (Locally I'm running 12.4, the server has 11.2.)

Next steps is to try to import the CSV line by line to see which line is problematic.

**Comment by inglesp** [comment]
Here's the CSV [nimodipine.zip](https://github.com/ebmdatalab/openprescribing/files/5260410/nimodipine.zip)

**Comment by inglesp** [comment]
> Next steps is to try to import the CSV line by line to see which line is problematic.

Every line seems to be problematic!  I've chosen several lines at random, and they all trigger the exception.

And I can reproduce without going via `copy_expert`:

```
>>> r = next(csv.reader(open("/tmp/nimodipine.csv")))
>>> r
['nimodipine', 'Y63', 'E54000049', '16C', 'U85008', 'A81009', '2018-02-01', '200.0', '8.74', '22.88329519450801', '99.87572493786246', '']
>>> kwargs = dict(zip(MEASURE_FIELDNAMES, r))
>>> kwargs
{'stp_id': 'E54000049', 'month': '2018-02-01', 'percentile': '99.87572493786246', 'numerator': '200.0', 'denominator': '8.74', 'pct_id': '16C', 'cost_savings': '', 'practice_id': 'A81009', 'pcn_id': 'U85008', 'measure_id': 'nimodipine', 'calc_value': '22.88329519450801', 'regional_team_id': 'Y63'}
>>> mv = MeasureValue(**kwargs)
>>> mv.save()
Traceback (most recent call last):
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range
```

None of the values in `kwargs` are large, and none of them are expected to be integers.

**Comment by inglesp** [comment]
Since we've created and deleted quite a lot of measure values over the years, a hunch is that we might have hit some kind of limit in Postgres.

```
# select max(id) from frontend_measurevalue;
┌────────────┐
│    max     │
├────────────┤
│ 2147070660 │
└────────────┘
```

2147070660 isn't anything very special, beyond being the phone number of a lawyer in Dallas.  2147070661 is a less interesting Dallas phone number.

But it's very close to 2147483647, which is the maximum size of a 4 byte signed int (and also probably a Dallas phone number).

Importing a lot of rows at once via `copy_expert` will have called `nextval('frontend_measurevalue_id_seq')` a lot of times, which would explain why this was first hit by some line halfway through the CSV file but is now hit for every line, and why I had not problem locally.

```
# select nextval('frontend_measurevalue_id_seq');
┌────────────┐
│  nextval   │
├────────────┤
│ 2147483659 │
└────────────┘
```

**Comment by inglesp** [comment]
The solution is probably to blow away the whole `frontend_measurevalue` table and reset `frontend_measurevalue_id_seq`, and then import the measures again.

**Comment by evansd** [comment]
Excellent sleuthing! Your diagnosis sounds exactly correct. I wonder in this case if we can get away with just resetting the sequence but not deleting anything. None of the existing rows will clash with the new low numbered IDs, and by the time we start generating large IDs again those rows will be long gone. And nothing has foreign keys pointing to them.

**Comment by inglesp** [comment]
That's worth a try.  I've just run `ALTER SEQUENCE frontend_measurevalue_id_seq RESTART;` and have restarted the pipeline.

**Comment by sebbacon** [comment]
Nice sleuthing indeed!

[Here](https://stackoverflow.com/a/24366594/559140) is a sensible-looking long-term solution

**Comment by inglesp** [comment]
A single run of `import_measures` has created 48863013 rows.  (I'm surprised this isn't a multiple of 60, and I'll take a quick look at that.)

This will give us space for 43 (= 2147483659 / 48863013) months.  Fingers crossed we'll be driving measures off the matrix store by then, but just in case have created a reminder to reset the index in September 2023.

**Comment by bloodearnest** [comment]
+1 for BIGINT serials, had to do this a few times before. Might take a few minutes, as it takes a table lock, but that's no issue here AIUI. 

If we need a longer term solution, we could explore a UUID, which removes the limit, and the cost of slower bulk insertion. Given bulk insert is kinda the whole ball game here AIUI, we might want to look at using a [ULID](https://github.com/geckoboard/pgulid) in that case, which generally does better on insert performance as is partially ordered.

obvious n00b question: do we need the surrogate key? Is there a reasonable unique tuple in the data we use instead?

**Comment by inglesp** [comment]
+1 for BIGINT serials

Yeah, if we still haven't implemented measures in the matrix store by 2027, let's do this!

> do we need the surrogate key?

Yes, I think Django expects one.

>  Is there a reasonable unique tuple in the data we use instead?

Yes: `(measure_id, month, practice_id, pcn_id, pct_id, stp_id, regional_team_id)` should be unique.

**Comment by inglesp** [comment]
48863013 = 61 * 9651.  Looks like we're create measure values for five years and one month.

**Comment by inglesp** [comment]
>  Fingers crossed we'll be driving measures off the matrix store by then, but just in case have created a reminder to reset the index in September 2023.

Oh.

There are now a lot of of undeleted preview measure values, so just resetting the index won't work.

So I've run (after checking with Rich):

```
DELETE FROM frontend_measurevalue WHERE measure_id LIKE 'preview_%';
ALTER SEQUENCE frontend_measurevalue_id_seq RESTART;
```

and have set another reminder for (gulp) September 2026.

**Comment by inglesp** [comment]
> and have set another reminder for (gulp) September 2026.

It is now September 2026.

```
# select max(id) from frontend_measurevalue;
┌────────────┐
│    max     │
├────────────┤
│ 2092849628 │
└────────────┘
```

So we're at about 95% capacity before we run out of numbers.

I'm going to create + document a management command that resets the sequence, and after discussion with @iaindillingham we'll set a reminder to do this annually so that we can build some kind of folk memory about what this is about.
