### ISSUE TITLE
Non-core measures showing on measures email

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#2886]
The email sent to subscribers includes "non-core" measures, including OME and nimodipine:

![image](https://user-images.githubusercontent.com/18683239/95341524-4632d400-08ae-11eb-97b3-c3387e2c19dd.png)

On investigation, the [nimodipine measure ](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/measure_definitions/nimodipine.json) has the `include_in_alerts` flag as `false`.

**Comment by sebbacon** [comment]
So I think, perhaps, we updated `include_in_alerts` flags in the JSON but never ran the command to update them in the database:

```python
>>> Measure.objects.get(pk="nimodipine").include_in_alerts
True
```
