### ISSUE TITLE
Possible error in denominators for PCN measures

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#2899]
There seems to be a disparity in the denominator for measures at PCN level between the site and both BQ and ePACT2.
e.g. https://openprescribing.net/pcn/U40115/measures/
![image](https://user-images.githubusercontent.com/18683239/97603660-93651a00-1a04-11eb-8e4e-94e865917da3.png)
shows denominator of 22.45 thousand for August 2020.

In comparison BQ returns 39268 patients: 
![image](https://user-images.githubusercontent.com/18683239/97603800-b2fc4280-1a04-11eb-9719-5a64166f3854.png)

and ePACT shows similar:

![image](https://user-images.githubusercontent.com/18683239/97603857-c0193180-1a04-11eb-8cbf-884eb942ebd3.png)

code for BQ list size:
```
select month, sum(total_list_size) as list_size
from hscic.practice_statistics as stats
inner join
hscic.practices as prac
on
stats.practice=prac.code
where
pcn_id = 'U40115'
group by month
order by month
```

**Comment by brianmackenna** [comment]
lol
