### ISSUE TITLE
Add hospitals to "area and practice dashboards"

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2909]
This will being users to a clean page/blog explaining our plans for openprescribing.net/hospitals

**Comment by inglesp** [comment]
You'll want to add `<li><a href="/link/to/blog">Hospitals</a></li>` to [this list](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/templates/base.html#L95-L102).

**Comment by brianmackenna** [comment]
https://openprescribing.net/hospitals/
