### ISSUE TITLE
Salbutamol Quantity Measure

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2910]
Had a quick idea for a new measure when we have time /resource for it.

**Quantity of salbutamol inhalers per patients on asthma/copd list**

There is rising concern with the overuse of salbutamol inhlaers and the [National Review of Asthma Deaths](https://www.rcplondon.ac.uk/projects/national-review-asthma-deaths) cited it specifically as a key thing to watch out for as a persons asthma was out of control and recommended systematic population monitoring. Ideally we'd do at a individual level but practice level monitoring may help support practices identify if there repeat med systems are leading to overprescribing of salbutamols.

Separately salbutamol MDIs are quite aharmful to the environment so we want to ensure no overprescribing or waste. This measure could be helful on our [Greener NHS dashboard](https://www.thedatalab.org/blog/2019/12/65/greener-nhs-prescribing-dashboards/).

**Comment by brianmackenna** [comment]
Discussed with @richiecroker  and we think this would be worthwhile exploring when we have time. @AnnaB45 Not for now but this might be a good one to help understand measure development, python, website etec.

**Comment by mattia-ficarelli** [comment]
Hi, my name is Mattia I am a Data Analyst working within the NHSX Analytics Unit. I would like to work on building the python script to ingest the data and process the quantity of salbutamol inhalers per patient on the asthma/COPD list at a CCG level. Is this the full BNF code list [HERE](https://www.opencodelists.org/codelist/user/brian-mackenna/salbutamol-inhalers/7ff72269/#full-list) for salbutamol inhalers? I'm struggling to find the data for the number of patients on the asthma/COPD list - would someone be able to direct me to it? I assume it is open access data? Thank you in advance for your time and support. @brianmackenna

**Comment by richiecroker** [comment]
we have created a prototype of this measure, and have decided that it wasn't of high enough quality to continue.
