### ISSUE TITLE
Maps not showing any context

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#2919]
CCG and practice maps are not showing any context around the shape/pin

E.g. https://openprescribing.net/ccg/78H/
![image](https://user-images.githubusercontent.com/24392156/100208194-5ce5c680-2f00-11eb-958c-6b1adeaee8d2.png)

![image](https://user-images.githubusercontent.com/24392156/100208178-57887c00-2f00-11eb-9a67-06f2f4b510a7.png)

**Comment by madwort** [comment]
mapbox tile requests return `"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"` -> 
https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

**Comment by inglesp** [comment]
Yes, see #2544.

**Comment by evansd** [comment]
Yeah, this has been on our radar for a while (see #2544) but E_NO_TIME...

**Comment by madwort** [comment]
closing as duplicate
