### ISSUE TITLE
Review ignored dependency upgrades now we're on Python 3.8

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2927]
As per https://github.com/ebmdatalab/openprescribing/issues/2103#issuecomment-558556893 we've had to ignore various dependency upgrades that weren't compatible with Python 3.5. Now we're running 3.8 we should review these.

#2245

Other unmerged dependency PRs:
https://github.com/ebmdatalab/openprescribing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+is%3Aunmerged+label%3Adependencies+comments%3A%3E1+updated%3A%3E%3D2019-11-27

**Comment by inglesp** [comment]
Have you seen the configuration in https://github.com/ebmdatalab/openprescribing/blob/master/.github/dependabot.yml?

**Comment by evansd** [comment]
Ah, I hadn't. I guess we just want to delete the entire "ignore" section?

**Comment by inglesp** [comment]
Worth a go.

**Comment by madwort** [comment]
I think this is done
