### ISSUE TITLE
Fix Dependabot CI

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/openprescribing#2959]
@dependabot-bot no longer has access to secrets for CI runs, so they fail (e.g. #2957 )
See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
Probably this is worth a read too: https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by madwort** [comment]
Also - dependabot "security updates" (which are different to "version updates") are currently failing to install e.g. https://github.com/ebmdatalab/openprescribing/security/dependabot/requirements.txt/django/open/update-logs/79578134 - this appears to be due to attempting to install scipy 1.4.1 on python 3.9, which I think doesn't have a wheel available and is failing to compile.

**Comment by benbc** [comment]
I've turned off dependabot alerts and dependabot security updates for this repo until this problem has been fixed.

**Comment by benbc** [comment]
@sebbacon I think that we should consider fixing this problem even though there is no active development on OpenPrescribing at the moment because Dependabot is our best safeguard against vulnerabilities caused by our dependencies.

**Comment by evansd** [comment]
Huge thread here on the issue: https://github.com/dependabot/dependabot-core/issues/3253 (with an [FAQ](https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544) at the end).

It seems like maybe we could do something with a `pull_request_target` workflow, but I haven't fully got my head around that.

**Comment by madwort** [comment]
this is indeed potentially a can of worms - for good security reasons, github has disabled forks having access to github actions secrets. However, dependabot runs from a fork & we need github actions secrets to run our CI. 
There's not an obvious way to square the circle, but there are different compromises. 

For instance - we could use `pull_request_target`, which would allow forks to access github actions secrets by running the actions with the permissions of the target rather than the head of the branch (i.e. the permissions of `origin/master` not  `fork/update`). However, this introduces a potential security hole - a compromised upstream dependency could automatically pwn our secrets before we knew about it (which in this case I think includes a key to access our old Google Compute account vms/dbs). Upstream dependencies do get pwned sometimes, but it's very rare, maybe we take the risk. At GitHub scale, they're worried about this, which is why it's under heavy development.

At the moment, for security updates / vulnerabilities, I've been re-running CI with my own permissions, but not for "version updates" - of which there are *a lot*.

**Comment by madwort** [comment]
> I've turned off dependabot alerts and dependabot security updates for this repo until this problem has been fixed.

This will not have the desired effect - these should both be turned back on and the dependabot version updates config changed in  https://github.com/ebmdatalab/openprescribing/blob/master/.github/dependabot.yml

**Comment by benbc** [comment]
Manual workaround for this problem is for a human to come along and trigger a re-run of the failed jobs, which gives them the necessary permissions.

**Comment by evansd** [comment]
This is fixed using https://github.com/ebmdatalab/openprescribing/settings/secrets/dependabot
