### ISSUE TITLE
Measure volume in DDDs or ADQs

### ISSUE THREAD

**Issue by stupidpupil** [ebmdatalab/openprescribing#3]
The [HSCIC's guide to Prescribing Measures](http://www.hscic.gov.uk/media/10952/Prescribing-Measures/pdf/CHttpHandler.pdf) says

> Historically, the number of items was used as a measure of volume. However, for  areas  of  prescribing  where  there  is  a  good  deal  of  repeat  prescribing,  the number of items can be misleading because different practices use a different duration  of  supply,  i.e.  some  will  issue  a  prescription  monthly,  others  for  two months  or  three  months  and  so  will  have  different  numbers  of  items  for  the same  amount  of  medication.  Even  within  a  single  practice  there  can  be differences  in  the  duration  of  prescriptions. 
> …
> The system of **Defined Daily Doses (DDDs)**, developed and maintained by the World  Health  Organisation  (WHO), attempts  to  overcome  these limitations.  In this  system  each  drug  is  given  a  value,  within  its  recognised  dosage  range, that  represents the  assumed  average  maintenance  dose  per  day  for  a  drug used for its main indication in adults. It is emphasised that the DDD is a unit of measurement;  it  is not a  recommended  dose  and  may  not  be  a  real  dose.
> …
> To  allow  comparison  of  prescribing  within  England  there  is  a  need  to  have  a system  which  more  accurately  reflects  primary  care  prescribing.  To  meet  this need  **Average  Daily  Quantities  (ADQs)**  have  been  developed  by  an  expert group convened by the PSU. 

ADQs and DDDs are commonly used in prescribing measures, indicators and comparators, both public and internal. They are generally supported, to some extent, by internal prescribing measurement applications like [_ePACT.net_](http://www.nhsbsa.nhs.uk/3230.aspx) (used in England) and _CASPA.net_ (used in Wales).

For these reasons it would be useful to support ADQs and/or DDDs in OpenPrescribing.
# Where can we find ADQs or DDDs?

**Defined Daily Doses (DDDs)** can be [looked individually up online](http://www.whocc.no/atc_ddd_index/). That states "Use of all or parts of the material requires reference to the WHO Collaborating Centre for Drug Statistics Methodology. Copying and distribution for commercial purposes is not allowed. Changing or manipulating the material is not allowed." (The German Institute of Medical Documentation and Information (DIMDI) makes [their own adaptation of the WHO DDDs](http://www.dimdi.de/static/en/klassi/atcddd/index.htm) 'freely' available.)

**Average Daily Quantities (ADQs)** can be found on the [HSCIC website](http://www.hscic.gov.uk/media/9376/Average-daily-quantity-ADQ-values-2012-13/pdf/adqs_2012_13.pdf). That document states "This work remains the sole and exclusive property of [HSCIC] and may only be reproduced where there is explicit reference to the ownership of The NHS Information Centre. Permission for reproducing this material must be sought in advance from The NHS Information Centre."

As can be seen, there are some intellectual property issues that need to be at least clarified before either of these sources can be used.
# How do we calculate volume in ADQs or DDDs?

There are two problems to be solved in order to calculate ADQs or DDDs:
1. Determining which, if any, ADQ/DDD applies to the Presentation.
2. Determining the amount of the Presentation _in the units_ of the ADQ/DDD.

In the case of DDDs, the first involves mapping BNF Presentations to codes in the [Anatomical Therapeutic Chemical Classification System](https://en.wikipedia.org/wiki/Anatomical_Therapeutic_Chemical_Classification_System). I am not aware of any freely available mapping. (See _The Detail_'s [report of prescribing](http://script-report.thedetail.tv/) for [an example of such mappings](http://script-report.thedetail.tv/static/rx/BNF%20ATC.html).)

In the case of ADQs, the first seems more straightforward. The HSCIC document linked above identifies that the relevant ADQ for a presentation usually depends only on the BNF Chemical and the route of administration. Some ADQs are more specific regarding the form of the presentation (aerosol vs. solution, for example) but the small number of relevant presentations could be identified manually.

I have opened #4 to look at how the given _BNF Name_ for a presentation might be used to extract both the route of administration and the amount in the units of the relevant ADQ.
# How do we make volume in ADQs or DDDs available?

Volume in ADQs or DDDs should be made available in the user interface and the API alongside the current measures of items and spend. This is complicated by the fact that not every presentation will have an ADQ or DDD defined and, as a consequence, it won't always be possible to measure volume in ADQs or DDDs for all of any Chapter, Section or even Chemical.

**Comment by annapowellsmith** [comment]
Thanks for this, really helpful. 

It sounds like the next steps are (i) to clarify the intellectual property issues (ii) to talk to our users about the priority of adding ADQs/DDDs, versus other things. 

We're going to be discussing new features in the new year.

In the meantime, I'll contact the NHS IC to see if they'd object in principle to us using ADQs. I'll ask them also if they know of any open data on units etc for BNF presentation codes. Will report back here. 

It sounds to me like using DDDs should be OK, since we're not commercial, and we're not changing the data.

**Comment by stupidpupil** [comment]
I've been told by Primary Care Services in NHS Wales that they hold a mapping between BNF presentation codes and their volume in ADQs (and possibly DDDs?), and that they think they can make this freely available. I've not had much in the way of details yet unfortunately.

**Comment by stupidpupil** [comment]
I've just noticed that the [Welsh data](http://www.primarycareservices.wales.nhs.uk/general-practice-prescribing-data-extrac) now seems to include pre-calculated ADQs and DDDs for each record.

(This is something that I discussed with the NHS Wales team involved a year ago but, since they never got back to me about it, I wonder if someone else asked for it as well..)
