### ISSUE TITLE
Alert email text for DOACs needs updating

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#301]
Feedback from user:

"By prescribing DOACs we are implementing NICE Technology Appraisals – which we should be doing. High Spend in this area is as a result of anticogulating people with AF at high risk of stroke. Please don’t describe this as a bad thing (‘worst’) – it’s just that everyone else needs to catch up. "

**Comment by lmfrench** [comment]
Had a chat with Rich - DOACs isn't the only measure that needs changing, will discuss in datalab day

**Comment by sebbacon** [comment]
Action: remove pregabalin and DOACS  to their own separate section in the alerts email. Wording provided by Ben via email.
