### ISSUE TITLE
Price per unit page logs errors for closed practices

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/openprescribing#3042]
We've recently started getting a lot of sentry.io notifications like this one: https://sentry.io/organizations/ebm-datalab/issues/2196049880/

It seems to be triggered by pages such as:
https://openprescribing.net/practice/C84632/price_per_unit/
https://openprescribing.net/practice/Y02608/price_per_unit/
https://openprescribing.net/practice/A82011/price_per_unit/

sending ajax requests such as
https://openprescribing.net/api/1.0/price_per_unit/?entity_code=A82011&date=2021-01-01&bnf_code=&aggregate=&entity_type=&format=json&_=1617889704107

They all happen to be closed practices - without having dug very far into it, I assume it's a  bug in the handling of closed practices that have been removed from the database / upstream datasets in some places & not others.

**Comment by sebbacon** [comment]
As PPU is never going to be useful for closed practices, just turning off PPU (by replacing PPU included template with a "not available for closed practices" message?) would be a fine solution, if it works

**Comment by sebbacon** [comment]
In the mean time, can/should we add some kind of suppression rules to Sentry for this error?

**Comment by evansd** [comment]
This has been annoying me too. I can fix it at the API level easily enough so I'll do that. The "missing practices trigger KeyError" behaviour was an inadvertent side effect of switching to the MatrixStore.

**Comment by madwort** [comment]
looks good, response is now e.g. `{"detail":"Unknown organisation ID: A82011"}`

**Comment by madwort** [comment]
Also fixes the same issue on the AJAX requests from e.g.  https://openprescribing.net/practice/F85643/ghost_generics/ - https://openprescribing.net/api/1.0/ghost_generics/?_=%2A%2A%2A%2A%2A%2A%2A%2A&date=2021-01-01&entity_code=F85643&entity_type=practice&format=json&group_by=presentation
