### ISSUE TITLE
Update CCG & GP Dashboard Text

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#315]
Remove text on dashboards that says:
'Over the past 6 months, this organisation has prescribed worse than the median on 5 of 14 measures.
The measure with the biggest potential for improvement was Dosulepin (KTT8), where this CCG was at the 90th percentile on average across the past 6 months.'

Replace this with text:
'These measures show only a small subset of the data available on OpenPrescribing. Use our [analyse page](https://openprescribing.net/analyse/) to ask your own questions of the data, and explore prescribing trends by [BNF section](https://openprescribing.net/bnf/) or [chemical](https://openprescribing.net/chemical/). You can also [compare CCG prescribing](https://openprescribing.net/measure/) for all of our measures'

**Comment by sebbacon** [comment]
I'd like to propose we just remove the text for the time being, and then A/B test adding the text at some point soonish.

null hypothesis: adding any text there is just noise and won't lead to increased exploration of our data through other means.

**Comment by lmfrench** [comment]
Yes agree!
