### ISSUE TITLE
Change antibiotic denominator to "all oral antibiotics"

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#3161]
Some of the abx measures have a very specific subset of antibiotics as denominator.  It is proposed that these markers are changed to reflect all oral abx in both numerator and denominator, using dm+d coding.

**Comment by chrisjwood16** [comment]
https://github.com/ebmdatalab/openprescribing/pull/4603
https://github.com/ebmdatalab/openprescribing/pull/4604
https://github.com/ebmdatalab/openprescribing/pull/4605

**Comment by chrisjwood16** [comment]
Ready to merge.
To discuss before merging:
https://github.com/ebmdatalab/openprescribing/pull/4604 - should the denominator change STAR-PU to list_size?
Do spot the difference blogs need to change?

**Comment by chrisjwood16** [comment]
https://github.com/ebmdatalab/openprescribing/pull/4603 - Updated - needs decision on denominator - STAR-PU vs list size.
https://github.com/ebmdatalab/openprescribing/pull/4604 - Updated - needs decision on denominator - STAR-PU vs list size.
https://github.com/ebmdatalab/openprescribing/pull/4605 - Updated

**Comment by richiecroker** [comment]
@richiecroker - remove STAR-PUs from analyse page

**Comment by richiecroker** [comment]
[ } Add proposal to summer newsletter
[ ] Action with June data import, if no noise.

**Comment by chrisjwood16** [comment]
Measures have been updated.

Outstanding:
- [ ] Remove STAR-PU from analyse page
- [ ] Remove STAR-PU from FAQs (or better yet - explain why we stopped using them)

**Comment by chrisjwood16** [comment]
Final actions covered in separate issue -https://github.com/ebmdatalab/clinical_info_projects/issues/81
