### ISSUE TITLE
Youtube Video Front Page

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3190]
The video on the front page is broken. It's not a video owned by the DataLab account - I think it's probably held in @Bengoldacre account but it doesn't appear on youtube search. 

https://www.youtube.com/embed/U-hvuEfUUOM

It was a very old video so maybe best to remove it until we make a new video?

**Comment by madwort** [comment]
This version of the link https://www.youtube.com/watch?v=U-hvuEfUUOM says: "This is a private video. Please sign in to verify that you may see it."
