### ISSUE TITLE
Deal with small list sizes

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#321]
In some cases, list sizes are fictional. In [this case](https://openprescribing.net/analyse/#org=practice&orgIds=Y02873&numIds=0408010AE&denom=total_list_size&selectedTab=summary
), the prescribing is real (149 items) but the list size is false (16 patients).  Therefore it skews the data in terms of cost per patient enormously.

![image](https://cloud.githubusercontent.com/assets/211271/23409388/53a903a6-fdc3-11e6-92be-d4993542885a.png)

This shouldn't be listed as a "4" (GP practice) in our dataset, but it is.  

[According to NHS BSA](https://contactcentreservices.nhsbsa.nhs.uk/selfnhsuktest/template.do;jsessionid=DF983133253CC51D59397C9A225F8D1A?name=What+is+the+procedure+for+setting+up+a+new+practice+or+cost+centre%3F&id=17237), a new GP Practice of Cost Centre must have a patient list size even if there are actually no patients there (e.g. patients are listed elsewhere); and this patient list size can be anything, though 

> we advise that the patient list size does not exceed 100 patients per quarter

Possible approaches are:

* Drop all practices with a list size of 100 or less
* Drop all practices in the bottom centile of list size (or similar)

**Comment by sebbacon** [comment]
These are "GP practices" with list sizes of up to 400 in Sept 2016:

```
┌────────┬─────────────────────────────────────────┬─────────────────┐
│  code  │                  name                   │ total_list_size │
├────────┼─────────────────────────────────────────┼─────────────────┤
│ Y02045 │ VERNOVA HEALTHCARE CIC                  │               3 │
│ Y02645 │ CALDERDALE SAFE HAVEN SERVICE           │              10 │
│ Y01297 │ DR.SAS PAT PEARSON CLINIC               │              14 │
│ Y04659 │ NEW CROSS HEALTH CENTRE                 │              16 │
│ Y02873 │ COMPASS HEALTH                          │              16 │
│ Y01262 │ PALLION PRIMARY CARE SERVICES           │              21 │
│ F85011 │ BOWES MEDICAL CENTRE                    │              29 │
│ Y00081 │ SAFE HAVEN UNIT - LCD                   │              39 │
│ Y05412 │ SOUTH WIGSTON ASYLUM SERVICE            │              43 │
│ B86651 │ ONE MEDICARE LLP                        │              54 │
│ Y00182 │ RAINBOW HEALTH CENTRE                   │              57 │
│ Y03584 │ C/O THE LIMES MEDICAL CENTRE            │              60 │
│ Y03303 │ THE RIDGEWAY HEALTH CENTRE              │              62 │
│ Y00054 │ THE HOMELESS HEALTHCARE TEAM            │              92 │
│ F82641 │ DR GILLETT-WALLER                       │             110 │
│ Y01924 │ SAWBRIDGEWORTH MEDICAL SERVICES         │             113 │
│ Y02650 │ WEYMOUTH COMMUNITY HEALTH CENTRE        │             150 │
│ H85691 │ NIGHTINGALE HOUSE                       │             158 │
│ N82659 │ BAYCLIFFE FAMILY HEALTH CENTRE          │             200 │
│ E87691 │ WESTMINSTER SCHOOL                      │             214 │
│ M85784 │ VENKAT MEDICAL CENTRE                   │             216 │
│ E87694 │ THE ROYAL MEWS SURGERY                  │             250 │
│ F81755 │ THE VICTORIA SURGERY                    │             283 │
│ E87711 │ ROYAL HOSPITAL CHELSEA                  │             291 │
│ E85705 │ THE BURLINGTON GARDENS SURGERY          │             299 │
│ G83068 │ DR NS GURAM'S PRACTICE                  │             304 │
│ K84066 │ LUTHER STREET MEDICAL PRACTICE          │             354 │
│ P81722 │ ASHFIELD MEDICAL CENTRE                 │             357 │
│ N81655 │ ST WERBURGH'S MEDICAL PRACTICE HOMELESS │             373 │
│ E85755 │ NORTH HYDE MEDICAL PRACTICE             │             387 │
└────────┴─────────────────────────────────────────┴─────────────────┘
```

**Comment by sebbacon** [comment]
@richiecroker @lmfrench looking at that list, do we think excluding those under 100 would not (a) exclude any "real" surgeries and (b) include any "fake" ones?

**Comment by HelenCEBM** [comment]
I've had issues with Nightingale House (158 patients in list above) as it's actually a care home even though it's type "4". So it does not have a "normal" range of patients or pattern of prescribing. 
- Is there an additional list of practices available that tells us what type they are (perhaps more specifically than our current list), or has more strict criteria on which are included? 
- Can we cross-reference with a list of care homes to exclude them? (Likely to have different codes in such a list so we'd probably have to use name and address). 
- In the black triangle work, I'm flagging practices that are in their first month of opening, or within a few months of disappearing from the data, which helps quite a lot:
https://github.com/ebmdatalab/Prescribing-of-Black-Triangle-and-Withdrawn-Drugs/issues/4

**Comment by lmfrench** [comment]
Y03584 looks like a 'real' practice, but it is in the dataset twice: https://openprescribing.net/practice/C82055/ and https://openprescribing.net/practice/Y03584
(http://www.limesmedicalcentre.co.uk/)

F85011 is a private medical centre, but they must be doing some NHS prescribing.

I thought we previously agreed we weren't going to drop these practices? #268

**Comment by richiecroker** [comment]
Been thinking about this.  Can we do analysis on changes in list size - i would suspect spurious codes will remain constant whereas "true" small practices will vary, however slightly...

**Comment by sebbacon** [comment]
Aha, I knew this had come up before, thanks for finding the old issue @lmfrench.

I think it's worth writing down why we would or wouldn't do anything about this for next time it comes up.

What are the reasons for fixing it?

* Analyses like the one I linked to sometimes don't make sense. The screenshot above is already zoomed in. If you didn't know to look out for this as a potential problem, you wouldn't know to try zooming in (none of the other bars are even visible at the default zoom level)
* Measures might be screwed. But if only 0.02% of practices are affected then they will never show up on our percentile lines. So I don't think that's an issue.

The effort to fix is like 3 hours or so. How often is this likely to be a problem? I guess any analysis for all practices in a CCG where one of these practices exist will exhibit the problem.

For example, there are 21 CCG with at least one practice under 300 patients. One such is 06T; [here's a Tramadol search](https://openprescribing.net/analyse/#org=practice&orgIds=06T&numIds=040702040&denom=total_list_size&selectedTab=summary) illustrating a less extreme version of the same issue. On the other hand, presumably several of these practices don't do any prescribing - so [this practices-in-CCG search](https://openprescribing.net/analyse/#org=practice&orgIds=01C&numIds=040702040&denom=total_list_size&selectedTab=summary) for example doesn't show the problem, even though the CCG has a small practice.

It may even be that we should just remove individual practices such as that one in Bristol; or we add an option for people to repeat an analysis without the top and bottom centiles; or we agree (once again!) to do nothing.

To answer your thought about if list size changes are significant @richiecroker, the answer appears to be that they're not - nearly all of them do change, leading me to wonder if the list sizes recorded are in fact (usually, but not necessarily) accurate:

```
┌────────┬──────────────────────────────────┬─────────────────┬───────────────┐
│  code  │               name               │ list_size_april │ list_size_aug │
├────────┼──────────────────────────────────┼─────────────────┼───────────────┤
│ Y02045 │ VERNOVA HEALTHCARE CIC           │               3 │             3 │
│ Y02645 │ CALDERDALE SAFE HAVEN SERVICE    │               9 │            10 │
│ Y01297 │ DR.SAS PAT PEARSON CLINIC        │              10 │            14 │
│ Y04659 │ NEW CROSS HEALTH CENTRE          │              17 │            16 │
│ Y02873 │ COMPASS HEALTH                   │              20 │            16 │
│ Y01262 │ PALLION PRIMARY CARE SERVICES    │              18 │            21 │
│ F85011 │ BOWES MEDICAL CENTRE             │               ¤ │            29 │
│ Y00081 │ SAFE HAVEN UNIT - LCD            │              36 │            39 │
│ Y05412 │ SOUTH WIGSTON ASYLUM SERVICE     │               ¤ │            43 │
│ B86651 │ ONE MEDICARE LLP                 │               ¤ │            54 │
│ Y00182 │ RAINBOW HEALTH CENTRE            │              36 │            57 │
│ Y03584 │ C/O THE LIMES MEDICAL CENTRE     │              55 │            60 │
│ Y03303 │ THE RIDGEWAY HEALTH CENTRE       │              61 │            62 │
│ Y00054 │ THE HOMELESS HEALTHCARE TEAM     │              87 │            92 │
│ F82641 │ DR GILLETT-WALLER                │               ¤ │           110 │
│ Y01924 │ SAWBRIDGEWORTH MEDICAL SERVICES  │             114 │           113 │
│ Y02650 │ WEYMOUTH COMMUNITY HEALTH CENTRE │               ¤ │           150 │
│ H85691 │ NIGHTINGALE HOUSE                │             155 │           158 │
│ N82659 │ BAYCLIFFE FAMILY HEALTH CENTRE   │               ¤ │           200 │
└────────┴──────────────────────────────────┴─────────────────┴───────────────┘
```

**Comment by lmfrench** [comment]
I think the reason behind keeping it was that some CCGs might not have specific practices for homeless people but those patients would still be attending GP practices elsewhere & receive prescriptions. By excluding the practices from the CCGs that have them we would be lowering the numbers of items they were prescribing, but places that don't have them we wouldn't be. However, I didn't fully understand the discussion, which is why I only wrote up the decision,  but @richiecroker may have better recollection! 

We did have a specific query from a CCQ about excluding Compass from their analyse searches (because of the skewing that you mention). We decided we didn't need to because they could use the zoom option to exclude it themselves

**Comment by richiecroker** [comment]
Could we put in a toggle switch to hide/show lowest percentile practices?

**Comment by lmfrench** [comment]
I think the other problem with excluding is that some of these practices have a list size higher than 100 so we wouldn't be excluding all of them e.g. N81655

**Comment by HelenCEBM** [comment]
Is it worth reporting all the practices we find which have the wrong codes to get them corrected..?
- Y03402 is a weekend-only drop-in centre but has code 4.
- Another, Y02511, is a home visiting GP Practice for over 65s, which (although probably is technically a normal practice), having a skewed population it won't have normal prescribing. 

Rather than the percentile filter, can we make a simple flag for all types of "unusual" practices (care homes, drop in centres, restricted age groups, safe havens, homeless etc) to allow toggling? 

Another argument in favour of filtering is that if they all had the correct "setting" codes, the care homes etc. would be excluded anyway, so we are only showing these if they happen to have the wrong code, and this is (presumably) not consistent across CCGs.

**Comment by lmfrench** [comment]
I think the organisation producing the data is ultimately responsible for making sure the data is correct, and any changes we try to do ourselves will likely miss some practices. Adding a filter for practice size or a toggle for percentiles seems reasonable, because it is easy to explain to users & easily reproducible, but I think there is a danger if we make our own flags for unusual practices that we will miss some or erroneously add some. My only thought on adding a toggle for percentile is that it may not be quick to do, and is probably not a higher priority than some other changes we've thought about.

I do agree though that we should tell the BSA or NHS Digital if we suspect the codes are incorrect, but we should leave the decision as to whether to change them down to them (talking about what we do with the website, rather than research!)

**Comment by HelenCEBM** [comment]
Created separate issue to discuss incorrect codes. 
Also noticed that this problem is the topic of issue #153 (still open).

**Comment by HelenCEBM** [comment]
Just to make a note of another practice with an issue, [Ropewalks practice in Liverpool](http://www.nhs.uk/Services/GP/Overview/DefaultView.aspx?id=36975) is large and active, and is on OP under this name, but only has very occasional data points, and has no registered population (and never has according to our `practice_statistics`!), yet the code has not been retired. It is part of a wider group but the group name is not located at the same address. It's possibly acting more like a branch surgery. I suppose anyone sufficiently interested would figure out that they needed to look for Brownlow group but it's far from obvious to a patient or non-local person... 

Perhaps it would be helpful to show the most recent registered population figure on the practice dashboards, and add a note to the effect of "a population below 100 may indicate a non-standard practice"?

**Comment by sebbacon** [comment]
I agree with @lmfrench that any fixes we apply should be programmatic.

Usually, this is a problem where the list size is the denominator, and it is smaller than the numerator.

So we could quite easily detect such cases, and suggest in the UI excluding those practices (and remember the user's decision with a cookie)
