### ISSUE TITLE
Methotrexate guidance changed in BNF

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#3217]
The MTX guidance in the BNF has now changed, and makes no mention of the 2.5mg prescribing (or in fact single formulation at all.)  @brianmackenna and I will need to have a conversation about this measure's wording
https://github.com/ebmdatalab/openprescribing/blob/main/openprescribing/measure_definitions/methotrexate.json

**Comment by brianmackenna** [comment]
It appears it has reverted and now includes this guidance again. Nice spot @richiecroker 

![image](https://user-images.githubusercontent.com/40460354/154797471-f5d103d5-e81d-470c-8eb1-bd6e7393eb16.png)
