### ISSUE TITLE
Remove IIF Dashboard

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3226]
There have been substantial developments to NHS England Investment and Impact fund. We previously launched a dashboard

https://openprescribing.net/regional-team/Y56/measures/?tags=iif

but the most recent IIF appears to utilise nearly all patient level metrics which we cannot reproduce from NHS open data.

They are listed at https://www.england.nhs.uk/wp-content/uploads/2021/08/B0828-iii-annex-b-investment-and-impact-fund-21-22-and-22-23.pdf

We could
a) leave the dashboard there for the measures we can reproduce (on a quick skim it looks like 1 or 2) with a note in the description
b) remove the dashboard

@richiecroker any preference?

**Comment by richiecroker** [comment]
@brianmackenna i think we should remove the dashboard as no longer current.  @evansd if we just remove https://github.com/ebmdatalab/openprescribing/blob/510e8c07e841cd42284c109774d1730b6463f376/openprescribing/common/measure_tags.json#L54-L56 will that remove it?

**Comment by richiecroker** [comment]
@evansd have you remembered the code?
