### ISSUE TITLE
Practices where setting = 4 appears to be incorrect

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#323]
This stems from issue #321, where it was discussed that some non-standard practices are incorrectly assigned to setting `4`, and these could perhaps be reported to NHS Digital(?), to be corrected in the `practices` dataset. 

In particular, some practices with setting `4` are care homes (hence should have code `13` hospice or `14` Nursing/care home). These can usually be identified via their highly elderly populations. (Homes for younger people are less straightforward to identify!).  

The first 7 in this list have disproportionate numbers over 65 (>90%), averaged over all months. The next practice is clearly odd (5 patients), but after that the numbers are more comparable with CCG averages and probably just represent more elderly neighbourhoods.
![image](https://cloud.githubusercontent.com/assets/24392156/23476438/aa99eb72-feb2-11e6-8948-cb50d876b0d9.png)

- [ ] Report these potential errors for investigation
- [ ] Check for other types of practice given incorrect setting codes such as walk-in-centres. 

Here is (potentially more widely useful) code used to calculate percent of registered patients over 65/75 for each practice, compared to their parent CCG average.
```
WITH a AS ( -- pct/ccg-level data
SELECT pct_id, month, 
(sum(male_65_74)+sum(male_75_plus)+ sum(female_75_plus)+sum(female_65_74))/sum(total_list_size) AS Percent_over_65,
(sum(male_75_plus)+ sum(female_75_plus))/sum(total_list_size) AS Percent_over_75
FROM ebmdatalab.hscic.practice_statistics p --prescribing 
INNER JOIN  ebmdatalab.hscic.practices prac ON prac.code =p.practice AND prac.setting = 4 
WHERE total_list_size >0
group by pct_id,  month
order by pct_id, month),

b AS ( -- average CCGs over all months
SELECT pct_id, avg(Percent_over_65) AS ccg_65, avg(Percent_over_75) AS ccg_75
from a
group by pct_id),

c AS ( --practice-level data
SELECT pct_id, practice, name, month, 
(sum(male_65_74)+sum(male_75_plus)+ sum(female_75_plus)+sum(female_65_74))/sum(total_list_size) AS Percent_over_65,
(sum(male_75_plus)+ sum(female_75_plus))/sum(total_list_size) AS Percent_over_75,
sum(total_list_size) AS total_list_size
FROM ebmdatalab.hscic.practice_statistics p --prescribing 
INNER JOIN  ebmdatalab.hscic.practices prac ON prac.code =p.practice AND prac.setting = 4 
WHERE total_list_size >0
group by pct_id, practice, name, month
order by pct_id, month)

SELECT c.practice, name, c.pct_id, max(b.ccg_65) AS ccg_avg_over_65, max(b.ccg_75) AS ccg_avg_over_75,
avg(Percent_over_65) as Avg_Percent_over_65,
avg(Percent_over_75) AS Avg_Percent_over_75,
avg(total_list_size) AS Avg_total_list_size
FROM c --prescribing 
LEFT JOIN b ON c.pct_id = b.pct_id
WHERE Percent_over_65 > ccg_65*2 or Percent_over_75 > ccg_75*2  
GROUP BY practice, name, pct_id
order by avg_percent_over_75 desc,avg_percent_over_65 desc
```

**Comment by sebbacon** [comment]
@lmfrench I've assigned this to you for following up with the authorities!

**Comment by lmfrench** [comment]
BSA have said this can only be changed by someone at a CCG, they won't give us a full list of contacts but will give us contact details for CCGs where we think a code change is needed. 

I'm not sure if all of those listed above need reporting e.g. [Eldercare](http://www.eldercaredoctors.co.uk/index.aspx) isn't based in a care home, it visits elderly people in the local area so although not a standard GP practice it doesn't really have anything else it could be classified as

**Comment by sebbacon** [comment]
Seems like we should perhaps close this issue and not address it? Fixing seems time consuming and potentially error-prone.

**Comment by lmfrench** [comment]
yep agree
