### ISSUE TITLE
PPU calculation ignores savings for presentations with no substitutions

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#3233]
This behaviour sounds reasonable but it isn't actually correct as there can be significant variation in the price of a single generic presentation (e.g. if it's not listed in the drug tariff).

The impact isn't huge (for example, the savings over All England in July 2021 go from £23,198,000 to £23,371,000) but it is more accurate and it means we don't misleadingly show zero available savings for certain presentations.

The fix is (I think) as simple as deleting this guard condition:
https://github.com/ebmdatalab/openprescribing/blob/8a7c57b6451e25341b40c21496c2b95a06633912/openprescribing/frontend/price_per_unit/substitution_sets.py#L173-L174

The downside will be an increase in the time it takes to do the full PPU savings calculation as this runs over all presentations with potential savings, and removing the condition will increase the size of that set. This is calculated once per `<organisation type, prescribing month>` pair and then cached so it's not a disaster if it takes longer. But if it takes too long we might start getting timeout errors after we deploy need data so we should benchmark before and after this change to check the impact.

**Comment by richiecroker** [comment]
This is an important change, and is a major part of how PPU originally functioned - picking up variability in pricing for items such as co-proxamol and sucralfate.  I'm not sure why it was removed.  If it's a simple fix then can we action please.
