### ISSUE TITLE
Edoxaban as preferred DOAC

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3361]
NHSE Guidance indicates a preference that clinicians use edoxaban for AF. A user has requested a measure on OP to inform implementation  

https://www.england.nhs.uk/wp-content/uploads/2022/01/B1279-national-procurement-for-DOACs-commissioning-recommendations-v1.pdf

**Comment by brianmackenna** [comment]
Annex D of this letter indicates IIF indicators will be launched in support of this measure 

https://www.england.nhs.uk/wp-content/uploads/2022/03/B1375_Letter-re-General-practice-contract-arrangements-in-2022-23_010322.pdf

**Comment by richiecroker** [comment]
https://github.com/ebmdatalab/openprescribing/pull/3470
