### ISSUE TITLE
Low carbon salbutamol pMDI measure

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#3374]
We have had a lot of emails from users who have requested a carbon measure for salbutamol inhalers.  We have been reluctant to do this in the past, due to issues as outlined in a [blog post](https://www.thedatalab.org/blog/2019/10/new-measure-inhalers-and-the-environment/):
>We have excluded it for two main reasons: a) about 60% of salbutamol inhalers are prescribed generically, so we can’t tell from the prescribing data which manufacturer’s MDI, and therefore the GWP, has been supplied b) further clinical review may be necessary to ensure a DPI is suitable even in the event of an asthma attack. 

However, in the context of the NHS drive towards sustainability, we could consider two measures which may be useful:

a)  % of Salbutamol pMDI as Salamol (or NOT as Salamol, as in OpenPrescribing, "high" = "bad":

Numerator:
```
Salamol 100micrograms/dose inhaler CFC free (Arrow) [0301011R0BIAHAP]
Salamol 100micrograms/dose inhaler CFC free (Teva) [0301011R0BIAFAP]
Salamol 100micrograms/dose Easi-Breathe inhaler [0301011R0BIAGBU]
```

Denominator
```
Salbutamol 100micrograms/dose inhaler CFC free [0301011R0%AP]
Salbutamol 100micrograms/dose breath actuated inh CFC free [0301011R0%BU]
```

b) Carbon emissions per inhaler

Using the table in the NHS [Network Contract Directed Enhanced Service Investment and Impact Fund 2021/22 guidance](https://www.england.nhs.uk/wp-content/uploads/2021/12/B1219-investment-and-impact-fund-implementation-guidance-2021-22-dec-21.pdf) we could calculate a practice's mean emission:
![image](https://user-images.githubusercontent.com/18683239/152775766-ffb49b2e-0f19-4e42-9306-cf1ec2b88de9.png) 

The main caveat still remains: between [50-85%](https://openprescribing.net/analyse/#org=regional_team&numIds=0301011R0AA&denomIds=0301011R0&selectedTab=chart)  (depending on region) of salbutamol prescribing is generic, and therefore any measure may not be wholly accurate, based on BSA data.

**Comment by brianmackenna** [comment]
#3375 is the PR for the measure and we are now previewing. Recording some helpful user feedback from a user. Not necessairily all to be actioned but for discussion

- [ ] update targets in description from long term plan to Net Zero plan which are slightly different

- [ ] in p2 could we mention that there are other ways to reduce salbuatmol impact i.e. reducing number prescribed by improving asthma control
- [ ] Carbon emissions per salbutamol inhaler ranges from x-y and data for all inhalers can be viewed in the [table here](https://docs.google.com/spreadsheets/d/1eyk2iqNM_4sobDzevZWWcRR00O2tmJO5HwdFZLjhfa4). 
- [ ] suggested to include link to [Greener Practice QI Toolkit](https://www.greenerpractice.co.uk/) - I wonder if this fits better in the overall greener dashboard?
