### ISSUE TITLE
Visually distinguish between chemicals/BNF codes that are used and unused

### ISSUE THREAD

**Issue by jamesscottbrown** [ebmdatalab/openprescribing#342]
The database includes all drugs in the BNF, many of which have no corresponding prescriptions recorded, either because there are better alternatives or they are inherently not suitable for use in primary care. 

It would be helpful if lists of drugs (on the [All chemicals view](https://openprescribing.net/chemical/) and BNF section pages [like this one](https://openprescribing.net/bnf/010101/)) visually indicated the unused drugs in some way, such as by changing the color of their names from blue to black/grey. 

This would:
* avoid users being frustrated by finding that many links they click on lead to empty pages
* provide an immediate impression of which drugs are actually used in primary care

**Comment by sebbacon** [comment]
Related to #253 

(@jamesscottbrown, thanks for all the feedback - there's less than one developer on the project so it may take some time for these suggestions to bubble to the top of the pile!)

**Comment by sebbacon** [comment]
Discussing in the team, there seems little benefit to greying out unused drugs over simply not showing them, which is what we'll do in the first instance, and test.
