### ISSUE TITLE
Explain BNF codes on 'All chemicals' page

### ISSUE THREAD

**Issue by jamesscottbrown** [ebmdatalab/openprescribing#343]
The [All chemicals](https://openprescribing.net/chemical/) page lists drugs odered by their BNF code. Several drugs (e.g. adrenaline) appear several times, with different codes corresponding to different indications. 

Currently only the numerical code is listed (e.g. "0207030A0", rather than "Part of chapter 2 Cardiovascular System, section 2.7 Sympathomimetics, paragraph 2.7.3 Cardiopulmonary Resuscitation"), making it more difficult for non-expert users to spot which entry they are interested in.

It would be helpful if the textual description of the BNF code were provided as a tooltip.

**Comment by lmfrench** [comment]
Related to #235
