### ISSUE TITLE
Libre measure review

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3503]
There is a new [AMP listed](https://openprescribing.net/dmd/amp/40571611000001104/) under the VMP that covers [Freestyle Libre.](https://openprescribing.net/dmd/vmp/34865511000001109/)

It doesn't have a BNF code but this should (probably) prompt a review of the [Libre measure](https://openprescribing.net/measure/libre/).

**Comment by richiecroker** [comment]
Updated measure appears identical at the moment to the existing one:
https://openprescribing.net/measure/libre/
https://openprescribing.net/measure/preview_libre/

**Comment by chrisjwood16** [comment]
@richiecroker Updated title/description here: https://docs.google.com/document/d/1541kclbCDZ14vayO7SAsLZGOMn7YAltqMnNEJ07Tztc/edit?usp=sharing

**Comment by richiecroker** [comment]
Thanks @chrisjwood16 , have made slight amendment (change "device" to "sensor" in the description for prescribing" renamed measure name and have added to #3509 .  Preview here (https://openprescribing.net/measure/preview_cgm_sensors/) with one "device" not changed, but subsequently done in PR.

**Comment by chrisjwood16** [comment]
@richiecroker Initial p tag can be removed to remove the new line after "Why it matter" - now I see why we leave this out. But otherwise looks all good to me.

**Comment by brianmackenna** [comment]
Is this ready for sharing with our expert users?
