### ISSUE TITLE
ICB Boundary Changes - CCG Abolition

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3571]
Legislation has passed that will remove CCGs as organisations and replace them with Integrated Care Boards (ICBs) from July 1st. There is more information here on [ODS code changes](https://elinkeu.clickdimensions.com/m/1/58255379/p1-b22167-cc675ea0aecf474ba0df3df29b5b8692/2/984/9ab9d96e-5acc-4995-9f60-05b940830e3a) and we expect an update from BSA in due course (which @richiecroker me or @a-d-brown should see in bulletins and update)

There are two different aspects to this a) straightforward organisational changes b) we lose CCG granularity what are we going to do?

a) straightforward organisational changes
Although tedious we have a lot of experience with new/replacing NHS organisations. ICBs are effectively a straight replacement for STPs which is already an [organisational layer](https://openprescribing.net/stp/ ) in OpenPrescribing https://openprescribing.net/stp/  Some jobs I can think of
tidy up nomenclature on site
make sure each STP has the right members
make judgments about CCG alerts like #949

b) we lose CCG granularity what are we going to do
There is no replacement for a CCG which used to number about 200  to be replaced by 42 STPs. As we use CCG deciles to illustrate variation this is problematic. Secondly for a user in an ICB the noise gets worse; for example I used to work in Islington CCG and my members was 35 practices which were easy to scan on a chart and I knew what they were all doing. Now I have [NCL STP](https://openprescribing.net/stp/E54000028/) and when I break down to members I immediately have >100 practices which is much too noisy to meaningfully work with.

I think we need to look at an organisation layer in between practice/PCN and STP

**Comment by brianmackenna** [comment]
> I think it is worth considering whether we continue to publish CCG level data

Sorry I probably wasn't clear on this bit. CCGs disappear legally on July 1st and they will also disappear from NHS data flows as a consequence (unless I have completely missed something?).  We would have to maintain CCG membership manually which we probably cannot do.

**Comment by a-d-brown** [comment]
I thought the CCG level data was just going to be renamed as 'Sub ICB Location' data - as an interim measure until the 'ICB Place' codes come into existence in April 2023.

That was the impression I'd taken from reading [this](https://digital.nhs.uk/services/organisation-data-service/integrated-care-boards/implementation-of-icbs-from-april-2022) - but I be misinterpreting it, have a read and see what you reckon!

<img width="970" alt="Screenshot 2022-06-16 at 14 58 03" src="https://user-images.githubusercontent.com/75492467/174086507-907b9789-67c7-42fc-a999-84d34c3ac756.png">

**Comment by brianmackenna** [comment]
Well spotted - lets check what BSA plan to do.

**Comment by brianmackenna** [comment]
From BSA

> From 1 July the naming convention for certain organisations will be changing.
•	STP’s (Sustainability and Transformation Partnerships) will be renamed as ICB’s (Integrated Care Boards) e.g. W YORKSHIRE & HARROGATE H&C P/SHIP STP will be changing to NHS WEST YORKSHIRE INTEGRATED CARE BOARD.
•	CCG’s (Clinical Commissioning Groups) will be renamed as SICBL’s (Sub Integrated Care Board Locations) e.g. KIRKLEES CCG will be changing to SICBL of NHS WEST YORKSHIRE ICB X2C4Y. 
Organisation codes are not changed, and you will need to be aware of codes when running both ICB and SICBL data.
The changes above will be reflected in May 2022 prescription data when it is published in our ODP around mid-July and the column headings affected by these changes will be renamed accordingly.

> Colum headings of STP_NAME and STP_CODE will be renamed to ICB_NAME and ICB_CODE and these changes will be reflected within the following datasets.

> Community Prescribing & Dispensing
Prescription Cost Analysis (PCA) Monthly Administrative Data
English Prescribing Dataset (EPD)

>Experimental Data Sets
English Prescribing Dataset (EPD) with SNOMED code


> English Prescribing Dataset (EPD) and English Prescribing Dataset (EPD) with SNOMED code
CCG names held under the column heading of PCO_NAME will reflect Integrated Care Board Sub Location Names as in the example stated above for KIRKLEES CCG.

> The Data Dictionaries that accompany these datasets will also be updated to reflect the above.

> **Boundary changes which take place from 1 July 2022 will be reflected in the July 2022 prescription data when it is published around mid-September.**

**Comment by chrisjwood16** [comment]
@inglesp May 22 English Prescribing data has now been published. This includes the changes mentioned above (except boundary changes mentioned in the last point which should come mid-September).

I've had a quick look through, hopefully shouldn't be too difficult to adjust as I think the only change that will be needed will be the column name changes (STP_NAME -> ICB_NAME) and (STP_CODE -> ICB_CODE).

Please could you have a look into this so we can update the OpenPrescribing data.
