### ISSUE TITLE
some measures missing for December 2016

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#359]
The following measures do not have Dec 16 data included, either on the website or the SQL server:

```
coproxamol
fungal
ktt9_antibiotics
ktt9_uti_antibiotics
pregabalin
```

I assume that this is due to the failed import of Dec 16 list size data, as these are all per 1000 patients etc.  Will the measures need to be run again?

**Comment by sebbacon** [comment]
Thanks, updating measures again now.
