### ISSUE TITLE
Libre BNF code issue for generic v brand

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3611]
Reminder to get to bottom of https://bennettoxford.slack.com/archives/C03HVM72273/p1658329389444659

**Comment by richiecroker** [comment]
email sent to NHSBSA today:

Hi

We’ve noticed that, unusually, the BNF code for the branded product FreeStyle Libre Sensor (Abbott Laboratories Ltd) and its generic record Glucose interstitial fluid detection sensor have the same BNF code (21480000100).  I’m just checking to see if this is correct, and now that there are multiple companies making these sensors, and they are now available to be prescribed, whether there are any plans to change this?

Many thanks!

Regards

Richard

**Comment by richiecroker** [comment]
@richiecroker tag for email

**Comment by richiecroker** [comment]
Thanks for contacting the Information Services support team

We aim to respond to all queries within a maximum of 5 working days.

This is your call number –BSA-13289-K6L4. You can quote this call number if you need follow up on your query.
 
If you would like a telephone/Teams response the next time you make contact please request this in your email.
 
If your enquiry is in relation to other NHSBSA services including Prepayment Certificates, Penalty Charge Notices, Pensions relevant contact details are available on our website: https://www.nhsbsa.nhs.uk/contact-us

Best Regards
 
Information Services Support Team
Data & Insight - Information Services

Email: [dataandinsightsupport@nhsbsa.nhs.uk](mailto:dataandinsightsupport@nhsbsa.nhs.uk)

Website: [www.nhsbsa.nhs.uk](http://www.nhsbsa.nhs.uk/)

Help us improve our service by completing our short survey [here.](https://www.snapsurveys.com/wh/s.asp?k=151878330131)

**Comment by richiecroker** [comment]
We received a reply from BSA (23rd August):

> Hi Richard,
> 
> I have queried this with our Medicines Data team who are responsible for allocation and population of BNF Codes.
> 
> They have confirmed that as this appliance is not listed generically in Part IX of the Drug Tariff and not Valid to prescribe as a VMP the VMP should not have been allocated a BNF code in the first place and the BNF Code will be ended.
> 
> They have also advised that they are investigating other VMPs that are not listed as generics in Part IX of the Drug Tariff that are not Valid to prescribe as a VMP with a view to ending those BNF codes as well.
> 
> Hope this has helped resolve your issue.
> 
> Regards
> Jackie

**Comment by richiecroker** [comment]
We need to check with September data if this has happened yet.

**Comment by richiecroker** [comment]
Generic name is no longer showing - we're able to close.
