### ISSUE TITLE
Zooming in on OpenPrescribing logo on charts takes you to Highcharts

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#365]
If you zoom in on a graph & end your click on the 'openprescribing.net' logo you get taken to highcharts.com instead of zooming

**Comment by sebbacon** [comment]
I can't reproduce this. Can you provide a URL, your browser, etc?

**Comment by lmfrench** [comment]
https://openprescribing.net/analyse/#org=CCG&numIds=0703021Q0BB&denomIds=0703021Q0&selectedTab=summary
Using Chrome
If you click on the openprescribing logo it acts as a link to highcharts.com - I don't think it's a zoom issue, but is most likely going to happen when you're trying to zoom
