### ISSUE TITLE
dm+d browser - missing GTIN

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#3689]
We've had an email from a user:

> GTIN 7613421064396 is missing
>
>Revolade 25mg tablets (Novartis Pharmaceuticals UK Ltd) 28 tablet 4 x 7 tablets
>17075611000001107

Having taken a look at both the [dm+d browser](https://openprescribing.net/dmd/ampp/17075611000001107/) and  the `gtin` table on BQ, I can only see one GTIN listed for this AMPP:
![image](https://user-images.githubusercontent.com/18683239/192301003-c209faf0-cde6-4c82-9f17-ad558c7f33f6.png)

However, on the TRUD release for this week, there appears to be 4, with 3 having end dates:

![image](https://user-images.githubusercontent.com/18683239/192301196-dcd4fc24-1595-47db-9cf5-da24117ca5d1.png)

How do we manage changes in GTIN?

**Comment by brianmackenna** [comment]
Just looking at the example https://openprescribing.net/dmd/ampp/17075611000001107/

It shows the old GTIN now but not the current one?

Should we not show both?

**Comment by inglesp** [comment]
We've now re-imported the latest dm+d data, and this page now shows:

![image](https://user-images.githubusercontent.com/28734/193584301-3e3236d0-2cd9-4225-b8ae-35e816036ad0.png)

Ugly, but an improvement.
