### ISSUE TITLE
Various IE8 bugs

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#379]
Just a single place to list all IE8 bugs for triage, and later possible splitting into different issues.

* [ ] Maps don't work at all - blank canvas
* [ ] Tabs to switch between graphs are broken - you can only see the spline chart tab
* [ ] Top menu doesn't appear - only a burger menu icon

**Comment by sebbacon** [comment]
* [ ] Measure graphs are too wide: ![bs_win7_ie_8 0](https://cloud.githubusercontent.com/assets/211271/24244577/75e80470-0fb7-11e7-84d5-46d026a784a8.jpg)

**Comment by evansd** [comment]
We no longer support IE8
