### ISSUE TITLE
Savings to NHS calculations

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#381]
Currently the measures page contains the message:

> **How the CCGs are doing:** Over the past 6 months, if all CCGs had prescribed at the median ratio or better, then NHS England would have spent £x less. (We use the national median as a suggested target because by definition, 50% of CCGs were already prescribing at this level or better, so we think it ought to be achievable.)

Most MO teams describe either annual savings (often by annualising 3 months worth of data), or quarterly savings, as prescribing behaviour has a greater tendency to change over 6 months, and given the time lag on the data the calculations are not as relevant.  

We should give consideration to either showing 3 month savings, or annualising.

This also relates to issue #375 in that we need to ensure clarity on the calculation is made.

We should also considering rounding up the savings value, as there is currently false precision.

e.g. for Keppra for December it states:

>How the CCGs are doing: Over the past 6 months, if all CCGs had prescribed at the median ratio or better, then NHS England would have spent £1,685,926.67 less. (We use the national median as a suggested target because by definition, 50% of CCGs were already prescribing at this level or better, so we think it ought to be achievable.)

It would be better to say something like:

>...then **the NHS in England** would have spent approximately £1.69 million less

Also note the change in language from "NHS England" to "the NHS in England", as CCGs, not NHS England, bear the costs of primary care prescribing.

**Comment by lmfrench** [comment]
Related to #50 (and there is also a suggestion for rounding savings in #133)

**Comment by lmfrench** [comment]
Make part of #135 (rounding was also suggested from user testing -  #133)
