### ISSUE TITLE
Cloudflare "currently offline" mode is confusing

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#387]
* User makes a query that takes more than 60 seconds to return
* Our web server times out and returns a 500
* Cloudflare decides the site is down and sets a cookie on the user's browser to indicate this
* The cookie stays on the user's browser for an unpredictable amount of time (I've had it stay for hours)
* As long as the cookie is there, the user can't use the website as they get a Cloudflare "currently offline" message

Ideal solutions might look like one of:

1. Ensure queries never time out:
   1. IIRC more or less impossible as the scan-and-union of many queries is inherently expensive and we can't use more than one CPU for this kind of query (though worth checking)
   2. Use a map-reduce backend instead of postgres, e.g. [Spark](http://spark.apache.org/)
   3. Hybrid: switch to using bigquery for complex queries
2. Gain control over timeout error messages:
   1. Work with Cloudflare support to understand the bug whereby cookies persist for too long
   2. Implement API data caching locally and only use cloudflare for edge caching of assets

**Comment by sebbacon** [comment]
Regarding 2 (i), it seems the presence of the following two session cookies ensures the site remains unavailable until a new browser session is opened:

* `cf_use_ob: 0`
* `cf_use_ob: 443`

**Comment by sebbacon** [comment]
I've turned off the "always online" feature, which may mitigate things.

**Comment by sebbacon** [comment]
Another thought: searches for multiple codes will probably be much faster when restricted to a single month. Perhaps we should only support a date slider / time series for "simpler" queries.

**Comment by sebbacon** [comment]
[Example of a very slow query](https://openprescribing.net/analyse/#org=practice&orgIds=G82099&numIds=0403010J0&denomIds=4.3&selectedTab=summary)

I believe queries for practices within a CCG become SQL which queries a practice table by practice id -- possibly this table could include a CCG column?

**Comment by sebbacon** [comment]
Update: there've not been any really slow queries for some time now, so hard to assess if turning off "always online" has helped or not.

**Comment by lmfrench** [comment]
Are we able to change how the new error message looks? I think it is more confusing than the old cloudflare one

**Comment by sebbacon** [comment]
Yes we can - my problem is reproducing a timeout so I can test etc. Can you?!

**Comment by lmfrench** [comment]
No! (yay!) Have this screenshot: 
![image](https://cloud.githubusercontent.com/assets/15875191/25172628/864a470a-24e9-11e7-8e51-3823df195b85.png)
I think we could move the 'What happened?' and 'What can I do?' to the top, and change the What Happened text to make it clear it wasn't caused by the user incorrectly entering their search (but perhaps not worth spending time on unless we start seeing it happen regularly again)

**Comment by sebbacon** [comment]
Here is documentation on customising Cloudflare error messages

https://support.cloudflare.com/hc/en-us/articles/200172706-How-do-I-customize-Cloudflare-error-pages-

**Comment by lmfrench** [comment]
Had a Cloudflare error this morning running this search: https://openprescribing.net/analyse/#org=CCG&orgIds=11H&numIds=0501130R0AAAGAG&denomIds=5.1&selectedTab=summary Working now, but suggests it is still happening. When the site went into 'always offline' mode, did it save the query as the URL? I can't remember, but the most frustrating thing about the current message is that you have to re-enter your search
