### ISSUE TITLE
Check how Dexcom One transmitter / CGM pack picked up in OP CGM measure

### ISSUE THREAD

**Issue by chrisjwood16** [ebmdatalab/openprescribing#3889]
Dexcom One Transmitter added to drug tariff March 2023. Will need to check how this is picked up in OP CGM measure to prevent double counting (sensor + transmitter).

https://psnc.org.uk/our-news/dexcom-one-transmitters-to-be-added-to-march-2023-drug-tariff/

Dexcom One Sensor is being picked up on OP since August 22.

"Previously, patients were advised to obtain the free-of-charge Dexcom One transmitters directly from the pharmacies, without a prescription, as the original Drug Tariff application for the transmitter was unsuccessful."

**Comment by chrisjwood16** [comment]
Waiting for March 2023 data - due mid-May 2023

**Comment by richiecroker** [comment]
https://github.com/ebmdatalab/openprescribing/pull/4107

**Comment by richiecroker** [comment]
Closed via #4107 - used `LOWER(nm) LIKE %transmitter%` as filter to exclude Dexcom (and other) transmitters.
