### ISSUE TITLE
Enumerate US drugs not approved in UK

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#393]
The goal is to enhance "black triange" analysis with another category of "possibly risky" drug.

The FDA approved drugs list is available as data [here](https://www.fda.gov/drugs/informationondrugs/ucm079750.htm#download) ([browsable version](https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm)).

The challenge is mapping USANs (US Adopted Names) to INNs (International Non-proprietary Names) - an example list is provided on [this Wikipedia page](https://en.wikipedia.org/wiki/United_States_Adopted_Name#cite_note-8).

One possibility is to use wikidata which appears to be fairly complete - [example SPARQL query](https://query.wikidata.org/#SELECT%20%3Fitem%20%3Flabel%20%3FitemLabel%20%3FitemAltLabel%0AWHERE%20%0A%7B%0A%09%3Fitem%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ11173%20.%0A%20%20%20%20%3Fitem%20p%3AP2275%20%3Fstatement%20.%20%0A%20%20%20%20%3Fitem%20rdfs%3Alabel%20%3Flabel.%0A%20%20%20%20FILTER%20CONTAINS%28%3Flabel%2C%20%22paracetamol%22%29.%0A%09SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%7D%20LIMIT%201).

Another possibility is to use the [PubChem compounds database](https://pubchem.ncbi.nlm.nih.gov/search/) which can be downloaded via FTP, but as that's not restricted to pharmaceuticals I'm not sure how we'd use it.

The [WHO publishes a "cumulative list of names"](http://apps.who.int/medicinedocs/en/d/Jh1806e/2.5.html) which appears to map INNs to US (and British) names. However, it doesn't appear to be published online, although I can find a [PDF of an old version](http://www.vpb.gov.lt/files/539.pdf) on a Lithuanian website.

The best source I have found is KEGG which has a REST API including [all known drug names](http://rest.kegg.jp/list/drug) including US and INN terms. From its home page this appears to be kept up to date.  I found this by Googling the list of example USAN / INN discrepancies from the Wikipedia page referenced above.

**Comment by sebbacon** [comment]
I've done some basic matching (recorded in [this notebook](https://gist.github.com/sebbacon/78bc62d7d4179d4102875d47643b7178)) against the best data for mapping I could find (the KEGG data), and it illustrates how this is going to be quite a big problem.

For example:

* CALCIUM CARBONATE which is not listed as a drug in the FDA database but is an "active ingredient" in other drugs, so is approved despite not appearing in their list
* SIMETICONE which is called SIMETHICONE in FDA database (i.e. no mapping in the KEGG data); additionally, it is similarly not listed on its own
* KETAMINE which is listed as KETAMINE HCL in the FDA database  (i.e. no mapping in the KEGG data)

**Comment by sebbacon** [comment]
Unless we can find a source that does the mapping for us, I personally think this is going to be too hard to warrant the time it takes.

**Comment by HelenCEBM** [comment]
Agree, this could be done for a few drugs manually, perhaps as an extension of black triangle work (see separate repository). It is also not the most useful measure of prescribing quality, because people would not know that drugs had a different approval status in another country; however, it could be an indirect way to encourage prescribers to think more about the evidence-base for their decisions... Park for now!
