### ISSUE TITLE
IIF Updates - review measures

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3943]
NHS England has issued [new guidance](https://www.england.nhs.uk/long-read/changes-to-the-gp-contract-in-2023-24/) on the GP contract and changes happening. I think the changes to the IIF are  particularly relevant to OpenPrescribing.

We should
- review the guidance in totality
- amend/retire measures as appropriate

**Comment by speed-vm** [comment]
Three IIF measures currently listed on OP
[Environmental impact of inhalers - average carbon footprint per salbutamol inhaler](https://openprescribing.net/measure/carbon_salbutamol/)
[Environmental impact of inhalers - prescribing of non-salbutamol Metered Dose Inhalers (MDIs)](https://openprescribing.net/measure/environmental_inhalers/)
[Proportion of Direct Acting Oral Anticoagulants (DOACs) not prescribed as edoxaban](https://openprescribing.net/measure/edoxaban/)
These will all retire 1/4/23.

**Comment by brianmackenna** [comment]
> Retire Edoxaban

I'm not sure I agree with retirement. I propose to amend the wording as the [policy](https://www.england.nhs.uk/wp-content/uploads/2022/01/B1279-national-procurement-for-DOACs-commissioning-recommendations-v1.pdf) still exists at the moment. It's only the additional policy that is being removed.

**Comment by a-d-brown** [comment]
Linked with this, there's always the option of systematically going through all current OP measures and score them for factors such as:
a) clinical importance
b) financial importance
c) alignment with current national incentives, e.g. IIF and QOF

There would obviously be a degree of subjectivity in scoring, but if there's a perceived need to keep measures relevant and manageable in number, then this sort of annual review might provide a rational basis for deciding which measures are the obvious ones to cull.

Maybe it's something we can discuss once we know more about the exact QOF specification for 23/24.
