### ISSUE TITLE
Is FP34 data included?

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#3945]
I have gotten a few questions recently about whether FP34 data is included

I think we should find out for definite (as we don't know for certain) and add to FAQS

**Comment by a-d-brown** [comment]
I've emailed the BSA to ask.

**Comment by a-d-brown** [comment]
Response from BSA confirms that FP34 data is included:

_"I can confirm that all items claimed for as part of FP34D/PD submissions are included in the English Prescribing Dataset. Please see the English Prescribing Dataset guidance which can be found on the link below, this shows what is and is not included within the data."_
 
[https://nhsbsa-opendata.s3-eu-west-2.amazonaws.com/English%20Prescribing%20Dataset%20Release%20Guidance%20v002.odt](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnhsbsa-opendata.s3-eu-west-2.amazonaws.com%2FEnglish%2520Prescribing%2520Dataset%2520Release%2520Guidance%2520v002.odt&data=05%7C01%7CANDREW.BROWN27%40NHS.NET%7C528d65d69c464fe8a75e08db2f6dcf24%7C37c354b285b047f5b22207b48d774ee3%7C0%7C0%7C638155920905315564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WLhKWxfdG3XR0jIaMlfSTyuhaXY5iTxAAeh4xuluSBk%3D&reserved=0)

**Comment by richiecroker** [comment]
https://github.com/ebmdatalab/openprescribing/pull/4031

**Comment by a-d-brown** [comment]
Approved updates to FAQ wording.
