### ISSUE TITLE
Remove "worst" reference for neutral measures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#400]
When `low_is_good` is null in a measure, we avoid any value judgement about the sort order.

Currently, we say the following on the page that shows all CCGs for a measure:

> CCGs are ordered by mean percentile over the past six months, with the worst-performing at the top

It should probably just say:

> CCGs are ordered by mean percentile over the past six months

**Comment by lmfrench** [comment]
I think it would be fine to remove 'worst-performing at the top' from all measures rather than doing extra work to make the neutral measures have different text. I can do this if you agree

**Comment by sebbacon** [comment]
Closed by #434
