### ISSUE TITLE
New measure: blood glucose test strips

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#4048]
NHSE have released new commissioning guidance on diabetes strips - on first glance it looks suitable for a measure

https://www.england.nhs.uk/publication/commissioning-recommendations-blood-glucose-and-ketone-meters-testing-strips-and-lancets/

We previously had a measure on the site for the low priority dashboard (NHSE didn't proceed with it for consultation) which may have useful code/text already there.

**Comment by richiecroker** [comment]
https://github.com/ebmdatalab/openprescribing/pull/4063
