### ISSUE TITLE
Add other old Newcastle CCGs to Newcastle Gateshead (13T)

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#408]
Newcastle CCGs merged. We currently only show Newcastle Gateshead on our dashboards (ignoring the error where Gateshead is still showing). 

A new code was not created when the CCGs merged, 13T was instead used as the code for the merged CCGs. For data prior to their merge, we only show data for the original 13T, and after the merge it is the data for all of them. It isn't clear to the user that this is what we've done. We should add the CCG data from the old CCGs to the CCG total. We also need to make a note somewhere (either on dashboard or FAQs) that this is what we've done

**Comment by lmfrench** [comment]
There were also changes to other CCGs in April:

- Cumbria CCG will become North Cumbria, Lancashire North will be Morecombe Bay. Both are keeping their old codes. Some practices in these CCGs are moving. User has been in touch to tell us which practices are moving into Morecombe Bay, and this should also be reflected in the ODS Quarterly update (May 26th)
- Manchester CCGs  (00W, 01M, 01N) are merging, new CCG will be Manchester CCG (14L)

Some GP Practices are also moving CCGs, full details here: https://digital.nhs.uk/organisation-data-service/news-and-updates and should be in the May 26th update.

**Comment by sebbacon** [comment]
Statement of problem:

```
┌──────┬──────────────────────────────────┬────────────┬────────────┐
│ code │               name               │ open_date  │ close_date │
├──────┼──────────────────────────────────┼────────────┼────────────┤
│ 00F  │ NHS GATESHEAD CCG                │ 2013-04-01 │ 2015-03-31 │
│ 00G  │ NHS NEWCASTLE NORTH AND EAST CCG │ 2013-04-01 │ 2015-03-31 │
│ 00H  │ NHS NEWCASTLE WEST CCG           │ 2013-04-01 │ 2015-03-31 │
│ 13T  │ NHS NEWCASTLE GATESHEAD CCG      │ 2014-11-26 │ ¤          │
└──────┴──────────────────────────────────┴────────────┴────────────┘

```

Currently:

* Measures use the current membership of a practice
* Analysis uses the membership of a practice as it was at the time

As I understand it, the solution is to change analysis to use current membership, as per Measures. To achieve this:

* The spending API displays current CCG membership but [queries on contemporary membership](https://github.co.m/ebmdatalab/openprescribing/blob/29fbf802dcc9983d6bc3f81f3887cf27eb8fc9f9/openprescribing/api/views_spending.py#L311). These should almost certainly match.
* All other table queries are based on views, which in turn use the `normalised_prescribing_*` views, which therefore should change to use current CCG membership in every case

A side-effect of this approach is that old CCGs will still show up for practices which have closed (which I presume is the case in issue #401).

Potential solutions for this:

* Attribute closed practices to the CCG that they would geographically be included in, were they still to exist (arguably the best solution?)
* Exclude closed practices from the CCG-level measures, but keep them in analyse charts (so we'll get tiny effects for some closed CCGs in some cases, a bit like the example in #401, but only for analyse charts)
* Exclude closed practices everywhere (so we lose some data)

**Comment by HelenCEBM** [comment]
I would vote for "Attribute closed practices to the CCG that they would geographically be included in, were they still to exist" because excluding the old code could leave a significant gap, if for example a large practice splits and is assigned two new practice codes. We just need to explain it clearly. 

I still like the idea of showing a population timeline for each practice and CCG so it's more clear when strange things are happening.

**Comment by richiecroker** [comment]
this is just an extension of the other problem, i.e. where does practice data go when it "closes".  Most of the time it merges with another practice.  Resolving this one would reduce a lot of the fossilised practice data we have.   In the meantime we should attribute to geographical area, as at a CCG level that is in effect the same as merging the practice data.

Also, this is clearly nonsense:

│ code │               name               │ open_date  │ close_date │
├──────┼──────────────────────────────────┼────────────┼────────────┤
│ 00F  │ NHS GATESHEAD CCG                │ 2013-04-01 │ 2015-03-31 │
│ 00G  │ NHS NEWCASTLE NORTH AND EAST CCG │ 2013-04-01 │ 2015-03-31 │
│ 00H  │ NHS NEWCASTLE WEST CCG           │ 2013-04-01 │ 2015-03-31 │
│ 13T  │ NHS NEWCASTLE GATESHEAD CCG      │ 2014-11-26 │ ¤      

13T, although allocated a code on 26th Nov 2014 wouldn't have been running until April 1st 2015...

**Comment by sebbacon** [comment]
This relates to #215

**Comment by sebbacon** [comment]
It turns out (notes [here](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/ccgmembership/CCG%20boundaries.ipynb)) that we can't accurately place practices in their CCGs by their location, because we don't have a reliable dataset of practice locations to use (we have to go on the centroids of the practice postcode, which will often place them in the wrong CCG where the postcode overlaps a CCG boundary).

Without accurate coordinates of practices, this approach will not be possible.

We are still likely to be able to place practices perhaps 75% of the time, but this is probably not really useful.

**Comment by sebbacon** [comment]
Now I'm trying to get the information [via an FOI](https://www.whatdotheyknow.com/request/gp_practice_codes_closures_and_m).

**Comment by sebbacon** [comment]
So according to the FOI response, PPD don't record the data in a database. (They just stuff the paperwork in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard).

Have tried PCSE who also, apparently, request almost the same information, via their "contact us" form, in early September - no reply.

**Comment by inglesp** [comment]
FOI to PCSE is here: https://www.whatdotheyknow.com/request/practice_mergers_and_closures_no#incoming-1108580.

**Comment by sebbacon** [comment]
Note I don't expect a successful response to that one. 

We will almost certainly have to come up with a solution that doesn't include mergers data.

**Comment by sebbacon** [comment]
Finally!  https://www.whatdotheyknow.com/request/practice_mergers_and_closures_no?nocache=incoming-1165255#incoming-1165255

**Comment by richiecroker** [comment]
@sebbacon i suspect the "effective date" is the one we want, as looking at it i think it refers to the date the merge actually happened - I suspect the "system merge date" is the date Capita merged the practices on the system (or not).

Either way, it shouldn't make too much difference, as we'll only see month granularity in the prescribing data.

**Comment by sebbacon** [comment]
Wrapped up into #891
