### ISSUE TITLE
Create labs measure for nitrofurantoin, per Quality Premium scheme

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#421]
This would probably be a labs measure, initially

See discussion in #382

**Comment by sebbacon** [comment]
Here's the mockup from the linked conversation:

![image](https://cloud.githubusercontent.com/assets/211271/25668170/d4bb366c-301d-11e7-9099-1acd61e5e1fe.png)

**Comment by HelenCEBM** [comment]
Deployed as measure
