### ISSUE TITLE
Labs: show a list of "where you are the most outliery" per CCG

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#423]
https://gist.github.com/sebbacon/d32c2fef3d0686a08ebe24804ed7b868

**Comment by sebbacon** [comment]
Idea: 

* Use analyses like the above to find a list of chemicals which have the most outliery behaviour
* For each of those, create a custom "labs" measure
* Similar analyses to find interesting measures
  * Numerator: section; denominator: astropu
  * See also Helen's outlierish analyses

**Comment by sebbacon** [comment]
Custom measures for some of these for 99P:

https://gist.github.com/sebbacon/6674e9ce9f08e88eb1c5ee96b15ab6d6

**Comment by HelenCEBM** [comment]
See also #890 (outliers by practice)

**Comment by richiecroker** [comment]
now live https://github.com/ebmdatalab/openprescribing/pull/3435
