### ISSUE TITLE
Bennett Bot reports that "op_deploy failed"

### ISSUE THREAD

**Issue by benbc** [ebmdatalab/openprescribing#4293]
A [Slack notification](https://bennettoxford.slack.com/archives/C31D62X5X/p1693840949575049) reported:

> Command `op_deploy` failed (find logs in /tmp/ebmbot/op_deploy/20230904-152225). Calling tech-support.

The corresponding `stderr` contains this:

```
Fatal error: No changes to pull from origin!

Aborting.
```

**Comment by inglesp** [comment]
Likely a blip.
