### ISSUE TITLE
Broken NHS Digital FAQ links

### ISSUE THREAD

**Issue by chrisjwood16** [ebmdatalab/openprescribing#4327]
Links on FAQ page to NHS Digital FAQ are no longer working and need an update. 
http://content.digital.nhs.uk/media/10048/FAQs-Practice-Level-Prescribingpdf/pdf/PLP_FAQs_April_2015.pdf

**Comment by speed-vm** [comment]
Update links for NHS digital Practice Level prescribing pages (Inc main page, more information and glossary)

[Practice level prescribing in England: a summary](https://digital.nhs.uk/data-and-information/areas-of-interest/prescribing/practice-level-prescribing-in-england-a-summary)

[More Information section](https://digital.nhs.uk/data-and-information/areas-of-interest/prescribing/practice-level-prescribing-in-england-a-summary/practice-level-prescribing-data-more-information)

[Glossary](https://digital.nhs.uk/data-and-information/areas-of-interest/prescribing/practice-level-prescribing-in-england-a-summary/practice-level-prescribing-glossary-of-terms)

**Comment by speed-vm** [comment]
Updated.
