### ISSUE TITLE
Change "per 1000 patients" denominator to "patients" on pop-ups

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#436]
This relates to the pop ups on the charts. 
![image](https://cloud.githubusercontent.com/assets/24392156/26066118/d18e2930-398d-11e7-98e5-a8a0dd21f4f6.png)
With whole numbers, for smaller practices population changes are mostly not distinguishable. E.g. in the image above, any change between 1,500-2,499 patients would not be apparent but could potentially affect the measures substantially. Also, for <500 patients it looks like there are zero patients.

**Comment by richiecroker** [comment]
I'd like it to say "patients", and give the number for that instead.  Any chance we can do that?

**Comment by inglesp** [comment]
If I've understood this correctly, a fix involves:

* For all "per 1000 patients" measures, changing the following fields in the JSON measure definitions:
   * `title` (eg from "co-proxamol per 1000 patients" to "co-proxamol per patient")
   * `description` (eg from "Prescribing of co-proxamol per 1000 patients" to "Prescribing of co-proxamol per patient")
   * `denominator_short` (from "1000 patients" to "patient")
   * `denominator_columns` (from "SUM(total_list_size / 1000.0) AS denominator, " to "SUM(total_list_size) AS denominator, ")
* For each such measure, update the corresponding `MeasureValue`s and `MeasureGlobal`s in the database:
   * multiply the `denominator` field by 1000
   * divide the `calc_value` field by 1000

I don't think we need to change any tables in BQ -- the only relevant tables are those used by the `import_measures` command, and these get overwritten on each import.

Is that right @sebbacon?

**Comment by sebbacon** [comment]
That all sounds correct.

**Comment by HelenCEBM** [comment]
I'm not sure we need to change that much - it is only the popup on the chart that looks odd when it says `1000 patients: 2` for example, and would be better saying `Patients: 2,435`. I'd say we want to keep the measures as per 1000 patients. What are your thoughts @richiecroker ?

**Comment by HelenCEBM** [comment]
I realise my title was misleading sorry! But as per issue description we were just wanting to change the pop-up on the charts.

**Comment by inglesp** [comment]
Aha, OK!

**Comment by alexwalkercebm** [comment]
I agree with Helen, I think it's still useful to have the denominator as per 1000 patients for the measure, but the pop up label needs to be per patient as is looks weird.

**Comment by richiecroker** [comment]
@helencebm is correct

**Comment by inglesp** [comment]
OK, so just to clarify... the only change required is that for measures where we currently say "1000 patients: N" in a pop-up, we should now say "Patients: N * 1000".  Is that correct?

**Comment by richiecroker** [comment]
No, currently it says "1000 patients: N/1000" and it should say "patients: N"

**Comment by inglesp** [comment]
Of course.

**Comment by inglesp** [comment]
Before (https://openprescribing.net/measure/fungal/practice/L83651/):

![image](https://user-images.githubusercontent.com/28734/35577506-a89f22ea-05d9-11e8-92fc-81416dbffda1.png)

After (http://staging.openprescribing.net/measure/fungal/practice/L83651/):

![image](https://user-images.githubusercontent.com/28734/35577539-bddd4cc2-05d9-11e8-8cdd-cc8cb61e46c9.png)

Is this what you're after?

**Comment by alexwalkercebm** [comment]
Yes, looks right to me.

**Comment by richiecroker** [comment]
Perfect ta

**Comment by HelenCEBM** [comment]
This is great! I just noticed that it doesn't apply to the low-priority compound measure though, is it possible to change that too @inglesp ?
