### ISSUE TITLE
Unsubscribe link possibly broken in OP email

### ISSUE THREAD

**Issue by bloodearnest** [ebmdatalab/openprescribing#4385]
Rich reported that the unsubscribe link in the email "just goes to the front page"

https://bennettoxford.slack.com/archives/C31D62X5X/p1698151383643319

**Comment by inglesp** [comment]
It works for me!

![image](https://github.com/ebmdatalab/openprescribing/assets/28734/30b8ccd9-1e40-4b16-ae32-21514452e4a3)

I clicked on the link at the bottom of the email:

![image](https://github.com/ebmdatalab/openprescribing/assets/28734/be25fd81-0b13-4877-8dfb-ef55f4f1f7bf)

@richiecroker what did you click on?

**Comment by richiecroker** [comment]
the same link!

**Comment by richiecroker** [comment]
I wonder if this is about Outlook safe links?
This is the URL I get from that button:
https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopenprescribing.us16.list-manage.com%2Ftrack%2Fclick%3Fu
(rest redacted)

**Comment by inglesp** [comment]
Could you DM me the full link?

**Comment by inglesp** [comment]
Thanks.  The request to https://gbr01.safelinks.protection.outlook.com/ redirects to https://openprescribing.us16.list-manage.com/track/click?u=XXX&id=YYY, which then redirects to http://feedback@openprescribing.net.

This matches the behaviour when I click on my link a second time.

So could you already have unsubscribed?

**Comment by richiecroker** [comment]
I don't know, I didn't get a page confirming it

**Comment by inglesp** [comment]
Hm.  You're still listed as being subscribed in the Mailchimp admin.

I'm going to close this, as I don't think there's much more we can do.

**Comment by evansd** [comment]
I think the issue might be that there are two footers, with two different sets of unsubscribe/update links.

The ones in the bottom most footer work correctly:
![image](https://github.com/ebmdatalab/openprescribing/assets/19630/6c876769-a1f9-4866-bb30-5fc51cb81813)
They are of the form:
`https://openprescribing.us16.list-manage.com/unsubscribe?u=[TOKEN]&id=[TOKEN]&e=[TOKEN]&c=[TOKEN]`
`https://openprescribing.us16.list-manage.com/profile?u=[TOKEN]&id=[TOKEN]&e=[TOKEN]&c=[TOKEN]`

The ones in the "inner" footer don't:
![image](https://github.com/ebmdatalab/openprescribing/assets/19630/2c3aa66f-4d92-4919-9aeb-f7ae7a7b77d6)
They are both of the form:
`https://openprescribing.us16.list-manage.com/track/click?u=[TOKEN]&id=[TOKEN]&e=[TOKEN]`

I imagine there's some magic string you're supposed to put as the link href in the template which gets substituted by MailChimp for the user-specific URL. And possibly we just haven't got that right.

**Comment by chrisjwood16** [comment]
I looked at this last time the newsletter went out, but because there was a long gap I'd forgotten about this. I don't think the unsubscribe links are needed within the black box because they are repeated below (and I'm not sure if there is a way to set them up anyway) - currently they have a slightly odd link 
![image](https://github.com/ebmdatalab/openprescribing/assets/96439159/f4d45b30-415b-4f09-a3f2-4e29e57ea10c)

Easy option here is just to remove them from the black footer and stick with the ones added by MailChimp. I've removed from template for next newsletter and will add a reminder to us to ensure not included in future newsletters.

**Comment by evansd** [comment]
I think the contents of the "Web address (URL)" should be `*|UNSUB|*` for the unsubscribe link and `*|UPDATE_PROFILE|*` for the update preferences link.

See:
https://mailchimp.com/help/the-unsubscribe-merge-tag/
https://mailchimp.com/help/add-an-update-your-preferences-link/

**Comment by chrisjwood16** [comment]
Great thanks! I've updated with these. Seems to work as far as I can tell from a test email.
