### ISSUE TITLE
Support BNF codes of different lengths in /analyse form

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#44]
Requested by Richard: "at moment can’t search for cephalsporins, quinolones, and co-amoxiclav as they are at different levels in the BNF hierarchy". 

https://openprescribing.net/api/1.0/spending_by_ccg/?format=json&code=4.3,0212000AA
is an example: support these kinds of queries, by aggregating queries across different materialised views.

**Comment by HelenCEBM** [comment]
closed in favour of #1099
