### ISSUE TITLE
alerts: best or worst performing in period is not aware of non-judgemental measures like DOACS

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#440]
The current logic will only show those in the "lowest" decile, but we want to show DOACS if it's in either the "lowest" or "highest".

**Comment by HelenCEBM** [comment]
Is this still not implemented? From sample of 2 November alerts, all non-judgemental measures appear to be in lowest decile, but the text says "top or bottom 10%" - think we should implement this change if possible as text implies that it will pick up top decile.

**Comment by sebbacon** [comment]
Yes, this has been implemented for a while. This month, there were 30 alerts where a non-judgemental measure was the most outliery in the section and it was in the lowest decile, and 63 alerts where it was in the highest.

* Example of the former ([email](https://openprescribing.net/admin/frontend/emailmessage/_3C20190129111801.3726.2604_40largeweb2.ebmdatalab.net_3E/change/?_changelist_filters=subject%3DYour%2Bmonthly%2Bupdate%2Babout%2BNHS%2BBuckinghamshire%2BCCG), [measure in question](https://openprescribing.net/measure/pregabalin/ccg/14Y/))
* Example of the latter  ([email](https://openprescribing.net/admin/frontend/emailmessage/_3C20190129103422.3726.6916_40largeweb2.ebmdatalab.net_3E/change/?_changelist_filters=subject%3DYour%2Bmonthly%2Bupdate%2Babout%2BNHS%2BSouth%2BKent%2BCoast%2BCCG), [measure in question](https://openprescribing.net/measure/doacs/ccg/10A/))

Please close this issue if I understood your concern correctly and it's OK!

**Comment by HelenCEBM** [comment]
Great, job done
