### ISSUE TITLE
Review generic desogestrel measure

### ISSUE THREAD

**Issue by a-d-brown** [ebmdatalab/openprescribing#4455]
Desorex is now cheaper than generic desogestrel, so the bold text from the 'Why it matters' of [this measure](https://openprescribing.net/measure/desogestrel/) is no longer correct:

Desogestrel is available as both generic tablets and as a number of brands. **For a time some of these brands were cheaper than the generic tablets**, so CCGs started to use them. However the price of the generic has now fallen **and is the cheapest option to prescribe.**

Possible solutions:

1. Edit to read as something like this:
Desogestrel is available as both generic tablets and as a number of brands. For a time, many of these brands were substantially cheaper than the generic tablets, so they were prescribed preferentially. However the price of the generic has now fallen and is amongst the cheapest options available to prescribe.

2. Retire the measure, acknowledging that most of the work on this has already been done by now.

3. Edit the measure to look at only brands costing more than generic, i.e. excluding Desorex. May require more long-term maintenance.

@richiecroker - do you have any preferred solution?

**Comment by richiecroker** [comment]
Would be interested to get the views of others (including @brianmackenna ) but my view would be that we could retire this measure, as this can also be found in the [PPU tool](https://openprescribing.net/sicbl/27D/price_per_unit/) where there is significant benefit.  I think OP has moved on a bit from this sort of measure, particularly where the "generic = cheapest" doesn't hold.

**Comment by brianmackenna** [comment]
Retire - PPU surpasses it.

Overall "generic" prescribing is the only worthwhile measure in this space IMO. Although we should keep an eye on it for tariff changes as there was a consultation about removing incentives for branded generics for commissioners.

**Comment by richiecroker** [comment]
OK, @a-d-brown can you retire (or create pull request to do so and I'll approve) please.  Can you also check current measures for any similar ones which we could also retire?

**Comment by a-d-brown** [comment]
[Pull Request here.](https://github.com/ebmdatalab/openprescribing/pull/4489)

And yeah I'll take a look to see if there's anything similar to retire.
