### ISSUE TITLE
Difficult presentation of alerts

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/openprescribing#449]
Comments/suggestions about the presentation and wording of alerts. It is difficult to auto-generate text that works well in all situations, as alerts are triggered for a number of reasons, including:
-being at an extreme end of the measure
-big, sudden increase in absolute prescribing for a measure
-small, persistent change in a measure
-change in peer prescribing
-very occasionally because of random noise or issues with data

**Comment by alexwalkercebm** [comment]
![image](https://cloud.githubusercontent.com/assets/24895935/26624591/3c32fe8e-45e9-11e7-89eb-e82ed90a196b.png)
this is an example of where the current text doesn't fit so well

**Comment by alexwalkercebm** [comment]
![image](https://cloud.githubusercontent.com/assets/24895935/26624686/887a789e-45e9-11e7-8b9f-92f03ac331d7.png)

Another example, though it may have triggered for the last couple of months, the change occurs over a longer period.

**Comment by sebbacon** [comment]
In the second example, the "2 months" is based on the last period of uninterrupted alerts. So in that case (barring a bug) there had been a stop in alerts 3 months ago, even if there had been slippage in months previous to that.

Perhaps we should remove the time period completely - not sure it adds anything.

**Comment by alexwalkercebm** [comment]
Are there any downsides to adding "in comparison with other practices/CCGs" after "slipped moderately"?

**Comment by sebbacon** [comment]
Yeh, I'll do something along those lines.
