### ISSUE TITLE
Understand BNF code publication scheme

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#456]
We've been informed that there's a single, annual publication of the NHS pseudo-BNF code list, which is published in January - the current year's release being known as BNF72. A code list is applied to prescribing data released from the date of the code list release (e.g. November and December 2016 for BNF 72).

However, the BNF does change in months subsequent to January. Fairly commonly, a small number of presentations are added, removed, or their names are modified. For example, between the versions published in March and April 2017, we saw changes including:

* Renaming: (ex: `Isosorbide Dinit_I/V Inf 10mg/10ml Amp` → `Isosorbide Dinit_Inj 1mg/ml 10ml Amp`
* Additions: (ex: `Mag Hydrox_Oral Susp 8%` (`0106040J0AAAIAI`))
* Deletions: (ex: `Gutron_Tab 5mg` (`0207020Y0BBABAD`)

In addition, we find the codes of some presentations changes entirely. For example, in the March 2017 prescribing data, `Mag Glycerophos_Tab Chble 97.2mg S/F` was identified by the code `0905013G0AADEDE`.  However, in the current BNF prescribing data, it has the code `0905013G0AAAYAY` (a code which does not appear in the current version of BNF 72 which can be downloaded from NHSBSA's website).

We checked with NHSBSA who said:

> New products/name changes/discontinuations happen throughout the year but the structure of the BNF coding only changes for January each year

Presumably the reference to "the structure of the BNF coding" is intended to mean that nothing up to the *product* level (i.e. the first 13 characters of the code) should change throughout the year. However, as described above, `Mag Glycerophos_Tab Chble 97.2mg S/F` had its full presentation code changed for the March prescribing data release.

In particular, if a code itself can change during the year, then the ["changes" file we were supplied in Jan 2017](https://github.com/ebmdatalab/openprescribing/files/1091589/BNF.Changes.xlsx) is now out of date, and we will be unable to track prescribing of `Mag Glycerophos_Tab Chble 97.2mg S/F` over time until a new such mapping file is released.

Our outstanding questions are:

* Is the description above accurate?
* Is the [BNF code list published by NHSBSA](https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=126) supposed to reflect all updates/deletions/additions for that month of prescribing data?  Or is there, for example, a lag between prescribing data being published and a new code list being published?
* How are complete code changes (like `Mag Glycerophos_Tab Chble 97.2mg S/F`) handled? Is the mapping file we were provided with updated throughout the year, or just at the end of each year?

**Comment by inglesp** [comment]
Looks like the name of the downloaded zip file contains a datestamp -- I've just downloaded 20170602_1496418406614_BNF_Code_Information.zip.
