### ISSUE TITLE
Specials: is there any guidance we can give?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#457]
The [largest saving opportunity in the country](http://staging.openprescribing.net/practice/P84049/price_per_unit/) is for one of the two practices in the country who are spending £225 on each Sulcalfrate Enema to spend what the other 6 practices are paying (£15 - £35 per enema). As it prescribes 120 of them, that's about £26,000 of savings in a month.

The vast majority of single cost-saving measures by practices are specials like this.

There are many less extreme examples (such as [this special](http://staging.openprescribing.net/ppu_histogram/0409020C0AAALAL/?date=2017-03-01&highlight=99P) and [this unlicensed special (part VIIIB) which is also imported](http://staging.openprescribing.net/ppu_histogram/0601040E0AABHBH/?date=2017-03-01&highlight=11M).

It's not clear how different prices for specials might be achieved, possibly because I know nothing about it! But we know many CCGs do need a bit of guidance.

How might savings be achieved in each of these cases?

**Comment by sebbacon** [comment]
Another example - this one a NP8 import - which is "costing" [one practice](http://staging.openprescribing.net/practice/F81213/price_per_unit/) £12,000 per month.

![image](https://user-images.githubusercontent.com/211271/27436743-1d9bf360-5758-11e7-83ab-b672cdda4ac8.png)

**Comment by sebbacon** [comment]
And [another practice](http://staging.openprescribing.net/practice/E82115/price_per_unit/) spending £8,500 too much a month on Metolazone 2.5mg tablets. Seems like the cheapest presentation there is a brand Zaroxolyn which is 18p for 14 tablets.

**Comment by Bengoldacre** [comment]
if savings from specials can't be achieved we should ?remove them or comment on that in the PPU paper.

**Comment by sebbacon** [comment]
So I've just worked it out and 61% of the total saving value (57% of the saving opportunities) in the top 100 practice-presentation opportunities are for specials, and 11% for imports.

**Comment by sebbacon** [comment]
Considerably less of an issue at the CCG level where only 2.4% of the saving opportunities in the top *1000* are imports or specials.

**Comment by richiecroker** [comment]
It's important we highlight them, and their inconsistencies.

There is an issue relating to specials in that, by their nature there is no consistency in how much pharmacies charge/are charged for them, and therefore how much CCGs pay for them.

It is out of control of the GP in the purest sense.  However, if a GP knows that "he" is being charged £225 per enema opposed to £15 for the same thing, he a) may consider checking whether he should be prescribing it, as unlicensed (and often GPs shouldn't be), b) talk to the patient or pharmacy about the costs, and c) phone up the CCG and complain, which may then facilitate the CCG to discuss further.

The really appealing thing to me here is *context*.  We all know in CCG-land that specials are expensive compared to commonly-available medicines.  BUT if we know that we're paying 20x more than everyone else, that would probably make me take a bit more notice.

Although these drugs are expensive in themselves, they are often very small numbers of items, and therefore get lost in the rosuva/pregabalin/fluticasone noise that is "usual" prescribing.

**Comment by sebbacon** [comment]
OK, then I suggest we add a little guidance to this effect (along the lines of: we can't help you decide what to do, but you should definitely investigate it).

Less clear if we should be including this data in the paper. What's your opinion?

**Comment by sebbacon** [comment]
Decided at meeting to keep specials in the paper but add a short discussion about them.
