### ISSUE TITLE
Should we make logarithmic scale the default?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#460]
Now we stack presentations, it's reasonably common for some presentations to be invisible on the chart.

**Comment by HelenCEBM** [comment]
I would lean towards no

**Comment by sebbacon** [comment]
Reasons please!  

Against: Log scale is not standard so unexpected

For: I've not got any examples right now, but I've seen a few cases where the mean PPU for a practice doesn't make sense because you can't see all the data points.
Also, I don't think people will be particularly interested in the y-axis over the x

**Comment by HelenCEBM** [comment]
I don't think it's worth the potential confusion if it's a small minority of cases. Though I still think we should think about a different way of presenting it. E.g. rather than y axis we could use size of data point / blob to indicate quantity..

**Comment by sebbacon** [comment]
Not sure what you mean re. different way? A series of differently-sized blobs all aligned at y=0, with x being PPU? Links to examples of the kinds of charts you mean would be helpful. Or even a photo of a scribble on a bit of paper.

I am struggling to think of something that illustrates volume and price perfectly.

**Comment by sebbacon** [comment]
If we're sticking with the current model, I'm still not convinced that using a log scale by default is wrong, on the grounds that I don't think people will be particularly confused: 

* most people won't care what the y-axis scale is
* when looking at numbers I think people will use the tooltips
* the y-axis is most useful for seeing which are the most popular price points; their size relative to each other is less important
* we can label it clearly for those that do ("frequency, log scale")

However, this is all speculation so I guess we should test it, one with the log scale, one without (cc @lmfrench)

**Comment by sebbacon** [comment]
Probably not necessary now we have a (slightly controversial!) minimum blob size.
