### ISSUE TITLE
Report of missing monthly updates

### ISSUE THREAD

**Issue by benbc** [ebmdatalab/openprescribing#4618]
@chrisjwood16 has asked for someone to investigate a report from an OpenPrescribing subscriber that she hasn't been getting monthly updates recently. Please could you follow this up?

Originally reported in [Slack](https://bennettoxford.slack.com/archives/CDT19RSV7/p1706050131372849).

**Comment by evansd** [comment]
Replied here:
https://bennettoxford.slack.com/archives/C051A4P27GE/p1707154930707459
