### ISSUE TITLE
OP deploy failed

### ISSUE THREAD

**Issue by benbc** [ebmdatalab/openprescribing#4619]
Bennett Bot [reports](https://bennettoxford.slack.com/archives/C31D62X5X/p1707150851504739) that an OP deploy failed.

Stderr says:

```
/opt/venv/lib/python3.12/site-packages/paramiko/transport.py:178: CryptographyDeprecationWarning: Blowfish has been deprecated
  'class': algorithms.Blowfish,
[31m
Fatal error: No changes to pull from origin!
[0m[31m
Aborting.
[0m
```

I'm not OP-savvy enough to know if that error is the actual cause of the failure.

**Comment by evansd** [comment]
I've seen this happen from time to time. _... Something something ..._ race condition in the delayed auto-deploy system.

_Very_ suspiciously however, the last time this happened was Sep 2023 when BenBC was on tech support. And then the time before that was 2019.

**Comment by evansd** [comment]
Oh, now it's happened again I think it's these PRs that are the culprits:
 * https://github.com/ebmdatalab/openprescribing/pull/4617
 * https://github.com/ebmdatalab/openprescribing/pull/4620

They've had `main` merged back into them and then something funny has happened. They have a status of `merged` but I can't see the corresponding event on the PR, and the associated branches have commits which `main` doesn't have. Very odd.

**Comment by benbc** [comment]
I can take myself off the Tech Support rota if that would help.

**Comment by evansd** [comment]
Was there a specific reason you re-opened this, Ben?

**Comment by benbc** [comment]
Because it happened again.

**Comment by evansd** [comment]
Ah, sorry, that was covered by my comment here:
 > Oh, now it's happened again I think it's these PRs that are the culprits
