### ISSUE TITLE
Non-bioequivalence: should we give stronger guidance?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#462]
Where brands are not necessarily bioequivalent, we are pulling this information from dm+d.

[example](http://staging.openprescribing.net/ccg/10Y/price_per_unit/):

On the ranking page:
![image](https://user-images.githubusercontent.com/211271/27530220-9ba8a5a6-5a4f-11e7-90af-36d460d57d11.png)

On the drug info page:
![image](https://user-images.githubusercontent.com/211271/27530258-c99e0e7e-5a4f-11e7-879f-380709dd3bbf.png)

* The example above is for a formulation switch. Is non-bioequivalence a potential issue for formulation swaps within brand, or just for any formulation between brands?
* Should we make this potential issue clearer at the top of the page?
* What is the answer to the question “why are you showing me this if I can’t change how I’m prescribing it”?

The meta issue here is how much guidance we should be giving. We can't really give accurate guidance because things are going to be different in each case. But on the other hand, giving *no* guidance where we could give basic guidance opens us to accusations of not providing pragmatic information.

**Comment by lmfrench** [comment]
I think it should be made clearer at top of page, particularly if we're going to keep the warning sign. When testing it, didn't know what it meant & thought the warning sign meant this was something they should pay more attention to.  We did have a bit of explanation on the pages at the time but it wasn't obvious, I think putting the symbol in the text as you've done here probably will help but unlikely that someone will scroll that far down
