### ISSUE TITLE
Use % rather than "per 1000" for suitable denominators in /analyse

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#47]
In queries like https://openprescribing.net/analyse/#org=CCG&orgIds=05F&numIds=4.3.3&denomIds=4.3 - where the numerator is a percentage of the denominator - Richard said this is odd and internally they would always use %. 

So add code to spot when the numerator is a % of the denominator, and update.

I think this is low priority.

**Comment by HelenCEBM** [comment]
closed in favour of #1099
