### ISSUE TITLE
Add logarithmic button to both graphs

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#473]
Toggle logarithmic button should also appear under prescribing by all practices graph, will make it easier for people to find

**Comment by lmfrench** [comment]
Comment from @alexwalkercebm 'Would a short sentence of explanatory text also help? e.g. "Graph looks weird? Try this toggle to make it more usable"' - agree this would be useful, most people won't know why the log scale would help

**Comment by sebbacon** [comment]
For now I'll just add the button -- because I think we should make the log scale the default anyway (see #460) -- so let's see what users reckon before doing any more.

**Comment by sebbacon** [comment]
This is probably not relevant now we're using bubble charts, as the bubbles have a minimum size.
