### ISSUE TITLE
Is a histogram the correct visualisation for PPU data?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#476]
I picked a histogram for the reasons below, but there's been some concern that this is confusing.  We should consider what the alternatives are, or if there are simple ways to make the current solution less confusing. We could also test if it's confusing with more end users.

----

> **TLDR**: the actual data is the best source of pragmatic alternative prescribing choices, but the actual data is messy and inconsistent, which requires grouping or reducing in some way (e.g. with a histogram).

We would expect a PPU for a presentation to be consistent across all dispensing in nearly every case:

* For something in the Drug Tariff which is prescribed generically, we would expect the PPU always to be consistent within any given month because the reimbursement price is set in the DT.
* For something prescribed as a brand, we would expect the PPU to be consistent because the reimbursement price is set as the list price (from dm&d).
* For something not in the DT and prescribed generically, we would expect a range of PPUs reflecting the underlying brands available.
* The **exceptions** are imports and specials, which are *expected* to have a wide range of PPUs ([example](http://staging.openprescribing.net/ppu_histogram/0601040E0AABHBH/?date=2017-03-01&highlight=11M)).

In theory, for all except specials/imports, the answer to the question "what should I do to save money" could be answered with reference either the list price or the DT price in the dm&d.

In that case, we could just present a standard column chart comparing the price for each presentation, listed in order of PPU.

However, in practice, this doesn't happen (see further down for examples):

* Generics in DT usually have a wide spread of PPU (albeit with 99% of the prescribing at the DT level)
* Sometimes brand prices also vary
* There are not always list prices available in dm&d

Once the PPU varies for each category, it starts to make sense to use a histogram rather than a simple column chart.  In particular, this makes sense for visualising what's happening with imports and specials -- there's no other way to know what prices people are obtaining other than inspecting the data.  It also makes sense for NP8 presentations to help understand why generic prescribing still results in a number of different price points.

We *could* adopt a hybrid approach: show a standard column chart for products which are not imports, specials or NP8 and *do* have list price data, and a histogram for the rest, though this would have the disadvantage of not showing the information consistently.

The other risk of showing options based on dm&d is that in practice some medicines may not be available. By basing the options-visualisation on actual prescribing, we're more likely to be able to suggest realistic alternatives.

# Examples of messy data

It is the rule, rather than the exception, for generically prescribed presentations to achieve a range of PPUs, even when in the DT.  These are randomly-picked examples for 11M:

## [Levetiracetam 500mg tablets](http://staging.openprescribing.net/ccg/11M/0408010A0AAABAB/price_per_unit/?date=2017-03-01)

Category M. Much variation in generic PPU, none in branded PPU:

![image](https://user-images.githubusercontent.com/211271/27681557-9804b01a-5cb7-11e7-9150-13616ffc710a.png)

## [Isosorbide mononitrate 60mg modified-release tablets](http://staging.openprescribing.net/ppu_histogram/0206010K0AAAEAE/?date=2017-03-01&highlight=11M)

Category C. Some (small) variation in brands; large variation in generic PPU

![image](https://user-images.githubusercontent.com/211271/27681759-24367ac8-5cb8-11e7-8ca0-f91dfe8c0965.png)

## [Lamotrigine 100mg tablets](http://staging.openprescribing.net/ppu_histogram/0408010H0AAAAAA/?date=2017-03-01&highlight=11M)

It's Category M. Very wide variation in generic prices. 

In 2016 Q4 (released Jan 2017) it was 0.0293 per pill
In 2017 Q1 (April 2017) it was 0.0286 per pill
In 2017 Q2 (July 2017) it was 0.0307 per pill

![image](https://user-images.githubusercontent.com/211271/27682778-b4fe5384-5cbb-11e7-833c-c436a65eb77c.png)

## [Venlafaxine](http://staging.openprescribing.net/ppu_histogram/0403040W0AAAEAE/?date=2017-03-01&highlight=11M)

Category M.  Wide variation in generic prices, narrow in brands.

![image](https://user-images.githubusercontent.com/211271/27683139-ead90084-5cbc-11e7-982f-e8ba3285b393.png)

## [Mirtazapine 15mg orodispersible tablets](http://staging.openprescribing.net/ppu_histogram/0403040X0AAALAL/?date=2017-03-01&highlight=11M)

Category M. Particularly large variation in generic prices.

![image](https://user-images.githubusercontent.com/211271/27683253-351b5aac-5cbd-11e7-80f2-a300e3be7f9a.png)

## [Latanoprost 50micrograms/ml eye drops](http://staging.openprescribing.net/ppu_histogram/1106000L0AAAAAA/?date=2017-03-01&highlight=11M)

This one is Category M (should have PPU of 0.4).

It has a very high variance in branded pricing as well as generic (note I've cropped the top off this; the vast majority of generic PPU is around 0.6).

![image](https://user-images.githubusercontent.com/211271/27683741-04fb2292-5cbf-11e7-914e-ef5a54dbbf5e.png)

**Comment by richiecroker** [comment]
So i've been taking a look at a few of these examples, and think I understand what's going on.

Where there are fluctuations in the average PPU for generic preparations that are in Category M or A of the Drug Tariff, these are likely to be due to the mean PPU between two prices.  

e.g. Sevelamer 800mg tablets:

The vast majority of these rx (5633 out of 5699) have a PPU of £0.27 - which is the correct Category M generic price: £48.87 for 100 tabs.
The next highest number of rx (46) has a PPU of £0.88, which doesn't seem to show anywhere in the Drug Tariff, but *is* the price of the [TEVA generic in the dm+d](http://dmd.medicines.org.uk/DesktopDefault.aspx?AMPP=28625111000001100&toc=nofloat)(180= £158.69). 

Why are some being priced at that?  I've no idea.

The other PPUs seem to be made of an a combination of the two:

e.g.
![image](https://user-images.githubusercontent.com/18683239/27790419-3f85fdac-5fe8-11e7-9036-2e6e442016a0.png)

has two rx of 84.

If you calculate that with one at PPU of £0.27 and one at PPU of £0.88:

((0.27*84)+(0.88*84))/168 = £96.60/168 = £0.58 (rounded up).

This works for others as well.

**Comment by richiecroker** [comment]
We have to accept that there will not be 100% accuracy in NHSBSA pricing.  I've been trying to get their latest pricing accuracy data, but it's currently not loading on the NHSBSA website.

Some of the issues I suspect are rounding of NIC.  e.g. Chemydur XL tabs 60mg are £3.49 for 28.
Depending on the number of tablets, the rounded NIC then the rounded PPU will vary between 12p and 13p per pill.

How can we fix it?

Is there the possibility of e.g. rounding up or down?
Could we strip (from national data) the outlying 1% (for example).

Does this then allow us to have columns charts, as opposed to histograms?

**Comment by sebbacon** [comment]
Rounding up or down is effectively what we're doing already by using histograms and a reasonable binning algorithm. The problem is that there are still outliers which don't make it to the bin a human might expect, and I think this is always going to happen when trying to correct for more-or-less random "errors" in the data.

Columns would still not work for specials, imports, and NP8 so I think we'd have to revert to a histogram for those?

If I understand you correctly, your concern is that someone viewing the charts as they currently exist might think "hang on, this generically prescribed sevelamer is appearing at a range of prices yet it is category C, so should only appear at one price, so I can't trust this data"?

If so, is it really better to tidy up the raw data in the hope of removing noise, which we won't be able to do consistently, than just to add an explanatory note?

**Comment by richiecroker** [comment]
Sorry, wasn't clear about rounding - i meant *always* either round up or down.
I am looking at this very much as an end-user, and was sat with my deputy looking at it last week.  It needs to be as simple and as *precise* as possible.

You've correctly described part of my concern, but it's not so much the range of prices, but the range of the bins.  Where we have big wide bins of 50p it makes me as an end-user doubt the quality of the site.

Could we not have hard bins, with e.g. 5p maximum range?

**Comment by richiecroker** [comment]
Biggest problem with all this is that, in my experience, if MO teams doubt the data on the first visit, they won't return.

**Comment by HelenCEBM** [comment]
Here's a rough idea of an alternative way to present the ranges of prices paid without relying on discrete bins. It separates out each brand/generic and also indicates the quantity in an approximate way (which is possibly a good thing because that's not the main point of the chart):
![image](https://user-images.githubusercontent.com/24392156/27794649-e3d83732-5ffa-11e7-9b8f-c0654468160e.png)

could also indicate bad-ness of cost using colour:
![image](https://user-images.githubusercontent.com/24392156/27794815-a1324bce-5ffb-11e7-85f4-729b23fa88ab.png)

**Comment by alexwalkercebm** [comment]
If we used Helen's approach above, we'd need to find a way of binning the values so that we know which to aggregate together into individual blobs.

Could we replace with a of box plot showing the median/IQR/range of PPU for each practice, for each drug?

Also, the order of drugs on the x-axis is relatively arbitrary/uninformative.

**Comment by sebbacon** [comment]
@richiecroker, yes we could try mandating a maximum bin size as a quick fix, and see if that would help.

For the record, [this](http://staging.openprescribing.net/ppu_histogram/0107020J0AAAEAE/?date=2017-03-01&highlight=99P) is the chart that triggered Rich's concern:

![image](https://user-images.githubusercontent.com/211271/27804317-2d3ed018-6026-11e7-884b-9011585e6b60.png)

**Comment by sebbacon** [comment]
Some other examples with fixed-width bins:
![image](https://user-images.githubusercontent.com/211271/27804675-1cf96a22-6028-11e7-908f-07735f27a9cf.png)

![image](https://user-images.githubusercontent.com/211271/27804686-302d0892-6028-11e7-8750-60f172203783.png)

**Comment by sebbacon** [comment]
Using bubble charts
