### ISSUE TITLE
Stop old CCGs appearing as outliers on Analyse results

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#479]
Since April old CCGs (Newcastle, Manchester) are appearing as outliers on some searches on the Analyse page. 

![image](https://user-images.githubusercontent.com/15875191/27733952-a15c7b64-5d90-11e7-9c1a-63fb80a7fa41.png)
https://openprescribing.net/analyse/#org=CCG&numIds=0703021Q0BB&denomIds=0703021Q0&selectedTab=summary

This appears to be caused by the closed practices still in the CCG:
![image](https://user-images.githubusercontent.com/15875191/27733964-b2bce47a-5d90-11e7-84d1-1f7f66651ea5.png)
https://openprescribing.net/analyse/#org=practice&orgIds=00F&numIds=0703021Q0BB&denomIds=0703021Q0&selectedTab=chart

The above search mentions Manchester CCGs in the screenshot as outliers even though it is a search for practices in Gateshead. If you click the link above it doesn't have this message at the bottom. This only appears if you first run this search, and then without refreshing change the search to practices:Gateshead CCG.

This message wasn't appearing on analyse before the April upload (I run the Cerazette/Desogestrel search in demos). 

Other examples:
https://openprescribing.net/analyse/#org=CCG&numIds=0601060D0BHABA0,0601060D0CUABA0&denomIds=6.1.6&selectedTab=summary
https://openprescribing.net/analyse/#org=CCG&orgIds=01Y&numIds=090402000BBQLA0,090402000BBRBA0,090402000BBRAA0,090402000BBQKA0,090402000BBQMA0&denomIds=9.4.2&selectedTab=chart

**Comment by sebbacon** [comment]
Relates to #408

**Comment by sebbacon** [comment]
Wrapped up into #891
