### ISSUE TITLE
Only include April 2013 data onwards in CCG downloads from Analyse page

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#480]
CCG downloads include data from 2012. This is most obvious when downloading data with total list size as the denominator, because it adds a list size of 0. Data for CCGs should be from April 2013 onwards

e.g.
https://openprescribing.net/analyse/#org=CCG&orgIds=03N&numIds=0401010AD&denom=total_list_size&selectedTab=summary

**Comment by HelenCEBM** [comment]
I think @inglesp has sorted all of this.
