### ISSUE TITLE
Iron Prescribing Measure

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#4832]
A user has suggested measure to support initiatives around reducing frequency of Iron dosing to once a day in line with [British Society of Gastroenterology](https://www.bsg.org.uk/clinical-resource/guidelines-iron-deficiency-anaemia-in-adults) guidance.

They have shared some more detail of a [deprescribing project here](https://docs.google.com/document/d/1bBgMSf6kzTI-aVFE7Tzn8cpdNNp51Pko/edit)

Is there anything we can do to capitalise on quantity data?

**Comment by richiecroker** [comment]
Discussed with CI team, looked at data, too ambiguous to find clear od or alt day prescribing, so unable to progress.

**Comment by richiecroker** [comment]
I looked at number of times each quantity of ferrous sulfate or ferrous fumarate were prescribed in the 12 months to April 2024:

![image](https://github.com/user-attachments/assets/951d0df5-9006-408f-b1d9-5002c4995e34)

The original request was
>someone asking could we do anything with alt day iron dosing on OpenPrescribing? either a measure or see if it is being implemented anywhere?
>bd / tds is bad ....... od / alt day fine/preferred

We could consider a measure of iron tablets over 28 in quantity.  However, given the large proportion of 56 tabs (and less so 84 tablets), we would not be able to confirm whether the 56 tabs are 1od for 56 days or 1bd for 28 days, and therefore the utility of the measure is limited.
