### ISSUE TITLE
Create a "what does this mean" resource for GPs

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#491]
Currently we provide a number of standard measures to GP practices and CCGs showing their performance.  What these measures don't show, however, is the specific drugs in the numerator that mean the practices/CCG are "poor".

It would be good to have a link on the measures page to show exactly the 10 highest items so that GPs know what to review.  It's also a useful check to make sure that the coding of drugs is correct.

It would be good if we could get it to be inline, looking a bit like this:
![image](https://user-images.githubusercontent.com/18683239/28028161-85bbd8b8-6593-11e7-8ec5-e62b1a047a90.png)

although a simple CSV download would be OK at this stage.

We've created some SQL for individual measures, e.g.
```sql
SELECT
  practice,
  bnf_name,
  SUM(items) AS items,
  sum(actual_cost) AS actual_cost
FROM (
  SELECT
    practice,
    bnf_name,
    SUM(items) AS items,
    sum(actual_cost) AS actual_cost,
    ROW_NUMBER() OVER (PARTITION BY practice ORDER BY SUM(items) DESC) AS pos
  FROM
    ebmdatalab.testdata.RC_prescribing_2016_Q4
  WHERE
    bnf_code LIKE '0407020Q0%AI'
    OR bnf_code LIKE '0407020Q0%DC'
    OR bnf_code LIKE '0407020Q0%EH'
    OR bnf_code LIKE '0407020Q0%DU'
    OR bnf_code LIKE '0407020Q0%AH'
    OR bnf_code LIKE '0407020Q0%DD'
    OR bnf_code LIKE '0407020Q0%EB'
    OR bnf_code LIKE '0407020Q0%DV'
    OR bnf_code LIKE '0407020Q0%DW'
    OR bnf_code LIKE '0407020Q0%AG'
    OR bnf_code LIKE '0407020Q0%DE'
    OR bnf_code LIKE '0407020Q0%EI'
    OR bnf_code LIKE '0407020AD%AR'
    OR bnf_code LIKE '0407020AD%AH'
    OR bnf_code LIKE '0407020AD%AI'
    OR bnf_code LIKE '0407020AD%AP'
    OR bnf_code LIKE '0407020AD%AQ'
    OR bnf_code LIKE '0407020AF%AD'
    OR bnf_code LIKE '0407020AG%AF'
    OR bnf_code LIKE '0407020AG%AG'
    OR bnf_code LIKE '0407020A0%AF'
    OR bnf_code LIKE '0407020A0%AG'
    OR bnf_code LIKE '0407020A0%AH'
    OR bnf_code LIKE '0407020B0%AF'
    OR bnf_code LIKE '0407020B0%AG'
  GROUP BY
    practice,
    bnf_name )
WHERE
  pos <=10
  and 
GROUP BY
  practice,
  bnf_name
ORDER BY
  practice,
  items DESC
```
It would be good to know if we could integrate somehow into the JSON for the measures so we ensure consistency in the BNF codes.

**Comment by sebbacon** [comment]
@richiecroker, would it be correct to say what we always want is a list of the top 10 numerators by total items (or quantity, or whatever the required `SUM` is for that measure)?

For things like co-proxamol, this would always be a list of one thing - would we still want to show it then?

If this is the case, it should be fairly simple to implement this and I'll do it ASAP.

Unfortunately for black triangle, because that's a special kind of compound measure, we'd have to deal with that as a special case.

----

For reference, the postgres version of this query is 

```sql
SELECT
  practice_id,
  presentation_code,
  SUM(total_items) AS items,
  SUM(actual_cost) AS actual_cost
FROM
  frontend_prescription
WHERE
  practice_id = 'L83106'
  AND processing_date = '2017-06-01'
  AND ( presentation_code LIKE '0407020Q0%AI'
    OR presentation_code LIKE '0407020Q0%DC'
    OR presentation_code LIKE '0407020Q0%EH'
    OR presentation_code LIKE '0407020Q0%DU'
    OR presentation_code LIKE '0407020Q0%AH'
    OR presentation_code LIKE '0407020Q0%DD'
    OR presentation_code LIKE '0407020Q0%EB'
    OR presentation_code LIKE '0407020Q0%DV'
    OR presentation_code LIKE '0407020Q0%DW'
    OR presentation_code LIKE '0407020Q0%AG'
    OR presentation_code LIKE '0407020Q0%DE'
    OR presentation_code LIKE '0407020Q0%EI'
    OR presentation_code LIKE '0407020AD%AR'
    OR presentation_code LIKE '0407020AD%AH'
    OR presentation_code LIKE '0407020AD%AI'
    OR presentation_code LIKE '0407020AD%AP'
    OR presentation_code LIKE '0407020AD%AQ'
    OR presentation_code LIKE '0407020AF%AD'
    OR presentation_code LIKE '0407020AG%AF'
    OR presentation_code LIKE '0407020AG%AG'
    OR presentation_code LIKE '0407020A0%AF'
    OR presentation_code LIKE '0407020A0%AG'
    OR presentation_code LIKE '0407020A0%AH'
    OR presentation_code LIKE '0407020B0%AF'
    OR presentation_code LIKE '0407020B0%AG')
GROUP BY
  practice_id,
  presentation_code
ORDER BY
  items DESC
LIMIT
  10;
```

**Comment by richiecroker** [comment]
short answer @sebbacon , yes.

**Comment by sebbacon** [comment]
I've done this by adding a link in the panel next to each measure:

![image](https://user-images.githubusercontent.com/211271/30873036-d6971b0c-a2e3-11e7-99a1-cb76ee88263d.png)

Which links to a table like this:

![image](https://user-images.githubusercontent.com/211271/30873065-eb368124-a2e3-11e7-8dfa-c8a5ba7173d3.png)

(with the chart at the bottom of the page)

Link (at least while it's on staging): http://staging.openprescribing.net/measure/glaucoma/practice/K82070/

**Comment by richiecroker** [comment]
@sebbacon that is amazing.  Deploy!  Deploy!

**Comment by Bengoldacre** [comment]
Glorious. Deploy!
