### ISSUE TITLE
CCG 13T has no name or boundary

### ISSUE THREAD

**Issue by barryrowlingson** [ebmdatalab/openprescribing#5]
Three CCGs:

```
NHS Newcastle North and East (00G)
NHS Newcastle West (00H)
NHS Gateshead (00F)
```

merged in April to form NHS Newcastle Gateshead, with the code 13T ( https://www.england.nhs.uk/resources/ccg-maps/ )

This exists in the system, but with no name or boundary... See:

https://openprescribing.net/ccg/13T

but the API returns blank for spending:

https://openprescribing.net/api/1.0/spending_by_ccg/?code=0212000AA&org=13T

If I query the API for all CCGs I get a few "null" things, and the entry for 13T with a null name:

https://openprescribing.net/api/1.0/org_code/?q=&org_type=CCG

I'm not sure what the right solution for the website/API is here... I can always resort to getting all GP spends and aggregating based on polygons for what I want to do...

**Comment by annapowellsmith** [comment]
Thanks for reporting. This is caused by the HSCIC data and our sources for CCG codes and boundaries getting out of sync. I'll take a look...

**Comment by sebbacon** [comment]
Now resolved. Sorry for the extremely long wait @barryrowlingson!
