### ISSUE TITLE
Update SNOMED/BNF mappings

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#502]
[DRUG_SNOMED_BNF_20170714.xlsx](https://github.com/ebmdatalab/openprescribing/files/1151882/DRUG_SNOMED_BNF_20170714.xlsx)

**Comment by dmcalli2** [comment]
Hello,
I came across this page on google as I am working with some routine heathcare data in SCotland and am keen to apply an ATC code based definition of comorbidity to the data.
If it is necessary for you to create this file as part of your tool, I wonder if you would be consider providing these mappings as a standalone resource, maybe on github somewhere, or as a link from your openprescribing webiste?
It would be hugely helpful for me, and I am sure many other researchers working with routine data.
I appreciate that it will not be possible to do a 1 to 1 mapping between all BNF codes and ATC codes, but it gets us a good way there.
Incidentally, I tried using the NHSBSA dictionary of medicines and devices, but could only find BNF code truncs when I downloaded their XML files and ran their tool.
Thanks very much for your time.
best wishes,
David
