### ISSUE TITLE
Retired measures need removing from website

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#5021]
We've recently retired a number of measures, and they need to be removed from the website:
dipyridamole
ulipristal
ktt12_diabetes_insulin
coproxamol

**Comment by richiecroker** [comment]
Sorry @inglesp @evansd I hadn't realised we've also got some _renamed_ measures where the "old" measure needs removing:

ktt9_cephalosporins_star
ktt9_cephalosporins
ktt9_antibiotics

**Comment by evansd** [comment]
All done :+1:
