### ISSUE TITLE
Incorrect savings for below median prescribing in Drugs for Erectile Dysfunction?

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#504]
The drugs for erectile dysfunction measure for 99P is showing at 22nd percentile.  However, it is still showing a large saving "if prescribed in line with median".

![image](https://user-images.githubusercontent.com/18683239/28309221-a2517e66-6ba0-11e7-9af2-c6b24b0097a1.png)

This seems fairly unclear across a number of CCGs:

![image](https://user-images.githubusercontent.com/18683239/28309568-ad1c318c-6ba1-11e7-8e07-bd1be25b1ec5.png)

Is this due to the cost/item being quite variable?

**Comment by sebbacon** [comment]
It looks to me like this is because the measure uses `items`, but the cost savings algorithm assumes `quantity`.

Is there any reason why `quantity` would not work as well as `items` in this case?

**Comment by sebbacon** [comment]
Comment from @richiecroker:

> quantity doesn't work unfortunately as there are two types of ED drugs, the "one when required" type, and the "take every day" type.  If you use quantity, the every day quantities will generally be higher per rx than the when required type

I don't think it's worth changing all the calculations unless we expect more "items-only" cost saving measures; I'd prefer simply to mark this as not-a-cost-saving-measure.

**Comment by richiecroker** [comment]
this still happening.  Can we just turn off the cost-saving bits please.

**Comment by inglesp** [comment]
@seb Do you just want me to cherry-pick e6698477b1e43b7a8d5cb78e7bbcae51c02cdefa?

**Comment by sebbacon** [comment]
Yeh! I started doing it yesterday, realised I'd done it on the wrong branch, got interrupted...  Thanks.
