### ISSUE TITLE
Asthma measures review

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#5081]
NICE have released new  guidance on asthma and there are quite substantial changes to treatment recommendations.

We should review our [respiratory measures](https://openprescribing.net/measure/?tags=respiratory) , specifically our SABA ones https://openprescribing.net/measure/saba/

**Comment by richiecroker** [comment]
Closed via:
https://github.com/ebmdatalab/openprescribing/pull/5083
https://github.com/ebmdatalab/openprescribing/pull/5084
https://github.com/ebmdatalab/openprescribing/pull/5088
