### ISSUE TITLE
Stop Central Manchester CCG appearing in Analyse Search Results

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#513]
Central Manchester appears in analyse search results. The dates it appears in differs e.g.

In [this search](https://openprescribing.net/analyse/#org=CCG&numIds=0703021Q0BB&denomIds=0703021Q0&selectedTab=summary) you can see it from Feb 16 - current

In [this search](https://openprescribing.net/analyse/#org=CCG&numIds=0212000AA&denomIds=2.12&selectedTab=summary) it appears from Nov 16 - current 

(Note: dates above refer to it appearing with no numerator data (so no bar), it might be visible with data in other months. I can't search with Central Manchester as the CCG - which is good - but it means I can't highlight in pink to find easily)

**Comment by sebbacon** [comment]
Tracking my progress on identifying the bug:

The view `vw__chemical_summary_by_ccg` does include a bunch of data right up to April:

```
127.0.0.1 prescribing@prescribing=> select processing_date, count(*) from vw__chemical_summary_by_ccg where pct_id = '00W' and processing_date > '2016-01-01' group by processing_date order by processing_date;
┌─────────────────┬───────┐
│ processing_date │ count │
├─────────────────┼───────┤
│ 2016-02-01      │   436 │
│ 2016-03-01      │   413 │
│ 2016-04-01      │   412 │
│ 2016-05-01      │   442 │
│ 2016-06-01      │   440 │
│ 2016-07-01      │   438 │
│ 2016-08-01      │   413 │
│ 2016-09-01      │   394 │
│ 2016-10-01      │   229 │
│ 2016-11-01      │   148 │
│ 2016-12-01      │   107 │
│ 2017-01-01      │    78 │
│ 2017-02-01      │    82 │
│ 2017-03-01      │    66 │
│ 2017-04-01      │    59 │
└─────────────────┴───────┘
```

The above results *do* match the data in BigQuery from which the view is generated:

![image](https://user-images.githubusercontent.com/211271/28526388-53f6082a-707f-11e7-92ef-adff2f33007e.png)

The corresponding most recent rows for `00W` in `normalised_prescribing_standard` show:

![image](https://user-images.githubusercontent.com/211271/28526550-bf5683c4-707f-11e7-88af-f436951e0acd.png)

If we focus on `P84676`, we can see that in the normalised view it is recorded as being in `00W` through April; but in the *base data* (the `prescribing` table) it is down as having changed to `14L` in April.

Since about a month ago, we've been using the `practices` table to compute current CCG membership.  In that table, `P84676` is recorded as being part of `00W` and also `dormant`.

**Comment by sebbacon** [comment]
In short, this appears to be a variation of the "closed practices" problem discussed in #479 and #408; what we are seeing here is all the prescribing for a single practice (the one still assigned to `00W`) going back through time.

We also see a few other practices which are now closed, per #408.

So: the question is if we should be applying the same fix described in #408 to dormant practices, as well as closed ones.

**Comment by sebbacon** [comment]
In May 2017 (the current prescribing data month). more than a third of CCGs had prescribing happening by dormant practices:

```sql
SELECT
  pct,
  COUNT(*)
FROM
  ebmdatalab.hscic.prescribing
INNER JOIN
  ebmdatalab.hscic.practices AS practices
ON
  practices.code = prescribing.practice
WHERE
  month = "2017-05-01"
  AND status_code = 'D' AND setting= 4
GROUP BY
  pct,
  month
ORDER BY
  pct
```
![image](https://user-images.githubusercontent.com/211271/28528357-61a230b0-7085-11e7-967b-d523b4c645f2.png)

Total prescribing by currently dormant practices declines over time:

![image](https://user-images.githubusercontent.com/211271/28528077-98b17530-7084-11e7-8b4b-70be894c8d0f.png)

...which query suggests that the problem of dormant practices is temporary, i.e. that things marked dormant in a given month continue to emit prescribing data for some time afterwards.  We know that data is recorded with the date when it is submitted to NHSBSA, not the date of the prescription. And spot checking historically dormant practices confirms that data peters out over about 3 months.

In the case of `00W`, there's an interesting situation where it is dormant *and* it has moved CCG.  Therefore, we should perhaps prefer the current month's CCG code over the current practices table's CCG code (*if* it is the case that the prescribing data is more likely to be up to date than the practices table).

```sql
SELECT
  month,
  practices.ccg_id AS membership_in_practices_table,
  prescribing.pct AS membership_in_data
FROM
  ebmdatalab.hscic.prescribing
INNER JOIN
  ebmdatalab.hscic.practices AS practices
ON
  practices.code = prescribing.practice
WHERE
  status_code = 'D'
  AND setting= 4
  AND practices.ccg_id != prescribing.pct AND month >= '2017-03-01'
GROUP BY
  month,
  practices.ccg_id,
  prescribing.pct
ORDER BY
  month,
  practices.ccg_id,
  prescribing.pct
```

![image](https://user-images.githubusercontent.com/211271/28528822-ba0a17ee-7086-11e7-9e0c-2e7f1f46c684.png)

**Comment by lmfrench** [comment]
Related: All of the Manchester CCGs still appear in the [All CCG](https://openprescribing.net/ccg/) lists if you search for Manchester

**Comment by sebbacon** [comment]
Currently blocked on #408

**Comment by sebbacon** [comment]
Wrapped up into #891
