### ISSUE TITLE
Make Manchester CCG Measures have the same start date as other CCGs

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#514]
Manchester CCG measures have a different start date to other CCGs:
![image](https://user-images.githubusercontent.com/15875191/28364126-20d4aac6-6c7b-11e7-874f-0e27025506fc.png)

Some measures go back to 2010 - I'm not sure if this is intended, I thought we were showing past 5 years. It isn't consistent though
e.g. [KTT9](https://openprescribing.net/measure/ktt9_cephalosporins/) is August 2010
[Diltiazem](https://openprescribing.net/measure/diltiazem/) is September 2011

On both of these pages Manchester goes back to June 2012, so it might be that Manchester is the only CCG working correctly

**Comment by sebbacon** [comment]
This was because old measure values had never been removed prior to the "rolling five years" change.

Fix:

    delete from frontend_measurevalue where month < '2012-05-01';
    delete from frontend_measureglobal where month < '2012-05-01';
