### ISSUE TITLE
Practices not geographically in their CCGs

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#528]
It's hard to find a clear definition in legislation of what exactly CCG boundaries are about. The clearest definition is [from the BMA](https://www.bma.org.uk/advice/employment/commissioning/commissioning-gps-guidance), which says:

> A CCG's geographical footprint must include all practices in an area and not contain 'gaps' within the boundaries. Once CCG boundaries are defined and finalised, the CCG or CCGs a practice is eligible to be a member of will be dictated by geography.
>
> While it would be feasible for a practice on the boundary of a CCG to change membership to a bordering CCG (thus retaining coherent geographical boundaries), practices in the centre of a CCG's locality would not have this option

However, we've found a large number of practices (particularly around Birmingham and Bradford) which are geographically outside the CCG of which they're a member -- all those marked red on this map:

![image](https://user-images.githubusercontent.com/211271/28818600-770a6674-76a3-11e7-8382-9ade143fd3d2.png)

For example, these are both assigned to 04X but are within the boundaries of 13P:

* https://openprescribing.net/practice/M85730/
* https://openprescribing.net/practice/M85097/

**Comment by lmfrench** [comment]
I've had a look at M85730 & M85097, and both used to be part of 13P - M85730 moved to 04X April 2016, and M85097 in June 2015

If you have a list of the practices not in the right boundary I can check whether they used to be

**Comment by sebbacon** [comment]
So it would seem that  a practice can choose to belong to any CCG within whose boundaries it practices.

A practice has both *inner* and *outer* boundaries. The *inner* boundary covers addresses of patients who must be accepted in a practice. The *outer* boundary is an expanded area within which registered patients can move without being compelled to re-register elsewhere. (To complicate matters, any patient has the right to apply to any practice).

The (approximate, uncleaned) inner boundaries are available [here](https://data.england.nhs.uk/dataset/gp-practice-submitted-inner-catchment-area-kml-file). In urban areas these boundaries overlap considerably; and the practice boundaries are not coterminous with CCG boundaries. Here we can see that M85097 covers CrossCity (`13P`) and Solihull (`05P`) and just touches South and Central (`04X`). My interpretation of the definitions I've read lead me to believe this gives the practice the right to be a member of any of these three CCGs:

![image](https://user-images.githubusercontent.com/211271/28817510-58ffb68c-76a0-11e7-84aa-f0e97695629b.png)

So, when it is near a CCG boundary, the location of a practice can't reliably tell us which CCG it is a member of.

Even if practice locations (rather than boundaries) defined CCG membership, there would still be issues, because a postcode-to-CCG mapping must always be approximate:

* CCG boundaries are coterminous with LSOA areas; 
* Practice locations are only defined with reference to postcodes; and
* Postcodes are not coterminous with LSOA areas

Therefore:

> postcodes are best-fitted [to LSOAs] by plotting the location of the postcode's mean address into the areas of the output geographies. 

([ONS postcode mapping file](https://ons.maps.arcgis.com/home/item.html?id=ef72efd6adf64b11a2228f7b3e95deea))

**Comment by sebbacon** [comment]
By coincidence, there was [an article](https://www.thetimes.co.uk/edition/news/patients-in-same-street-get-different-nhs-care-l09z6tjn2) about this in the Times today.

> People attending different GP practices in the same building face huge variations in waiting times for the same procedures
...
> The Times data team analysed the addresses of all English GP surgeries and found 120 pairs within 500 metres of each other that were governed by separate clinical commissioning groups (CCGs), the GP-led bodies that decide what the NHS will pay for locally.
>
> Many had identical postcodes and all are thought to accept patients from the same or overlapping areas, but provision varied wildly within the pairs.
...
> Under the Health and Social Care Act 2012, CCGs are responsible for paying for the NHS care of any patient registered at any of their member GP surgeries, but can set their own policies on what they will fund.
> 

>

**Comment by HelenCEBM** [comment]
I don't think this still needs to be an issue, no action necessary @sebbacon ?
