### ISSUE TITLE
Some chart labels are replaced by numbers

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#533]
http://staging.openprescribing.net/bubble/0601060D0AAA0A0/?date=2017-03-01&highlight=10Q

**Comment by lmfrench** [comment]
Updated link: https://openprescribing.net/ccg/10Q/0601060D0AAA0A0/price_per_unit/?date=2017-06-01

**Comment by HelenCEBM** [comment]
This was duplicated (and fixed) in #1050
