### ISSUE TITLE
Minor things to fix on PPU

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#555]
- Change "where" to "were" on CCG practice tables
`...no saving opportunities over £50 where identified for this product.`
https://openprescribing.net/ccg/10Q/0407041R0AAABAB/price_per_unit/?date=2017-05-01

- Can we right-align the numbers in the tables?

- Put commas in the headline savings `We have identified about £201900 of possible savings`

**Comment by lmfrench** [comment]
Have had a couple of comments through doorbell & twitter about making it clearer the price data might have changed since May

**Comment by lmfrench** [comment]
A user pointed out that the y axis sometimes extend to a negative value:

https://openprescribing.net/ccg/08H/0403040W0AAAEAE/price_per_unit/?date=2017-05-01
![image](https://user-images.githubusercontent.com/15875191/29319902-85c7e35a-81cd-11e7-8146-06675f483ed5.png)

**Comment by lmfrench** [comment]
Text on x axis sometimes overlap:

![image](https://user-images.githubusercontent.com/15875191/29625781-998c4b9e-8824-11e7-9ff8-786a68417384.png)
https://openprescribing.net/practice/E81061/0105010B0AAAAAA/price_per_unit/?date=2017-05-01
(Firefox, Chrome, IE11 tested)

**Comment by lmfrench** [comment]
Items are sometimes appearing twice:
https://openprescribing.net/practice/F82030/price_per_unit/

![image](https://user-images.githubusercontent.com/15875191/29723652-53be0a72-89bd-11e7-80e2-b1f50b84bdca.png)

**Comment by lmfrench** [comment]
Having now clicked through, this not just a problem with it duplicating in the table - on the presentation page it doubles the potential cost savings to £27200 (from £13,579 on the practice page). 

![image](https://user-images.githubusercontent.com/15875191/29723778-de3a6510-89bd-11e7-8243-ce40944cf962.png)
https://openprescribing.net/practice/F82030/1404000H0AAAFAF/price_per_unit/?date=2017-05-01

**Comment by HelenCEBM** [comment]
when looking on Safari on an iPad, on the chart showing the different drugs for a single practice, the drug names were cut off so only the top half of each word was visible. It looks fine on Chrome on PC though.
https://openprescribing.net/practice/M82005/040702040AAACAC/price_per_unit/?date=2017-05-01
![image](https://user-images.githubusercontent.com/24392156/29749096-8b78ed32-8b1c-11e7-8b31-022ab0fd775a.png)

**Comment by lmfrench** [comment]
Sometimes the data on the table for savings doesn't match the figure when you click through to the graph e.g.
https://openprescribing.net/ccg/99P/price_per_unit/ Pregabalin 300mg is listed at £15909 (June 2017), and when you [click through](https://openprescribing.net/ccg/99P/0408010AEAAAGAG/price_per_unit/?date=2017-06-01) it says £15400

**Comment by lmfrench** [comment]
Look at adding NCSO flag, in mean time add NCSO to FAQs

**Comment by lmfrench** [comment]
Spoken with NHSE & BSA about NCSO list - NHSE don't have the data "it's a DoH/BSA/PSNC interaction"), BSA [do publish](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-updates) but not in dm+d or BNF format

**Comment by sebbacon** [comment]
Closing in favour of new individual tickets
