### ISSUE TITLE
Finish and deploy low priorty measures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#567]
We've decided to keep these as a separate category of measures.

To provide a portal into them, make an omnibus measure which is a mean of all the other measures, and include that in the main list of measures.

We also need to decide if we include the individual measures or just the omnibus one in our alerts.

**Comment by richiecroker** [comment]
Will a mean work, given the differences in prescribing costs between e.g. tramacet and co-proxamol - won't it end up only focusing on the "bigger" problems?  And is that a problem?

**Comment by sebbacon** [comment]
I meant a mean of the percentiles

**Comment by HelenCEBM** [comment]
Wording issues:
- [ ] liothyronine: `Levothyroxine` shouldn't be capitalised if it's a chemical name
- [ ] tadalafil: remove extra word `20mg does dose`
- [ ] vaccines: re-word: `are not supposed which have been prescribed by practices in error.`
- [ ] dosulepin: 'dothiapen` should be dothiapin; could be phrased better.
- [ ] rrimipramine: misspelled in title? (not sure what it should be).
- [ ] lutein and antioxidants: add comma `(e.g. vitamin A, C E and zinc)`
- [ ]  paracetamol and tramadol combination: `Tramadol` shouldn't be capitalised mid-sentence as it's a chemical name.
- [ ] omega-3 fatty acid compounds: spell out acronym? `CV events`
- [ ] oxycodone: remove extra full stop and capitalisation of Naloxone.
- [ ] glucosamine: remove extra full stop
- [ ] homeopathy: `... found homeopathy not evidence based and based on a placebo effect.` Hyphenate evidence-based; could be worded better, e.g `...found no evidence that homeopathy has any effect other than as a placebo`

**Comment by HelenCEBM** [comment]
Link back to useful previous pages such as http://staging.openprescribing.net/ccg/10Q/?tags=lowpriority:
- [ ] on CCG comparison pages, e.g. http://staging.openprescribing.net/measure/lpliothyronine/
- [ ] and practice comparison pages, e.g. http://staging.openprescribing.net/ccg/10Q/lpglucosamine/

**Comment by sebbacon** [comment]
* [ ] Create Gluten Free measure

**Comment by lmfrench** [comment]
- [ ] The 'Why it matters: View the individual  measures here' link on the all Practices in a CCG page keeps you on the same page rather than taking you to the individual measures list  e.g. For Oxford this links to http://staging.openprescribing.net/ccg/10Q/lpzomnibus/?tags=lowpriority instead of http://staging.openprescribing.net/ccg/10Q/?tags=lowpriority
