### ISSUE TITLE
Investigate failing smoketest after 2017_06 import

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#573]
```
call_command ('run_smoketests', '2017_06')
...........F
======================================================================
FAIL: test_presentation_by_one_practice (pipeline.smoketests.TestSmokeTestSpendingByOnePractice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 82, in test_presentation_by_one_practice
    PRESCRIBING_DATA_MONTHS)
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 41, in _run_tests
    self.assertEqual(len(all_rows), expected_total)
AssertionError: 61 != 60

----------------------------------------------------------------------
Ran 12 tests in 10.474s

FAILED (failures=1)
```

**Comment by inglesp** [comment]
The CSV file at https://openprescribing.net/api/1.0/spending_by_practice/?format=csv&code=0703021Q0BBAAAA&org=A81015 contains data for 2012-07-01 to 2017-06-01, but also an extra row for 2012-03-01.

The API response uses this query:

```
SELECT pr.practice_id AS row_id,
       pc.name AS row_name,
       pc.setting AS setting,
       pc.ccg_id AS ccg,
       pr.processing_date AS date,
       SUM(pr.actual_cost) AS actual_cost,
       SUM(pr.total_items) AS items,
       CAST(SUM(pr.quantity) AS bigint) AS quantity
FROM frontend_prescription pr
JOIN frontend_practice pc ON pr.practice_id=pc.code
WHERE (pr.presentation_code LIKE %s)
  AND (pr.practice_id=%s)
GROUP BY pr.practice_id,
         pc.code, date
ORDER BY date, pr.practice_id
```

and it looks like there is data in the database from 2012_03:

```
127.0.0.1 prescribing@prescribing=> select count(*) from frontend_prescription where processing_date = '2012-03-01';
┌──────────┐
│  count   │
├──────────┤
│ 10168363 │
└──────────┘
```

But there is nothing from 2012_04:

```
127.0.0.1 prescribing@prescribing=> select count(*) from frontend_prescription where processing_date = '2012-04-01';
┌───────┐
│ count │
├───────┤
│     0 │
└───────┘
```

**Comment by inglesp** [comment]
2012_03 is the only month before five years ago that's in the database.

This data should have been deleted by `drop_oldest_month` when `import_hscic_prescribing` was run.

It looks like the partition is still there:

```
> select relname from pg_inherits join pg_class on pg_class.oid = pg_inherits.inhrelid where pg_inherits.inhparent = 'frontend_prescription'::regclass order by relname;
┌──────────────────────────────┐
│           relname            │
├──────────────────────────────┤
│ frontend_prescription_201203 │
│ frontend_prescription_201207 │
│ frontend_prescription_201208 │
...snip...
│ frontend_prescription_201704 │
│ frontend_prescription_201705 │
│ frontend_prescription_201706 │
└──────────────────────────────┘
(61 rows)
```

`drop_oldest_month` should drop the partition from five years ago, and delete any `PracticeStatistics` from that month.

There are no `PracticeStatistics` objects from 2012_03:

```
>>> PracticeStatistics.objects.filter(date='2012-03-01').count()
0
```

This suggests that `drop_oldest_month` did run, but the partition didn't get dropped.

**Comment by inglesp** [comment]
It's just occurred to me that 2012_03 isn't actually five years ago.

Could this just have been missed in April this year?  Have we actually seen the smoke tests pass recently?

**Comment by sebbacon** [comment]
Yes, I think this could have been missed in April. In the past when the import process failed, resuming the process was manual so it was quite easy to resume it incorrectly - and I do recall a bug relating to dropping the oldest month at some point in the last 6 months.

Every month there have been several things wrong with the smoketests which I have fixed, but I'm ashamed to admit I've often got near the date of the next import when progressing through the fixes and thought "I'll fix that one next time", without keeping a record.

So - I'll fix this by deleting the offending partition, and I think we'll see it all working next month.
