### ISSUE TITLE
List more than one generic product for PPU formulation swaps

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#579]
We only list one product as being prescribed generically when we have an item with a formulation swap e.g. 
https://openprescribing.net/ccg/06Y/0403040W0AAAEAE/price_per_unit/?date=2017-06-01
This lists Venlafaxine_Cap 150mg M/R as generic, but isn't listing Venlafaxine_tab 150mg M/R

If you go to the page for the tabs: https://openprescribing.net/ccg/06Y/0403040W0AAAKAK/price_per_unit/?date=2017-06-01 it still lists only the caps as generic

**Comment by HelenCEBM** [comment]
Appears to be fixed
