### ISSUE TITLE
Implement Trends tool on OP

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#588]
| Page | Embed Link |
| --- | --- |
|  `openprescribing.net/pca` | `<div class='tableauPlaceholder' id='viz1506442689570' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506442689570');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1243px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/antipsychotics` | `<div class='tableauPlaceholder' id='viz1506443311761' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Anti-Psychotics&#47;Anti-Psychotics&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-Anti-Psychotics&#47;Anti-Psychotics' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Anti-Psychotics&#47;Anti-Psychotics&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443311761');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/antidepressants` | `<div class='tableauPlaceholder' id='viz1506443384483' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Antidepressants&#47;Antidepressants&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-Antidepressants&#47;Antidepressants' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Antidepressants&#47;Antidepressants&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443384483');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/thyroid` | `<div class='tableauPlaceholder' id='viz1506443224018' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-ThyroidHormones&#47;ThyroidHormones&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-ThyroidHormones&#47;ThyroidHormones' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-ThyroidHormones&#47;ThyroidHormones&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443224018');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/testosterone` | `<div class='tableauPlaceholder' id='viz1506443188995' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Testosterones&#47;Testosterone&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-Testosterones&#47;Testosterone' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Testosterones&#47;Testosterone&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443188995');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/quinine` | `<div class='tableauPlaceholder' id='viz1506443265722' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Quinine&#47;Quinine&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-Quinine&#47;Quinine' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-Quinine&#47;Quinine&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443265722');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |
|  `/pca/nicotine` | `<div class='tableauPlaceholder' id='viz1506443346786' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-NicotineDependence&#47;Antidepressants&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrends-NicotineDependence&#47;Antidepressants' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrends-NicotineDependence&#47;Antidepressants&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506443346786');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1220px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>` |

**Comment by HelenCEBM** [comment]
Testing options for Thyroid hormones using main dashboard:
view: `https://public.tableau.com/shared/S2JJKJJ3F?:display_count=yes`
original: `https://public.tableau.com/views/PrescribingTrendsmulti-functionforOP/TRENDSDETAIL?:embed=y&:display_count=yes`

embed view:
`<div class='tableauPlaceholder' id='viz1506506169146' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;S2&#47;S2JJKJJ3F&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='path' value='shared&#47;S2JJKJJ3F' /> <param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;S2&#47;S2JJKJJ3F&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506506169146');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1243px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>`

Embed original:
`<div class='tableauPlaceholder' id='viz1506506246298' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='path' value='views&#47;PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL?:embed=y&amp;:display_count=y' /> <param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsmulti-functionforOP&#47;TRENDSDETAIL&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1506506246298');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1243px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>`

**Comment by HelenCEBM** [comment]
Final plan: embed on a single page only. The subject-specific dashboards will be available via Tableau directly instead.  `<div class='tableauPlaceholder' id='viz1507036021896' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsfnalforOP&#47;TRENDSDETAIL&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='2' /> <param name='site_root' value='' /><param name='name' value='PrescribingTrendsfnalforOP&#47;TRENDSDETAIL' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;PrescribingTrendsfnalforOP&#47;TRENDSDETAIL&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1507036021896');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1120px';vizElement.style.height='1243px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>`

## Explanatory text
This is an interactive tool for exploring the national Prescribing Cost Analysis (PCA) data. It shows annual data, going back to 1998, on all drugs *dispensed* in the community in England (note this makes it slightly different to the monthly dataset used elsewhere on OpenPrescribing). Here we have ensured that most drugs have a consistent classification over time, based on their *current* position in the latest BNF dictionary, so that time trends are not disrupted by drugs being reclassified, for example moving between Chapters. All figures are adjusted for England's population size and costs are corrected for inflation.

**Comment by HelenCEBM** [comment]
add: "Our paper describing this tool and the normalisation of the data is currently under review at BMJ Open"

**Comment by HelenCEBM** [comment]
# FAQ section
### How is this different to the data on the rest of the site?
This tool uses Prescription Cost Analysis (PCA) data back to 1998, all items dispensed in England, whereas the data used elsewhere on the site shows what was *prescribed*. This data can’t be split down to months or practices but shows useful long-term trends. 

### How can I share the view I created?
Scroll to the bottom right, then:
- To share the dashboard as a link for someone else to access, or to save for later, select **Share**. If you have made changes then "Current View" will be selected. Copy the link:
![image](https://user-images.githubusercontent.com/24392156/31814267-03bf8fc4-b581-11e7-8374-a9f7ee72f272.png)
- To share the view as an image or PDF, select **Download** and select your preferred option.

### Can I download the data?
You can download the entire dataset, either the compiled original data or our normalised data, from [FigShare](https://figshare.com/articles/NHS_prescription_cost_analysis_data_1998-2016/5447194)

**Comment by HelenCEBM** [comment]
Video walkthrough (currently published as private, to be reviewed)
<iframe width="560" height="315" src="https://www.youtube.com/embed/7IBOywY_fj8" frameborder="0" allowfullscreen></iframe>

**Comment by sebbacon** [comment]
@HelenCEBM is there anything else to do on this? If not, please feel free to close!
