### ISSUE TITLE
Things to fix on measure-breakdown pages

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#595]
* [x] Link from measure overview page for Omnibus measure is broken (https://openprescribing.net/measure/lpzomnibus/)
* [x] Also on that page "number of areas which should not routinely prescribed in primary care" is missing a "be"
* [x] We are using BNF truncated names rather than full DMD names. Would be nice to use the latter
* [x] There should be a link to breakdown from each CCG panel in main measure page (e.g. https://openprescribing.net/measure/doacs/)
* [x] The breakdown page for a practice should not provide a "split this measure down by practices" link
* [x] The breakdown page for a practice should not provide a "break the denominator down" link (i.e. a link to itself...)

**Comment by sebbacon** [comment]
* [ ] Ensure importing measure definitions updates `tags_focus`
* [ ] No link to individual measures here: http://staging.openprescribing.net/ccg/10Y/lpzomnibus/

**Comment by lmfrench** [comment]
- [ ] Add option to download

**Comment by lmfrench** [comment]
- [ ] Link in preview to alert emails to low priority measures doesn't take you to the correct place e.g. takes you to https://openprescribing.net/ccg/08M/#lprubefacients

**Comment by sebbacon** [comment]
@lmfrench can you clarify? Don't understand! Maybe with screen shot?

**Comment by lmfrench** [comment]
In the alert emails, you get a link to the measures that are good/bad. When you click the link, it greys out the rest of the CCG dashboard and moves you down to the measure you clicked. 

The low priority measure links take you to the normal measures page rather than the low priority dashboard (and the measure isn't on that page so it doesn't grey out and move you to the measure you clicked). Can't screenshot because all it does is take you to the normal dashboard.

**Comment by sebbacon** [comment]
ah ok, so you mean if it's one of the broken down LP measures? I think we should only include the ominbus in alerts in any case...

**Comment by sebbacon** [comment]
* [ ] Don't include individual LP measures in monthly alerts

**Comment by lmfrench** [comment]
Why not? Someone in the presentation I did yesterday was interested init  - they'd done some work on it so were pleased to see it come up as one of the 'improving' measures

**Comment by sebbacon** [comment]
I think it needs more thought, because these measures are still out for consultation and we mark them as "experimental"; they run the risk of crowding out more "important" measures from the alerts.

But yes, I think ultimately they should be included in some form.

**Comment by sebbacon** [comment]
* [ ] On the main measure page ([example](http://staging.openprescribing.net/measure/lpdosulepin/)), it would be good to link to the numerator breakdown table, like we do on the [broken-down-by-practice equivalent](http://staging.openprescribing.net/ccg/07J/ktt9_cephalosporins/)

**Comment by sebbacon** [comment]
These are all the affected pages to review!

* [All CCGs for one measure](http://staging.openprescribing.net/measure/lpdosulepin/) (Low priority measure)
* [All CCGs for one measure](http://staging.openprescribing.net/measure/keppra/) (Core measure)
* [All CCGs for one measure](http://staging.openprescribing.net/measure/lpzomnibus/) (Omnibus measure)
* [All core measures for one CCG](http://staging.openprescribing.net/ccg/07J/)
* [All LP measures for one CCG](http://staging.openprescribing.net/ccg/07J/?tags=lowpriority) 
* [All measures for one Practice](http://staging.openprescribing.net/practice/N85003/)
* [All LP for one Practice](http://staging.openprescribing.net/practice/N85003/?tags=lowpriority)
* [All practices for one measure](http://staging.openprescribing.net/ccg/07J/keppra/) (Core measure)
* [All practices for one measure](http://staging.openprescribing.net/ccg/07J/lpzomnibus/) (Omnibus measure)
* [All practices for one measure](http://staging.openprescribing.net/ccg/07J/lpdosulepin/) (LP measure)
* [Numerator breakdown for one practice](http://staging.openprescribing.net/measure/ktt3_lipid_modifying_drugs/practice/N85003/) (Core measure)
* [Numerator breakdown for one CCG](http://staging.openprescribing.net/measure/ktt3_lipid_modifying_drugs/ccg/07J/) (Core measure)

**Comment by lmfrench** [comment]
For 'All CCGs for one measure' would be good to add a link to a practice breakdown at the same time (or change it so the CCG hyperlink on the top takes you there - see #520)

All CCGs for one measure (Omnibus measure) and All practices for one measure (Omnibus measure) don't have a link, but I don't think it is meant to?

**Comment by sebbacon** [comment]
Thanks. To your second point: yes, we can't easily break down an omnibus (too big a query), unfortunately.

**Comment by lmfrench** [comment]
Suggestion from presentation last week - would like to see the BNF codes in the tables to make it easier to replicate in ePACT if they want to
