### ISSUE TITLE
PubMed scraper

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#612]
Use cases:
* Paper describing prevalence of trial ID in clinical trials in pubmed (either in the `Accession Number` field or parsed from the Abstract field based on matching against the ISCTR trial ID list)
* Tool for ranking journals by time-to-publication 

Possible implementations:
* Command line tool taking pubmed search query as input and creating database table as output; also with "update" option
* One massive bigquery implementation of all of PubMed

Notes:
* There are about 30k clinical trials a year - our sample will be about 200k records.

**Comment by benmeg** [comment]
FYI, PubMed now offers a bulk download (with daily updates): https://ncbiinsights.ncbi.nlm.nih.gov/2017/06/22/pubmed-available-for-download-without-license/

**Comment by sebbacon** [comment]
The starter search is

    ("randomized controlled trial"[Publication Type] OR (randomized[Title/Abstract] AND controlled[Title/Abstract] AND trial[Title/Abstract])) AND ("2006/06/01"[Date - Publication] : "2017/17/10"[Date - Publication]) NOT (review[Publication Type] OR editorial[Publication Type] OR meta-analysis[Publication Type] OR practice-guideline[Publication Type])

**Comment by sebbacon** [comment]
Initial approach, using bigquery, documented [here](https://github.com/ebmdatalab/pubmed-trialids)
