### ISSUE TITLE
nondeterministic bigquery failures

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#622]
This is to collect these as and when we see them (/cc @inglesp)

**Comment by sebbacon** [comment]
```
======================================================================
ERROR: setUpClass (frontend.tests.commands.test_import_measures.BigqueryFunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/test/testcases.py", line 1037, in setUpClass
    cls.setUpTestData()
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 198, in setUpTestData
    cls._createData()
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 494, in _createData
    table.insert_rows_from_csv(prescribing_fixture_path)
  File "/code/openprescribing/gcutils/bigquery.py", line 182, in insert_rows_from_csv
    job = self.gcbq_table.upload_from_file(f, **options)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 1110, in upload_from_file
    raise exceptions.from_http_response(exc.response)
BadRequest: 400 POST https://www.googleapis.com/upload/bigquery/v2/projects/ebmdatalab/jobs?uploadType=resumable: No schema specified on job or table
```
(from [here](https://travis-ci.org/ebmdatalab/openprescribing/jobs/298050307))

**Comment by sebbacon** [comment]
@inglesp actually this doesn't look nondeterministic - I'm reproducing reliably. Can you take a look?

**Comment by inglesp** [comment]
:fire:

**Comment by inglesp** [comment]
I'm baffled here.

The failing line is in `test_import_measures.py`, which is trying to insert data from CSV into the `test_normalised_prescribing_legacy` table in the `measures` dataset.

This table does not exist.

But nor does the `normalised_prescribing_legacy` table.

(The full list of tables is at https://bigquery.cloud.google.com/dataset/ebmdatalab:measures)

So where have they gone?  [This](https://travis-ci.org/ebmdatalab/openprescribing/builds/296290336) was the last successful build, on 2017-11-02.

**Comment by inglesp** [comment]
I'm getting a horrible feeling about this...

The new `backup_prescribing` task has been run precisely once, and the timing is suspicious:

```
>>> from pipeline.models import TaskLog
>>> TaskLog.objects.filter(task_name='backup_prescribing').count()
1
>>> tl = TaskLog.objects.filter(task_name='backup_prescribing').first()
>>> tl.ended_at
datetime.datetime(2017, 11, 1, 12, 57, 58, 533356, tzinfo=<UTC>)
```

But no, that's bollocks (I think/hope).  We're talking about different tables, and I can't see how the code in https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/pipeline/management/commands/backup_prescribing_table.py can do any damage!

**Comment by inglesp** [comment]
And actually, the timing's not suspicious at all!  The last successful build was after the backup ran.  Am just feeling a bit paranoid!

**Comment by sebbacon** [comment]
Hmm. I don't recall how the tests are/were set up, but `normalised_prescribing_legacy` when used in the  main app is a *view*, not a table.

I'm not looking at it right now, just quick comment in case you still are. I wonder if the views were never set up in a fixture and then something changed...

Good to be paranoid!
