### ISSUE TITLE
We haven't downloaded anything for prescribing_metadata since 2017_03

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#628]
The `prescribing_metadata` source uses the [`hscic_prescribing`](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/pipeline/management/commands/hscic_prescribing.py) fetcher.

The fetcher worked by searching for "presentation level data", ordered by "Most+recent", at http://content.digital.nhs.uk/searchcatalogue, following a link to the first relevant search result, and downloading three CSV files (`TyyyymmADDR BNFT.CSV`, `TyyyymmCHEM SUBS.CSV`, `TyyyymmPDPI BNFT.CSV`).

We only have data for 2017_03, but the files have a timestamp from 2017-09-26.

This suggests that either the search results weren't ordered as we'd expected, and so we were repeatedly misidentifying the 2017_03 data as the most recent data.

However we cannot check this hypothesis, as the search page no longer exists.  (The fetcher failed during the 2017_08 import, which is how I noticed that something was wrong here.)

Writing a new scraper will be straightforward; less straightforward is working out what to do about having missed five months (2017_04 to 2017_08) of prescribing metadata.

**Comment by inglesp** [comment]
##### `import_hscic_chemicals`

For each record in the `TyyyymmCHEM SUBS.CSV` file, this gets or creates a `Chemical` record with the corresponding BNF code, and then sets the `chem_name` field.

There are 3480 records in the August file, and we lack corresponding `Chemical` records for 22 of them.

**Comment by inglesp** [comment]
##### `import_practices`

For each record in the `TyyyymmADDR BNFT.CSV` file, this gets or creates a `Practice` record.

There are 9747 records in the August file, and they all have corresponding `Practice` records.

**Comment by sebbacon** [comment]
> There are 3480 records in the August file, and we lack corresponding Chemical records for 22 of them

It would be useful to make a list of these.

If we can track them down, there may be a better route to filling in these gaps than the `prescribing_metadata` route. (Note: it will likely take a long time to track them down, if at all...)

**Comment by inglesp** [comment]
Fixed by #634.
