### ISSUE TITLE
Investigate Basic-Auth errors on staging

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#63]
Our staging API will not allow requests from the staging site, even though the origin in the same. As a result we can't mimic behaviour on production, because all API requests are disallowed. 

This is mysterious, but of limited interest. The easiest way to deal with this may be to disable Basic-Auth on the API using nginx.

**Comment by sebbacon** [comment]
I'm going to time box this to 30 mins, by debugging direct on the staging server.

**Comment by sebbacon** [comment]
To reproduce:

200:

    curl -s 'http://staging.openprescribing.net/' -H 'Authorization: Basic
dGVjaDpVZFByPm00Vw==' -o /dev/null -D -


403:

    curl -s 'http://staging.openprescribing.net/api/1.0/org_location/?p=1'
-H 'Authorization: Basic dGVjaDpVZFByPm00Vw==' -o /dev/null -D -

**Comment by sebbacon** [comment]
It seems this is nothing to do with Basic Auth, as we continue to see the problem when that is switched off.  A new data point is that if we switch Cloudflare to "development mode" (i.e. turn off caching) we get the same behaviour in the production flavour:

    $ curl -s 'https://openprescribing.net/api/1.0/org_code/?org_type=CCG&q=boggle'  -H 'Authorization: Basic dGVjaDpVZFByPm00Vw==' -o /dev/null -D -
HTTP/1.1 403 Forbidden
Date: Mon, 06 Jun 2016 09:18:19 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d8a5083cf4a2527af8354bc60d5beb9061465204699; expires=Tue, 06-Jun-17 09:18:19 GMT; path=/; domain=.openprescribing.net; HttpOnly
Vary: Accept, Cookie
Allow: OPTIONS, GET
Server: cloudflare-nginx
CF-RAY: 2aeac6bd68690b81-LHR

**Comment by sebbacon** [comment]
So it *was* something to do with Basic Auth; cloaked by the fact that you apparently get a 403 if you send nginx auth headers when there's no auth required.

Closing this as per @annapowellsmith's preference to just not have HTTP auth for the staging server.
