### ISSUE TITLE
refresh_class_currency does not refresh Presentations

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#666]
In [`import_hscic_prescribing`](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_hscic_prescribing.py#L102-L124), we set the `is_current` flag to `True` on any `Section`, `Chemical`, or `Product` that we haven't seen before.

However, we don't do so for `Presentation`s.

Assuming this isn't deliberate, we should:

* Add `(Presentation, 'bnf_code')` [here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_hscic_prescribing.py#L108-L112)
* Run something to ensure `is_current` is set correctly for `Presentation`s.  There are currently ~34k `Presentation`s with `is_current` set to `False`, so I'm not sure how best to do this efficiently.
 * One idea: list all distinct BNF codes in the `hscic.prescribing` table in BQ, and compare against the list of BNF codes for entries in the `Presentation` table.

**Comment by inglesp** [comment]
* Got a list of BNF codes in BQ's `hscic.prescribing` table using `SELECT bnf_code FROM hscic.prescribing GROUP BY bnf_code ORDER BY bnf_code`
  * There are 49,220 such codes
* Got a list of BNF codes for `Presentation`s with `is_current` set to `False` using `SELECT bnf_code FROM frontend_presentation WHERE is_current = false ORDER BY bnf_code`
  * There are 34,253 such codes

Comparing the two lists show that there are 297 `Presentation`s that are not marked as current, but that should be.  See [to_be_marked_as_current.txt](https://github.com/ebmdatalab/openprescribing/files/1513271/to_be_marked_as_current.txt).

**Comment by sebbacon** [comment]
For the record, these changes were introduced in #380
