### ISSUE TITLE
Add Feb data on production

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#67]

**Comment by annapowellsmith** [comment]
Also to BQ

**Comment by annapowellsmith** [comment]
And make any improvements / automation to the process as seems appropriate!

**Comment by sebbacon** [comment]
@annapowellsmith I think you said you have some raw notes you follow for adding data. Can you point me at them?

**Comment by annapowellsmith** [comment]
Done!
