### ISSUE TITLE
Spend showing x1000 on y axis when not using denominators

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#673]
When using the spend chart on the analyse page without denominators, the y-axis is showing a scale x1000 greater than it should.  For example this scale should read 0-2000, not 0-2m.

![image](https://user-images.githubusercontent.com/18683239/33426994-9e107868-d5bb-11e7-9d8d-2c8173052af8.png)

**Comment by sebbacon** [comment]
For the record [this](https://openprescribing.net/analyse/#org=practice&orgIds=01H&numIds=0309010L0AAAHAH&denom=nothing&selectedTab=summary) is the query in question

**Comment by HelenCEBM** [comment]
- This issue now reported by a user
- Also, if you zoom on the spending chart and then reset the zoom, the scale and the bars appear even more incorrect - here the bars appear the same size even though displaying different values on hover [(link)](https://openprescribing.net/analyse/#org=CCG&numIds=0212000V0&denom=nothing&selectedTab=summary&hideOutliers=true):
![image](https://user-images.githubusercontent.com/24392156/35870150-d0806772-0b58-11e8-9ac1-6911e28ba3ac.png)
This is a bit similar to problems with chart encountered after playback of map (issue #681) 
- Show/hide outliers doesn't seem to have any effect.

**Comment by inglesp** [comment]
[This line in chart_utils.js](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/media/js/src/chart_utils.js#L221) seems to be the culprit, and removing it (on staging!) fixes [the chart that @richiecroker reported](http://staging.openprescribing.net/analyse/#org=practice&orgIds=01H&numIds=0309010L0AAAHAH&denom=nothing&selectedTab=summary).

However, it then seems to break other charts where the denominator is not "nothing", such as [this one](http://staging.openprescribing.net/analyse/#org=practice&orgIds=01H&numIds=0309010L0AAAHAH&denomIds=0309010L0AA&selectedTab=summary).

By analogy with the [`ratio_items` calculation](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/media/js/src/chart_utils.js#L213-L215), I think we should only scale `ratio_actual_cost` by 1000 when the denominator is not "nothing", but I don't fully understand what's going on here, so would like @sebbacon's input.
