### ISSUE TITLE
Investigate pack size (Estriol in particular) and consider fixes

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#676]
Per [this comment](https://github.com/ebmdatalab/price-per-dose/issues/12#issuecomment-348983680) (and the following one), there is a potential pack size issue which *might* be the result of human error (I think it's unlikely but worth checking).

Check with @richiecroker - and if this was result of human error, see if there are any improvements we could make to our manual reconciliation process.

Also, add any relevant info to https://github.com/ebmdatalab/price-per-dose/issues/12.

If not the result of human error, consider if/how we should fix errors like this when we see them.  Usually, NHSBSA correct errors when we point them out, but only for future data releases - they rarely fix historic data.   It may be a good idea to maintain a table of "pack size corrections" which we apply in bigquery when generating measures / prescriptions tables; also link to a publicly accessible version of this table from our FAQ, with explanation.

**Comment by richiecroker** [comment]
fixed by ODD
