### ISSUE TITLE
Refactor dropdown javascript so it doesn't keep breaking

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#683]
The way the dropdown activation is implemented (for the primary navigation) means it's very easy to forget to include it on new pages.

Currently it is broken at https://openprescribing.net/tariff/.

Fix it there, in a manner that makes it harder to screw up again in future.

**Comment by sebbacon** [comment]
Previously fixed by including [the entire openprescribing.js script](https://github.com/ebmdatalab/openprescribing/pull/409/files).

**Comment by HelenCEBM** [comment]
mentioned by a user via email yesterday

**Comment by sebbacon** [comment]
Fixed in #689
