### ISSUE TITLE
Duplication of influenza vaccine in price-per-unit

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#686]
Influenza vaccine is appearing twice in the price-per-pill report:
![image](https://user-images.githubusercontent.com/18683239/33935430-cfa035b6-dff3-11e7-8637-65e1c5d1d721.png)

**Comment by sebbacon** [comment]
This is related to how we join to the dm+d products table.

Some BNF codes are matched to more than one SNOMED code. This is one such example.

Question: which of the two options that match `1404000H0AAAFAF`would be correct in this case?

```
┌───────────────────┬───────────┬───────────────┬──────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       dmdid       │   vpid    │ concept_class │         product_type │                                                name                                                 │
├───────────────────┼───────────┼───────────────┼──────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│         348047008 │ 348047008 │           VMP │              Generic │ Influenza vaccine (surface antigen, inactivated) suspension for injection 0.5ml pre-filled syringes │
│         348046004 │ 348046004 │           VMP │              Generic │ Influenza vaccine (split virion, inactivated) suspension for injection 0.5ml pre-filled syringes    │
└───────────────────┴───────────┴───────────────┴──────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by sebbacon** [comment]
Just to note in the BNF/SNOMED mapping we're given, 
Incidentally, the BNF name is `Influenza_Vac Inact 0.5ml Pfs` in both cases - so I guess we are unable to distinguish between split virion and surface antigen vaccines in prescribing data.

**Comment by richiecroker** [comment]
Short answer is, we don't know which are being used.  They're clinically the same:
https://patient.info/doctor/influenza-vaccination#nav-4

e.g. Agrippal is surface antigen: https://www.medicines.org.uk/emc/product/1541
Enzira is split virion: https://www.medicines.org.uk/emc/product/391

But interchangeable.

**Comment by richiecroker** [comment]
What other things have >1 matching?

**Comment by sebbacon** [comment]
There's lots of solution/suspension for example. [Here](https://gist.github.com/sebbacon/24f2777842292b49e83afb530cbd0d67) are some BNF codes for the 1520 generic items that appear more than once for you to knock yourself out with!

(First column is the count of the number of appearances)

Taken from this spreadsheet:

[Converted Snomed - BNF.XLSX](https://github.com/ebmdatalab/openprescribing/files/1559299/Converted.Snomed.-.BNF.XLSX)
