### ISSUE TITLE
STAR-PU Calculations

### ISSUE THREAD

**Issue by glfharris** [ebmdatalab/openprescribing#7]
Not sure if you're still looking for this, but I knocked up a star-pu calculator by practice for the weightings I could find on http://www.hscic.gov.uk/prescribing/measures.

Anyway it's at https://github.com/glfharris/starpu if it would be useful.

**Comment by annapowellsmith** [comment]
Awesome, thank you for this!

There are a few things we'd need to do before we can use this in the main codebase: 

1. Add tests - tedious and slow but vital. I think we need one test per STAR-PU. We should manually calculate the expected value of the STAR-PU for a random practice, and then write a test to check that the calculated value from the library matches the expected value. 

2. Use quarterly list size data - the BSA publishes some going back to April 2013, which is what we currently use. (If we could find annual data going back to 2010, I could be persuaded that we should use that instead. But so far I haven't been able to find either quarterly or annual data pre-2013. NHAIS Exeter has some older data, but it doesn't match the age bands used for STAR-PUs, so is no use for our purposes.)

We'd also need to add CCGs once the above is fixed. 

This is a great start, thank you!

**Comment by annapowellsmith** [comment]
Hello! I just wanted to let you know that I used your code for parsing the Excel file in this commit: https://github.com/ebmdatalab/openprescribing/commit/ee39524d3115cb50b732978a16c1f230cdf5db9e

We should shortly be adding STAR-PUs to the API methods on production, and then hopefully making them available via the front-end. 

Thanks very much for contributing this, it saved a lot of time!

**Comment by glfharris** [comment]
Hey! Thank you, glad I could help out!
Cheers,
George
On 4 Feb 2016 4:54 p.m., Anna Powell-Smith <notifications@github.com> wrote:Hello! I just wanted to let you know that I used your code for parsing the Excel file in this commit: ee39524

We should shortly be adding STAR-PUs to the API methods on production, and then hopefully making them available via the front-end. 

Thanks very much for contributing this, it saved a lot of time!
