### ISSUE TITLE
Remove list sizes pre-2013 for CCGs

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#70]
At least until we figure out a way to backfill presentation/chemical data for CCGs pre-2013. 

This is because while we have list size data for the period, but no prescribing data, the graphs show misleading/unhelpful trends.  

For example: 
https://openprescribing.net/analyse/#org=CCG&numIds=0205051I0&denom=total_list_size&selectedTab=chart

And https://openprescribing.net/ccg/11E/ - the antibiotics charts look broken. 

I think the best way to get around this is simply to remove the list size data from the database.

**Comment by lmfrench** [comment]
Analyse chart still looks broken, but I don't think it is for the same reason - now from 2010-2013 the graph is at 0, would be better if those graphs started in 2013
(Antibiotics chart looks fine)

**Comment by sebbacon** [comment]
Yep, closing in favour of #385
