### ISSUE TITLE
Synchronise all postgres tables to BigQuery

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#713]
It's important that the team can do ad-hoc queries with up-to-date data.

In the past I've done this with direct access to postgres, but I think doing it via BigQuery is better, because then we don't have to think or worry about bad queries taking the website down, etc.

So I propose that we alter our monthly process to back up all tables to BigQuery.

These should probably append rather than replace; for performance (and to extent, UI) reasons we limit a lot of data in postgres to the last 6 years.

**Comment by sebbacon** [comment]
In addition, we have a specific request from @HelenCEBM to provide `practice_statistics` going back to 2010, which it might make sense to address as part of this issue

**Comment by sebbacon** [comment]
Just checking (from datalab meeting) - did this include the monthly thing for @HelenCEBM and if so can you point her at it - thx!

**Comment by inglesp** [comment]
[hscic.practice_statistics_all_years](https://bigquery.cloud.google.com/table/ebmdatalab:hscic.practice_statistics_all_years) has data for 2010-10-01 to 2017-10-01.  (I don't know where this came from!)

[hscic.practice_statistics](https://bigquery.cloud.google.com/table/ebmdatalab:hscic.practice_statistics) just has the last five years, currently for 2012-12-01  to 2017-11-01.

@HelenCEBM is this enough?  Or would you prefer `hscic.practice_statistics_all_years` to have all the data?  (And if so, how urgently?)

**Comment by HelenCEBM** [comment]
See issue #723 - i made the `hscic.practice_statistics_all_years` table as a sort of temporary fix but all of the historical data from there should be combined into `practice_statistics` and updated monthly

**Comment by inglesp** [comment]
Closing in favour of #723 and #734.
