### ISSUE TITLE
Some numerators are not up to date for October

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#720]
OK:
* Chapter
* Paragraph
* Section
* Chemical 

Not OK:
* Product
* Presentation

**Comment by sebbacon** [comment]
Strange - this implies there's something wrong with the `frontend_presentations` table, yet the data is there:

```sql
SELECT
  pr.processing_date,
  pc.code,
  SUM(quantity)
FROM
  frontend_prescription pr
JOIN
  frontend_practice pc
ON
  pr.practice_id = pc.code
WHERE
  presentation_code LIKE '0703021Q0BBAAAA%'
  AND pr.processing_date = '2017-10-01'
GROUP BY
  pc.code,
  pc.name,
  pr.processing_date
ORDER BY
  pr.processing_date,
  pc.code ASC
LIMIT
  5;
```

**Comment by sebbacon** [comment]
My mistake: this is for the "by CCG" grouping option which queries `vw__presentation_summary_by_ccg`, and is indeed short of October,

**Comment by sebbacon** [comment]
As described in #711, last month's view creation was done by hand, presumably leading to this oversight.

Now running the following command in a screen session:

```
python manage.py create_views --view presentation_summary_by_ccg --settings=openprescribing.settings.production
```

**Comment by inglesp** [comment]
@sebbacon What's the status of this?

**Comment by sebbacon** [comment]
thx for nudge
