### ISSUE TITLE
NHS19 graphs financial savings button not working

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#725]
We've had a comment from South Devon and Torbay CCG, that the button for potential savings in the NHS19 graphs doesn't work:
![image](https://user-images.githubusercontent.com/18683239/34818698-7f9f5dcc-f6b3-11e7-9e2f-b99b36440b82.png)

Instead it leads to the page being blank of all graphs.

We currently don't calculate potential savings for these markers  - is it something we should do?

**Comment by sebbacon** [comment]
Example URL: https://openprescribing.net/ccg/04M/?tags=lowpriority

**Comment by evansd** [comment]
I've tried to address the "doesn't work" part by showing a warning message (see below) and created a new ticket (#927) to track the more substantive question.

![localhost_8000_ccg_04m__tags lowpriority](https://user-images.githubusercontent.com/19630/42330079-3b31fbcc-806a-11e8-859f-0fbcab70ebdb.png)
