### ISSUE TITLE
EPIC: Start to investigate alerts

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#73]
There is background in the Health Foundation doc in gdrive. 

- Investigate where we might get email addresses for GPs
- Think about the architecture needed to monitor for alertable events and send emails
- Write a tech document about the architecture
- Do some sketches of how the experience might look for a GP, ready for Lisa to test

**Comment by sebbacon** [comment]
* I've done some initial research about contact details and written it up [here](https://docs.google.com/document/d/1oys-t6VEGapJys2tCX0i6zhgXQVohlFspY141ZaU-Zs/edit#heading=h.eq8ew9eubtff)
* Written a scraper for NHS Choices data (as it looks likely we'll want it somehow anyway, and it will give us some base data to play with) [here](https://github.com/ebmdatalab/openprescribing-data/blob/master/fetchers/nhs_choices.py) and running it over the weekend

**Comment by sebbacon** [comment]
Initial thoughts.

My reading of our original proposal is that the following alerts are required on the following conditions:

1. a specific practice goes above or below X% in a given measure
2. a specific CCG goes above or below X% a given measure
3. any practice in a specific CCG goes abvoe or below X% in a given measure
4. a practice or ccg slips by more than X% over period Yin a given measuure

The obvious implementation is:
1. create an "alerts" table that joins alert criteria (notification_email, time period, threshold, granularity) to each measure
2. iterate over each alert; decide if an alert should be sent, and if so, send them
3. provide a UI for creating, reviewing and managing alerts
4. this could be implemented with user registration & login, or only via emails which contain management URLs

Technical problems
* The basic measures infrastructure is already there. The limiting factor is likely to be the time it would take to compute each measure, as the most obvious implementation is to allow users to create their own measures.
  * The current architecture for measures performs an aggregate search for each practice for each month. 
  * This is indexed and fast (3ms).  We have 13,500 practices (NB I thought there were 8,000 practices in England?); recomputing the measures for cerazette for a single month takes 226 seconds.
  * So what is the upper bound on what we can achieve with the current architecture? I guess we want to be able to alert people within, say, 2 weeks of us updating the data, which (based on the cerazette example) would allow us to process 5352 measures
* If we were to allow users to design their own measures, note that at the moment measures are defined with raw SQL on the filesystem; presumably we'd just allow them to "save" analyses via the analyse page, and nothing more 
* Postgres tends to use close to 100% of one core when processing queries. This may starve other resources.

Alternative implementations:
* Elasticsearch based (using something like [this](https://github.com/Yelp/elastalert). Would require running an ES instance. We're probably not have the space on our current server - would require about 60Gb. Would be a big bit of work so there would have to be other benefits (q.v. #74)
* Parallelise the measure-computing work using a concurrency framework such as [Google Dataflow](https://cloud.google.com/dataflow/service/dataflow-service-desc). We'd presumably get a very big speedup on the per-practice computations, but there would be associated ongoing monthly costs, and again this would be a fairly large bit of work.

**Comment by sebbacon** [comment]
Notes from call. Possible types of alert:

* Set up alerts for any arbitrary analysis (a.k.a. roll-your-own-measures)
* Set up alerts for any predefined measures
* Opt into canned alerts digest based on predefined measuers
* Automatic datamining: you as a practice are an outlier on this arbitrary thing
  * For each chemical, compute distribution of practice count within its BNF paragraph
  * If it's a normal distribution, identify outliers and notify them
    * Noob question: why as a proportion? Why wouldn't absolute count be interesting?

**Comment by annapowellsmith** [comment]
Re question: absolute count will depend heavily on how many patients you have, and what type of patients they are.

**Comment by annapowellsmith** [comment]
Classifying this as "blocked" while we work on #74.

**Comment by annapowellsmith** [comment]
NB: Seb has discovered that CCGs have comprehensive lists of all practices on their patch with up-to-date staff addresses - these should be regarded as the definitive source.

**Comment by annapowellsmith** [comment]
Closing in favour of #143 - and Seb wrote up this in more detail in the spec document: https://docs.google.com/document/d/1Nlg_3xEtD77p9rodNRwW9VETLSS6xsH0KQP0_DnvpJs/edit?usp=drive_web
