### ISSUE TITLE
Review BigQuery synch

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#734]
* [x] Is  PPU synchronised?
* [x] Drug Tariff and NCSO should be synchronised on any change

**Comment by sebbacon** [comment]
@inglesp more queries coming up in the meeting...

**Comment by inglesp** [comment]
PPU isn't yet; NCSO is; and DT will be once #735 is deployed.

**Comment by inglesp** [comment]
PPU savings are now at https://bigquery.cloud.google.com/table/ebmdatalab:hscic.ppu_savings, and will be updated automatically in future.
