### ISSUE TITLE
Make an "all England" page 

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#736]
* Measures without red lines and with possible savings nationwide
* Link to nationwide PPU page with download
* Some viz of total possible savings - e.g. stacked chart of total costs
* PPU should include realistic and total theoretical savings stacked chart.

**Comment by evansd** [comment]
After discussion with Seb, we've decided the two priorities:
 * Measures without red lines and with possible savings nationwide
 * Link to nationwide PPU page with download

**Comment by HelenCEBM** [comment]
Done!
