### ISSUE TITLE
Document automatically-created bigquery tables

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#764]
Most importantly, what their names are, where they are, and how often they are updated.

For the time being, this is for the benefit of our internal team, so that would do to start with. Notify the team of its location when done. 

However, within a couple of months we will be releasing our BigQuery OP dataset publicly, so it would also be useful to add to this document some stubs describing the source and purpose of each table and how it joins to the others.

I suggest the location should be the readme [here](https://github.com/ebmdatalab/prescribing-queries) - a repository which is supposed to be a collection of handy exemplar queries for internal and external use. We could iterate that and aim to tidy it up in a couple of months.

**Comment by inglesp** [comment]
Have begun to work on this at https://github.com/ebmdatalab/prescribing-queries/compare/document-bq-tables?expand=1

**Comment by inglesp** [comment]
Before we make this public, we may want to make some changes to the data.

A few off the top of my head:

* Change `hscic.prescribing.net_cost` and `hscic_prescribing.actual_cost` to be integers not floats
* Change all the `TIMESTAMP` fields to `STRING`s of the format `yyyy_mm`
* Change references to "PCT" to "CCG"
* Be consistent in pluralising table names (we currently have `practices` and `presentation`)
* Be consistent in whether we use `*_id` in field names

**Comment by richiecroker** [comment]
Are net_cost and actual_cost Integers?  Also, I like timestamps!

**Comment by sebbacon** [comment]
Note that I've merged the WIP referenced above, to make it easier for non-coders to collaborate on iteratively improving it
