### ISSUE TITLE
BigQuery measures tables - restore missing tables and remove default expiry

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/openprescribing#765]
The tables ending in:
`ktt9_antibiotics`
`opioidper1000`
`lyrica`
...in `ebmdatalab.measures` were previously there but have disappeared recently (I presume because of the expiry time of 90 days for that folder). Could these be restored and the default expiry for the measures folder removed so that they stay there permanently.

**Comment by alexwalkercebm** [comment]
just noticed that all tables ending in `pregabalinmg` have also disappeared in the last few days

**Comment by inglesp** [comment]
Hypothesis of 90-day expiration seems the most likely.  I've updated the default table expiration for the `measures` dataset to "Never",  and tonight will re-import all the measures.  We can't just import the measures that are now missing, as changing the default table expiration only affects new tables.  I'm re-importing the measures overnight, as doing so will temporarily remove the measures from the website and it's probably best not to do that during working hours!

**Comment by alexwalkercebm** [comment]
After the import last night there's now a different set of tables missing - looks like everything alphabetically from `pregabalinmg` onward. Perhaps something didn't complete?

**Comment by inglesp** [comment]
Yes, I'm aware of this!  No data in the site is missing though.

**Comment by alexwalkercebm** [comment]
Yes site looks fine from what I've seen! Will there be another attempted import soon? Could do with the tables next week. Thanks :)

**Comment by inglesp** [comment]
Will try to finish it off at some point today.

**Comment by inglesp** [comment]
This is happening now and should be finished by 16:00 at the latest.

**Comment by alexwalkercebm** [comment]
Ah fantastic, thanks!

**Comment by inglesp** [comment]
This is done.  The reason the process didn't initially complete was because the `pregabilin_total_mg` view had expired, and so creating the `pregabalinmg` measure (which depends on the view) crashed.

I have since recreated the `pregabilin_total_mg` view and set the expiry time for the other views (`opioid_total_ome ` and `practice_data_all_low_priority`) to "Never", so we shouldn't hit this again.
