### ISSUE TITLE
tariff.csv is out of date

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#771]
tariff.csv, downloadable from https://openprescribing.net/tariff/, hasn't been updated since December.

**Comment by inglesp** [comment]
Looks like we're pre-generating the CSV file and serving it from `openprescribing/assets/tariff.csv` on the filesystem.

@sebbacon Do you know how we update this?  And can we make updating it part of the `fetch_and_import_drug_tariff` task?

**Comment by sebbacon** [comment]
@inglesp this was a [hack at launch](https://github.com/ebmdatalab/openprescribing/commit/11fa67ce7d6c1e044ab0d3cb6e0844bb8a11cd65) to get around the fact that the SQL took too long to generate.

I think you fixed the SQL, right? So we can hopefully revert that commit.

**Comment by inglesp** [comment]
This is fixed, and the CSV file takes about 5s to generate and download.
