### ISSUE TITLE
population sizes in Low Priority omnibus measure are too low

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#777]
similar to issue #619 but less dramatic 

E.g. For Dec 2017 this CCG has **332,562** patients according to most per-1000 measures (inc low priority individual measures) but for low priority compound measure it is **314K** 
https://openprescribing.net/ccg/02R/

**Comment by inglesp** [comment]
After a lot of head scratching...

The problem's that there are only 17 measures listed in `practice_data_all_low_priority.sql`, while in `lpzomnibus.json`, `denominator_columns` is `"SUM(denominator)/18 AS denominator, "`.  (332,562 * 17 / 18 == 314,085).

And we claim in the [why it matters](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/lpzomnibus.json#L11) that the measure is for "18 of the 19 measures".

So presumably we've lost a measure somewhere.  When I'm next at my laptop I'll work out which one.

**Comment by inglesp** [comment]
`lpglutenfree` is missing from `practice_data_all_low_priority.sql`.

So either:

1) We add `lpglutenfree` to `practice_data_all_low_priority.sql'
2) We change 18 to 17 in `lpzomnibus.json`.

**Comment by inglesp** [comment]
This is now fixed and data on the website has been updated.
