### ISSUE TITLE
Duplication of rows in PPU savings page

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#793]
At https://openprescribing.net/practice/L83073/price_per_unit/, we see duplicates for Diazepam 10mg/5ml oral solution/suspension:

![image](https://user-images.githubusercontent.com/28734/36796521-a0e48db2-1c9d-11e8-85d6-87c9adaf06e3.png)

And we also see duplicates for Pregabalin 75mg capsules:

![image](https://user-images.githubusercontent.com/28734/36796563-b7c60d9e-1c9d-11e8-9453-1de3f60872a5.png)

The causes are separate.

For Diazepam, there are two records in the `dmd_product` table with `bnf_code = '0401020K0AAA1A1'` and `concept_class = 1`.  These records have different names.

```
127.0.0.1 prescribing@prescribing=# select dmdid, bnf_code, name from dmd_product where bnf_code = '0401020K0AAA1A1' and concept_class = 1;
┌───────────────────┬─────────────────┬───────────────────────────────────┐
│       dmdid       │    bnf_code     │               name                │
├───────────────────┼─────────────────┼───────────────────────────────────┤
│ 13893211000001109 │ 0401020K0AAA1A1 │ Diazepam 10mg/5ml oral suspension │
│  8792711000001108 │ 0401020K0AAA1A1 │ Diazepam 10mg/5ml oral solution   │
└───────────────────┴─────────────────┴───────────────────────────────────┘
(2 rows)

Time: 48.993 ms
```

For Pregabalin, the problem is to do with the way that price concessions are being picked up by [this query](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/api/views_spending.py#L214-L263):

```
# SELECT DISTINCT                                                                    
    frontend_ppusaving.id AS id,
    frontend_ppusaving.date AS date,
    frontend_ppusaving.lowest_decile AS lowest_decile,
    frontend_ppusaving.quantity AS quantity,
    frontend_ppusaving.price_per_unit AS price_per_unit,
    frontend_ppusaving.possible_savings AS possible_savings,
    frontend_ppusaving.formulation_swap AS formulation_swap,
    frontend_ppusaving.pct_id AS pct,
    frontend_ppusaving.practice_id AS practice,
    frontend_ppusaving.bnf_code AS presentation,
    frontend_practice.name AS practice_name,
    dmd_ncsoconcession.id IS NOT NULL as price_concession,
    -- COALESCE(dmd_product.name, frontend_presentation.name) AS name,
    frontend_presentation.name AS name
FROM frontend_ppusaving
LEFT OUTER JOIN frontend_presentation
    ON frontend_ppusaving.bnf_code = frontend_presentation.bnf_code
LEFT OUTER JOIN frontend_practice
    ON frontend_ppusaving.practice_id = frontend_practice.code
LEFT OUTER JOIN dmd_product
    ON frontend_ppusaving.bnf_code = dmd_product.bnf_code
LEFT OUTER JOIN dmd_vmpp
    ON dmd_product.vpid = dmd_vmpp.vpid
LEFT OUTER JOIN dmd_ncsoconcession
    ON dmd_vmpp.vppid = dmd_ncsoconcession.vmpp_id
    AND frontend_ppusaving.date = dmd_ncsoconcession.date
WHERE
    frontend_ppusaving.date = '2017-12-01'
    AND dmd_product.concept_class = 1
    AND frontend_ppusaving.practice_id = 'L83073'
    AND dmd_product.name LIKE 'Pregabalin 75mg%'
;
┌─[ RECORD 1 ]─────┬────────────────────────┐
│ id               │ 2323721                │
│ date             │ 2017-12-01             │
│ lowest_decile    │ 0.0805357142857143     │
│ quantity         │ 1806                   │
│ price_per_unit   │ 0.180033222591362      │
│ possible_savings │ 179.6925               │
│ formulation_swap │ ¤                      │
│ pct              │ 99P                    │
│ practice         │ L83073                 │
│ presentation     │ 0408010AEAAACAC        │
│ practice_name    │ BRANNAM MEDICAL CENTRE │
│ price_concession │ f                      │
│ name             │ Pregabalin_Cap 75mg    │
├─[ RECORD 2 ]─────┼────────────────────────┤
│ id               │ 2323721                │
│ date             │ 2017-12-01             │
│ lowest_decile    │ 0.0805357142857143     │
│ quantity         │ 1806                   │
│ price_per_unit   │ 0.180033222591362      │
│ possible_savings │ 179.6925               │
│ formulation_swap │ ¤                      │
│ pct              │ 99P                    │
│ practice         │ L83073                 │
│ presentation     │ 0408010AEAAACAC        │
│ practice_name    │ BRANNAM MEDICAL CENTRE │
│ price_concession │ t                      │
│ name             │ Pregabalin_Cap 75mg    │
└──────────────────┴────────────────────────┘

Time: 68.485 ms
```

(Note the `t` and the `f` for the `price_concession` column.)

**Comment by inglesp** [comment]
Diazepam first... this looks like a re-emergence of #686, presumably introduced by #770.

The problem is that some BNF codes have multiple products with `concept_class = 1`.  (@richiecroker says they're ["clinically the same"](https://github.com/ebmdatalab/openprescribing/issues/686#issuecomment-351705554).)

The fix to #686 was to pick a product arbitrarily.  We can do that again here, or we could use the names that come from https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=126.  These are the names we use elsewhere on the site.

@sebbacon is there a good reason not to do this?

**Comment by inglesp** [comment]
For pregabalin, I think the fix is to move the condition `frontend_ppusaving.date = dmd_ncsoconcession.date` from the `LEFT OUTER JOIN` to the `WHERE`.

**Comment by sebbacon** [comment]
The reason not to use the names in the BNF tables is that these are truncated names, as opposed to nice, human-readable dm+d names.

**Comment by inglesp** [comment]
> For pregabalin, I think the fix is to move the condition `frontend_ppusaving.date = dmd_ncsoconcession.date` from the `LEFT OUTER JOIN` to the `WHERE`.

This is total nonsense, sorry.

The actual problem is that a `PPUSaving` only has a BNF code, and doesn't know anything about a pack size -- basically, it corresponds to a VMP.  But concessions are for VMPPs.  Because a VMP might have many VMPPs, and because of how the SQL for the query is written, we'll have one row in the PPU table for each VMPP with the same VMP as a VMPP with a concession.

Will fix tomorrow.
