### ISSUE TITLE
List of BQ tables we use for analysis vs website only

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#795]
To keep a track of which tables need to be available/maintained for analysis use:
- [x] @sebbacon  and @inglesp to share a list of tables used for website, 
- [ ] the rest of us to annotate how else we use them

**Comment by inglesp** [comment]
The easiest way to answer the first checkbox is to see what tables are created by end-to-end tests.  I've just merged #802 which will make that easier, by keeping the tables around for 24 hours after each test run.

**Comment by inglesp** [comment]
The import process creates/uses the following tables, arranged by dataset:

* `hscic`
  * `bnf`
  * `bnf_map`
  * `ccgs`
  * `normalised_prescribing_legacy` (a view)
  * `normalised_prescribing_standard` (a view)
  * `ppu_savings`
  * `practice_statistics`
  * `practice_statistics_all_years`
  * `practices`
  * `prescribing`
  * `prescribing_YYYY_MM`
  * `prescribing_with_merged_codes_YYYY_MM`
  * `presentation`
  * `tariff`
  * `vw__ccgstatistics`
  * `vw__chemical_summary_by_ccg`
  * `vw__chemical_summary_by_practice`
  * `vw__practice_summary`
  * `vw__presentation_summary`
  * `vw__presentation_summary_by_ccg `
* `measures`
  * For each meausure:
    * `ccg_data_MEASURE`
    * `global_data_MEASURE`
    * `practice_data_MEASURE`
  * Views used as input for certain measures
    * `opioid_total_ome`
    * `practice_data_all_low_priority`
    * `pregabalin_total_mg `
* `dmd`
  * `product`
  * `vmpp`
* `tmp_eu` (we should not rely on these!)
  * `formatted_prescribing_YYYY_MM`
  * `raw_prescribing_data_YYYY_MM`
  * `unused_codes_chemical_code`
  * `unused_codes_para_code`
  * `unused_codes_presentation_code`
  * `unused_codes_product_code`
  * `unused_codes_section_code `

**Comment by inglesp** [comment]
@HelenCEBM Can you let us know which of these tables are currently used for non-website queries?

**Comment by HelenCEBM** [comment]
`hscic` tables | Used?
-- | --
`bnf` | yes
`bnf_map` |
`ccgs` | yes
`normalised_prescribing_legacy`   (a view) |
`normalised_prescribing_standard`   (a view) | yes
`ppu_savings` |
`practice_statistics` | yes
`practice_statistics_all_years` | yes
`practices` | yes
`prescribing` |
`prescribing_YYYY_MM` | yes
`prescribing_with_merged_codes_YYYY_MM`
`presentation` | yes
`tariff` | yes
`vw__ccgstatistics`
`vw__chemical_summary_by_ccg`
`vw__chemical_summary_by_practice`
`vw__practice_summary`
`vw__presentation_summary`
`vw__presentation_summary_by_ccg`


`measures` For each measure: | Used?
--- | ---
`ccg_data_MEASURE`
`global_data_MEASURE`
`practice_data_MEASURE`

Views used as input for certain measures | Used?
-- | --
`opioid_total_ome` | 
`practice_data_all_low_priority` | 
`pregabalin_total_mg` | 

`dmd` | Used?
-- | --
`product` | 
`vmpp` | 

`tmp_eu` (we should not rely on these!) | Used?
--- | ---
`formatted_prescribing_YYYY_MM` | 
`raw_prescribing_data_YYYY_MM` | 
`unused_codes_chemical_code` | 
`unused_codes_para_code` | 
`unused_codes_presentation_code` | 
`unused_codes_product_code` | 
`unused_codes_section_code ` | 

- [ ] @alexwalkercebm to add any yeses to the list
- [ ] @richiecroker  to add any yeses to the list

**Comment by richiecroker** [comment]
The reason I have put think so for the dmd section is that i believe they're used in calculating price concession burden.

**Comment by sebbacon** [comment]
Just to note there are also views to document -
 the main prescribing views, but also https://github.com/ebmdatalab/openprescribing/issues/701#issuecomment-370138852

**Comment by inglesp** [comment]
Thanks folks.  And here's the next step: tables that are in BQ that are *not* used by the import pipeline.  Please could you indicate which, if any are in use?  My plan, if it's not too much of a hassle for the rest of the team, is to move any tables that are used to a new dataset (eg `analysis`), and move any that we think are unused to another dataset in preparation for deleting them in a few months' time.

- [ ] @HelenCEBM to add any yeses to the list
- [ ] @alexwalkercebm to add any yeses to the list
- [ ] @richiecroker  to add any yeses to the list

`hscic` tables | Used?
-- | --
`NEW_prescribing` |
`aug_presentations` |
`bnf_name_to_product_special_cases_helen` |
`bnf_to_supplier` |
`bnf_vertical` |
`chem_by_section` |
`chemicals` |
`compiled_ADQs_HC` |
`devon_BNFarchive` |
`dmd` |
`drug_name_alt_spellings_in_PCA_data_2016_HC` |
`drug_name_alt_spellings_in_PCA_data_HC` |
`drug_name_changes_2013` |
`eccg` |
`epcmem` |
`epraccur` |
`epracmem` |
`gridall` |
`imd` |
`normalised_prescribing_standard_latest_month` |
`ons_mapping` |
`pca_bnf_name_to_code_fuzzy_lookup` |
`pca_chemical_old_to_new_lookup` |
`pca_chemical_old_to_new_lookup_2016` |
`pca_paragraph_old_to_new_lookup` |
`pca_product_old_to_new_lookup` |
`pca_section_old_to_new_lookup` |
`poss_savings_by_ccg` |
`practice_list_sizes_foi_2010_2013_copy` |
`practices_mem` |
`prescribing_1998_2010` |
`prescribing_pca_1998_2015_full` |
`prescribing_pca_1998_2015_full_v2` |
`prescribing_pca_1998_2016_full` |
`prescribing_pca_1998_2016_full_v2` |
`prescribing_temp` |
`qof_ccgs_1415` |
`qof_practices_1415` |
`super_bnf` |
`super_bnf2` |
`test_normalised_prescribing_legacy_legacy` |
`test_practices` |
`test_test_normalised_prescribing_legacy` |
`tmp_specials` |
`vw__ccg_statistics` |



`dmd` tables | Used?
-- | --
`lookup_dt_payment_category` |
`ncso_calculator` |


`tmp_eu` tables | Used?
-- | --
`opioids_one_month` |
`ppu_data_2017_11` |
`results_20180214_142038` |
`results_20180216_091345` |
`results_20180219_090701` |
`results_20180219_095116` |
`results_20180219_132222` |
`results_20180220_132636` |
`results_20180221_152134` |
`results_20180222_145131` |
`results_20180301_151252` |

**Comment by alexwalkercebm** [comment]
Slight problem with moving tables to a new dataset is that it would break any existing notebooks that call BQ tables until the table names are corrected. Not a huge issue for current notebooks, but a bit of a pain for notebooks that are associated with published papers, where they're posted to Figshare or similar.

We'd have to update these ones on Figshare etc, in order for them to continue to work, which is especially important if we're to eventually share the BQ tables publicly.

**Comment by sebbacon** [comment]
Is it an option to share a link to our github repo rather than Figshare for code in the future?

We could link to a specific revision (at a given point in time) and visitors can then choose to use newer versions as they like.

**Comment by HelenCEBM** [comment]
Haven't commented on the tmp_eu tables as the whole point of them is that they are temporary and get automatically removed after a month.

**Comment by inglesp** [comment]
Once #998 is merged, I will archive the following:

* `NEW_prescribing`
* `aug_presentations`
* `bnf_to_supplier`
* `chemicals`
* `eccg`
* `epcmem`
* `epraccur`
* `epracmem`
* `gridall`
* `imd`
* `normalised_prescribing_standard_latest_month`
* `ons_mapping`
* `pca_chemical_old_to_new_lookup_2016`
* `poss_savings_by_ccg`
* `practice_list_sizes_foi_2010_2013_copy`
* `practices_mem`
* `prescribing_1998_2010`
* `prescribing_pca_1998_2015_full`
* `prescribing_pca_1998_2015_full_v2`
* `prescribing_pca_1998_2016_full`
* `prescribing_temp`
* `super_bnf`
* `super_bnf2`
* `test_normalised_prescribing_legacy_legacy`
* `test_practices`
* `test_test_normalised_prescribing_legacy`
* `tmp_specials`
* `vw__ccg_statistics_2`

**Comment by inglesp** [comment]
These have all been moved to the `archive` dataset.
