### ISSUE TITLE
Don't reject presentations with BNF codes shorter than 15 chars

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#81]
In our `import_bnf_codes` script we reject presentations with BNF codes that are shorter than 15 chars. 

However, some devices seem to have presentation codes of less than 15 chars. For example:

21010220113    Flutter Oscillating Positive Expiratory Pressure Dev   
21010220114   Acapella Oscillating Positive Expiratory Pressure Dev   

These are legitimate so we should not exclude them.

**Comment by sebbacon** [comment]
There are 21,080 with fewer than 15 chars (29% of all codes):

```
 csvcut -c 14 bnf_codes.csv | awk '{print length}' | sort | uniq -c | sort -g
      1 21
  21080 11
  52870 15
```

These are predominantly non-chemicals, e.g. ileostomy bags, dressings, catherers, etc.
