### ISSUE TITLE
Tamoxifen measure

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#810]
Measure to accompany tamoxifen paper being published imminently. 

```
{
  "name": "Prescribing of tamoxifen",
  "title": [
    "Prescribing of tamoxifen"
  ],
  "description": [
    "Number of Average Daily Quantities (ADQs) for tamoxifen (20mg/day) ",
    "per 1000 female population aged 35-74."
  ],
  "why_it_matters": [
    "Alongside its use as a cancer treatment, in 2013 ",
    "<a href='https://www.nice.org.uk/guidance/cg164'>NICE recommended</a> ",
    "that tamoxifen should also be prescribed for chemoprevention of breast cancer ",
    "for women at increased risk. ",
   "Improving the use of preventative therapies was also reiterated in England's ",
    "<a href='https://www.cancerresearchuk.org/sites/default/files/achieving_world-class_cancer_outcomes_-_a_strategy_for_england_2015-2020.pdf'>Cancer Strategy</a> ",
    "for 2015-2020. ",
    "This measure accompanies our paper investigating the national response to these guidelines, ",
    "published in the British Journal of Cancer."
  ],
  "numerator_short": "Tamoxifen ADQs",
  "denominator_short": "1000 female patients aged 35-74",
  "url": null,
  "is_percentage": false,
  "is_cost_based": false,
  "low_is_good": null,
  "tags": ["core"],
  "numerator_columns": [
    "SUM(quantity/ CASE WHEN bnf_name LIKE '%Oral%' THEN 10 ",
    "WHEN bnf_name LIKE '%Liq%' THEN 10 ",
    "WHEN RTRIM(bnf_name) LIKE '%10mg' THEN 2 ",
    "WHEN RTRIM(bnf_name) LIKE '%40mg' THEN 0.5 ",
    "ELSE 1 END) AS numerator, "
  ],
  "numerator_from": "{hscic}.normalised_prescribing_standard ",
  "numerator_where": [
    "(SUBSTR(bnf_code,1,9) = '0803041S0')  "
  ],
  "denominator_columns": [
    "(max(female_35_44) + max(female_45_54) + max(female_55_64) + max(female_65_74)) ",
    "/ 1000.0) AS denominator "
  ],
  "denominator_from": "{hscic}.practice_statistics ",
  "denominator_where": [
    " max(female_35_44) > 10 "
  ]
}
```

**Comment by sebbacon** [comment]
Looks good! Comments

* Missing space before closing double quote: `for tamoxifen",`
* I presume this is matching your paper and makes perfect sense, but FWIW it seems odd to me that the exclusion criterion is only on the 35-44 band yet the selected columns are on several...
* In the description, should we link to the definition you're using for ADQs? Not just for general public but also our own benefit should we need to revisit?

**Comment by HelenCEBM** [comment]
- Exclusion based on 35-44 because some 'practices' have only older patients, i.e. they are probably care homes or similar specialised services (but can still be occasionally listed as type 4). 
- Will add definition of ADQs, thanks!

**Comment by sebbacon** [comment]
Might be worth adding the exclusion principle either in the description, or (if you think that'll make it too verbose) in a comment (again, just for the benefit of future developers / researchers)

If you go with a comment -- there is no way of doing a comment in JSON, but you can just add a redundant field thusly:

    "comments": "Exclusion based on 35-44 because...."

**Comment by sebbacon** [comment]
Implemented [thusly]( https://github.com/ebmdatalab/openprescribing/blob/962d4b67980eaf0e614d72900419ca14e27d8f08/openprescribing/frontend/management/commands/measure_definitions/tamoxifen.json)
