### ISSUE TITLE
Investigate postgres performance for matviews

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#82]
Materialized views are very slow to update. Spend an hour or so looking into why.

**Comment by annapowellsmith** [comment]
I suspect the most likely reason will be lots of indexes to update. I had a check a while ago for unused indexes, but most of the existing ones seem to be used.

We could see if deleting the indexes, updating, and then re-creating the indexes is any faster.

**Comment by sebbacon** [comment]
Creating indexes is also very slow, sometimes. 

During high-impact operations on large tables, there are two different bottlenecks, at different times:

* Disk writing at 100% utilisation (at around 39686 wkB/s and 79 w/s)
* CPU at 100% utilisation

Regarding CPU, the problem is that postgres doesn't allow splitting a query across more than one core, so although we have 20 cores, we can only use one of them. Each core is an `Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz`

Mitigation strategies:
* Fewer cores, higher performance
* Postgres 9.6 should support parallel sequential scans, but won't be released until Q3 this year. 

Regarding disk, the write throughput we're seeing is surprisingly low for a modern controller - 85 mB/sec for sequential 4k blocks (compare with 242 mB/Sec on my laptop) (although better for random reads).  I'm more bothered about this as I've noticed I've not been able to other things on the console sometimes, presumably because everything is waiting for IO.

Mitigation strategies:
 * Write to Digital Ocean about the expected max throughput

I agree that if this becomes a big issue we should also review the application design for performance.

Just wanted to keep some notes somewhere about it, in preparation for when it does become an issue. Might be worth clarifying the disk issue with Digital Ocean now.

**Comment by sebbacon** [comment]
From a quick look, most of the matviews do a few sequence scan of, typically, 66 million records, and this is mostly CPU-bound.  Don't think there's a way round this apart from either changing hardware or awaiting 9.6

**Comment by annapowellsmith** [comment]
Brilliant thank you. Please do send a ticket to DigitalOcean support and let's see what they say!

**Comment by sebbacon** [comment]
A bit more investigation:

A disk scan is required whenever a sort can't be done in memory, and that's certainly the case for most of the materialized views: they typically take 43B per row, which, with other related data structures ([ref](https://rjuju.github.io/postgresql/2015/08/18/estimating-needed-memory-for-a-sort.html)), adds up to about 66GB across the entire prescribing table.

Here is the query plan for `vw__presentation_summary_by_ccg`:

```sql
prescribing=> EXPLAIN SELECT processing_date, pct_id, presentation_code, SUM(total_items) AS items, SUM(actual_cost) AS cost, CAST(SUM(quantity) AS bigint) AS quantity FROM frontend_prescription GROUP BY processing_date, pct_id, presentation_code;
                                           QUERY PLAN                                            
-------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=136764033.26..149193863.66 rows=66292429 width=43)
   Group Key: processing_date, pct_id, presentation_code
   ->  Sort  (cost=136764033.26..138421343.98 rows=662924288 width=43)
         Sort Key: processing_date, pct_id, presentation_code
         ->  Seq Scan on frontend_prescription  (cost=0.00..19238784.88 rows=662924288 width=43)
```

In terms of improving the query time, I guess we'd do best to make the sorting as fast as possible, which means reducing the row size, normalising further, etc. I can't see any obvious candidates for this.

Given this is a once-a-month operation, is this perhaps better achieved using bigquery? AFAICT the following would be equivalent to the above:

```sql
SELECT month, pct, bnf_code, SUM(items) AS total_items, SUM(actual_cost) AS cost, SUM(quantity) AS quantity FROM [hscic.prescribing] GROUP BY month, pct, bnf_code LIMIT 100;
```

Given we don't actually need to recompute data for every month, but just the latest month, could we add a `WHERE month > '2016-01-01'` to the query above, then append the results to a static table (rather than a materialized view)?

Alternatively, we could do the same thing without involving bigcloud at all.

**Comment by sebbacon** [comment]
Update: refreshing `vw__presentation_summary_by_ccg` took 7 hours 43 mins (27800533.211ms to be precise).

**Comment by annapowellsmith** [comment]
Is that for a concurrent refresh? 

BigQuery could be a good way to go. It would mean we could get rid of raw SQL queries in views. It would be a good test step for the measure-calculating process too, where we will definitely need to use BigQuery if we are doing personalised measures. 

For BigQuery, the results will be too large to download directly, so the process will be: (1) calculate on BigQuery (2) export to temp table (3) export to GCS (4)`COPY` to Postgres.

**Comment by sebbacon** [comment]
Yes it is for a concurrent refresh.

Which raw SQL queries are you thinking of?

**Comment by annapowellsmith** [comment]
Cool, that's faster than I expected. Was that after the underlying data had
changed?

All the queries to matviews in all the views are raw SQL, which is not
ideal, if they were tables we could use the Django ORM.

**Comment by sebbacon** [comment]
Oddly (given updating one view took about the same time), updating all the materialized views took less than 8 hours. Perhaps because the indexes for the prescribing table are loaded into memory by the first view refresh?

**Comment by annapowellsmith** [comment]
Next steps: "Write to Digital Ocean about the expected max throughput"

**Comment by sebbacon** [comment]
Have submitted a [support request](https://cloud.digitalocean.com/support/tickets/1148401) using the account associated with Anna's email address -- please let me know when you get a substantive reply.

**Comment by annapowellsmith** [comment]
Have forwarded reply...

**Comment by annapowellsmith** [comment]
The disk was indeed running too slowly. DigitalOcean have migrated us to a different server. Closing as the only outstanding point is whether we can use BQ for calculating matviews, which comes under the heading of other work.

**Comment by sebbacon** [comment]
See also #148 for further comments about performance
