### ISSUE TITLE
Post e2e test failures to #tech in Slack

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#829]
e2e test failures don't need to be shared with #general.

I've created a [new integration](https://ebmdatalab.slack.com/services/BA4L1TRJ7) to post to #tech, but it'd be better to reuse the existing @ebmbot integration.

I've tried changing how we [POST to Slack](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/openprescribing/slack.py#L17) to include the channel in the payload, but that gets ignored.

@sebbacon, as you've spent more time on this stuff than me, do you know how to get @ebmbot to post to a different channel?

**Comment by HelenCEBM** [comment]
done?

**Comment by inglesp** [comment]
No -- it's still posting to #general.  But the error messages are much less obtrusive than they were, so I suggest we close this.
