### ISSUE TITLE
KeyError when updating measures for `practice` org type

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#83]
It seems that a `calc_value` key is expected in a `pandas.core.series.Series`, but the actual structure returned looks more like:

```
(Pdb) df.quantile(10/100.0)
denom_cost            0.0
denom_items           0.0
denom_quantity        0.0
denominator           0.0
id                40510.2
num_cost              0.0
num_items             0.0
num_quantity          0.0
numerator             0.0
rank_val              NaN
dtype: float64

```

Traceback:

```
processing dataframe of length 7943

Traceback (most recent call last):
  File "/home/seb/Code/openprescribing/openprescribing/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/seb/Code/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 54, in handle
    mg = self.create_or_update_measureglobal(df, measure, month, 'practice')
  File "/home/seb/Code/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 358, in create_or_update_measureglobal
    percentiles[c] = df.quantile(c/100.0)['calc_value']
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/pandas/core/series.py", line 557, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/seb/.virtualenvs/openprescribing/local/lib/python2.7/site-packages/pandas/core/index.py", line 1804, in get_value
    raise e1
KeyError: 'calc_value'

```

**Comment by sebbacon** [comment]
Just hit this when importing live data.

```
<snip>
updating KTT8 (Dosulepin): First choice antidepressant use in adults with depression or anxiety disorder for CCGs in 2016-02-01
processing dataframe of length 212
Updating measure: ktt9_antibiotics
Handling month 2016-02-01 for ktt9_antibiotics
updating KTT9 (Antibiotic prescribing - especially broad spectrum antibiotics) for practices in 2016-02-01
creating measurevalue for practice 0 of 7943
elapsed time 1 seconds
creating measurevalue for practice 1000 of 7943
elapsed time 28 seconds
creating measurevalue for practice 2000 of 7943
elapsed time 51 seconds
creating measurevalue for practice 3000 of 7943
elapsed time 69 seconds
creating measurevalue for practice 4000 of 7943
elapsed time 84 seconds
creating measurevalue for practice 5000 of 7943
elapsed time 100 seconds
creating measurevalue for practice 6000 of 7943
elapsed time 116 seconds
creating measurevalue for practice 7000 of 7943
elapsed time 131 seconds
Total elapsed time 144
processing dataframe of length 7943
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/manage.py", line 11, in <module>   
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()

```

**Comment by sebbacon** [comment]
Note to self: I can also reproduce this locally with 

     python manage.py import_measures --month=2016-01-01

**Comment by sebbacon** [comment]
I believe the problem is that the SQL queries to calculate the [numerator](https://github.com/ebmdatalab/openprescribing/blob/38b26cf8bf7c0ccc63075f87b429168a0ea3e437/openprescribing/frontend/management/commands/import_measures.py#L258) and [denominator](https://github.com/ebmdatalab/openprescribing/blob/38b26cf8bf7c0ccc63075f87b429168a0ea3e437/openprescribing/frontend/management/commands/import_measures.py#L273) may sometimes return an empty set.

If either value is non-truthy, then [the method](https://github.com/ebmdatalab/openprescribing/blob/38b26cf8bf7c0ccc63075f87b429168a0ea3e437/openprescribing/frontend/management/commands/import_measures.py#L410-L418) that works out the `calc_value` field for a MeasureValue will set a null value in the database.

This in turn [leads to](https://github.com/ebmdatalab/openprescribing/blob/38b26cf8bf7c0ccc63075f87b429168a0ea3e437/openprescribing/frontend/management/commands/import_measures.py#L351-L354) a dataframe that only has default (zero) values set for some columns (not including `calc_value`).

I'm going to write a test to capture this. Is the solution to set a `calc_value` of zero rather than null on the MeasureValue, or to `calc_value` add to the columns that the dataframe is filled with?

**Comment by annapowellsmith** [comment]
Well calculated sir. 

If the denominator is zero, then the `calc_value` should be null. 

If the denominator is non-zero, but the numerator is zero, then the `calc_value` should be zero.

**Comment by sebbacon** [comment]
For this condition to occur, *all* the MeasureValues for a given measure need to have had zeros for all their denominators and numerators, which is rare enough we'd expect it to be indicative of another error if it does happen.

On my development box, it happens because I have sparse prescribing data, so null values are not uncommon.

On the production box, this failed because the `PracticeStatistics` data (derived from the `patient_list_size` dataset) had not been updated for the current month(s), and some of the KTT measures depend on this for their denominator.

* The last `patient_list_size` dataset was from Jan; I've just realised there is a new one to import. So had I done this, the measure updating wouldn't have failed; however
* Given there won't always be `patient_list_size` data every month, perhaps the correct fix is to alter the import script not to update the measures at all if they fail because data for the current month is not available in the PracticeStatistics table?

**Comment by annapowellsmith** [comment]
Ah yes, the measures need to come last in the process, after everything else (including materialized views) is up to date. 

Yes, they should not be imported if the list sizes are not up to date. 

List sizes are updated quarterly, usually slightly later in the month than the prescribing data. To date,  in the months where new list size data is is due, I've simply delayed updating the prescribing data until the list size data is available.

**Comment by sebbacon** [comment]
To be clear: measures should only be updated quarterly?

**Comment by annapowellsmith** [comment]
No sorry. Let me try to explain... Each month, I import the prescribing data, and the list sizes *for that month*. Then calculate matviews. And finally update the measures. 

The list sizes are published in calendar quarters and cover all months in that quarter. However, in January, I don't import January, February and March: I import list sizes for only January. In February, I import list sizes for February. Etc. 

Typically, at the start of a quarter, the prescribing data for the month is available a week or two before the new list sizes for the quarter are published by BSA. To date, I've just been waiting for the new list size data to appear on the BSA site before I start the data import for the month.

**Comment by sebbacon** [comment]
I'm afraid I still don't understand, sorry... specifically, I don't understand what "I import list sizes for only January" means.  Here's my understanding:

There is a reference in the comments in the importer to " the BSA's multi-year data", but I've not seen that data. The code path we take creates an entry for each month in the previous quarter based on the filename, and the data we use (from [here](https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=128)) covers all practices for that quarter. In other words, the data for a quarter is going to be identical for each of the three months. And, as such, the importer imports the entire quarter at once.

**Comment by annapowellsmith** [comment]
See e.g. line 138 in https://github.com/ebmdatalab/openprescribing/commit/277c06943dce0610847926b0c03c7fd09156a7db#diff-04c6e90faac2675aa89e2176d2eec7d8R138

Say you were loading list size data only for January. 
If you're loading list size data just for January, then you would rename the file from `Patient_List_Size_2016_01-03.csv` to `Patient_List_Size_2016_01-01.csv` and the importer would import data for only that month.

Obviously, this is hacky and not exactly well documented. Sorry! You are working on the Robinson Crusoe of codebases.

**Comment by sebbacon** [comment]
OK! Two more questions:

* Why not ingest the entire quarter as soon as it's ready, even when we don't have prescribing data for all those months?
*  You said higher in the thread "measures need to come last in the process, after everything else (including materialized views) is up to date"; the docs you just linked to say "Then update measures ... Finally, refresh the materialized views". Which is it?

**Comment by sebbacon** [comment]
I'm closing this issue in favour of a new one (issue #96) which directly addresses the fact I'd not understood how the patient list size data should be ingested and how it relates to measures etc.
