### ISSUE TITLE
Produce visualisation of data flow through OpenPrescribing

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#831]
The way that data goes from its source to a page on the website is complex, and after working on it for over a year I still don't have everything straight in my head.  A visualisation might help here.

The visualisation should cover:

* Sources of data
* Data in the database
* Data in BigQuery
* API endpoints
* Pages on the website

**Comment by HelenCEBM** [comment]
Progress @inglesp ?
