### ISSUE TITLE
Don't 500 on invalid dates for PPU

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#832]
URLs like /ccg/07H/price_per_unit/?date=123 are being spidered, and are producing a lot of error alert noise.

These should return a 200 to the user, with an error message that the date is not valid.

**Comment by inglesp** [comment]
👍 for [400](https://http.cat/400) from me.

**Comment by sebbacon** [comment]
Yes, makes sense -- though shouldn't we use [rest_framework exceptions](http://www.django-rest-framework.org/api-guide/exceptions/) like the 400s we already raise e.g. [here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/api/views_spending.py#L37-L39)?

**Comment by evansd** [comment]
We should indeed!

**Comment by evansd** [comment]
Deployed to the staging server:
http://staging.openprescribing.net/ccg/07H/price_per_unit/?date=not-really-a-date
