### ISSUE TITLE
Re-importing ktt9_uti_antibiotics measure gives slightly different practice percentiles

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#840]
As part of testing #826, I recalculated the `ktt9_uti_antibiotics` measure data in BQ, and the calculated values in the `practice_data.percentile` column differed by up to 0.3%.  The biggest difference (for 2017_01) was for practice P81218, where the original percentile was 0.46145, while the recalculated percentile was 0.46266.  (The original values are still on the site.)

To ensure the problem was not related to #826, I redid the recalculation with the original code and the effect is still there.  I did recalculations with other measures, and all values were unchanged to the nearest 1e-15, (which is still slightly interesting, but not at all concerning).

`ktt9_uti_antibiotics` is different to other measures because its query joins the `hscic.presentation` table, and we use the `percent_of_adq` column in the calculation.  But I can't immediately see why this would cause the percentile values would change slightly on recalculation.

I can investigate further, but only if we think that a 0.3% difference is worth losing sleep over.

**Comment by sebbacon** [comment]
What's more important is if the gross figures have changed -- obviously a matter of taste to some degree.  So - have the shapes of the centiles on the chart changed visibly? Has the relative ordering of practices changed?

Given we have approx 7000 practices, then a 0.3% change in percentile might have the effect of practices 21 positions apart switching places. 

I think the greater concern is why this might have happened. Given it only affects this measure, it seems likely it's related to the ADQ values.   I see [here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_adqs.py#L48-L57) that we calculate percent of ADQ based on units that we find in the BNF name, so perhaps something has changed this month for how units are described in antibiotics in BNF?

Given what we know about the BNF and NHSBSA's use of it, it wouldn't surprise me if this were the case. I think it is worth just following the % of ADQ lead a bit further, just to be sure we understand what's going on. These days I wonder if it would be better to use DMD (if it contains the same information); but then, we also have an outstanding issue relating to mapping to BNF there...!

**Comment by inglesp** [comment]
I've just run `import_measures` for this measure twice in a row, and each time it gives slightly different results for the percentiles, with the biggest difference being about 0.26%.

I think this rules out anything to do with the ADQ values changing.  (Still to investigate: why does this only seem to affect this measure?)

Only the percentiles are changing significantly.  The other values (`numerator` and`calc_value`) are changing too, but by 1e-15, eg from 323.83333333333337 to 323.83333333333331.  This change in `calc_value` is not the same for each practice, but it is enough to change the order of practices whose `calc_value` is essentially the same.  And this changes the percentiles.

The biggest change in position is from 2718 to 2709.

I don't think there's anything we can do about this, and I don't think it's particularly important.

@sebbacon Does this make sense?  And do you agree we can close this?

**Comment by sebbacon** [comment]
I think we've understood enough! But I will put it on the agenda for next Tues to check with rest of the team.

I guess the solution would be something like rounding the percentiles and then ranking by percentile, practice_id, giving consistency. If it matters.

**Comment by Bengoldacre** [comment]
We've discussed this in DL day and we think we can drop it. But it's good to be aware that it can happen. There is no likely impact on CUSUM or real quality of service, and likely impact on perceived quality of service is also low. Let's just remember, if odd stuff like this happens in future, that this might be the issue.
