### ISSUE TITLE
GDPR/privacy page

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#858]
* [x] Add this text to OpenPrescribing
* [x] Remove User-ID tracking as we don't use it anyway
* [x] Delete User-ID data from Google Analytics
* [ ] Put this text on EBM Data Lab website and link there from retractobot
* [ ] Consider replacing OpenPrescribing text with a link to embdatalab.net to keep things in one place

-----
Suggested text:

*Privacy notice*

The only personally identifiable data we manage are email addresses, and (where you supply them) names, job roles and institutions.

If you have given us your email address, we use it to tell you about information we believe is relevant to your interests.  Your email address is communicated to EBM DataLab for the purposes of sending you the email.  We may use your data in combination with data about website visit behaviour to help inform our research about putting clinical information into practice, but this is never linked to individual information, only in aggregate.

Usually we will have your email address because you have signed up to a service. Sometimes individuals in a particular role contact us to let us know they have now left this role, asking us to add their replacement to our services.

We will keep your email for as long as our service is maintained unless you ask us to remove it before that.

Every email we send contains a link allowing you to unsubscribe from our mailing list. When you unsubscribe, we delete your email address permanently from our records.

The list of email addresses is only accessible to appropriate team members and we will not share identifiable information with any third parties.

For the purposes of [GDPR](https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr) our Data Controller is EBM DataLab and you contact us at hello@ebmdatalab.net

**Comment by HelenCEBM** [comment]
DataLab!

**Comment by HelenCEBM** [comment]
- Note people can also opt to provide their names, job roles and institutions, so the first statement might need amendment.
- > We may use data about your interests

  sounds a bit odd
- Should we mention adding people on someone else's request? (Eg. "I have now left this role, please add my replacement to your mailing list instead")
- Suggest:
  > The list of email addresses is only accessible to appropriate team members and we will not share identifiable information with any third parties.

**Comment by sebbacon** [comment]
Have updated the text in the initial report to reflect @HelenCEBM's suggestions

**Comment by evansd** [comment]
Just slightly rejigged the task checkboxes to reflect what we're now doing
