### ISSUE TITLE
Suggestion for making an intermediate file with BNF/ATC mappings available to users

### ISSUE THREAD

**Issue by dmcalli2** [ebmdatalab/openprescribing#874]
Hello,
This request/suggestion is in response to a google search where I came across a file attached to  your closed issue #502.
I wasn't sure of the etiquette for closed issues so I've commented at #502, but linked to it with this new issue.
best wishes,
David McAllister

**Comment by sebbacon** [comment]
Yes, this would be great... it's going to be a while before it happens though! Could do a one-off extract for you for the time being, if that would be helpful.

**Comment by dmcalli2** [comment]
That would be much appreciated! Many thanks.

**Comment by sebbacon** [comment]
This is a gzipped CSV. 

`dmdid` is either a VMP id or a VMPP id. BNF codes usually map to VMPs, each of which may map to multiple VMPPs.

In a bit of a hurry right now, so hopefully you can make sense of it!

[dmd_2018_06.csv.gz](https://github.com/ebmdatalab/openprescribing/files/2111656/dmd_2018_06.csv.gz)

**Comment by dmcalli2** [comment]
Many thanks was able to link this easily to the ATC codes in the file from DMD download tool "f_bnf.xlsx".
