### ISSUE TITLE
Label dormant / closed practices

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#889]
In the list of practices at the top of a CCG page([example](https://openprescribing.net/ccg/08C/)), and at the top of a Practice page ([example](https://openprescribing.net/practice/E85124/)), we should clearly label Closed and Dormant practices as such (with the word "Closed" or "Dormant").

In analyses, where someone is searching for organisations the practice name should also indicate "(closed)" or "(dormant)".  

Presumably a safe way of doing this is to add it to the generated title of a practice.

It may be worth linking somewhere to [our explanation of "dormant"](https://ebmdatalab.net/what-is-a-dormant-gp-practice-and-why-are-they-prescribing/) if it's possible to do discreetly.

For further background, see #215 and #522.

The current status is stored in our Practice model.

**Comment by HelenCEBM** [comment]
@evansd  I don't think the labelling of closed/dormant practices on practice pages is working. 

E.g. on CCG page: 
![image](https://user-images.githubusercontent.com/24392156/58562123-8301ac00-8220-11e9-91f4-d79c22a3c094.png)

But on its practice page it's not labelled as closed
![image](https://user-images.githubusercontent.com/24392156/58562169-9f9de400-8220-11e9-9fae-cf4ac3ab816f.png)

https://openprescribing.net/practice/K81667/

**Comment by richiecroker** [comment]
We should also consider labelling a practice as "dormant" or "closed" in the heading of practice level graphs within a CCG page.  E.g. here the label could be "K81667: TAPLOW HEALTH CENTRE (CLOSED)

![image](https://user-images.githubusercontent.com/18683239/58563139-7da56100-8222-11e9-8751-58e886dc5204.png)

**Comment by richiecroker** [comment]
Could we also use the closed date from `epraccur.csv`, so it says "Closed in May 2016"?

**Comment by inglesp** [comment]
Changes to the entity homepages are in #1727.  Changes to the measure panels is going to be a bit harder, as it involves API changes.  How important are changes to the measure panel headings?

**Comment by HelenCEBM** [comment]
I wouldn't bother with the measure panel headings if tricky as it's usually obvious they're closed from lack of prescribing (obvious to us, anyway, but maybe not all users). 

But could closed practices have their practice names replaced with [practice name]+"closed", so it appears like that everywhere? Or is that meddling with something complicated? ...Might be confusing on the analyse page, say, when looking back at a time when a practice was open and it being labelled as closed. Unless as @richiecroker suggests we put the date as well.

**Comment by inglesp** [comment]
> But could closed practices have their practice names replaced with [practice name]+"closed", so it appears like that everywhere?

We'd have to make a separate change in each place the practice name is shown, so this isn't going to be trivial.

**Comment by inglesp** [comment]
Places to show practice status:

* https://openprescribing.net/practice/L83032/price_per_unit/
* https://openprescribing.net/practice/L83032/concessions/
* https://openprescribing.net/practice/L83032/ghost_generics/
* https://openprescribing.net/measure/aafpercent/practice/L83032/
