### ISSUE TITLE
Create new Labs page for finding outlier practices

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#890]
aka "Black Sheep" practices. 

Based on [this notebook](https://github.com/ebmdatalab/outlier-detection/blob/master/black_sheep_practices/Finding%20black%20sheep%20practices-box%20plots.ipynb)

**Comment by Bengoldacre** [comment]
also think about thumbs up and down for rows in PPU at the same time.

**Comment by richiecroker** [comment]
now live https://github.com/ebmdatalab/openprescribing/pull/3435
