### ISSUE TITLE
Measures are only recalculated for last five years

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#907]
When importing measures each month, we calculate (or recalculate) measure values for the last five years.

This causes two problems:

1. For new CCGs (eg [Bucks](https://openprescribing.net/ccg/14Y/)) we can only show five years of data, but have percentiles going back to May 2012.

![image](https://user-images.githubusercontent.com/24895935/41978949-c768bdde-7a1a-11e8-8da3-668881ca01e7.png)

2. For CCGs that have been around more than five years, any measures older than five years do not reflect the current composition of practices in the CCG, but the composition five years later.

Some possible solutions, with quick thoughts about what each would involve:

1. Only ever show five years of measures.  This would be easiest.
2. Recompute all months' measures each month.  We currently only keep five years of prescribing data (presumably to save space), so this would involve (a) keeping prescribing data indefinitely; (b) reinstating prescribing data from more than five years ago.  We _should_ have backups of all the source prescribing data, but it may be fiddly to reimport.
3. Reconstruct CCG measure values from practice measure values.  We have practice measure values going back to May 2012, and as the CCG measure values aggregate these, it _may_ be possible to reconstruct the CCG measure values from the practice measure values.  However we wouldn't be able to cope with cases where the measure definition changes.

This lazy programmer strongly favours 1, but there may be a good business case for exploring 2 or 3, and @sebbacon may have a brilliant idea for 4.

**Comment by sebbacon** [comment]
We've previously agreed that 5 years of data meets 99% of use cases and for anything outside that we can fall back to custom analyses in BigQuery.

So I think this is actually a bug in measures, that we don't trim at 5 years.  So lazy wins.

**Comment by inglesp** [comment]
OK, good.

Two possible fixes:

* Delete all `MeasureValue` and `MeasureGlobal` objects older than five years in `import_measures`.
* Only return five years of data in the measures API views.

@sebbacon Preferences?

**Comment by sebbacon** [comment]
The former. A bit like this (though we don't use partitioned tables for measures):

https://github.com/ebmdatalab/openprescribing/blob/4e46ee0a7a754b3baa3c5114e24df6d63ba89840/openprescribing/frontend/management/commands/import_hscic_prescribing.py#L173-L177
