### ISSUE TITLE
Patient Description on Low Priority Dashboards

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#912]
On the Low Priority dashboard when you how over the deciles the "Total List Size" = "Patients".

Suggest we change to "Registered Patients"?

![image](https://user-images.githubusercontent.com/40460354/42161683-c476cb2a-7df3-11e8-8243-f573fc7bc1c4.png)

**Comment by brianmackenna** [comment]
NB. I have looked at the code in https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/lplidocaine.json 
but the pop up over the mouse code doesn't seem to be in there.

**Comment by sebbacon** [comment]
Yes, the labels are part of the code, not the measure definition.

**Comment by brianmackenna** [comment]
@evansd If we could change "patients" to "Registered Patients" please?

Thanks to @Rich for the links!
https://github.com/ebmdatalab/openprescribing/blob/a6a93e8500487071fc18ae0c07760f0e865a477f/openprescribing/media/js/src/measure_utils.js#L484
