### ISSUE TITLE
Is the BNF table up to date?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#918]
Following the April 2018 import, it seems that we may not be using the latest BNF table.

@richiecroker noticed that `ActiPatch Knee Pulsed Electromagnetic Stimulator` (`21490000101`) is not in our BNF table, but *is* in the latest CSV available from the source we usually use

**Comment by inglesp** [comment]
The BNF file (version 74) on the [NHS BSA ISP](https://apps.nhsbsa.nhs.uk/infosystems/data/showDataSelector.do?reportId=126) is different to the file we downloaded during the last import (at ~/openprescribing-data/data/bnf_codes/2018_06 on largeweb2).

The filename of the file on the ISP is 20180702_1530535816192_BNF_Code_Information.csv.  The first part of the filename is a datestamp, which indicates that this version of the file was probably uploaded to the ISP on 2nd July, after the latest import.

As such, I'm happy that the import process is working as expected.

@richiecroker Do you want us to import the latest BNF codes now?

@sebbacon Can you think of anything we'd need to do after importing the BNF codes?

**Comment by sebbacon** [comment]
Also upload it to BigQuery, otherwise, no.

**Comment by inglesp** [comment]
Have just imported the latest BNF codes and they're now in the `hscic.bnf` BQ table.

I ran:

* `fetch_bnf_codes`
* `import_bnf_codes`
* `pipeline.runner.upload_all_to_storage()`
* `pipeline.management.commands.bigquery_upload.update_bnf_table()`
