### ISSUE TITLE
Analyse queries highlighting CCGs cut off at August 2013

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#920]
Analyse queries that highlight a CCG or CCGs ([example](https://openprescribing.net/analyse/#org=CCG&orgIds=99P&numIds=0703021Q0BB&denom=nothing&selectedTab=chart)) only show data going back to August 2013, while all other queries ([example](https://openprescribing.net/analyse/#org=practice&orgIds=99P&numIds=0703021Q0BB&denom=nothing&selectedTab=chart)) show data going back five years.

This is deliberate although possibly mistaken.  [This comment](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/media/js/src/chart_utils.js#L273-L276) says that CCGs were formed in August 2013, but my understanding from [here](https://www.nhscc.org/ccgs/) is that they were formed in April 2013.

@richiecroker Can you think of any reason not to show data for CCGs from before August 2013?

@sebbacon You added the check for August 2013 in f8690afb.  When we discussed this a couple of months ago, you thought this might be a mistake.  Can you confirm?

**Comment by sebbacon** [comment]
All I can confirm is that it might be a mistake, still!  It's plausible that I might have "months starting wth 'A'" mixed up.

**Comment by richiecroker** [comment]
Nothing special about August 2013! April 2013 on the other hand was the first month of CCGs.
