### ISSUE TITLE
Missing BNF codes in DT download

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#924]
There are still some missing codes in the DT download, most obvious is Vit B co tabs.

![image](https://user-images.githubusercontent.com/18683239/42313263-358897a6-803a-11e8-9410-494eac1cbcaf.png)

Is this related to #818?

**Comment by inglesp** [comment]
Have just re-run BNF/SNOMED mapping import, and now all but 4 of the records in the CSV file have a BNF code.

The exceptions are all for VMPP "Ibuprofen 200mg / Phenylephrine 6.1mg tablets 16 tablet".  This VMPP (34874111000001109) isn't referenced in the mapping file (although its AMPP (34875011000001107)) is.

**Comment by sebbacon** [comment]
I've written to BSA about the Ibuprofen example.

**Comment by sebbacon** [comment]
Answer: it's a newer product than the mapping.

> In relation to the product Ibuprofen 200mg / Phenylephrine 6.1mg tablets 16 tablet, this item was only added to our CDR database in April this year and the June mapping file relates to data that was available in CDR in March 2018. The next mapping file due to be published in September will be based on data that was available in CDR for June 2018 and as such this product will be included in this dataset.

**Comment by inglesp** [comment]
And if it's a new product in April we won't see it in the prescribing data until July, so it should only be without a BNF code for a couple of months.

**Comment by sebbacon** [comment]
See #1029 for a systematic analysis of missing codes
