### ISSUE TITLE
Consider whether to treat some Low Priority measures as Cost Saving

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#927]
At the moment we don't, which leads to the slightly odd behaviour raised in #725.

Which of the current crop of low priority measures are candidates for cost savings?

And does it still make sense to calculate savings in the same way as we do for other measures (i.e. compare to best performing decile)? Or as the "ideal" prescribing quantity for these is zero, should we treat the entire cost as a potential saving?

Thoughts @richiecroker?

**Comment by sebbacon** [comment]
This is tagged at you @richiecroker !

**Comment by sebbacon** [comment]
And again for @richiecroker email test

**Comment by HelenCEBM** [comment]
We now calculate cost savings for all cost-per-1000 measures
