### ISSUE TITLE
Understand how Y03584's CCG was set

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#928]
According to our Practice table, [Y03584 (C/O THE LIMES MEDICAL CENTRE)](https://openprescribing.net/practice/Y03584/) is in [03W (NHS EAST LEICESTERSHIRE AND RUTLAND CCG)](https://openprescribing.net/ccg/03W/).

In the prescribing dataset, it's been listed as being in [Q59](https://openprescribing.net/ccg/Q59/) since 2014_11.  Q59 is in the PCT table with no `name` and "Unknown" `org_type`.

(Before that it was listed in [13A (LEICESTERSHIRE AND LINCOLNSHIRE COMMISSIONING HUB)](https://openprescribing.net/ccg/13A/) which now closed, and [5PA (Leicestershire County and Rutland)](https://openprescribing.net/ccg/5PA/) which is not listed as closed but only has a couple of orphan practices.)

In the epraccur.csv data, it's always listed as being in Q78, which does not exist in the PCT table.

So where has 03W come from?

**Comment by sebbacon** [comment]
Not to my memory. I don't recall that issue ever having anything to do with CCG membership, nor can I see why it would do.

The relevance may just be that it's a "weird" practice.

So - I have no idea about `03W`!

But don't we reimport epraccur every month? So whatever's changing it is doing it every month?

**Comment by inglesp** [comment]
> But don't we reimport epraccur every month? So whatever's changing it is doing it every month?

I wondered that, but no, since the CCG in epraccur is not in our database:

    try:
        # Not all practices have a CCG - the ones that don't are mostly
        # in Jersey, Isle of Man, etc.
        pco_code = row[23].strip()
        ccg = PCT.objects.get(code=pco_code)
        practice.ccg = ccg
    except PCT.DoesNotExist:
        if self.IS_VERBOSE:
            print 'ccg not found with code', pco_code

My best theory is that it was set by some prehistoric import from a different dataset.

**Comment by inglesp** [comment]
Also: Q78 is another field value in the eccg.csv dataset, which might explain the problem.

```
$ grep 03W 2017_06/eccg.csv 
"03W","NHS EAST LEICESTERSHIRE AND RUTLAND CCG","Y55","Q78","BRIDGE PARK PLAZA","BRIDGE PARK ROAD","THURMASTON","LEICESTER","LEICESTERSHIRE","LE4 8BL","20130401","","","C","","","","","","","","0","","","","",""
```

Unfortunately eccg.csv doesn't have column headers.

**Comment by inglesp** [comment]
Q78 is the "High Level Health Geography" according to the [Organisation Data Service Standards Repository](https://digital.nhs.uk/binaries/content/assets/legacy/pdf/n/8/odsstandards.pdf) docs.

**Comment by inglesp** [comment]
I will send NHS Digital a quick email, but I don't think there's anything else we need to worry about here.

**Comment by richiecroker** [comment]
It's not a "real" GP practice, it's a violent patients service.  Little prescribing.
https://www.leicester.gov.uk/media/181923/homelessness-jspna.pdf
