### ISSUE TITLE
Missing file extension on CSV download

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#933]
From doorbell (not yet investigated this at all but sounds plausible and should be an easy fix):

> On Wed, 11 Jul 2018 at 12:26, Simon Hailstone <Simon.Hailstone@phe.gov.uk> wrote:
>
> Hi, Just spotted a minor bug, when pressing the download csv link on this page: https://openprescribing.net/chemical/0501011P0/
>
>  
>
> I get a file called download which doesn’t have a file extension. Obviously it’s easy to add one but less tech savvy users might be confused. Here is the download link: https://openprescribing.net/api/1.0/spending_by_ccg/?code=0501011P0&format=csv
>
>  
>
> Best wishes
>
>  
>
> Simon Hailstone

**Comment by evansd** [comment]
This is due to the DRF CSV library we use not adding the `Content-Disposition` header:
https://github.com/mjumbewu/django-rest-framework-csv/issues/19

Possibly we can subclass the renderer and add this behaviour ourselves.

**Comment by sebbacon** [comment]
This is how we do it for the tariff data:

https://github.com/ebmdatalab/openprescribing/blob/1fb309ecbd89098ae89d6fa0f21064cab2c5227f/openprescribing/api/views_spending.py#L244-L248

**Comment by evansd** [comment]
Ah I see. I didn't know about the `request.accepted_renderer.format ` trick

**Comment by sebbacon** [comment]
ISTR it taking me quite a lot of code-diving to work it out!

**Comment by HelenCEBM** [comment]
Any progress @evansd ?

In the meantime we should add a note to tell people to add the file extension before opening the file, if absent.
