### ISSUE TITLE
Easily Confused Drug Names

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#935]
This user suggested the following. I have looked at a couple of combinations but cannot find a useful measure. However I think a useful measure could be done with patient level data
e.g. where a patient has had Amlodipine medicine previously but has been prescribed Nimodipine. 
 - suggest I send as suggestion to BSA/MHRA unless someone else can think of a measure?

> 

*Easily confused drugs*
> The BNF states that some drugs are easily confused because they have
> similar-sounding names. 
>
> Drug name confusion: reminder to be vigilant for potential errors between 
>> clobazam and clonazepam, atenolol and amlodipine, propranolol and 
>> prednisolone, risperidone and ropinirole, sulfadiazine and sulfasalazine, 
>> amlodipine and nimodipine, mercaptamine and mercaptopurine, zuclopentixol 
>> acetate and zuclopentixol decanoate [MHRA/CHM advice]. 
>> 
>
> Source: https://bnf.nice.org.uk/about/changes.html
> <http://mailstat.us/tr/t/8hyi28rjia0vwp3/1/https://bnf.nice.org.uk/about/changes.html>; 
>
>
> I did a quick analysis for these pairs, effectively just one divided by
> the other. This showed that there were indeed some outliers at CCG level,
> which turned out to be driven by a small number of GP practices. This may
> simply be because the overall prescribing volume of one or the other is
> low, so an analysis based on more than a month's data would have been
> helpful, but it's a good starting point. 
>
> Derby Hospitals has a more extensive list of easily confused drug names: 
>http://www.derbyhospitals.nhs.uk/primary/pharmacy/formulary/drug-names-
> that-look-sound-alike/
> <http://mailstat.us/tr/t/8hyi28rjia0vwp3/2/http://www.derbyhospitals.nhs.uk/primary/pharmacy/formulary/drug-names-that-look-sound-alike/>; 
>
> A new measure could target all or some of these, perhaps even as a
> composite measure.

>

**Comment by richiecroker** [comment]
No, i looked at this, and couldn't work out how to make it a usable measure.  I thought i'd replied, but obviously not!

**Comment by richiecroker** [comment]
Because what does it mean?  A lot of commonly prescribed drugs there.

**Comment by brianmackenna** [comment]
Not feasible on OP public dataset. Passed to NHSE/BSA for further consideration.
