### ISSUE TITLE
Improve links between Presentation and dmd models

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#947]
The `Presentation` model represents prescribable items in the BNF.  However, names in the BNF are clunky abbreviations (such as "Paracet_Cap 500mg").  Another dataset of prescribable items is the dm+d which has nicer names like "Paracetamol 500mg capsules".

There is a quarterly spreadsheet from the BSA that contains a mapping from items in the dm+d to items in the BNF, so we should be able to use the nice dm+d names for BNF items.

However, the mapping is not straightforward.

In most cases a BNF item logically maps either to a VMP or an AMP.  However, in some cases a BNF item maps to a VMPP or an AMPP.  The mapping in the spreadsheet only contains mappings between a BNF item and a VMPP or AMPP.  In cases (the majority) where a BNF item maps to a VMP or AMP, we will have to notice that all the VMPPs/AMPPs belong to the same VMP/AMP.  See https://github.com/ebmdatalab/openprescribing/issues/818#issuecomment-406335414 for more.

We can add a nullable `bnf_code` field to the `[AV]MPP?` tables to be set when the spreadsheet is imported.  This would be straightforward, but not very useful in terms of getting a nice dm+d name for a `Presentation`.

Beyond that, we have at least three options (in each case, the new field(s) would be updated when the spreadsheet is imported):

* Add a `dmd_name` field to `Presentation`
* Add four foreign keys on `Presentation` to each of the`[AV]MPP?` tables
* Add a single `GenericForeignKey` from `Presentation` to the `[AV]MPP?` tables

(The second and third options would require creating Django models for the `dmd_[av]mpp?` tables, which I'd like to do anyway.)

We could also combine the first option with one of the other two, to make writing certain queries easier.

In the short term I propose to do the first option.

We should also aim to drop the `bnf_code` field from `dmd_product` (which contains both AMPs and VMPs) as we know that some BNF items map to AMPPs or VMPPs.

**Comment by inglesp** [comment]
Since writing this, we have a new BNF->dm+d map (#1029), which gives us a BNF code for (all? almost all?) `[AV]MPP?`s, and which includes mappings for all but 252 BNF codes.

**Comment by inglesp** [comment]
> * Add four foreign keys on Presentation to each of the [AV]MPP? tables
> * Add a single GenericForeignKey from Presentation to the [AV]MPP? tables

These don't make sense, since a BNF code can refer to multiple `[AV]MPP?`s.

But we could add a `bnf_code` field to each of the `dmd_[av]mpp?` tables.

**Comment by inglesp** [comment]
How do we currently use the `DMDProduct` model?

* To show "nice names" for `Presentation`s in various places:
  * Measure breakdowns by Presentation (eg [here](https://openprescribing.net/measure/keppra/ccg/05Y/))
  * On all the PPU pages (both [by entity](https://openprescribing.net/ccg/02N/price_per_unit/) and [by entity and presentation](https://openprescribing.net/ccg/02N/0802020T0AAABAB/price_per_unit/?date=2018-07-01))
  * The title and the dropdown list in the [tariff viewer](https://openprescribing.net/tariff/)
* To show extra information about a presentation on the PPU by presentation page (eg when mousing over "Phytomenadione 10mg tablets" [here](https://openprescribing.net/ccg/02N/0906060Q0AAACAC/price_per_unit/?date=2018-07-01))
* To find tariff prices for a given BNF code in the [tariff viewer](https://openprescribing.net/tariff/)

**Comment by sebbacon** [comment]
Yes, it makes sense to add the bnf_code field directly to AMPPs or VMPPs as this is the format in which they are given.

Just going over all this again for my own benefit:

`Paracet_Tab 500mg` is `0407010H0AAAMAM` in the prescribing data. This is a VMP.  Doctors never prescribe by product pack (except when they do, see below).

In the Drug Tariff, this presentation appears twice, listed against two VMPPs. DT prices are always given against a pack size. The DT always uses generic coding, i.e. it never refers to AMPPs. Here it is in the DT:

|VMPP Snomed Code | Drug Name | Pack size |   | Basic Price|
|-- | -- | -- | -- | --|
|1064711000001107 | Paracetamol 500mg tablets | 32 | tablet | 50|
|1251111000001105 | Paracetamol 500mg tablets | 100 | tablet | 156|

In the latest mapping we've been provided, the VMP `Paracetamol 500mg tablets` is mapped against *every* VMPP *and* VMP in dm+d for us; no work to do. Though it would be good to verify it's been done correctly.

What about the occasional item where a BNF code should not be mapped to all sibling MPP, but can only be mapped to a single MPP?  One example is `Seretide 250_Accuhaler 250mcg/50mcg(60D)` whose BNF code is `0302000N0BCABAY`.  This is an example of when a doctor does prescribe by pack, and in the MDR data the only indication this is the case is the appearance of `60D` in the MDR name. In the BNF->DMD mapping, this BNF code appears twice: once for a single AMPP (`Seretide 250 (GlaxoSmithKline UK Ltd) 60 doses`) and once for an AMP (`Seretide 250 (GlaxoSmithKline UK Ltd)`). This seems to make sense. 

(However, I've spotted [what looks like an error](https://github.com/ebmdatalab/openprescribing/issues/1029#issuecomment-426603099) in the code for products which are available in multiple packs...)

To meet the use cases listed by @inglesp above:

* nice names: a BNF code should return the name of the MP that it matches *unless* it's a BNF code that only maps to one MPP - in those cases we want the MPP name
* tariff prices: as per current viewer, any AM should be turned to a VM.  Then you look up all the MPPs for that MP.  For the BNF codes that map only to MPPs, I'd expect the same logic to continue to work.

**Comment by inglesp** [comment]
The extra information about a presentation on the PPU by presentation page is:

* Tariff category -- this comes from `dmd_dtinfo.pay_catcd`, and `dmd_dtinfo` as a foreign key to `dmd_vmpp`
* Availability restrictions -- this comes from `dmd_amp.avail_restrictcd`
* Prescribability status -- this comes from `dmd_vmp.pres_statcd`

**Comment by inglesp** [comment]
With #1718 and #1737, I'd say this is done!
