### ISSUE TITLE
Sort measures correctly

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#97]
On the new CCG and practice dashboards, we sort the measures by "outsiderishness", highest first. However, it turns out that higher is not always worse, when it comes to the KTTs.

Establish for which of the KTTs lower is worse - Richard has sent us a partial list, we need to chase him to complete this. 

Then work out a way in the JS to rank correctly. This will probably involve adding a new field to the Measure table, returning it in the API, and using this in the JS to order the ranking. 

And write comprehensible copy explaining how the ranking works, not too long or confusing.

**Comment by sebbacon** [comment]
To be clear, currently we know of two ways to sort a measure.

1) By mean percentile over last six month, ascending
2) By mean percentile over last six month, descending

Is that right?

Can I be CC'd on the lists of KTT with Richard so I can chase him?

**Comment by annapowellsmith** [comment]
Currently by default we sort by mean percentile over the last six
months, descending (A).

If you click the button on the page, you can sort by cost saving over the
past six month, descending (B).

(B) is fine and can stay as it is.

(A) needs to be amended, because sometimes a high mean percentile is good,
sometimes a high mean percentile is bad. This is because sometimes the
measure itself is "good" when high, sometimes "bad" when high. We don't
know which is the case for each measure, because the KTT definition docs
don't specify this, so far as I can see.

You can find the KTT definition docs by googling for "Medicines
Optimisation Key Therapeutic Topics Comparators 2015/16 (Formerly QIPP
Prescribing Comparators". And more background (fwiw) here
http://www.hscic.gov.uk/prescribing/measures

I'll add you to the email thread with Richard!

On 5 July 2016 at 09:02, Seb Bacon <notifications@github.com> wrote:

> To be clear, currently we know of two ways to sort a measure.
>
> 1) By mean percentile over last six month, ascending
> 2) By mean percentile over last six month, descending
>
> Is that right?
>
> Can I be CC'd on the lists of KTT with Richard so I can chase him?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ebmdatalab/openprescribing/issues/97#issuecomment-230411998>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAExTGWTIYzSCsO-dfZ7Yqwa6dms8z2Sks5qSg98gaJpZM4JDKEY>
> .
>



-- 
Anna Powell-Smith MA MPhil
07812 357037
anna.powell-smith@phc.ox.ac.uk
Honorary Research Fellow
Centre for Evidence-Based Medicine
Department of Primary Care Health Sciences
University of Oxford
Woodstock Road
Oxford OX2 6GG
www.ebmDataLab.net <http://www.ebmdatalab.net/>

**Comment by annapowellsmith** [comment]
We're also going to need to fix the text that says: "Over the past 6 months, this organisation has prescribed above the median on 8 of 16 measures. We think this is acceptable performance overall.". This should change to "has prescribed worse than the national median" or similar, and the calculations will need to be amended accordingly.
