### ISSUE TITLE
Have 2018 pseudo-BNF changes been applied?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#972]
i.e. the old code -> new code mapping.

See attached
[Information Changes BNF V72 - V74.xlsx](https://github.com/ebmdatalab/openprescribing/files/2265890/Information.Changes.BNF.V72.-.V74.xlsx)

**Comment by sebbacon** [comment]
Also think about a good way to remind us to do this every year. Maybe ask Lydia to set up a reminder? (Or do it ourselves)

**Comment by inglesp** [comment]
- [x] Add mapping to `presentation_replacements/2018.txt`
- [ ] Merge and deploy
- [ ] Run `generate_presentation_replacements`
- [ ] Set up reminder to review regularly (see #985 for proposal)
