### ISSUE TITLE
Alert feedback/tweaks

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/openprescribing#979]
This email:
```
RE: Your monthly update about The Barnabas Medical Ctre

These graphs are meaningless.  

1.    Is a higher score better or worse than a lower score?  It doesn't say, and it isn't obvious - especially as it may be different for different measures.
2.    How can a practice be "in the worst 10% on Antibiotic stewardship: three-day courses for uncomplicated UTIs" but also "in the best 10% on
Antibiotic stewardship: three-day courses for uncomplicated UTIs"?
3.    How to write a totally meaningless statement: "this practice was in the top or bottom 10% on Direct Oral Anticoagulants (DOACs)".  Duh!

I'll take this seriously when you can produce robust statistics and reports.

Keith
```

Points out some issues with the alerts.

1. I'm sure we've discussed this one before at some point. It's obvious to us and lots of frequent users, but clearly not to everyone
2. This practice appears in both the top and bottom in the last 3 months https://openprescribing.net/practice/E85127/measures/#ktt9_uti_antibiotics I'd suggest either taking an average over the 3 months, or suppressing alerts about it when it appears in both.
3. Not sure why it says "top or bottom"

**Comment by HelenCEBM** [comment]
1. We could add: "Need help interpreting the data? Check out our FAQ" (with link, and make sure that it says "lower is better" somewhere in faq. 


3. I agree with you @sebbacon - I don't know why he thought that was meaningless.. However, if we so desired, I assume it should be easy to narrow it down to the one which actually applies in each case:

> There are some areas where there is disagreement about whether higher, or lower, is better. Nonetheless it is interesting to know when an organisation is very different from standard prescribing behaviour.
>
> Over the last three months, we found that this practice was in the **top** 10% on Direct Oral Anticoagulants (DOACs)

**Comment by alexwalkercebm** [comment]
I like "deviated a long way from the median practice".

**Comment by brianmackenna** [comment]
1. No problem - don't fix
2.  Worth considering further in the other issue.
3. Not a problem worth spending time on. I always think it was a bit odd that I got an e-mail that didn't know whether I was in the top or bottom.

**Comment by sebbacon** [comment]
Closing for #1295
