### ISSUE TITLE
Teething problems with new Practice dashboards

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#988]
### 1. Measures are selected as having the most potential for improvement are inconsistent with ranked list:
- this may be because the measure is selected based on only one month of data (unlike the ranked list which takes into account 6 months of data). E.g. this practice gets opioids highlighted (97th percentile last month) but at the top of the ranked list is glaucoma (96th percentile last month) https://openprescribing.net/practice/E81030/measures/
- But sometimes they are measures with no data, e.g. https://openprescribing.net/practice/F85024/
![image](https://user-images.githubusercontent.com/24392156/44146070-e36f3724-a085-11e8-8f6c-577f51047133.png)
- This also applies to the CCG dashboards.

### 2. Links for the worst measure do not work correctly
When the measure title is clicked on, it redirects to `ccg/[practice_code]/[measure_name]` which comes up with an error. 

### 3. There seems to be a problem when the worst measure is the low-priority omnibus measure:
![image](https://user-images.githubusercontent.com/24392156/44145764-cfb72cce-a084-11e8-97ec-d67179dea119.png)

### 3. For some practices no PPU savings appear:
https://openprescribing.net/practice/F85024/
![image](https://user-images.githubusercontent.com/24392156/44145877-19f31280-a085-11e8-94cb-4f0913684faa.png)
This might not be an error but because there are no savings: https://openprescribing.net/practice/F85024/price_per_unit/

However, this makes it look broken, so it would be helpful to have an appropriate message on the practice home page. E.g. "smiley face - we found no savings above the £1000 threshold for the latest month!"

**Comment by sebbacon** [comment]
Closing in favour of new subissues referenced above
