### ISSUE TITLE
Dashboards: Links for the worst measure do not work correctly

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#990]
On a practice dashboard page, when the measure title is clicked on, it redirects to `ccg/[practice_code]/[measure_name]` which comes up with an error, i.e. `ccg` is wrongly in the URL.

**Comment by sebbacon** [comment]
This issue is broken out from #988

**Comment by sebbacon** [comment]
The javascript to select if it's a practice or CCG url depends on a variable `rollUpBy` being `measure_id` (or not):

https://github.com/ebmdatalab/openprescribing/blob/3c1f0dd6c0e128645b279bb993f785e584ab2288/openprescribing/media/js/src/measure_utils.js#L347-L371

This is set on the dashboard for both practices and CCGs thus:

https://github.com/ebmdatalab/openprescribing/blob/3c1f0dd6c0e128645b279bb993f785e584ab2288/openprescribing/templates/entity_home_page.html#L134

One possible fix is to set that variable differently for each flavour of the view, though off the top of my head I'm not sure what other effects setting this variable has on that page.

**Comment by sebbacon** [comment]
This seems still to be broken.

**Comment by evansd** [comment]
I think these are working, but perhaps not working in the way you expected. They link to a page showing the performance of the practice on that measure in the context of the other practices in the CCG, which is how the links work on the old practice dashboard.

Compare:
https://openprescribing.net/practice/G85724/
https://openprescribing.net/practice/G85724/measures/

**Comment by sebbacon** [comment]
Ah, thanks for checking!
