### ISSUE TITLE
Dashboards: for some practices no PPU savings appear

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#992]
https://openprescribing.net/practice/F85024/
![image](https://user-images.githubusercontent.com/24392156/44145877-19f31280-a085-11e8-94cb-4f0913684faa.png)
This might not be an error but because there are no savings: https://openprescribing.net/practice/F85024/price_per_unit/

However, this makes it look broken, so it would be helpful to have an appropriate message on the practice home page. E.g. "smiley face - we found no savings above the £1000 threshold for the latest month!"

(this issue broken out from #988)

**Comment by HelenCEBM** [comment]
Is it a £1000 threshold for practices and CCGs? Is this appropriate or should it be lower for practices? (If that's possible/easy)

**Comment by sebbacon** [comment]
@HelenCEBM if you still think that's worth considering (I'm not sure either way) could you make a separate issue and/or get someone like Rich's opinion on it?

**Comment by HelenCEBM** [comment]
I noticed that there are savings under £1000 for some practices so the threshold is lower, though I'm not sure what it is. Should be fine!
