### ISSUE TITLE
Review copyright assignment in license

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#995]
The [license](https://github.com/ebmdatalab/openprescribing/blob/3c1f0dd6c0e128645b279bb993f785e584ab2288/LICENSE.txt) still assigns copyright to Anna. Should we change this? My contract includes a rights assignment clause, and I assume the same for others, so perhaps it should be property of the DataLab, or the University.

**Comment by sebbacon** [comment]
Anna's given me permission by email to reassign copyright, so we just need to decide to whom. EBM DataLab would be best, but then it's not a legal entity so I'm not sure we can do that?

**Comment by Bengoldacre** [comment]
agree DL best, suspect ox best but no time to check off all implications in full right now so make it me for time being cheers.
